### ISSUE TITLE
Default the Naming Strategy for Hibernate to snake case (lower case, underscore separated)

### ISSUE THREAD

**Issue by lucasmogari** [micronaut-projects/micronaut-data#103]
micronaut 1.2.0
micronaut-data 1.0.0.BUILD-SNAPSHOT

Database is migrated with flyway.

I'm getting the following exception when using a repository:
Postgres
```
Caused by: org.postgresql.util.PSQLException: ERROR: column user0_.firstname does not exist
  Hint: Perhaps you meant to reference the column "user0_.first_name".
```

H2
```
Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "USER0_.FIRSTNAME" not found; SQL statement:
select user0_.id as id1_0_, user0_.email as email2_0_, user0_.firstName as firstNam3_0_ from accounts_user user0_ [42122-199]
```

Example repository: https://github.com/lucasmogari/micronaut-data-naming-strategy

**Comment by lucasmogari** [comment]
Using this don't work also:
@MappedEntity(namingStrategy = NamingStrategies.UnderScoreSeparatedLowerCase.class)

**Comment by graemerocher** [comment]
This relates to https://github.com/micronaut-projects/micronaut-sql/issues/17 

Currently for Hibernate the default is not underscore separated.

**Comment by lucasmogari** [comment]
@graemerocher How to configure the naming strategy?

With micronaut-data 1.0.0.M5, JPA still doesn't use underscore/lowercase by default.

This property doesn't translate to first_name:

private String firstName;

> Hibernate: select user0_.id as id1_0_, user0_.email as email2_0_, user0_.firstName as firstNam3_0_, user0_.lastName as lastName4_0_ from accounts_user user0_
> ERROR SqlExceptionHelper ERROR: column user0_.firstname does not exist
>   Hint: Perhaps you meant to reference the column "user0_.first_name".
>   Position: 56

**Comment by lucasmogari** [comment]
This worked.

```
jpa:
  default:
    properties:
      hibernate:
        physical_naming_strategy: "io.micronaut.data.hibernate.naming.DefaultPhysicalNamingStrategy"
```
