### ISSUE TITLE
Schema generation issues using PostgreSQL

### ISSUE THREAD

**Issue by tdudouet** [micronaut-projects/micronaut-data#104]
I have some issues when moving from H2 to PG on `example-jdbc-kotlin` project.

First of all, seems to have some dialect issues when generating schema.
> Create Table Failed: ERROR: syntax error at or near "AUTO_INCREMENT"

Then a single table is created (pet), but no primary nor foreign key is declared.
> postgres=# \d
>         List of relations
>  Schema | Name | Type  |  Owner   
> --------+------+-------+----------
>  public | pet  | table | postgres
> (1 row)
> 
> postgres=# \d pet
 >                         Table "public.pet"
 >  Column  |          Type          | Collation | Nullable | Default 
> ----------+------------------------+-----------+----------+---------
>  id       | character varying(255) |           |          | 
>  name     | character varying(255) |           |          | 
>  owner_id | bigint                 |           |          | 
>  type     | character varying(255) |           |          | 

I'm using PG 11.4, updated the driver on `build.gradle` file, declared `@JdbcRepository(dialect = Dialect.POSTGRES)` on the two repositories and updated the application.yml to declare the datasource accordingly.

**Comment by graemerocher** [comment]
Yeah so the automatic schema creation is only really for testing when moving to Postgres you should introduce a schema migration tool that populates the dB

**Comment by tdudouet** [comment]
Too bad... but thanks for your answer !

**Comment by graemerocher** [comment]
Just a not that the current snapshots supports sequences now with `@GeneratedValue(GeneratedValue.Type.SEQUENCE)` for Postgres 11
