### ISSUE TITLE
Build failure on rudimentary example using GraalVM, Kotlin, MariaDB, & micronaut-data

### ISSUE THREAD

**Issue by bradkarels** [micronaut-projects/micronaut-data#1045]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Install MariaDB 10.3 local on port 3306 with a `test` database - create user tbl and optionally insert some rows (SQL provided in repository (user.sql) - user=root, password=passwd) `docker run --rm -p 3306:3306 --name lmdb -v /path/to/your/data/mysql:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=passwd -d mariadb:10.3`
2. Install micronaut 2.5.5 (I used sdkman) `sdk i micronaut 2.5.5`
3. Clone [sample repository](https://gitlab.com/dead_cat_bounce/micronaut-data-demo)
4. cd into `micronaut-data-demo`
5. run `./gradlew clean run

### Expected Behaviour

The application should start up normally and run.

### Actual Behaviour

Compilation failure with the error:

    rev@~/dev/mn/micronaut-data-demo % ./gradlew clean run

    > Task :kaptKotlin FAILED
    error: Unable to implement Repository method: UserRepository.update(Object arg0). Invalid query method [update] of repository [com.te.repositories.UserRepository]: No ID found for entity: com.te.model.UserNote: Writing reflect-config.json file to destination: META-INF/native-image/com.te/model/reflect-config.jsonNote: Writing resource-config.json file to destination: META-INF/native-image/com.te/model/resource-config.jsonNote: Creating bean classes for 4 type elements
    FAILURE: Build failed with an exception.

    * What went wrong:
    Execution failed for task ':kaptKotlin'.
    > A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptExecution
       > java.lang.reflect.InvocationTargetException (no error message)

    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

    * Get more help at https://help.gradle.org

    Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
    Use '--warning-mode all' to show the individual deprecation warnings.
    See https://docs.gradle.org/7.0/userguide/command_line_interface.html#sec:command_line_warnings

    BUILD FAILED in 2s
    4 actionable tasks: 4 executed

User.kt

    import io.micronaut.data.annotation.GeneratedValue
    import io.micronaut.data.annotation.Id
    import io.micronaut.data.annotation.MappedEntity
    
    @MappedEntity(value="user")
    data class User(@Id @GeneratedValue
                var id: Int,
                var fname: String,
                var lname: String,
                var email: String)

UserRepository.kt

    import com.te.model.User
    import io.micronaut.data.jdbc.annotation.JdbcRepository
    import io.micronaut.data.model.query.builder.sql.Dialect
    import io.micronaut.data.repository.CrudRepository
    
    @JdbcRepository(dialect = Dialect.MYSQL)
    interface UserRepository : CrudRepository<User, Int> {}

### Environment Information

- **Operating System**: macOS BigSur 11.4
- **Micronaut Version:** 2.5.5
- **JDK Version:** 21.0.0.2.r8-grl (same behavior with 21.1.0.r11-grl)

### Example Application

- [sample repository](https://gitlab.com/dead_cat_bounce/micronaut-data-demo)

### Full description of the issue

Trying to create about the most simple example for micronaut-data using Micronaut 2.5.5, Kotlin, & MariaDB. Following the documentation as best I am able and doing some pretty decent amounts of searching, I am unable to get past the above error for my simple entity. Hoping I am missing something as I do not know how to simplify this trial any more. Additionally, I hope I have provided good and sufficient information in this issue.

**Comment by graemerocher** [comment]
See https://micronaut-projects.github.io/micronaut-data/latest/guide/#kotlinData

Id has to be  @field:Id

**Comment by bradkarels** [comment]
Thank you @graemerocher - swapping out the annotation for `@field:Id` has resolved the build error. Closing.
