### ISSUE TITLE
Allow @DateCreated/Updated behaviour to match precision of database

### ISSUE THREAD

**Issue by nhoughto** [micronaut-projects/micronaut-data#1055]
As of Java 15 the time precision of `OffsetDateTime.now()` is in nanoseconds (https://bugs.openjdk.java.net/browse/JDK-8242504) so the current DateTimeProvider in Java 15+ will return DateTime objects with nanoseconds.

Many databases (Postgres in my case) don't support or don't default to supporting this level of precision in timestamps and you get a weird problem where the Entity object you persist and return via `save()` has a different timestamp value to what is actually in the database, such that if you call `findById` and compare the saved vs found objects the timestamps don't match.

This is made worse by the behaviour of how the database/JDBC driver/layers in-between goes from DateTime w/ nanos to whatever precision it actually supports. In my case it was being rounded to the nearest microsecond (up or down) not truncated, so the standard 'use truncateTo()' solution didn't work.

It is easily worked around via a custom DateTimeProvider like:
```
@Primary
@Singleton
@Replaces(CurrentDateTimeProvider.class)
public class MicrosecondCurrentDateTimeProvider implements DateTimeProvider<OffsetDateTime> {
    @Override
    public OffsetDateTime getNow() {
        return OffsetDateTime.now().truncatedTo(ChronoUnit.MICROS);
    }
}
```

but feels like something that could be exposed on the `@DateCreated` annotation itself so you could specify precision as part of the annotation, overriding the single DateTimeProvider is quite a sledgehammer solution and can really only be done once (what if I have 2 databases with different precisions?). Another alternative would be to try and guess better, but that opens up a long tail of 'you guessed wrong' problems, so letting the user choose feels better.

**Comment by dstepanov** [comment]
I think adding a precision for the `@DateCreated` and `@DateUpdated` would be a good solution. It should be easy to add `truncatedTo` in `AutoTimestampEntityEventListener` based on the annotation value.

**Comment by nhoughto** [comment]
ok great.

For people from google I also added an EntityEventListener to for non-autopopulated `OffsetDateTime` properties to be truncated, this one feels a bit imprecise but is functional:

```
@Singleton
public class DateTimeTruncatingEntityEventListener implements EntityEventListener<Object> {

    @Override
    public boolean prePersist(EntityEventContext<Object> context) {
        // if the property of the entity is an OffsetDateTime then truncate its precision to
        // microseconds, as thats what Postgres support.
        for (RuntimePersistentProperty property :
                context.getPersistentEntity().getPersistentProperties()) {
            if (property.isAssignable(OffsetDateTime.class)) {
                final BeanProperty<Object, OffsetDateTime> beanProperty =
                        (BeanProperty<Object, OffsetDateTime>) property.getProperty();
                Optional<OffsetDateTime> existingTimestamp =
                        property.getProperty().get(context.getEntity(), OffsetDateTime.class);
                if (existingTimestamp.isPresent()) {
                    context.setProperty(
                            beanProperty, existingTimestamp.get().truncatedTo(ChronoUnit.MICROS));
                }
            }
        }
        return true;
    }
}
```

**Comment by Goldmensch** [comment]
A `truncatedTo` option was added in #1558. This issue can be closed
