### ISSUE TITLE
@TransactionalAdvice is marked as internal

### ISSUE THREAD

**Issue by Phil-Ba** [micronaut-projects/micronaut-data#1061]
### Task List

- [X] Steps to reproduce provided
- [X] Stacktrace (if present) provided
- [] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create application with two datasources.
2. Use entityManager to access the datasources, eg.
```
@Singleton
open class TestB(
        val entityManagerA: EntityManager,
        @Named("person")
        val entityManagerB: EntityManager
) {

    @Transactional
    open fun doesA() {
        entityManagerA.persist(Cart())
    }
    //Have to use internal API
    @TransactionalAdvice("person")
    open fun doesB() {
        entityManagerB.persist(Person())
    }

}
```

### Expected Behaviour
It should be possible to use multiple datasources without using internal API.
### Actual Behaviour
As far as I can tell, the only way to specify which transactionManager is used for a transaction is by using @TransactionalAdvice. The javax @Transactional does not provide any attribute to specify the transactionManager. @TransactionalAdvice however, is marked as internal only and it's usage seems to be undocumented. 

Relates to
https://github.com/micronaut-projects/micronaut-data/issues/686

**Comment by graemerocher** [comment]
Good point. I think I was undecided whether to use another annotation (like `@Resource`) to specify the name or not, but probably it is find for `@TransactionalAdvice` to just not be internal

**Comment by Phil-Ba** [comment]
Whats the process to contribute to documentation? I'd like to document this, since I had to search quite a bit to find out how to set this up.

**Comment by graemerocher** [comment]
Contributions welcome! You can click the "Improve this Doc" button and submit a PR https://micronaut-projects.github.io/micronaut-data/latest/guide/
