### ISSUE TITLE
Different behavior in update and updateAll

### ISSUE THREAD

**Issue by noeliajimenezg** [micronaut-projects/micronaut-data#1094]
My use case is about implementing my own **findDirty** check extending the **org.hibernate.EmptyInterceptor**.
The findDirty will:
- skip entities with older dates
- restore the previous state on the entity
- set to true a flag

Using the repository.update returns the entity with the previous state restored.
Using the repository.updateAll returns the entity with the values that are discarded.

### Steps to Reproduce

1. Run the unit tests from the example application. 

### Expected Behaviour

repository.updateAll returns the entities with the previous state restored and the flag to true.
So, updateAll should have the same behavior.

### Actual Behaviour

repository.updateAll returns the entities with the values that are discarded.

### Example Application

https://github.com/noeliajimenezg/micronaut-update-all-issue

**Comment by dstepanov** [comment]
I think the problem is in `HibernateJpaOperations`:
```
@NonNull
    @Override
    public <T> Iterable<T> updateAll(@NonNull UpdateBatchOperation<T> operation) {
        AnnotationMetadata annotationMetadata = operation.getAnnotationMetadata();
        String queryString = annotationMetadata.stringValue(io.micronaut.data.annotation.Query.class).orElse(null);
        return transactionOperations.executeWrite(status -> {
            if (queryString != null) {
                for (T entity : operation) {
                    executeEntityUpdate(annotationMetadata, queryString, entity);
                }
                return operation;
            }
            EntityManager entityManager = sessionFactory.getCurrentSession();
            for (T entity : operation) {
                entityManager.merge(entity);
            }
            flushIfNecessary(entityManager, operation.getAnnotationMetadata());
            return operation;
        });
    }
```
Probably we need to return the result of the merge? Can you validate it?

**Comment by graemerocher** [comment]
So `update` and `updateAll` are not really the same implementation wise, the latter uses a batch update query and does not update them one by one.

**Comment by noeliajimenezg** [comment]
My suspicion was more related to the iterable immutable object that is in entityManager. 
I think it's the returned operation at the end.
