### ISSUE TITLE
Groovy JdbcRepository interface that extends another fails to run

### ISSUE THREAD

**Issue by burtbeckwith** [micronaut-projects/micronaut-data#1110]
The sample app has 2 Data JDBC entities with a many-one relationship. To retrieve the parent `Game` when retrieving a child `GameState` I added an override of `findById` with `@Join`. Calling this from the running app or in a test (and with both Oracle and H2) fails with

```
java.lang.IllegalStateException: Micronaut Data method is missing compilation time query information. Ensure that the Micronaut Data annotation processors are declared in your build and try again with a clean re-build.
```

The proble appears to be due to `H2GameStateRepository` extending `GameStateRepository` - if you comment out the code in each under "FAILS" and uncomment the code under "WORKS" everything runs as expected.

https://github.com/burtbeckwith/mn-jdbc-groovy-bug

**Comment by dstepanov** [comment]
Please try the latest Data version

**Comment by dstepanov** [comment]
Probably https://github.com/micronaut-projects/micronaut-data/issues/1075

**Comment by burtbeckwith** [comment]
No luck with that. This may be related to that issue but the app does start and work otherwise, it only fails at runtime when calling `findById`

**Comment by dstepanov** [comment]
The solution is to remove `@Repository` from `GameStateRepository`.
I have created an issue in Core https://github.com/micronaut-projects/micronaut-core/issues/5902 it seems both Java and Groovy are affected.

**Comment by dstepanov** [comment]
Going to close it as there is nothing we can do here
