### ISSUE TITLE
Transient annotation not supported for Java Records

### ISSUE THREAD

**Issue by craighewetson** [micronaut-projects/micronaut-data#1112]
### Expected Behavior

If I create a java record and annotate one of its fields/properties within the constructor with Transient then I would expect Schema generator to ignore this field.

### Actual Behaviour

Instead the schema generator throws an exception when dealing with this property.
 
> Bean definition [io.micronaut.data.jdbc.config.SchemaGenerator] could not be loaded: Error instantiating bean of type [io.micronaut.data.jdbc.config.SchemaGenerator]: Constructor argument [...] for type [...] must have an associated getter

(micronaut-data/data-model/src/main/java/io/micronaut/data/model/runtime/RuntimePersistentEntity.java)
From what I can see from the source code, all constructor properties to be persistable and therefore records cannot support transient properties since all the non-static properties of a java record are defined in the constructor.
 

### Steps To Reproduce

This fails:
```
@MappedEntity
public record MyEntity(@Id @GeneratedValue @Nullable Long id,
                       @Transient @Nullable String nonPersistedData ) {
}
```

This works:

```
@MappedEntity
public class MyEntity{ 
 @Id @GeneratedValue @Nullable public Long id;
 @Transient @Nullable public String nonPersistedData;

... 
 // plus all the getters and setters :-(
...
}
```

### Environment Information

Java 16

### Version

2.4.4

**Comment by craighewetson** [comment]
I thought I would try and create a patch for this. I am currently trying to figure out how to get the
`constructorArgument`, in the constructor of the  `io.micronaut.data.model.runtime.RuntimePersistentEntity` class to have its AnnotationMetadata populated with the "Transient" annotation information. 

It somehow gets stripped out in the annotation processing/bean introspection creation.
My test (wip):
```
    void 'test runtime persistent entity with transient constructor value'() {
        given:
        def introspection = buildBeanIntrospection('test.Plant', '''
package test;
import io.micronaut.data.annotation.*;
import io.micronaut.core.annotation.NonNull;

@io.micronaut.data.annotation.MappedEntity
record Plant(@Id @GeneratedValue @io.micronaut.core.annotation.Nullable Long id, @Transient String name, @NonNull Integer age) {}
''')
        RuntimePersistentEntity.of(introspection)
    }

```

I am expecting the `introspection` instance to contain the transient annotation information for the 'name' constructor argument  before `RuntimePersistentEntity.of(introspection)` is called.

**Comment by dstepanov** [comment]
The logic that needs to be changed is probably in `SqlResultEntityTypeMapper` and the code around `entity = introspection.instantiate(args)`

You can probably add some new entity with transient parameter to `jdbc-example-records-java` tests

**Comment by craighewetson** [comment]
Thanks.
What I did was add a test to `io.micronaut.data.processor.visitors.RecordsSpec`(it looked like the right place to add it)
and it throws the same exception that I got when I reported the bug.

I am going to double check but if appears that the error happens before any of the code within the `SqlResultEntityTypeMapper` is called.

**Comment by craighewetson** [comment]
I suspect (with my limited/zero knowledge of the code base) that (part of the) issue is somewhere within `micronaut-core`  lib and maybe within (micronaut-inject).
When the  `BeanIntrospector.SHARED.findIntrospections(MappedEntity.class); ` is called in `io.micronaut.data.jdbc.config.SchemaGenerator`  the `BeanIntrospection` instance representing the record (with the transient annotation) does not have the `Transient` annotation within its constructorArgument's `annotationMetadata` instance. 

I will keep digging/debugging, but any clues/hints will be useful.

**Comment by dstepanov** [comment]
Might be caused by `MappedEntityMapper`

**Comment by dstepanov** [comment]
I have added a test that show how to use transient field in records https://github.com/micronaut-projects/micronaut-data/pull/1146

**Comment by craighewetson** [comment]
@dstepanov  does this mean the bug is fixed and the test confirms it? I can't seem to find a link to the code changes that fix the actual bug.
