### ISSUE TITLE
New Micronaut 3.0.0 io.micronaut.core.annotation.Nullable doesn't work

### ISSUE THREAD

**Issue by alejandropg** [micronaut-projects/micronaut-data#1123]
### Expected Behavior

Hi,

I think could be an error with the new Micronaut 3.0.0 default annotation to specify that an item is nullable `io.micronaut.core.annotation.Nullable`.

For example:

```java
import io.micronaut.core.annotation.Nullable;
import io.micronaut.data.annotation.GeneratedValue;
import io.micronaut.data.annotation.Id;
import io.micronaut.data.annotation.MappedEntity;
import lombok.Data;
import lombok.NonNull;

import java.time.LocalDateTime;

@Data
@MappedEntity
public class Todo {
    @Id
    @GeneratedValue
    public final Integer id;

    public final @NonNull String title;
    public final @NonNull LocalDateTime creationDate;
    public final @Nullable LocalDateTime doneDate;

}
```

### Actual Behaviour

but when the JDBC repository try to instantiate the retrieve objects you get the error:

```shell
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running io.archimedesfw.maven.micronaut.example.todo.persistence.jdbc.TodoRepositoryIT
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 1.16 s <<< FAILURE! - in io.archimedesfw.maven.micronaut.example.todo.persistence.jdbc.TodoRepositoryIT
[ERROR] find_all  Time elapsed: 0.189 s  <<< ERROR!
io.micronaut.data.exceptions.DataAccessException: Error instantiating entity [io.archimedesfw.maven.micronaut.example.todo.Todo]: Null argument specified for [doneDate]. If this argument is allowed to be null annotate it with @Nullable
	at io.archimedesfw.maven.micronaut.example.todo.persistence.jdbc.TodoRepositoryIT.find_all(TodoRepositoryIT.java:22)
Caused by: io.micronaut.core.reflect.exception.InstantiationException: Null argument specified for [doneDate]. If this argument is allowed to be null annotate it with @Nullable
	at io.archimedesfw.maven.micronaut.example.todo.persistence.jdbc.TodoRepositoryIT.find_all(TodoRepositoryIT.java:22)

[ERROR] find_by_id  Time elapsed: 0.101 s  <<< ERROR!
io.micronaut.data.exceptions.DataAccessException: Error instantiating entity [io.archimedesfw.maven.micronaut.example.todo.Todo]: Null argument specified for [doneDate]. If this argument is allowed to be null annotate it with @Nullable
	at io.archimedesfw.maven.micronaut.example.todo.persistence.jdbc.TodoRepositoryIT.find_by_id(TodoRepositoryIT.java:48)
Caused by: io.micronaut.core.reflect.exception.InstantiationException: Null argument specified for [doneDate]. If this argument is allowed to be null annotate it with @Nullable
	at io.archimedesfw.maven.micronaut.example.todo.persistence.jdbc.TodoRepositoryIT.find_by_id(TodoRepositoryIT.java:48)
```

where the important is:

```
Null argument specified for [doneDate]. If this argument is allowed to be null annotate it with @Nullable
```

If you run the same example using the old `javax.annotation.Nullable`, all works fine.

Thanks a lot!

### Steps To Reproduce

1. Open file https://github.com/archimedes-projects/archimedes-maven-micronaut-examples/blob/main/micronaut-java-parent-example/domain/src/main/java/io/archimedesfw/maven/micronaut/example/todo/Todo.java
2. Uncomment line 3 to use `import io.micronaut.core.annotation.Nullable`
3. Comment line 10 so you don't use `javax.annotation.Nullable`
4. Run `mvn clean install` to build the project
5. You will wee the error in the console

### Environment Information

- macOS 11.5.2
- Java 11.0.11, vendor: AdoptOpenJDK
- Maven 3.8.2

### Example Application

https://github.com/archimedes-projects/archimedes-maven-micronaut-examples/tree/main/micronaut-java-parent-example

### Version

3.0.0

**Comment by dstepanov** [comment]
You need to have the annotation specified on the constructor, I suspect that Lombok copies some default list of annotations.

The solution is to add `lombok.config` with:
```
lombok.copyableAnnotations += io.micronaut.core.annotation.Nullable
```

**Comment by graemerocher** [comment]
Lombok 😱🙄

**Comment by alejandropg** [comment]
hehehehe @graemerocher ok, ok, I'm not a big fan of Lombok too but, why not? 😂😂😂🙈

I tested the @dstepanov solution and works really fine 👌

If you are curious you have the complete example in https://github.com/archimedes-projects/archimedes-maven-micronaut-examples/tree/main/micronaut-java-parent-example

As always, really thanks a lot for your support 👏👏👏
