### ISSUE TITLE
Ambiguous documentation for optimistic locking

### ISSUE THREAD

**Issue by kibertoad** [micronaut-projects/micronaut-data#1125]
### Expected Behavior

Documentation clearly states that JDBC Micronaut Data does not support pessimistic locking.

### Actual Behaviour

There is a section underneath `JDBC Repositories`, which talks about optimistic locking, without saying anything that it is actually only supported for Hibernate: https://micronaut-projects.github.io/micronaut-data/latest/guide/#optimisticLocking

It would be less confusing if there was explicit mention that it is only applicable to Hibernate in this section.

If JDBC actually started supporting optimistic locking, then https://micronaut-projects.github.io/micronaut-data/latest/guide/#jdbc needs to be updated to say so.

### Version

latest

**Comment by uzoltan** [comment]
My issue might be because of this then? 
https://github.com/micronaut-projects/micronaut-data/issues/1133
