### ISSUE TITLE
Composed entity attributes are not mapped by micronaut data

### ISSUE THREAD

**Issue by msalaslo** [micronaut-projects/micronaut-data#113]
micronaut 1.2.0
micronaut-data 1.0.0.M1

Entity Attributes that are composed by two words are not mapped by micronaut data, for instance:
public String installationId --> is no mapped
public String serial --> is mapped

I don't have errors, but the entity returned by the queries doesn't contain composed attributes.

This is the entity object (getters and setters generated with Lombok):

```java
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Entity
@Table(name = "CAMERAPOC")
public class Camera implements Serializable{
	@Id
	public String serial;
	@GeneratedValue
	public int id;
	public String countryCode;
	public String installationId;
	public String zone;
	public String alias;
	public Date creationTime;
	public Date lastUpdateTime;
}
```

Attributes serial, id, zone and alias are returned properly.
Attributes 

Response JSON example:

```json
{
    "serial": "XXXXX",
    "id": 186749,
    "zone": "001",
    "alias": "TEST ALIAS"
}
```

This is the repository class:

```java
@Repository
public interface CameraRepositoryData extends PageableRepository<Camera, String>{
	public Camera findBySerial(String serial);
	public Camera findByCountryCodeAndInstallationIdAndZone(String countryCode, String installationId, String zone);
	public List<Camera> findByCountryCodeAndInstallationId(String countryCode, String installationId);
	public Page<Camera> findByZoneStartingWith(String zoneStarting, Pageable pageable);
	public List<Camera> findByCountryCodeAndInstallationIdAndZoneStartingWith(String countryCode, String installationId, String zoneStarting);
}
```

I have included the @MappedProperty but it doesn't solve anything, example with one attribute:

`@MappedProperty(value = "COUNTRY_CODE", definition = "COUNTRY_CODE")
	public String countryCode;`

I have included the @MappedEntity and namingStrategy, as far as I understand this enables the mapping the database field CAMERA_CODE with the Java entity attribute cameraCode:

`@MappedEntity(namingStrategy = NamingStrategies.UnderScoreSeparatedUpperCase.class)`

**Comment by msalaslo** [comment]
Micronaut Data creates new columns without underscore and does not map the original in the data base. For instance:
Original field: COUNTRY_CODE --> Micronaut Data mapped/created field: COUNTRYCODE

IT seems is ignoring: 
@MappedProperty(value = "COUNTRY_CODE", definition = "COUNTRY_CODE") public String countryCode;

and 
@MappedEntity(namingStrategy = NamingStrategies.UnderScoreSeparatedUpperCase.class)

**Comment by graemerocher** [comment]
Could be the use of lombok, unsure right now. Will investigate

**Comment by msalaslo** [comment]
Thank you for your answer. I will try without Lombok to confirm the issue.

**Comment by graemerocher** [comment]
Could you attach an example that reproduces the issue?

**Comment by msalaslo** [comment]
[micronaut-jpa-cache-master.zip](https://github.com/micronaut-projects/micronaut-data/files/3583364/micronaut-jpa-cache-master.zip)

Attached.
Mavenized project using Oracle 12c (keep in mind ojdbc12 driver in your maven settings) as database.

**Comment by msalaslo** [comment]
I have removed lombok from my DTO and Entity classes (default constructors and getter/setters added), but it doesn't solve the problem.
Attaching the project with this modification.
[micronaut-jpa-cache-master.zip](https://github.com/micronaut-projects/micronaut-data/files/3586597/micronaut-jpa-cache-master.zip)

**Comment by graemerocher** [comment]
This duplicates https://github.com/micronaut-projects/micronaut-data/issues/103

For customization when using JPA you should use JPA annotations so instead of `@MappedProperty` you use `@Column`
