### ISSUE TITLE
@where on supper class not working with micronaut-data-jdbc:3.0.0

### ISSUE THREAD

**Issue by funnyleolee** [micronaut-projects/micronaut-data#1136]
### Expected Behavior

We have a supper class as base entity

> import io.micronaut.data.annotation.Id;
> import io.micronaut.data.annotation.Where;
> import lombok.Getter;
> import lombok.Setter;
> import java.time.LocalDateTime;
> 
> @Setter
> @Getter
> @Where("@.deleted = false")
> public class BaseEntity {
>     &nbsp;&nbsp;&nbsp;&nbsp;@Id
>     &nbsp;&nbsp;&nbsp;&nbsp;private String id;
>     &nbsp;&nbsp;&nbsp;&nbsp;private String updateBy;
>     &nbsp;&nbsp;&nbsp;&nbsp;private LocalDateTime updateTime;
>     &nbsp;&nbsp;&nbsp;&nbsp;private String createBy;
>     &nbsp;&nbsp;&nbsp;&nbsp;private LocalDateTime createTime;
>     &nbsp;&nbsp;&nbsp;&nbsp;private boolean deleted;
> }

We use `@where("@.deleted = false")` as general query conditions.

Normal entity example

> import io.micronaut.data.annotation.MappedEntity;
> import lombok.Getter;
> import lombok.Setter;
> 
> @Getter
> @Setter
> @MappedEntity("t_unit")
> public class Unit extends BaseEntity {
>     &nbsp;&nbsp;&nbsp;&nbsp;private String name;
>     &nbsp;&nbsp;&nbsp;&nbsp;private Integer status;
> }

Add logback.xml SQL Logging  DEBUG configuration `<logger name="io.micronaut.data.query" level="DEBUG"/>`

With **micronaut-data-jdbc:2.5.12**  it working  well.
And SQL logger print:

> 11:54:09.120 [io-executor-thread-1] DEBUG io.micronaut.data.query - Executing Query: SELECT unit_."id",unit_."name",unit_."status",unit_."update_by",unit_."update_time",unit_."create_by",unit_."create_time",unit_."deleted" FROM "t_unit" unit_ WHERE (**unit_.deleted = false**)

### Actual Behaviour

When we upgrade to **micronaut-data-jdbc: 3.0.0**  it not working.
And SQL logger print:

> 11:57:51.268 [io-executor-thread-1] DEBUG io.micronaut.data.query - Executing Query: SELECT unit_."id",unit_."name",unit_."status",unit_."update_by",unit_."update_time",unit_."create_by",unit_."create_time",unit_."deleted" FROM "t_unit" unit_

### Environment Information

- Operating System: **Manjaro 21.1.1 Pahvo**
- Kernel: **x86_64 Linux 5.10.56-1-MANJARO**
- JDK Version: **Oracle JDK 1.8.0_301**

### Version

3.0.0

**Comment by graemerocher** [comment]
Looks like `@Where` is not meta annotated with `@Inherited`
