### ISSUE TITLE
Unsupported query with long camel case variable name

### ISSUE THREAD

**Issue by kosi96** [micronaut-projects/micronaut-data#115]
I can not make queries with variables that have a long camel case name.

```java
public class DeviceInfo {

    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    public Long id;

    private String manufacturerDeviceId;

    @ManyToOne
    @JoinColumn(name="manufacturer_id")
    public DeviceManufacturer manufacturer;
    public String name;
    public String description;
    public String deviceIp;

    public DeviceInfo() {
    }


    @Builder
    public DeviceInfo(Long id, String externalId, DeviceManufacturer manufacturer, String name, String description, String deviceIp) {
        this.id = id;
        this.manufacturerDeviceId = externalId;
        this.manufacturer = manufacturer;
        this.name = name;
        this.description = description;
        this.deviceIp = deviceIp;
    }}


public interface DeviceInfoRepository extends CrudRepository<DeviceInfo, Long> {

    DeviceInfo findByManufacturerDeviceId(String id);

    DeviceInfo findByName(String name);}

```

> Error:(10,16) java: Unable to implement Repository method: DeviceInfoRepository.findByManufacturerDeviceId(String id). Invalid query method [findByManufacturerDeviceId] of repository [si.kivik.api.infra.DeviceInfoRepository]: Cannot use [Equals] criterion on non-existent property path: manufacturerDeviceId

I would like to know if it will be resolved in the future?

**Comment by rickerju** [comment]
I have the same issue

**Comment by rickerju** [comment]
I have this same proplem. If there are 2 or more words in camelcase that error seems to be thrown.

for example a parameter named redWhiteBlue would fail. But a parameter named redWhite or red would succeed

**Comment by rickerju** [comment]
I have this same proplem. If there are 2 or more words in camelcase that error seems to be thrown.

for example a parameter named redWhiteBlue would fail. But a parameter named redWhite or red would succeed

**Comment by graemerocher** [comment]
An attached example would help narrow down the issue. Thanks
