### ISSUE TITLE
Cannot use @EntityGraph annotation to handle multiple nested properties of the same association with Hibernate-JPA

### ISSUE THREAD

**Issue by mstein** [micronaut-projects/micronaut-data#1160]
### Expected Behavior

Considering the following Entity classes : 
```groovy
@Entity
class Franchise {
    @Id
    Long id
    String name

    @OneToMany(mappedBy = 'franchise')
    Set<Media> medias
}

@Entity
class Media {
    @Id
    Long id
    String name

    @ManyToOne
    Franchise franchise

    @ElementCollection
    Set<String> alternateNames

    @OneToMany(cascade = CascadeType.ALL, orphanRemoval = true, mappedBy = 'media')
    Set<MediaTag> tags
}

@Entity
class MediaTag {
    @EmbeddedId
    MediaTagKey id

    @ManyToOne
    @MapsId('mediaId')
    @JoinColumn(name = 'media_id')
    Media media

    @ManyToOne
    @MapsId('tagId')
    Tag tag
    // ...
}
```
I omitted the `Tag` and `MediaTagKey` definition to make this example shorter, and their content isn't relevant to the problem.

I expect to be able to define an EntityGraph allowing a repository method to fetch the relations of the attributes in the specified paths, which may include nested properties from relations.

```groovy
interface FranchiseRepository extends CrudRepository<Franchise, Long> {
	@EntityGraph(attributeNames = ['medias.alternateNames', 'medias.tags.tag'])
	Optional<Franchise> findById(Long id)
}
```
The `findById` method should return a `Franchise` instance with its `medias` association eagerly fetched, and those `Media` should also have their `alternateNames` and `tags` associations eagerly fetched.

### Actual Behaviour

In the result of the `findById` method, only the `medias.tags.tag` relation is actually fetched, the `medias.alternateNames` collection is not fetched and will trigger a lazy load when the property is accessed.
Also note that if the order of paths are declared in the annotation is reversed, then it's the property declared last that is taken in account, the previous one is ignored : 
```groovy
// Declared in that order, medias.alternateNames is fetched, but not medias.tags.tag
@EntityGraph(attributeNames = ['medias.tags.tag', 'medias.alternateNames'])
```
Digging a bit in the code, it seems like the problem resides in the part of the code that build the entity graph from the collection of path provided : [HibernateJpaOperations.java#L438](https://github.com/micronaut-projects/micronaut-data/blob/5964f9766b1c5ee6939a2b57cb710c158b60bf90/data-hibernate-jpa/src/main/java/io/micronaut/data/hibernate/operations/HibernateJpaOperations.java#L438)

The code does not check if an existing subgraph was already created for a property, so it will create new subgraphs multiple times for the same property, overriding the previous one each time.
In the my last example, it's the `medias` property, which will create a subgraph first for the `medias.tags.tag` path, and then will override it when the loop will process the `medias.alternateNames` path.
It means that the way it is done right now, we cannot use `@EntityGraph` to fetch multiple nested relations on an association.

This can be confirmed by enabling DEBUG log on the package `org.hibernate.graph.internal` and triggering the repository method : 
```
01:38:57.291 [default-nioEventLoopGroup-1-2] DEBUG o.h.graph.internal.AttributeNodeImpl - Making sub-graph : ( (Media) medias )
01:38:57.292 [default-nioEventLoopGroup-1-2] DEBUG o.h.graph.internal.AttributeNodeImpl - Making sub-graph : ( (MediaTag) tags )
01:38:57.292 [default-nioEventLoopGroup-1-2] DEBUG o.h.graph.internal.AttributeNodeImpl - Making sub-graph : ( (Media) medias )
01:38:57.292 [default-nioEventLoopGroup-1-2] DEBUG o.h.graph.internal.AttributeNodeImpl - Adding sub-graph [org.hibernate.graph.internal.SubGraphImpl@4348c7d8] over-wrote existing [org.hibernate.graph.internal.SubGraphImpl@548c5665]
```
(as the last line shows, the "medias" subgraph was overwritten, so the first declaration was lost)

The code should implement a way to keep track of the created subgraphes and reuse the existing ones if multiple paths include the same association. For example keeping track of each subgraph created in a map with their path, and checking for each path if a subgraph exists for that path, or using a recursive function after building a tree from the attributeNames.
Maybe use as reference what they've done in spring-data for their [entity graph generation](https://github.com/spring-projects/spring-data-jpa/blob/ccf6039be5243de892598cc472039fbf53b6b67b/src/main/java/org/springframework/data/jpa/repository/query/Jpa21Utils.java#L159).

### Environment Information

- Operating System: Windows 10 Pro 21H1
- JDK version : Oracle JDK 16.0.2 (compilation target java 11)
- Groovy 3.0.8
- Micronaut 3.0.1, Micronaut-data 3.0.1

### Version

3.0.1

**Comment by mstein** [comment]
As additional note, it seems like #406 is still happening. After I tried to replace the `attributeNames` with a reference to a `@NamedEntityGraph` instead, I found that just specifying the name in the annotation was not enough to make it work : 

```groovy
// Doesn't work, the named graph defined on the Entity is just ignored
@EntityGraph('myNamedGraph')
```

The workaround described in #406 still seems to work, adding an empty `attributeNames` make it work :
```groovy
@EntityGraph(name = 'myNamedGraph', attributeNames = '')
```

From [HibernateJpaOperations.java#L427](https://github.com/micronaut-projects/micronaut-data/blob/5964f9766b1c5ee6939a2b57cb710c158b60bf90/data-hibernate-jpa/src/main/java/io/micronaut/data/hibernate/operations/HibernateJpaOperations.java#L427), the whole entity graph creation is skipped if there is no queryHint on the query.
In this case, a queryHint exists either by adding a `@QueryHint` annotation ([AbstractQueryInterceptor.java#L1083](https://github.com/micronaut-projects/micronaut-data/blob/5964f9766b1c5ee6939a2b57cb710c158b60bf90/data-runtime/src/main/java/io/micronaut/data/runtime/intercept/AbstractQueryInterceptor.java#L1083)) or provided by the underlying [operations implementation](https://github.com/micronaut-projects/micronaut-data/blob/5964f9766b1c5ee6939a2b57cb710c158b60bf90/data-runtime/src/main/java/io/micronaut/data/runtime/intercept/AbstractQueryInterceptor.java#L1094).

For `HibernateJpaOperations`, the query hint is only created if the `attributeNames` annotation value exists ([HibernateJpaOperations.java#L179](https://github.com/micronaut-projects/micronaut-data/blob/5964f9766b1c5ee6939a2b57cb710c158b60bf90/data-hibernate-jpa/src/main/java/io/micronaut/data/hibernate/operations/HibernateJpaOperations.java#L179)), thus if we only provide the name of a `@NamedEntityGraph`, it's not enough to actually get the entity graph generation.

**Comment by dstepanov** [comment]
@mstein Could you provide a PR with a fix?
