### ISSUE TITLE
(1.0.0-M1)Data reading issue when using DTO Projections with default naming strategy 

### ISSUE THREAD

**Issue by shawnone** [micronaut-projects/micronaut-data#117]
In DTOMapper, the name used for calling ResultSet's getXXX(String) methods comes from property.getPersistedName(), which is the name of the column. And in DTO Projections case, **AS clause** is used in the generated SQL, the name of the entity class member becomes the column label. The ResultSet's getXXX(String) methods needs a column label, so if you have member like userId, you get a SQL_STATE_COLUMN_NOT_FOUND error because user_id is not column label now. 

One solution is to set useColumnNamesInFindColumn=true in the jdbc connection string. But is it better to use property.getName() in DTOMapper to get the real column label for reading data?

**Comment by graemerocher** [comment]
Can you provide an example that reproduces the issue?

**Comment by shawnone** [comment]
Please check the attached example project. 
[hello-world.zip](https://github.com/micronaut-projects/micronaut-data/files/3566525/hello-world.zip)
