### ISSUE TITLE
Missing `io.r2dbc` dependencies in BOM with 3.0.2-SNAPSHOT

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-data#1174]
### Expected Behavior

It should be possible to define an R2DBC driver dependency without specifying the version, something like:
```
runtimeOnly "io.r2dbc:r2dbc-postgresql"
```

### Actual Behaviour

Starting with Micronaut Data 3.0.2-SNAPSHOT that is not possible anymore.

I have an application that uses R2DBC postgres driver. It uses Micronaut 3.0.1 and Micronaut Data 3.0.1. I'm able to resolve the r2dbc-postgresql dependency without specifying the version:

```
 gw dependencyInsight --configuration runtimeClasspath --dependency r2dbc-postgresql
Starting a Gradle Daemon, 1 stopped Daemon could not be reused, use --status for details

> Task :dependencyInsight
io.r2dbc:r2dbc-postgresql:0.8.7.RELEASE (by constraint)
   variant "runtime" [
      org.gradle.status              = release (not requested)
      org.gradle.usage               = java-runtime
      org.gradle.libraryelements     = jar
      org.gradle.category            = library

      Requested attributes not found in the selected variant:
         org.gradle.dependency.bundling = external
         org.gradle.jvm.environment     = standard-jvm
         org.gradle.jvm.version         = 8
   ]

io.r2dbc:r2dbc-postgresql:0.8.7.RELEASE
\--- io.r2dbc:r2dbc-bom:Arabba-SR9
     +--- io.micronaut.r2dbc:micronaut-r2dbc-bom:2.0.0
     |    +--- io.micronaut.data:micronaut-data-r2dbc:3.0.1
     |    |    +--- runtimeClasspath (requested io.micronaut.data:micronaut-data-r2dbc)
     |    |    \--- io.micronaut.data:micronaut-data-bom:3.0.1
     |    |         \--- io.micronaut:micronaut-bom:3.0.1
     |    |              +--- runtimeClasspath
     |    |              +--- io.micronaut.data:micronaut-data-r2dbc:3.0.1 (requested io.micronaut:micronaut-bom:3.0.0) (*)
     |    |              +--- io.micronaut.reactor:micronaut-reactor:2.0.0 (requested io.micronaut:micronaut-bom:3.0.0-RC1)
     |    |              |    +--- runtimeClasspath (requested io.micronaut.reactor:micronaut-reactor)
     |    |              |    +--- io.micronaut.data:micronaut-data-r2dbc:3.0.1 (*)
     |    |              |    +--- io.micronaut:micronaut-bom:3.0.1 (*)
     |    |              |    \--- io.micronaut.reactor:micronaut-reactor-http-client:2.0.0
     |    |              |         +--- runtimeClasspath (requested io.micronaut.reactor:micronaut-reactor-http-client)
     |    |              |         \--- io.micronaut:micronaut-bom:3.0.1 (*)
     |    |              +--- io.micronaut.r2dbc:micronaut-r2dbc-core:2.0.0 (requested io.micronaut:micronaut-bom:2.5.12)
     |    |              |    +--- runtimeClasspath (requested io.micronaut.r2dbc:micronaut-r2dbc-core)
     |    |              |    +--- io.micronaut.data:micronaut-data-r2dbc:3.0.1 (*)
     |    |              |    \--- io.micronaut.r2dbc:micronaut-r2dbc-bom:2.0.0 (*)
     |    |              +--- io.micronaut.data:micronaut-data-runtime:3.0.1 (requested io.micronaut:micronaut-bom:3.0.0)
     |    |              |    +--- io.micronaut.data:micronaut-data-bom:3.0.1 (*)
     |    |              |    \--- io.micronaut.data:micronaut-data-r2dbc:3.0.1 (*)
     |    |              +--- io.micronaut.data:micronaut-data-model:3.0.1 (requested io.micronaut:micronaut-bom:3.0.0)
     |    |              |    +--- io.micronaut.data:micronaut-data-bom:3.0.1 (*)
     |    |              |    +--- io.micronaut.data:micronaut-data-r2dbc:3.0.1 (*)
     |    |              |    \--- io.micronaut.data:micronaut-data-runtime:3.0.1 (*)
     |    |              +--- io.micronaut.data:micronaut-data-tx:3.0.1 (requested io.micronaut:micronaut-bom:3.0.0)
     |    |              |    +--- io.micronaut.data:micronaut-data-bom:3.0.1 (*)
     |    |              |    \--- io.micronaut.data:micronaut-data-model:3.0.1 (*)
     |    |              \--- io.micronaut.reactor:micronaut-reactor-http-client:2.0.0 (requested io.micronaut:micronaut-bom:3.0.0-RC1) (*)
     |    \--- io.micronaut:micronaut-bom:3.0.1 (*)
     \--- io.micronaut.r2dbc:micronaut-r2dbc-core:2.0.0 (*)

io.r2dbc:r2dbc-postgresql -> 0.8.7.RELEASE
\--- runtimeClasspath

(*) - dependencies omitted (listed previously)
```

When I force Micronaut Data to version 3.0.2-SNAPSHOT that doesn't work anymore:

```
$ gw dependencyInsight --configuration runtimeClasspath --dependency r2dbc-postgresql

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'micronaut-r2dbc-graal'.
> Could not resolve all files for configuration ':runtimeClasspath'.
   > Could not find io.r2dbc:r2dbc-postgresql:.
     Required by:
         project :
```

### Version

3.0.1 and Micronaut Data 3.0.2-SNAPSHOT

**Comment by dstepanov** [comment]
This is what I really don't understand, the BOM Gradle only collects the project artifacts.
It might have been caused by https://github.com/micronaut-projects/micronaut-data/commit/fc2f076c8359cb19c4d9bad1aa26d55fbdae4d28 but I have no idea how.
Maybe @melix can help 🙏

**Comment by dstepanov** [comment]
Also master should be 3.1 SNAPSHOT of course

**Comment by melix** [comment]
BOM imports, oh joy. This is the least understandable feature of all dependency management :/ @ilopmar would you mind sharing a reproducer, I'd like to understand how the dependencies are declared, it looks like it's an issue with replacing the import from the micronaut BOM with the `io.r2dbc:r2dbc-bom` directly.

**Comment by dstepanov** [comment]
@melix It would be nice to have the same Gradle improvements as Core too!

**Comment by melix** [comment]
I didn't check yet but the root cause might be the same as #6198

**Comment by ilopmar** [comment]
@melix reproducer:
- `mn create-app test-r2dbc --features data-r2dbc`
- It works

Add the snapshot repository and force the dependency:

```groovy
repositories {
    ...
    maven { url "https://s01.oss.sonatype.org/content/repositories/snapshots/" }
}

...

configurations {
    all {
        resolutionStrategy {
            eachDependency { DependencyResolveDetails details ->
                if (details.requested.group == 'io.micronaut.data') {
                    details.useVersion '3.0.2-SNAPSHOT'
                }
            }
        }
    }
}

...
```

Now it fails to resolve the `io.r2dbc:r2dbc-postgresql` dependency

**Comment by melix** [comment]
So the difference is in the `io.r2dbc:r2dbc-bom`
 BOM. With 3.0.1, we resolve version Arabba-SR9: https://ge.micronaut.io/s/dv7xapf2br6i6/dependencies?focusedDependencyView=versions&toggled=W1swXSxbMCwyXSxbMCwyLFszMDFdXSxbMCwyLFszMDZdXSxbMCwyLFszMDYsMjQ1XV0sWzAsMixbMzA2LDI0NSwxNjNdXSxbMCwyLFszMDYsMjQ1LDE2MywyNV1dXQ

This version contains an entry for `io.r2dbc:r2dbc-postgresql`: https://repo1.maven.org/maven2/io/r2dbc/r2dbc-bom/Arabba-SR9/r2dbc-bom-Arabba-SR9.pom

Starting from 3.0.2-SNAPSHOT, we resolve version Borca-M2: https://ge.micronaut.io/s/k2xgiine6cwqa/dependencies?focusedDependencyView=versions&toggled=W1swXSxbMCwwXSxbMCwwLFsyOTddXSxbMCwwLFsyOTcsMjU1XV1d

And this version **does not** declare a version for `io.r2dbc:r2dbc-postgresql`: https://repo1.maven.org/maven2/io/r2dbc/r2dbc-bom/Borca-M2/r2dbc-bom-Borca-M2.pom

It looks like the group id changed from `io.r2dbc` to `org.postgresql` in that BOM so it looks like a bug in `r2dbc`.

**Comment by dstepanov** [comment]
Ah yes, the dependency moved to `org.postgresql` BOM does work for us in the r2dbc module

**Comment by ilopmar** [comment]
Modifying the dependency to `runtimeOnly("org.postgresql:r2dbc-postgresql")` works again but I'm not sure if we should do it now. The resolved version is `0.9.0.M2` so probably it would be better to wait and not use a milestone version.

@dstepanov thoughts?

**Comment by dstepanov** [comment]
Hmm, yes using milestones probably is not the best idea... wdyt @graemerocher ?

**Comment by graemerocher** [comment]
all releases of r2dbc so far are milestones so I don't see how that is relevant?

**Comment by ilopmar** [comment]
The previous version is `0.8.7.RELEASE`. Even if it's not 1.0 yet, at least is not milestone...

**Comment by graemerocher** [comment]
Ok, although many things are broken in `0.8.7` but yeah get the point

**Comment by dstepanov** [comment]
I will use the previous release for now https://github.com/micronaut-projects/micronaut-data/pull/1180
Oracle Driver 0.3.0 will pull the latest API for testing but only for 11+
