### ISSUE TITLE
Leaking dependency of micronaut-data-tx to mictonaut-test

### ISSUE THREAD

**Issue by morki** [micronaut-projects/micronaut-data#1187]
### Expected Behavior

No warning is shown when using `micronaut-data-tx` without `micronaut-test` when building native image.

### Actual Behaviour

Warning is show during native image build.

> Warning: class initialization of class io.micronaut.transaction.test.$DefaultTestTransactionExecutionListener$Definition failed with exception java.lang.NoClassDefFoundError: io/micronaut/test/context/TestExecutionListener. This class will be initialized at run time because option --allow-incomplete-classpath is used for image building. Use the option --initialize-at-run-time=io.micronaut.transaction.test.$DefaultTestTransactionExecutionListener$Definition to explicitly request delayed initialization of this class.

### Steps To Reproduce

For example create empty Micronaut application with following dependencies and build native image:

```kotlin
micronaut {
    version("3.0.2")
    runtime("netty")
    processing {
        incremental(true)
    }
}

dependencies {
    implementation("io.micronaut:micronaut-runtime")
    implementation("io.micronaut.data:micronaut-data-tx")
    implementation("io.micronaut.sql:micronaut-jdbc-hikari")
    kapt("io.micronaut.data:micronaut-data-processor")
    runtimeOnly("ch.qos.logback:logback-classic")
    runtimeOnly("org.postgresql:postgresql")
}
```

### Environment Information

JDK version: GraalVM 21.2.0

### Version

3.0.2

**Comment by morki** [comment]
Oh, I found related PR #1114 from @ilopmar

**Comment by ilopmar** [comment]
We just need to bother @dstepanov so he merges it :laughing:
