### ISSUE TITLE
Question: how to use @Join for multi level?

### ISSUE THREAD

**Issue by adamatti** [micronaut-projects/micronaut-data#12]
Let’s say I have Country / State / City entities, how do I use @Join to fetch the second level? 

I tried something like: 

```
@Join(“state.city”) 
Optional<Country> findByName(String name)
```

and it didn’t work. Is it possible?

Thanks in advance.

**Comment by graemerocher** [comment]
Yeah that is in the todo list will get it working shortly. Thanks for the feedback

**Comment by graemerocher** [comment]
This does actually already work for single-ended associations

https://github.com/micronaut-projects/micronaut-predator/blob/master/predator-tck/src/main/groovy/io/micronaut/data/tck/tests/AbstractRepositorySpec.groovy#L344

The support for joining on multi-ended associations is more limited currently and is only supported for queries that return a single result. We will likely improve that over time.

The example you had that didn't work, I assume it was for multi-ended associations?

**Comment by adamatti** [comment]
Right, it was a multi-ended. Thanks @graemerocher

**Comment by graemerocher** [comment]
Joins for multi ended associations that return a single result does work too. We need to consider how far we go with this and whether we support allowing different fetch models such as performing an extra select in the case of returning multiple results and so on.

**Comment by Adva11** [comment]
Hi, 
does it make sense to have additional **parentAlias** property in **@Join** annotation so the builder could build the whole "tree" of joins based on the provided aliases?
E.g. 
```
@Join(value = “state”, alias="s")
@Join(parentAlias="s", value = “city”, alias="c") 
Optional<Country> findByName(String name)
```
Dot notation is more limited comparing to the several @Join properties imho.

**Comment by graemerocher** [comment]
How would this be different to?:

```
@Join("state")
@Join("state.city")
```

**Comment by Adva11** [comment]
Aliases could be convenient to reuse the same join:
```
@Join("state s")
@Join("s.city")
@Join("s.country")
```
And less string parsing. But agreed in general it's the same.

**Comment by graemerocher** [comment]
currently the same join is reused anyway. Closing this as I think it is complete
