### ISSUE TITLE
findById(UUID) does not work for MariaDB/MySQL

### ISSUE THREAD

**Issue by debuglevel** [micronaut-projects/micronaut-data#1210]
### Expected Behavior

```kotlin
@Entity
data class Animal(
    @Id
    @GeneratedValue
    var id: UUID?,
)
```

```kotlin
val animal = repository.save(Animal(null))
val foundAnimal = repository.findById(animal.id)
```

should get the saved object.

### Actual Behaviour

The resulting `Optional<Animal>` is empty with MariaDB and MySQL.

Works for PostgreSQL and H2.

### Steps To Reproduce

1. Clone https://github.com/debuglevel/issue-micronaut-data-1210
2. Run `./gradlew test`
3. `createAndExistsById` and `createAndFindById` will fail.

### Environment Information

- JDK: 1.8
- some Windows 10
- Used Micronaut Launch as a template
- MySQL (8, testcontainer) and MariaDB (10, testcontainer)

### Example Application

https://github.com/debuglevel/issue-micronaut-data-1210

### Version

3.1.3

**Comment by debuglevel** [comment]
`CrudRepository.update()` therefore also does not work, but has a rather unexpected behavior: It does not throw an Exception or something, but inserts a new record.

i.e.
```kotlin
val animal = repository.save(Animal(null))
[...]
repository.update(animalToUpdate)
```
results in two records.

This is really unexpected and might be quite hard to debug. Maybe micronaut-data could do some sanity checks here in case of something terrible happened?

**Comment by dstepanov** [comment]
This Hibernate specific issue, works for me:
```
@Entity
data class Animal(
    @Id
    @GeneratedValue(generator = "uuid2")
    @GenericGenerator(name = "uuid2", strategy = "uuid2")
    @Column(columnDefinition = "BINARY(16)")
    var id: UUID?,
)
```

**Comment by debuglevel** [comment]
I see. Is there anything Micronaut Data could do to circumvent this issue or point the developer towards this problem and how to fix it? Because finding out what the issue is and how to solve it could be quite time consuming (especially if e.g. H2 was used for development and everything worked fine there).

**Comment by dstepanov** [comment]
I don't see anything that can be done, we delegate all the operations to the Hibernate. You can try Micronaut Data JDBC, which might be enough for a simple scenario.
