### ISSUE TITLE
JPA: inconsistent setup documentation

### ISSUE THREAD

**Issue by esocode** [micronaut-projects/micronaut-data#1212]
When creating a new micronaut-data-hibernate-jpa project following the documentation the resulting application always received a "No backing RepositoryOperations configured for repository" error when accessing the repository. Only when analysing a project generated with Micronaut Launch I noticed that the dependency _io.micronaut.sql:micronaut-jdbc-hikari_ is needed for the JPA repository mapping to work. In the documentation it is mentioned only for the JDBC part. And in the Launch example it is added as a Gradle implementation dependency although `runtimeOnly` would be sufficient.

Especially the exception can be quite confusing for new users of Micronaut as the error message doesn't give any hint to the real problem. So if the Hikari dependency is really needed it should be mentioned for JPA as well.

**Comment by Goldmensch** [comment]
@dstepanov can be closed, since the need for a jdbc driver is already mentioned in the [Quick Start Section](https://micronaut-projects.github.io/micronaut-data/latest/guide/#hibernateQuickStart)
