### ISSUE TITLE
Generate Nullable relation to manage Zero-To-One relation  

### ISSUE THREAD

**Issue by msequino** [micronaut-projects/micronaut-data#1213]
### Feature description

Hi folks,
can micronaut-data-jdbc manage zero-to-one relations?

For example I have a parent class that may be linked to a child class.

`
MappedEntity

Data 

public class Parent {

  Id private Long id;

  Relation(value = Relation.Kind.ONE_TO_ONE) Optional<Child> child;

}
`

`
MappedEntity

Data  

public class Child {

  Id private Long id;
  Relation(value = Relation.Kind.ONE_TO_ONE, mappedBy = "parent") Parent parent;

}
`

Moreover, in test phase, these two entity generate the following code:

`
CREATE TABLE parent (`id` BIGINT AUTO_INCREMENT PRIMARY KEY,`child_id` BIGINT NOT NULL) -- child_id should be NULLABLE
`
`
CREATE TABLE child (`id` BIGINT AUTO_INCREMENT PRIMARY KEY)
`

I deleted all dot 'cause they mention other users

Thanks

**Comment by dstepanov** [comment]
@msequino Did you figure it out?

**Comment by msequino** [comment]
Hi @dstepanov not properly.
Is there a way to make a foreign key nullable?

**Comment by dstepanov** [comment]
It should work properly with optional, but we might have not correctly generated the schema, you can try to use flyway to generate db tables.

**Comment by msequino** [comment]
Now I moved to javax.persistence package.
With jdbc, I used MappedProperty to make it optional but it didn't work
