### ISSUE TITLE
Breaking Change for Kotlin coroutines - "Async return type doesn't support transactional execution."

### ISSUE THREAD

**Issue by MT-Jacobs** [micronaut-projects/micronaut-data#1216]
### Issue description

The [Micronaut Data 3.1.0 release](https://github.com/micronaut-projects/micronaut-data/releases/tag/v3.1.0) added Kotlin coroutine support.

This introduced a breaking change. Previously, one could use `suspend` functions in Micronaut Data `@Repository` interfaces just fine, though now attempting to do so can result in a `ConfigurationException` stating that "Async return type doesn't support transactional execution."

See the discussion [here](https://github.com/micronaut-projects/micronaut-data/pull/1165/files#r746080283) for more details, but in short, the prior suspending functions weren't _actually_ async but were instead using a `SynchronousTransactionManager`, and that "support" was removed.

Full disclosure, I'm doing this writeup expecting no code to be changed (though it'd be nice if this was documented as a breaking change or part of the documented requirements). I'm writing this so that Google searches will point developers to why their upgrade to 3.1.0+ isn't working.

All that said, hypothetical other developers, here are two workarounds:

1) Use a reactive transaction manager like [R2DBC](https://micronaut-projects.github.io/micronaut-r2dbc/latest/guide/). I haven't used this yet myself, but TransactionalInterceptor demands a [`ReactiveTransactionOperations` implementation](https://github.com/micronaut-projects/micronaut-data/pull/1165/files#diff-ad46901a48c0483178545c356c5828a4ebd2e0c5aa3f5b4c27cb4858d6973e77R104) to avoid throwing the `ConfigurationException`, and [DefaultR2dbcRepositoryOperations](https://github.com/micronaut-projects/micronaut-data/blob/8649d853b2a9096e259b234aef471c79da0a04c1/data-r2dbc/src/main/java/io/micronaut/data/r2dbc/operations/DefaultR2dbcRepositoryOperations.java#L130) is the only class that implements that interface so far.
2) Convert all your suspending functions in your repositories to non-suspending.

**Comment by zsiegel** [comment]
I just ran into this today! I have had success running against a SNAPSHOT of master that I pushed to my local maven. 

I am not exactly sure what changes occurred to address this but hopefully the next 3.1.3 release should be back to at least "working"?

**Comment by dstepanov** [comment]
Can somebody provide an example project that doesn’t work?

**Comment by zsiegel** [comment]
I have been playing around with this sample project and the current commit demonstrates the issue I think - https://github.com/zsiegel/micronaut-data-testing-ground
