### ISSUE TITLE
InvalidPathException when using join in Specification implementing PageableRepository, JpaSpecificationExecutor

### ISSUE THREAD

**Issue by brcina** [micronaut-projects/micronaut-data#1225]
### Expected Behavior

FindPageSpecificationInterceptor should not throw InvalidPathException when executing the count query

### Actual Behaviour

FindPageSpecificationInterceptor throws InvalidPathException when executing the count query

Line 100-118 in FindPageSpecificationInterceptor
```
...
typedQuery.setFirstResult((int) pageable.getOffset());
typedQuery.setMaxResults(pageable.getSize());
final List<Object> results = typedQuery.getResultList();
final CriteriaQuery<Long> countQuery = criteriaBuilder.createQuery(Long.class);
final Root<?> countRoot = countQuery.from(getRequiredRootEntity(context));
final Predicate countPredicate = specification.toPredicate(root, query, criteriaBuilder);
countQuery.where(countPredicate);
countQuery.select(criteriaBuilder.count(countRoot));

return Page.of(
        results,
        pageable,
        entityManager.createQuery(countQuery).getSingleResult()
);
```
Line 102 in FindPageSpecificationInterceptor executes without problem:
```
final List<Object> results = typedQuery.getResultList();
```
Using the same Predicate as in Line 105
```
final Root<?> countRoot = countQuery.from(getRequiredRootEntity(context));
final Predicate countPredicate = specification.toPredicate(root, query, criteriaBuilder);
```
But with the difference that is not creating the Predicate with the countRoot what results in a InvalidPathException:
```
14:32:10.625 [default-nioEventLoopGroup-1-5] ERROR o.h.hql.internal.ast.ErrorTracker -  Invalid path: 'generatedAlias1.nameDe'
org.hibernate.hql.internal.ast.InvalidPathException: Invalid path: 'generatedAlias1.nameDe'
	at org.hibernate.hql.internal.ast.util.LiteralProcessor.lookupConstant(LiteralProcessor.java:111)
```

### Steps To Reproduce

1. Create Entity class with a ManyToOne relationship
2. Create a repository Implementation implementing PageableRepository, JpaSpecificationExecutor
3. Write a Specification returning a Predicate joining on the ManyToOne
4.  Use it f.e. with Page page = findAll(spec,pageable)

### Version

3.1.4

**Comment by dstepanov** [comment]
Cannot find a way to reproduce it. Can you please create a sample project?

**Comment by ch0c4** [comment]
Thanks, it works perfectly
