### ISSUE TITLE
Problems with the Micronaut Data @Where since the last update

### ISSUE THREAD

**Issue by nfode** [micronaut-projects/micronaut-data#1233]
### Expected Behavior

After updating from micronaut 3.0.2 to 3.2.0 using the `@Where` annotation on an entity or a repository, no errors should occur, and the queries correctly should be appended with the `@Where` clause.

### Actual Behaviour

We did not find any information about `@Where` changes between micronaut 3.0.2 and 3.2.0, so we assume the 3.0.2 behaviour is the correct one.

When using `@Where` on an entity with nullable fields, the following exception (shortened) occurs:
```
Unexpected exception thrown: java.util.concurrent.CompletionException: io.micronaut.core.convert.exceptions.ConversionErrorException: Failed to convert argument [Object] for value [null] due to: Property of type [class java.lang.String] cannot be converted to type: class java.lang.Object
org.opentest4j.AssertionFailedError: Unexpected exception thrown: java.util.concurrent.CompletionException: io.micronaut.core.convert.exceptions.ConversionErrorException: Failed to convert argument [Object] for value [null] due to: Property of type [class java.lang.String] cannot be converted to type: class java.lang.Object
```

This can be reproduced using this test: https://github.com/flip-corp/micronaut-bugreports-demo/blob/a2fd0b7da38ef2f8d8883cf90d40e7de496769d2/src/test/kotlin/com/example/db/UserRepositoryWhereOnEntityTest.kt#L27

We tried using the Hibernate `@Where` annotation as a workaround, and this removed the error and also correctly filtered the queries.

We had some more troubles with the Micronaut `@Where` Annotation on a Repository. With the default  repository methods a new query projections, everything works fine. But at some places, we override built in methods for better typing. We have for example something like this (https://github.com/flip-corp/micronaut-bugreports-demo/blob/e177df6d2861646c25be42f68fd654f5e08fb2ba/src/main/kotlin/com/example/db/UserRepositoryWhereOnRepository.kt#L15):
```
override fun findById(id: UUID): Mono<UserWhereOnRepo>
```

This worked before, but now the clause in `@Where` is not appended. Using the `@Where` Annotation from Hibernate as a workaround on a repository does nothing, meaning the clause in `@Where` is not appended, neither when using built-in repository methods nor custom new projections.

### Steps To Reproduce

1. Checkout the demo project here: https://github.com/flip-corp/micronaut-bugreports-demo/tree/micronaut_data_where_annotation_problems
2. Run the tests here: https://github.com/flip-corp/micronaut-bugreports-demo/tree/micronaut_data_where_annotation_problems/src/test/kotlin/com/example/db

There are tests for the `@Where` annotation on the Entity (https://github.com/flip-corp/micronaut-bugreports-demo/blob/micronaut_data_where_annotation_problems/src/test/kotlin/com/example/db/UserRepositoryWhereOnEntityTest.kt) and for `@Where` on the repository (https://github.com/flip-corp/micronaut-bugreports-demo/blob/micronaut_data_where_annotation_problems/src/test/kotlin/com/example/db/UserRepositoryWhereOnRepositoryTest.kt)

### Environment Information

- JDK: openjdk 17
- kotlin: 1.6.0

### Example Application

https://github.com/flip-corp/micronaut-bugreports-demo/tree/micronaut_data_where_annotation_problems

### Version

3.2.0

**Comment by nfode** [comment]
@dstepanov thank you for the fast fix! I tested it with the 3.2.1 version in our demo project, it works for the `@Where` annotation on Entities, but when overriding a repository method the clause in the annotation is not appended to the query.

See her for an example: https://github.com/flip-corp/micronaut-bugreports-demo/blob/e177df6d2861646c25be42f68fd654f5e08fb2ba/src/main/kotlin/com/example/db/UserRepositoryWhereOnRepository.kt#L15
The corresponding test here fails: https://github.com/flip-corp/micronaut-bugreports-demo/blob/e177df6d2861646c25be42f68fd654f5e08fb2ba/src/test/kotlin/com/example/db/UserRepositoryWhereOnRepositoryTest.kt#L62

Is this wanted behavior? Then we need to stop overriding built-in repository methods.

**Comment by dstepanov** [comment]
I would expect it to work, probably a bug.

**Comment by nfode** [comment]
Are you then going to reopen this report, or should I open a new one?

**Comment by dstepanov** [comment]
Please create a new issue, thanks!
