### ISSUE TITLE
OptimisticLockException no longer thrown

### ISSUE THREAD

**Issue by tmalinakis-vng** [micronaut-projects/micronaut-data#1251]
### Expected Behavior

When using Micronaut JPA with Hibernate, an OptimisticLockException should be thrown when a Versioned object attempts to be updated with a mismatched version. This used to work up until Micronaut Data 3.2.0.

### Actual Behaviour

The transaction goes through and no exception is thrown.

### Steps To Reproduce

1. Save a dummy entity with a Version annotation.
2. Update the entity with Version 0. This should succeed.
3. Attempt to update the entity with Version 0 again. This should fail but it succeeds.

### Environment Information

JDK version: 17

### Version

Micronaut-Data 3.2.1

**Comment by dstepanov** [comment]
Are you using custom methods like `updateBy`?

**Comment by tmalinakis-vng** [comment]
Hi, no we don't.

**Comment by dstepanov** [comment]
Can you please provide a sample project?

**Comment by tmalinakis-vng** [comment]
I can't reproduce the issue in a small project. However, it appears to be working as expected in a production environment, so it's probably an issue with our tests. Apologies for the false alarm.

**Comment by dstepanov** [comment]
Thanks for the update!
