### ISSUE TITLE
Support Auto Commit semantics

### ISSUE THREAD

**Issue by evergreen-wq** [micronaut-projects/micronaut-data#1252]
### Expected Behavior

A number of JDBC drivers (Oracle in our case) use auto commit by default and doesn't require explicit commit to be issued. This is extremely handy for reads to reduce the latency.

### Actual Behaviour

Micronaut data (JDBC) always issues explicit commit regardless of the autoCommit setting used in connection pool setting.

### Environment Information

- Operating system: Windows 10
- JDK: 17

### Version

3.1.0

**Comment by dstepanov** [comment]
I'm adding a way to disable TX per operation https://github.com/micronaut-projects/micronaut-data/pull/1277
Is there anything else can be done?
