### ISSUE TITLE
Propagate R2DBC transaction in Kotlin coroutines

### ISSUE THREAD

**Issue by dstepanov** [micronaut-projects/micronaut-data#1276]
### Feature description

It would be nice to have transactional propagation working for coroutines and R2DBC

**Comment by marcmarcet** [comment]
Hi @dstepanov 

Could you clarify if this affects normal `@JdbcRepository` repositories?

I'm trying to use `@Transactional` with a `CoroutineCrudRepository` but transactions don't seem to work at all (throwing an exception doesn't rollback the changes) unless I make everything blocking.

I've seen #1274 so I'd assume that it should work in 3.3.0-M1, but no luck so far... can try to provide a minimal repro project if needed.

**Comment by dstepanov** [comment]
JDBC should work see test service from the PR PersonSuspendRepositoryService. Maybe if you can provide an example or extend existing test with your use-case I can take a look.

**Comment by marcmarcet** [comment]
Would you mind taking a very quick look to this minimal example? 

As it is now, the `companyRepository.count()`keeps increasing on every POST to /companies. However, if you remove all the `supend` modifiers and make everything blocking, it works as expected and always returns 0.

https://github.com/marcmarcet/micronaut-data-repro/blob/main/src/main/kotlin/com/example/Application.kt

**Comment by marcmarcet** [comment]
I've been debugging a little bit and it seems that at some point there is a call to `TransactionSynchronizationManager.getSynchronizations()` that ends up throwing a `IllegalStateException("Transaction synchronization is not active")` which seems to break the rollback.

But I have no idea what it means 😕

**Comment by dstepanov** [comment]
This should be working
