### ISSUE TITLE
`@ColumnTransformer` acts strange when a non-placeholder variant of `@` is in the string

### ISSUE THREAD

**Issue by Steven-M-Brown** [micronaut-projects/micronaut-data#1294]
### Expected Behavior

I expected `@ColumnTransformer` to only replace the exact string `@.` with `alias.`

At least that is the impression the documentation gave so if this is working as intended an update to clarity there may be in order.
https://github.com/micronaut-projects/micronaut-data/blob/master/src/main/docs/guide/sql/dbc/sqlMapping/columnTransformer.adoc

### Actual Behaviour

The `@.` is treated as regex matching `@` and any valid character (the call to `quoteReplacement` doesn't do anything since that only impacts `$` and `\\`) instead causing it to eat a character in a call to the transform function.

### Steps To Reproduce

Latest micronaut + micronaut-data + postgres.

Put this on a entity column:
```
  @ColumnTransformer(
      read =
          "pgp_sym_decrypt(column_name::bytea, 'amazingKeyWith@InIt')",
      write = "pgp_sym_encrypt(?, 'amazingKeyWith@InIt')")
```

Use the default crud repository to read/write it to the table.

Inspect the Introspected repository class's query and see that it was substituted wrong.

### Version

3.2.7 (found originally in 2.5.13)

**Comment by Steven-M-Brown** [comment]
Any chance of a back-port to the 2.5 series?

**Comment by dstepanov** [comment]
Probably not. Is there something that is blocking you to migrate to the latest version?
