### ISSUE TITLE
Update should update instead of create another new object

### ISSUE THREAD

**Issue by recursivecodes** [micronaut-projects/micronaut-data#1299]
### Expected Behavior

When calling `update` on a repository, the existing object should be updated.

### Actual Behaviour

A new object is inserted into the database.

Oddly, the console shows that a `replaceOne` was executed...

```
14:23:51.698 [default-nioEventLoopGroup-1-3] DEBUG io.micronaut.data.query - Executing Mongo 'replaceOne' with filter: {"_id": {"$oid": "61f19fb1ff9bdf0c6851a384"}}
```

### Steps To Reproduce

1. Check out https://github.com/recursivecodes/mn-atp-mongo
2. Connect to ATP instance
3. Issue a `POST` to insert a record
4. Issue a `PUT` to update the record
5. Query the database (or issue `GET` to `/book` to list records)
6. Observe two objects instead of one updated object

### Environment Information

-OSX Monterrey

### Example Application

https://github.com/recursivecodes/mn-atp-mongo

### Version

3.3.0-M1

**Comment by dstepanov** [comment]
I cannot reproduce it with MongoDB. I think there might be a problem with ATP implementation.
