### ISSUE TITLE
existsBy* throws exception for Reactive queries

### ISSUE THREAD

**Issue by lehotskysamuel** [micronaut-projects/micronaut-data#130]
Hi, I have the following repository:

```
@JdbcRepository(dialect = Dialect.POSTGRES)
public interface AccountRepository2 extends RxJavaCrudRepository<Account, UUID> {

    // existsByEmail method

}
```

When I declare **existsByEmail** method like this: ```Boolean existsByEmail(@NotBlank String email);```, everything works as it should but the query is not reactive.

When I try to declare the method reactively: ```Single<Boolean> existsByEmail(@NotBlank String email);```, I get the following exception:

```
{
  "message": "Internal Server Error: Error reading object for index [1] from result set: Cannot cast to boolean: \"4d8e34fa-7c9d-40da-b592-d0aac8b85814\"",
  "logref": null,
  "path": null,
  "_links": {},
  "_embedded": {}
}
```

I have other similar methods that are generated correctly, for example this one: ```Single<Account> getByEmail(@NotBlank String email);```. But existsBy* always fails on the above exception.

Is this a bug? Or is it not yet supported?

Thanks.

**Comment by graemerocher** [comment]
Seems very bug like to me
