### ISSUE TITLE
Add a MongoQueryExecutor interface that you can extend from

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-data#1306]
### Feature description

Similar to https://github.com/micronaut-projects/micronaut-data/blob/master/data-model/src/main/java/io/micronaut/data/repository/jpa/JpaSpecificationExecutor.java it should provide methods that take a MongoDB filter. See https://mongodb.github.io/mongo-java-driver/3.4/driver/getting-started/quick-start/#specify-a-query-filter

**Comment by dstepanov** [comment]
I would prefer to support something like: `Book find(@MongoFilter Bson filter)`

**Comment by dstepanov** [comment]
Even so, creating all possible method combinations with an interface would be nice.
