### ISSUE TITLE
findBy in JpaRepository throws EmptyResultException instead of returning null

### ISSUE THREAD

**Issue by weaser** [micronaut-projects/micronaut-data#1323]
### Expected Behavior

I expect a CRUD method like findByEmail in an JpaRepository to return null, when no entry is found in the mysql database.

`User findByEmail(String email);`

### Actual Behaviour

`User user = userRepository.findByEmail("xxx@example.com");`
results in an io.micronaut.data.exceptions.EmptyResultException

Checking for null `if(user==null)` is not reached.

### Steps To Reproduce

Executing a CRUD method in an JpaRepository with no expected results from the db table should reproduce it.

### Environment Information

- Windows 10
- Micronaut version 3.2.0
- Java version 11
- mysql 8.0.20 in docker

### Example Application

https://github.com/weaser/jpa-test

### Version

3.2.0

**Comment by graemerocher** [comment]
You have to annotate the return type with Nullable

**Comment by weaser** [comment]
OK, sorry, thanks! I migrated my code from Spring and could not figure out, why it was not working anymore. --Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 05.02.22, 20:32 schrieb Graeme Rocher ***@***.***>:

   
  You have to annotate the return type with Nullable

**Comment by weaser** [comment]
@graemerocher 
The Nullable solution did not work for me, at least I could not figure it out.
I do not know if the following solution is optimal, but it works for me.

Using `Optional<User> findByEmail(String email);` in the repository
and then after the call checking `user.isEmpty()`

**Comment by dstepanov** [comment]
@weaser I have added a test case that shows how to avoid ERE https://github.com/micronaut-projects/micronaut-data/pull/1349

**Comment by dstepanov** [comment]
Closing it as non-issue.
