### ISSUE TITLE
Select for Update default implementation in `AbstractSqlLikeQueryBuilder`

### ISSUE THREAD

**Issue by dzou** [micronaut-projects/micronaut-data#1330]
### Feature description

We recently upgraded micronaut versions and hit an error that Select For Update was not supported by `AbstractSqlLikeQueryBuilder`:

* In 3.1.2 this was a no-op: https://github.com/micronaut-projects/micronaut-data/blob/v3.1.2/data-model/src/main/java/io/micronaut/data/model/query/builder/AbstractSqlLikeQueryBuilder.java#L813
* In 3.2.6 this throws an error: https://github.com/micronaut-projects/micronaut-data/blob/master/data-model/src/main/java/io/micronaut/data/model/query/builder/AbstractSqlLikeQueryBuilder.java#L877

Wondering if there could just be a default impl that appends a `for update` to a select query in the right place? If not, then wanted to know why it is unimplemented, and how we could take advantage of it in repository methods?

**Comment by dstepanov** [comment]
The method is left for the actual implementation to be implemented, ordinary sql vs jpql.

What is your use case of implementing the builder?

**Comment by dzou** [comment]
Oh I get it. So we hit this error when using the [`JpaQueryBuilder`](https://github.com/micronaut-projects/micronaut-data/blob/master/data-model/src/main/java/io/micronaut/data/model/query/builder/jpa/JpaQueryBuilder.java):

```
For update not supported for current query builder: JpaQueryBuilder
```

So I think our real request is if `appendForUpdate` could be implemented for JpaQueryBuilder? Or at least understand the limitations better for why it was not implemented.

**Comment by dstepanov** [comment]
Correct me if i’m wrong but I don’t think JPA / Hibernate supports FOR UPDATE in the query. That’s why I added the error. Did it work for you before?

**Comment by dzou** [comment]
Ahh I see. I think it was just a no-op before and wasn't doing anything then.

From what i'm reading, it looks like in JPA that one needs to set the locking strategy to use "for update"? Like this: https://mobiarch.wordpress.com/2013/08/01/doing-select-for-update-in-jpa/

Is this something possible to set in the query builder? Or if not, how would we be able to use select-for-update functionality?

**Comment by dstepanov** [comment]
The best solution would be to introduce a new annotation that would have LockModeType and then set it in the Hibernate repository implementation.

**Comment by dzou** [comment]
Ok, thanks for the infos. Gonna close this.
