### ISSUE TITLE
Empty Postgres array e.g. `{}` in `VARCHAR(255) []` interpreted as Java's `new String[] { "{}" }`.

### ISSUE THREAD

**Issue by soberich** [micronaut-projects/micronaut-data#1334]
### Expected Behavior

Empty array stored/saved in Postgres e.g. `{}` in `VARCHAR(255) []` column should be extracted as Java's `new String[0]`.

### Actual Behaviour

Empty Posgres array `VARCHAR(255) []` interpreted as single value array with string `{}` e.g. `new String[] { "{}" }`.

### Steps To Reproduce

```java
package com.example;

import io.micronaut.data.annotation.TypeDef;
import io.micronaut.data.jdbc.annotation.JdbcRepository;
import io.micronaut.data.model.DataType;
import io.micronaut.data.model.query.builder.sql.Dialect;
import io.micronaut.data.repository.PageableRepository;
import io.micronaut.test.extensions.junit5.annotation.MicronautTest;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import lombok.Value;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

@MicronautTest(startApplication = false, rollback = false)
class SomeTest {

    @Value
    @Entity
    public static class Ent {
        @Id
        @GeneratedValue
        Long id;
        @TypeDef(type = DataType.STRING_ARRAY)
        String[] strings;
    }

    @JdbcRepository(dialect = Dialect.POSTGRES)
    public interface Repo extends PageableRepository<Ent, Long> {
    }

    @Test
    void someTest(Repo repo) {

        // Succeeds!
        assertThat(repo.save(new Ent(null, new String[0])).getStrings())
            .isEmpty();

        // FIXME: Fails!!!
        assertThat(repo.findById(1L).orElse(null).getStrings())
            .withFailMessage("Empty array e.g. '{}' in 'strings' column should have been extracted as Java String[0], but instead interpreted as single value array with string '{}'")
            .isEmpty();
    }
}

```

### Environment Information

- openjdk version "11.0.12" 2021-07-20
  OpenJDK Runtime Environment Homebrew (build 11.0.12+0)
  OpenJDK 64-Bit Server VM Homebrew (build 11.0.12+0, mixed mode)
- Darwin Kernel Version 21.4.0
- `micronaut-data-*:3.2.2`
- postgres jdbc driver `42.2.12`
- micronaut-plugin.version `3.1.1` 

### Version

3.3.1

**Comment by soberich** [comment]
Any comment here?
I now see that basically ANY array type is not usable, since any `JavaType[]` eventually interpreted by micronaut as `{JavaType[]}` upon extraction from resultset. So there is alway an error saying something like "`{sometype[]}` can't be extracted as `sometype[]`...
Also `@TypeDef` is completely ignored inside `@Embeddable` but this is a separate issue I discovered trying to resolve this one.

**Comment by dstepanov** [comment]
I will investigate it

**Comment by soberich** [comment]
I am not sure if it is by design that array coming from conversion is not handeded somehow natively by falls back to conversion service for converting from PgArray (which extends java.sql.Array, hence the assumption it may have been handled somehow more "natively") to String[], but the issue with that conversion service handling is that it tries to convert, doesn't find converter, widens the type eventually to conversion from Object.class to String[].class or say List<String> and at that moment just calls toString() on PgArray seeing it as Object.class. That's why it surrounded by curly braces.
Lookup of converter seems suboptimal, since it iterates through all the combinations of 150+ converters multiple times... seems every time it tries to extract String[] or List from PgArray.

**Comment by dstepanov** [comment]
I'm not able to reproduce it https://github.com/micronaut-projects/micronaut-data/pull/1348
Maybe it's driver version-related? Converters should be cached and only be resolved once.

**Comment by soberich** [comment]
Created now from


https://micronaut.io/launch?type=DEFAULT&name=demo&package=com.example&javaVersion=JDK_11&lang=JAVA&build=GRADLE&test=JUNIT&features=postgres&features=data-jdbc&version=3.3.3


https://github.com/soberich/micronaut-data-1334


<img width="1681" alt="image" src="https://user-images.githubusercontent.com/25544967/155005711-3420f9fa-d6dd-4444-8c7a-73e602bc4a1f.png">

**Comment by soberich** [comment]
Great! Thanks a lot!

**Comment by pyttel** [comment]
Great Job! Also a big thanks! This saved me a lot of time!
