### ISSUE TITLE
Certain property name creates duplicated columns in insert statement

### ISSUE THREAD

**Issue by sascha-frinken** [micronaut-projects/micronaut-data#1343]
### Expected Behavior

An entity with a property name as `s3Name` should not create an invalid insert query.

```groovy
@MappedEntity
class Test {
    @Id
    @AutoPopulated
    UUID id

   @NotBlank
    String s3Name
}
```

### Actual Behaviour

The insert query has to inserts for the column.

```sql
insert into test (…, `s3_name`, …, `s3_name`) values (…)
```

### Steps To Reproduce

https://github.com/safri-net/mn-data-issue-1343

### Environment Information

- OS: Linux
- JDK: zulu 17

### Version

3.3.3

**Comment by dstepanov** [comment]
Please provide a sample app.

**Comment by sascha-frinken** [comment]
@dstepanov any update?

**Comment by dstepanov** [comment]
It's more of Core issue that duplicated the properties

**Comment by sascha-frinken** [comment]
@dstepanov Do you want me to open a new issue?

**Comment by dstepanov** [comment]
Fixed in Core
