### ISSUE TITLE
`save(anEntity)` doesn't result in a record in the database when run in unit test

### ISSUE THREAD

**Issue by Gubaer** [micronaut-projects/micronaut-data#1347]
### Expected Behavior

This bug report is about a trivial use case: Saving a single entity to a Postgres database using `aCrudRepo.save(anEntity)`. Everything looks fine if the demo code provided in this [repo](https://bitbucket.org/gubaer/micronaut-data-sql-issue.git) is run (no errors reported in the log, no exceptions thrown) **but** if it runs in a unit test, the new record doesn't end up in the database. 

The use case is so trivial that I'm most likely doing something wrong. However, after reading the documentation and playing with variations of the code and the configuration of the data source, and the JDBC driver used, I didn't come up with something working.

So, maybe this is a bug, so I report it here.

1.  setup database (start a docker container with a postgresql database)
     ```bash
     ./gradlew startDevDatabase
    ```

2.  run the sample code as [application](https://bitbucket.org/gubaer/micronaut-data-sql-issue/src/ea316cbb64374f0aa92295a1a0e7b855a097ec97/src/main/kotlin/ch/guggis/micronaut/issue/App.kt#lines-33)

     ```bash
     # this should save a new record for the entity Message into the database
     ./gradlew run 
   
    # a new record is saved, check with ...
    export PGPASSWORD=test
    psql -h localhost -U postgres <<EOF
    select * from messages;
    EOF
    ```

3. run the sample code in a unit test

    ```bash
     # this should save a new record for the entity Message into the database.
     # The test report looks fine, no warnings, no errors, no exceptions.
     ./gradlew test -i --rerun-tasks --tests ch.guggis.micronaut.issue.MessageTest01
   
    # a new record **should** have been saved, but it isn't, check with ...
    export PGPASSWORD=test
    psql -h localhost -U postgres <<EOF
    select * from messages;
    EOF
    ```

The log in step (3) includes the following three lines which are missing after step (2):
```
11:41:34.575 [Test worker] DEBUG io.micronaut.transaction.jdbc.DataSourceTransactionManager - Initiating transaction rollback
11:41:34.576 [Test worker] DEBUG io.micronaut.transaction.jdbc.DataSourceTransactionManager - Rolling back JDBC transaction on Connection [HikariProxyConnection@1749978269 wrapping org.postgresql.jdbc.PgConnection@6b2e46af
11:41:34.577 [Test worker] DEBUG io.micronaut.transaction.jdbc.DataSourceTransactionManager - Releasing JDBC Connection [HikariProxyConnection@1749978269 wrapping org.postgresql.jdbc.PgConnection@6b2e46af] after transaction
```
Why does the transaction manager initiate a rollback when the code is run within a unit test? 

The repo includes two additional test case. 

The test case [MessageTest02](https://bitbucket.org/gubaer/micronaut-data-sql-issue/src/ea316cbb64374f0aa92295a1a0e7b855a097ec97/src/test/kotlin/ch/guggis/micronaut/issue/MessageTest.kt#lines-23) explicitly invokes `commit()` on the database connection **after** the test is run. Again, no errors nor exceptions are reported, but the new record is not in the database.

The test case [MessageTest03](https://bitbucket.org/gubaer/micronaut-data-sql-issue/src/ea316cbb64374f0aa92295a1a0e7b855a097ec97/src/test/kotlin/ch/guggis/micronaut/issue/MessageTest.kt#lines-44) explicitly invokes `commit()` on the database connection **at the end of the test method**. In this case, the new record ends up in the database, as expected.

### Actual Behaviour

Described above

### Steps To Reproduce

1. Clone the [sample repo](https://gubaer@bitbucket.org/gubaer/micronaut-data-sql-issue.git)

2. Run the steps described above

### Environment Information

Linux integrationbox-02 5.13.0-30-generic #33~20.04.1-Ubuntu SMP Mon Feb 7 14:25:10 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

openjdk 17.0.1 2021-10-19
OpenJDK Runtime Environment (build 17.0.1+12-Ubuntu-120.04)
OpenJDK 64-Bit Server VM (build 17.0.1+12-Ubuntu-120.04, mixed mode, sharing)

Micronaut 3.3.3

### Example Application

https://bitbucket.org/gubaer/micronaut-data-sql-issue.git

### Version

3.3.3

**Comment by dstepanov** [comment]
Tests are by default transactional and do the rollback after it's done. You can disable it by `@MicronautTest(rollback=false)`

**Comment by Gubaer** [comment]
Ah, thanks!

**Comment by markjfisher** [comment]
I've just come across this problem (my tests were working but no data in repo), and lucked out with a google search on this issue.

Is the `rollback=false` documented anywhere obvious?

I'm reading https://micronaut-projects.github.io/micronaut-data/latest/guide/ and the word rollback isn't mentioned on the page at all, so I'm not sure how we're supposed to discover this fact?
It's really useful to know, but it did lose me a couple of hours of head scratching.
Cheers, Mark

**Comment by markjfisher** [comment]
Eventually found it in https://micronaut-projects.github.io/micronaut-test/latest/guide/
for anyone else who finds this ticket.

**Comment by paulhilliar** [comment]
To help others.....
I ended up here because I had an entity with a field annotated @Id and a different field called "id"
And the Micronaut CrudRepository findById was favouring the id property over the field annotated @Id

I can see where it's coming from but it was kindof frustrating that it wasn't a validation error.
