### ISSUE TITLE
Colons in SQL strings in native queries doesn't work and can't be escaped (Postgres)

### ISSUE THREAD

**Issue by rehnarama** [micronaut-projects/micronaut-data#1354]
### Expected Behavior

You should be able to use colons as literals in SQL strings in native queries, or at least, escape them.

### Actual Behaviour

Compiler complains about no method parameter found for whatever is after the colon.

This used to work in earlier version when on micronaut 2 (started seeing the error after migrating to micronaut 3)

Similar issue from a long time ago: https://github.com/micronaut-projects/micronaut-data/issues/423 has there been a regression? 🤔

### Steps To Reproduce

First an entity pointing to some table in 
```java
@MappedEntity("some_table")
public record ColonEntity(String example) {
}
```

And then the repository
```java
@Repository("some_repository")
@JdbcRepository(dialect = Dialect.POSTGRES)
public interface SomeRepository {

    @Query(
        value = "SELECT 'one:two:three' as example",
        nativeQuery = true
    )
    ColonEntity reproduceColonError();

    @Query(
        value = "SELECT 'one\\:two\\:three' as example",
        nativeQuery = true
    )
    ColonEntity reproduceColonErrorEscaped();
}
```

Try to compile and you will get the error
```
Unable to implement Repository method: SomeRepository.reproduceColonError(). No method parameter found for named Query parameter: two
```
The same goes when trying to escape the colons in the second example function.

### Environment Information

- Windows
- JDK 17.0.0
- Micronaut data version=3.2.2
- io.micronaut.data:micronaut-data-jdbc:3.2.2
- io.micronaut.data:micronaut-data-model:3.2.2
- io.micronaut.data:micronaut-data-processor:3.2.2
- io.micronaut.data:micronaut-data-runtime:3.2.2
- io.micronaut.data:micronaut-data-tx:3.2.2

### Version

3.3.3

**Comment by graemerocher** [comment]
As a workaround you can put your queries in configuration, for example in `application.yml`:

```yaml
my:
   query: "SELECT 'one:two:three' as example"
```

And repository:

```
    @Query(
        value = "${my.query}",
        nativeQuery = true
    )
    ColonEntity reproduceColonError();
```
