### ISSUE TITLE
the document of finderpattern svg not found

### ISSUE THREAD

**Issue by ibmsoft** [micronaut-projects/micronaut-data#1358]
### Expected Behavior

5 Writing Queries
 Improve this doc
The implementation of querying in Micronaut Data is based on the dynamic finders in [GORM](https://gorm.grails.org/).

A pattern matching approach is taken at compilation time. The general pattern of query methods is:

### Actual Behaviour

<img width="496" alt="image" src="https://user-images.githubusercontent.com/26042/155881759-6bb5d429-dd90-433e-95ea-f18271779c18.png">

### Version

3.2.2

**Comment by graemerocher** [comment]
Works for me, can you try a different browser?

**Comment by ibmsoft** [comment]
it is ok now!
