### ISSUE TITLE
JDBC: update entities

### ISSUE THREAD

**Issue by dayanfcosta** [micronaut-projects/micronaut-data#136]
I'm trying to perform an update in my entities but I'm not even able to compile my project.
The source code is like this:

```
@JdbcRepository(dialect = Dialect.H2) 
public interface AccountRepository {
    @Query(value = "update account set balance = :balance where id = :id", nativeQuery = true)
     void update(@Id long id, BigDecimal balance);
}
```

but always I try to compile my code and run my tests I get these two messages:

> Error:(33, 8) java: Could not resolved root entity. Either implement the Repository interface or define the entity as part of the signature
Error:(33, 8) java: Unable to implement Repository method: AccountRepository.update(long id,BigDecimal balance). Unable to establish persistent entity to query for method: update

**Comment by lehotskysamuel** [comment]
Have you tried extending one of Micronaut's repository interfaces? E.g. ```public interface AccountRepository extends RxJavaCrudRepository<Account, TypeOfYourId>```

**Comment by graemerocher** [comment]
Yeah as a minimum you should extend `GenericRepository<Account, TypeOfYourId>` otherwise Micronaut cannot work out which entity the query is targeting

**Comment by dayanfcosta** [comment]
@lehotskysamuel and @graemerocher I haven't extend these classes because one of the requiremets is to don't use spring, and when I extend `GenericRepository` or `CrudRepository` it depends on spring to inject the hibernate `SessionFactory`, but I think I can teach the micronaut how to inject the hibernate's `SessionFactory` and it should work.
I'm gonna try this approach tonight.

**Comment by graemerocher** [comment]
@dayanfcosta I am not referring to Spring's version. see https://micronaut-projects.github.io/micronaut-data/latest/api/io/micronaut/data/repository/GenericRepository.html

**Comment by dayanfcosta** [comment]
@graemerocher I've tried to extends the `GenericRepository<Account, Long>`  and all my tests failed with the following message:
```
io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations]

Message: Missing bean argument value: transactionOperations
Path Taken: new DefaultJdbcRepositoryOperations(String dataSourceName,DataSource dataSource,[TransactionOperations transactionOperations],ExecutorService executorService,BeanContext beanContext)
```
I've found out that the interface `TransactionOperations` has only two implementations, which are Spring Implementations into micronaut packages.
Weird behavior, since just one test was failing and then all failed,

**Comment by dayanfcosta** [comment]
I removed all spring's dependencies from my project since it's a requirement.

**Comment by dayanfcosta** [comment]
I'm gonna close it because I found out that this module depends on Spring, so it's the root cause of the error I'm seeing.

**Comment by rdamus** [comment]
@dayanfcosta why did you close this?  i'm getting the exact same error.  it seems like the issue was never specifically resolved.

**Comment by dayanfcosta** [comment]
@rdamus this issue was discussed on gitter and this error is caused because, currently, the Data JDBC needs Spring's dependencies and when I remove them it isn't able to instanciate the needed classes. At least it's what I've understood, but in they're suposed to be removing these dependencies in some newer release.

**Comment by rdamus** [comment]
@dayanfcosta thanks for the info.
