### ISSUE TITLE
Make @ColumnTransformer behaviour available for repository method parameters

### ISSUE THREAD

**Issue by zoltan-toth-mw** [micronaut-projects/micronaut-data#1367]
### Feature description

Sometimes type casts are needed in the generated SQL, like in case of a user defined enum type in postgresql.
@ColumnTransformer supports that feature nicely but only on entity methods or fields.

If I want to filter by an enum type in a CrudRepository or PageableRepository , I need to write a custom query with a type cast to make it work, otherwise postgresql will throw an error as it doesn't know how to filter by a varchar input on an enum type.

```
 @Query(value = "select * from holder h where h.kind = CAST(:kind AS holder_kind)",
        nativeQuery = true,
        countQuery = "select count(*) from holder h where h.kind = CAST(:kind AS holder_kind)")
    Page<HolderEntity> findByKind(HolderKind kind, Pageable pageable);
```

**It would be much cleaner if @ColumnTransformer  could be applied on repository method parameters too.**
An example of the code above if the feautre was supported:
```
 Page<HolderEntity> findByKind(@ColumnTransformer(writer="?::holder_kind") HolderKind kind, Pageable pageable);
```

**Comment by dstepanov** [comment]
Which versions are you using? This should be supported if the transformer is defined on the property

**Comment by zoltan-toth-mw** [comment]
@dstepanov 
Micronaut version is 3.2.7 which imports micronaut data 3.2.2

**Comment by zoltan-toth-mw** [comment]
Added it to the field:
```
@MappedEntity("holder")
public class HolderEntity extends Metadata {

    // [...]
    
    @ColumnTransformer( write = "?::holder_kind")
    @NotNull
    private Kind kind;
    
    // [...]
}
```

The repo method looks like this:

```
  Page<HolderEntity> findByKind(HolderEntity.Kind kind, Pageable pageable);
```

The argument "kind" was not casted.
```
15:24:57.756 [main] DEBUG io.micronaut.data.query - Executing Query: SELECT holder_entity_."id",holder_entity_."version",holder_entity_."name",holder_entity_."adict_rules",holder_entity_."kind",holder_entity_."updated_at",holder_entity_."created_at" FROM "holder" holder_entity_ WHERE (holder_entity_."kind" = ?) LIMIT 10 
15:24:57.756 [main] TRACE io.micronaut.data.query - Binding parameter at position 1 to value PUBLISHER with data type: STRING
```

**Comment by dstepanov** [comment]
Try to define the read value for the transformer, you might want to use @ as a placeholder for the table alias.

**Comment by zoltan-toth-mw** [comment]
@dstepanov I tried that too earlier, that doesn't help either, it is not applied on the parameter.

```
    @ColumnTransformer(read = "@.kind::holder_kind", write = "?::holder_kind")
    @NotNull
    private Kind kind;
    
     Executing Query: SELECT holder_entity_."id",holder_entity_."version",holder_entity_."name",holder_entity_."adict_rules",holder_entity_.kind::holder_kind AS kind,holder_entity_."updated_at",holder_entity_."created_at" FROM "holder" holder_entity_ WHERE (holder_entity_.kind::holder_kind = ?) LIMIT 10 
09:28:35.414 [main] TRACE io.micronaut.data.query - Binding parameter at position 1 to value PUBLISHER with data type: STRING

```

**Comment by zoltan-toth-mw** [comment]
Implicit cast is already in place, that doesn't help. We don't need  @ColumnTransformer at all for save,update,get as they work because of the implicit cast, I tried it because of your suggestion.  Postgres doesn't do implicit cast in this case, in filtering context. Creating a custom database operator is difficult, error prone and over kill so that is not an option.

**Comment by dstepanov** [comment]
I see, the solution might be to add the value transformer.

**Comment by dstepanov** [comment]
This should fix your case https://github.com/micronaut-projects/micronaut-data/pull/1501
