### ISSUE TITLE
CrudRepository#find returns no entity if no values can be joined

### ISSUE THREAD

**Issue by Goldmensch** [micronaut-projects/micronaut-data#1382]
### Expected Behavior

```java
@MappedEntity("templates")
public record Template(
    @JsonIgnore
    @Id @GeneratedValue
    int id,

    String name,
    @Relation(value = Kind.ONE_TO_MANY, mappedBy = "template", cascade = Cascade.ALL)
    List<Question> questions
) {}
```
```java

@MappedEntity("questions")
public record Question(

    @JsonIgnore
    @Id @GeneratedValue
    Integer id,

    @JsonIgnore
    @Nullable
    @Relation(Kind.MANY_TO_ONE)
    Template template,

    int number,
    String question
) {}

```

```java
@JdbcRepository
public interface TemplateRepo extends CrudRepository<Template, Integer> {
  @NotNull
  @Join("questions")
  Optional<Template> findByName(String name);
}
```

Database is filled with templates without questions.
Expected: Return an Templates with an empty list of questions.

### Actual Behaviour

Returns an empty optional.
Same problem with TemplatesRepo#findAll (implementation with join), it returns an empty List.
Templates with questions are returned by both methods.

### Environment Information

- Manjaro Linux
- Java 17
- postgres database

### Version

3.3.4

**Comment by Paullo612** [comment]
Hmmm. Seems like you've missed a join spec.

Please try this:
```java
@JdbcRepository
public interface TemplateRepo extends CrudRepository<Template, Integer> {
    @NotNull
    @Join(value = "questions", type = Join.Type.LEFT_FETCH)
    Optional<Template> findByName(String name);
}
```

**Comment by dstepanov** [comment]
You need to make sure the join is of the correct type, some of them will not return any rows when there is no match.

**Comment by Goldmensch** [comment]
> You need to make sure the join is of the correct type, some of them will not return any rows when there is no match.

Yeah, that was my fault here. LEFT_FETCH solved it :+1:
