### ISSUE TITLE
StackOverflow Error trying to save child of parent to child relationship

### ISSUE THREAD

**Issue by markjfisher** [micronaut-projects/micronaut-data#1383]
### Expected Behavior

I can create one to many relationships in a parent / child setup using kotlin data classes, and the child refers back to the parent

### Actual Behaviour

I get a stackoverflow trying to save the child data after setting its backreference to the parent.
The stackoverflow is given in the readme of the example project.

### Steps To Reproduce

Download the application example given below and run the tests.
Additional notes are in the README.

I don't understand if I'm doing something wrong in setting up the one to many relationship, but finding decent documentation or concrete examples for this is very sparse or very old.

### Environment Information

Linux Ubuntu Java 11.
The example application was built from using mn cli with command:
```bash
mn create-app -l kotlin -t junit -b gradle -f data-jpa,jdbc-hikari,h2,hibernate-jpa mn-data
```

### Example Application

https://github.com/markjfisher/mn-data

### Version

3.3.4

**Comment by markjfisher** [comment]
I've found if I implement simple hashCode and equals methods (as in PostComment class [here](https://vladmihalcea.com/the-best-way-to-map-a-onetomany-association-with-jpa-and-hibernate/)) then I can save the relationship.

e.g. for the Pack data class
```kotlin
    override fun hashCode(): Int {
        return javaClass.hashCode()
    }

    override fun equals(o: Any?): Boolean {
        if (this === o) return true
        return if (o !is Pack) false else id == (o as Pack).id
    }
```

**Comment by dstepanov** [comment]
I don't think we can do anything about it. It looks like Kotlin generates equals/hashcode which includes a circular reference.

**Comment by markjfisher** [comment]
Thanks for confirmation, I'm using IntelliJ's "equals/hashcode generate" to build custom versions as the data model evolves. Also need to do custom toString() as the debugger can't display the entities for the same reason when it tries to build a string representation of the class.
