### ISSUE TITLE
JDBC: java.sql.SQLSyntaxErrorException when having table name with - character

### ISSUE THREAD

**Issue by sromic** [micronaut-projects/micronaut-data#140]
Micronaut v 1.2.0
Micronaut Data Jdbc v. 1.0.0.M1
JVM Version: 1.8.0_172
MySQL 8.0

Table name contains "-" and looks like: **T-Table-Ratings**.
So in order to execute SQL with this table name, this should be quoted as: 'T-Table-Ratings' (at least that's the case for MySQL)

Example model entity:

```
@MappedEntity(value = "`T-Table-Ratings`")
@Data
public class Table1 {
    @Id
    private final Long id;

    @MappedProperty(value = "`T-Rating`", type = DataType.INTEGER)   
    private final int rating;
}
```

and repository:

```
@JdbcRepository(dialect = Dialect.MYSQL)
public interface Table1Repository extends CrudRepository<Table1, Long> {
    @Query(value = "SELECT * FROM `T-Table-Ratings`")
    Stream<Table1> streamAll();
}

```

Getting this error when any of repository methods are executed:
 _

> **java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''T-Table-Ratings' 'T-Table-Ratings'_'**

_ 

As from generated SQL, problem here is incorrectly generated table alias: **'T-Table-Ratings'_** which is causing above error.

**Comment by graemerocher** [comment]
I have enabled the ability to escape table/column names in generated queries. See https://github.com/micronaut-projects/micronaut-data/commit/948fc9a0fc7dfe7ab8f2e0066e66546e0dd93ba4#diff-50362e33ad5703881fb80fe7456a12d0R17 for documentation.
