### ISSUE TITLE
micronaut-data on Oracle database

### ISSUE THREAD

**Issue by p4vl1n** [micronaut-projects/micronaut-data#1406]
### Expected Behavior
Actually this is related to micronaut-data package : 
When fetching nested entities using the @Join annotation the select should return all the data from the database
For example :
SELECT P."ID",P."NAME",P."AGE",P."ADDRESS_ID",a."VERY_LONG_COLUMN_NAME_30_CHARS" AS avery_long_column_name_30_chars,a."ANOTHER_VERY_LONG_COLUMN_NAME" AS aanother_very_long_column_name FROM "PERSON" P LEFT JOIN "ADDRESS" a ON P."ADDRESS_ID"=a."ID"

### Actual Behaviour

"Internal Server Error: SQL Error executing Query: ORA-00972: identifier is too long\n"

### Steps To Reproduce

1. Start Oracle using public docker image : https://hub.docker.com/r/oracleinanutshell/oracle-xe-11g
2. Execute DDL script attached to the project
3. Start micronaut application
4. Hit the endpoint http://localhost:8080/person
5. Instead of returning data an error is produced  ORA-00972: identifier is too long

### Environment Information

OS - WIndows
Java 11
Oracle 11g

### Example Application

https://github.com/p4vl1n/join-oracle-problem

### Version

3.4.0

**Comment by shingjo** [comment]
@p4vl1n Can you update your example with a test case that highlights your issue? 

It makes our lives easier if the example application creates the database, tables and populates them with sample data.

**Comment by p4vl1n** [comment]
@shingjo Actually no need for sample data to see the problem :
```
20:25:35.952 [DEFAULT-nioEventLoopGroup-1-3] DEBUG io.micronaut.data.query - Executing Query:
SELECT
	P."ID",
	P."NAME",
	P."AGE",
	P."ADDRESS_ID",
	a."VERY_LONG_COLUMN_NAME_30_CHARS" AS **avery_long_column_name_30_chars**, -- <=  ORACLE 11 COMPLAINS
	a."ANOTHER_VERY_LONG_COLUMN_NAME" AS aanother_very_long_column_name
FROM
	"PERSON" P
LEFT JOIN "ADDRESS" a ON
	P."ADDRESS_ID" = a."ID"
```

In Oracle 11  identifiers must be no longer than 30 characters while micronaut-data creates identifiers with 31 characters because it combines table name ( at least 1 character ) with the column name ( 30 characters )

**Comment by dstepanov** [comment]
The only way would be to introduce a custom alias for properties and you would need to define it manually using `@MappedProperty(alias = "myal")`

**Comment by p4vl1n** [comment]
> The only way would be to introduce a custom alias for properties and you would need to define it manually using `@MappedProperty(alias = "myal")`

That's perfect. Actually we were intuitively searching for "alias" in @MappedProperty :)

**Comment by graemerocher** [comment]
if there is something we can do to improve the docs in this area let us know

**Comment by p4vl1n** [comment]
> @MappedProperty
Currently MappedProperty do not support "alias" parameter so first it should be implemented then improve the documents IMHO

**Comment by graemerocher** [comment]
sorry misinterpreted Denis' comment, yes it makes sense
