### ISSUE TITLE
Add support postgresql json type

### ISSUE THREAD

**Issue by altro3** [micronaut-projects/micronaut-data#1408]
### Feature description

Currently, only the binary format is supported - jsonb in postgres, but there is another type - json - for the string representation of jsons in the database. Differs from text in that postgres allows you to add selectors on json fields.

Hibernate supports both types correctly. I think it would be cool if micornaut supported both types too

**Comment by dstepanov** [comment]
What doesn't work with the JSON type? Can you please post a link to the Postgres documentation where it mentions the difference?

**Comment by altro3** [comment]
@dstepanov Hi! Sorry, I misunderstood the `@TypeDef(type = DataType.JSON)` type definition. I thought that there is some kind of separation between binary jsonb and json in micronaut, but I checked both variants- everything works correctly.

It might be worth adding a note in the documentation that everything works correctly for both types, because in hibernate they are different type sand this can lead to a misunderstanding, as I have
