### ISSUE TITLE
findOne generate a wrong query

### ISSUE THREAD

**Issue by dykim-sfive** [micronaut-projects/micronaut-data#1433]
### Expected Behavior

<pre>
@Repository
interface ReservationRepository : JpaRepository<ReservationEntity, Long> {
       // select * from reservation where status = ?
       fun findOneByStatus(status: String): ReservationEntity? 
       // select * from reservation where status = ?
       fun findFirstByStatus(status: String): ReservationEntity?
}
</pre>
findOneByStatus generate sql without 'limit'
Hibernate: select reservatio0_.id as id1_35_, reservatio0_.customer_name as customer5_35_, reservatio0_.status as status28_35_, from service.reservation reservatio0_ where reservatio0_.status =? limit ?

### Actual Behaviour

api request All entity without limit And pick one after fetching all entity

but works with 'limit'
<code>
fun findOneByStatus(status: String): List<ReservationEntity>
</code>

### Environment Information

1. kotlin 1.6.10
2. micronaut-data 3.0.1
3. jdk 16

### Version

3.0.1

**Comment by dstepanov** [comment]
Why do you need a find one query without limit?

**Comment by dykim-sfive** [comment]
@dstepanov sorry for by wrong desicription.
"findOneByXXXX : Entity?" generate query without 'limit 1' so it request all entity from DB.

**Comment by dstepanov** [comment]
`findOne` is intended for fetching one result if you want multiple records, use `findAll` and a collection result.

**Comment by dstepanov** [comment]
Ah yes, I see that the Hibernate code is using `iterator.next()`. I will investigate what is a better solution.
