### ISSUE TITLE
LazyLoadException when Lazy Loading an entity on non-default datasource

### ISSUE THREAD

**Issue by LajosPolya** [micronaut-projects/micronaut-data#1438]
### Expected Behavior

The Lazy Loaded child entity is fetched.

### Actual Behaviour

A LazyLoadException is thrown when the LazyLoaded child entity is fetched.

### Steps To Reproduce
I have step by step instructions in the attached GitHub link.

1. Create two Datasources both connected to the same database. (In my production env one datasource is connected to a read-only instance)
2. Create a repository with two instances, one for the default datasource and one for the other datasource.
3. Write APIs to create and fetch the entities
4. Create the entity
5. Fetch the entity from the non-default datasource
6. Fetch the entity's child entity (make sure it's Lazy Loaded)
7. Exception will be thrown.

I have an example application attached.

### Environment Information

OS: Windows 10 and Mac Monterey (run within IntelliJ)
JDK: 11 and 16
Micronaut 3.4.1

### Example Application

https://github.com/LajosPolya/Micronaut-3.4.1-MultiDataSource

### Version

3.4.1

**Comment by dstepanov** [comment]
Please create a test case and integrate with testcontainer if you need real db

**Comment by radovanradic** [comment]
Updating annotation on method `Service.readOnlyExecutable` to `@TransactionalAdvice(readOnly = true, value = "readonly")` seems to resolve the issue.

**Comment by radovanradic** [comment]
Related documentation: https://micronaut-projects.github.io/micronaut-data/latest/guide/#dbcRepositories

Closing now as no code changes are needed, imo. If still see issues, please reopen
