### ISSUE TITLE
Extra SQL update being performed when PrePersistEventListener

### ISSUE THREAD

**Issue by ramiroeruiz** [micronaut-projects/micronaut-data#1441]
### Expected Behavior

Hello everyone
I've come to a bug or unexpected behavior
I came to the conclusion that when an object is saved and this object is attach to a PrePersistEventListener, an extra sql update is being performed

In the sample project I provide 2 test classes:
- **ContactCRUDTest** creates a new **Contact,** asserts the initial version is 0, then performs an update and asserts version is modified to 1. This test works as expected.
- **AuditContactCRUDTest** created a new **AuditContact** asserts the initial version is 0, then performs an update and asserts version is modified to 1. **This tests fails as the initial version turns out to be 1**

You may notice there is a AuditContactListener factory class that listens to and performs a logic before an AuditContact is persisted and before an AuditContact is updated.
this is based on the doc [https://micronaut-projects.github.io/micronaut-data/latest/guide/#entityEvents](https://micronaut-projects.github.io/micronaut-data/latest/guide/#entityEvents)

When checking the logs, I can see that when AuditContactRepository.save(AuditContact) is called, an sql insert is performed and **right away also an sql update is performed**. And I suppose this is related to the PrePersistEventListener but I couldn't find it on the micronaut-data repo.

### Steps To Reproduce

A sample github project is provided
The Test Class ContactCRUDTest reproduces the expected behaviour when no audit fields are present.
The Test Class AuditContactCRUDTest reproduces the error when audit fields are present.

### Environment Information

OS Ubuntu 20.04.4 LTS
JDK 17.0.2

### Example Application

https://github.com/ramiroeruiz/mnatPrepersistPoc

### Version

micronautVersion=3.4.1

**Comment by dstepanov** [comment]
Please integrate testcontainers so no DB needs to be started locally.

**Comment by ramiroeruiz** [comment]
Hello @dstepanov 
Just updated the project and now it is integrated with testcontainers
Thanks

**Comment by dstepanov** [comment]
Looks like that's the correct behavior for Hibernate which can be avoided by modifying the entity state, look for the example https://github.com/micronaut-projects/micronaut-data/pull/1563

You might want to try Micronaut Data JDBC to avoid using Hibernate.
