### ISSUE TITLE
JPA: Repository support for UPDATE queries with Postgres text[] type

### ISSUE THREAD

**Issue by svepemar** [micronaut-projects/micronaut-data#147]
Hello,

I'm using MicronautData with JPA together with Postgres database and I'm not able to create Repository **update** method that would update a column with _text[]_ type.

**Project setup:**
* database: Postgres
* connection-pool: micronaut jdbc hikari
* JPA: micronautdata hibernate JPA
* micronaut version: latest (tried both M1 and build-snapshot)

**Class with the entity:**
```
@Entity
@Table(name = "policy")
class Policy {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private long id;

    @Column(name = "policy_name")
    private String policyName;

    @Type(type = "my.package.StringArrayType")
    @Column(name = "issue_labels", columnDefinition = "text[]")
    private Set<String> issueLabels;

    @Column(name = "strategy_name")
    private String strategyName;

    // Constructors and getters/setters
}
```

**Repository for Policy class:**
```
@Repository
public interface PolicyRepository extends RxJavaCrudRepository<Policy, Long> {

    Single<Long> updateById(
            @Id Long id,
            String policyName,
            Set<String> issueLabels,   // PROBLEMATIC PARAMETER
            String strategyName);

    // other methods
}
```

Since Hibernate does not support Postgres Array types by default, I've created custom UserType to map java Set of strings to Postgres _text[]_ array. This type is referenced in Policy.class with `@Type(type = "my.package.StringArrayType")`.

```
public class StringArrayType implements UserType {
    private final int[] arrayTypes = new int[] {Types.ARRAY};

    @Override
    public int[] sqlTypes() {
        return arrayTypes;
    }

    @Override
    public Class<Set> returnedClass() {
        return Set.class;
    }

    @Override
    public boolean equals(Object x, Object y) throws HibernateException {
        return x == null ? y == null : x.equals(y);
    }

    @Override
    public int hashCode(Object x) throws HibernateException {
        return x == null ? 0 : x.hashCode();
    }

    @Override
    public Object nullSafeGet(ResultSet rs, String[] names, SharedSessionContractImplementor session, Object owner)
            throws HibernateException, SQLException {
        if (names != null && names.length > 0 && rs != null && rs.getArray(names[0]) != null) {
            Object array = rs.getArray(names[0]).getArray();
            if (array instanceof String[]) {
                return new HashSet<>(Arrays.asList((String[]) array));
            } else {
                return null;
            }
        }
        return null;
    }

    @Override
    public void nullSafeSet(PreparedStatement st, Object value, int index, SharedSessionContractImplementor session)
            throws HibernateException, SQLException {
        if (value != null && st != null) {
            Set<String> set = (Set<String>) value;
            String[] castObject = set.toArray(new String[set.size()]);
            Array array = session.connection().createArrayOf("text", castObject);
            st.setArray(index, array);
        }
    }

    @Override
    public Object deepCopy(Object value) throws HibernateException {
        if (value == null) {
            return null;
        }
        Set<String> set = (Set<String>) value;
        HashSet<String> clone = new HashSet<>();
        for (String str : set) {
            clone.add(str);
        }
        return clone;
    }

    @Override
    public boolean isMutable() {
        return true;
    }

    @Override
    public Serializable disassemble(Object value) throws HibernateException {
        return (Serializable) value;
    }

    @Override
    public Object assemble(Serializable cached, Object owner) throws HibernateException {
        return cached;
    }

    @Override
    public Object replace(Object original, Object target, Object owner) throws HibernateException {
        return original;
    }
}
```

With this code, I'm able to successfully use basic **save()** and **find()** operations from the Repository on Policy table, so it properly maps Set of strings (Policy field _issueLabels_) to Postgres _text[]_ column, but the custom _updateById()_ operation fails.

**I found these 2 problems:**
* generated query from `@Query` annotation looks ok `UPDATE my.package.Policy policy_ SET policy_.policyName=:p1,policy_.issueLabels=:p2,policy_.strategyName=:p3 WHERE (policy_.id = :p4)`, however _PreparedStatement_ from _nullSafeSet()_ function call after that looks like this `HikariProxyPreparedStatement@1721893440 wrapping update policy set policy_name='policyName', issue_labels=(? , ?), strategy_name='strName' where id=1`. issue_labels=('L1' , 'L2') is not the correct syntax for array update.
* when using _save(entity)_ function of the repository, Micronaut properly calls _nullSafeSet()_ function and passes correct data type of issueLabels field (Set of strings) so the function can do its job and fill in the statement with generated Array. However, for _updateById()_ call, Micronaut calls _nullSafeSet()_ for each string of the set separately to fill the placeholders `issue_labels=(? , ?)`. It cannot generate the correct form `issue_labels='{"L1" , "L2"}'`.

**Finally my question:** since it works for _save(entity)_ method of the repository, is it possible to provide some additional metadata to _updateById()_ method (more specifically to its _issueLabels_ parameter) so Micronaut would generate correct statement etc.? Or how can I update the _text[]_ column in the database with custom Repository method please?

Thank you very much
Kind regards
Marek

**Comment by graemerocher** [comment]
So yeah for inserts it seems we shouldn't expand collections in an in list query. However your example is slightly odd because using a java `Set` is an unordered collection so would return the array elements in a different order for each query. I don't understand how that would ever be desirable.

**Comment by svepemar** [comment]
You are right, but for my usecase the ordering of elements in the collection is not important.
Anyway,  if the collection is expanded even with the custom Type defined, is it currently possible to update this individual field with update or I have to use save/persist methods?

**Comment by graemerocher** [comment]
I looked into this and it seems Micronaut Data is doing the correct thing, but Hibernate is not. I suggest you maybe raise the issue with the Hibernate team as to why JPA-QL update statements don't handle custom types correctly. In the meantime you can always lookup the object manually and perform a manual update by injecting the `EntityManager`
