### ISSUE TITLE
Cannot query entity [xxx] on non-existent property

### ISSUE THREAD

**Issue by ahetawal-p** [micronaut-projects/micronaut-data#1481]
### Expected Behavior

Trying to update a query criteria with `like` and `and`.

`List<UserDetails> findByNameIlikeOrUsernameIlikeAndDestinationFalse(String name, String username, Pageable from);`

Existing query looks like this:

`List<UserDetails> findByNameIlikeOrUsernameIlike(String name, String username, Pageable from);`

### Actual Behaviour

This query fails:
`List<UserDetails> findByNameIlikeOrUsernameIlikeAndDestinationFalse(String name, String username, Pageable from);`

```
Unable to implement Repository method: UserRepository.findByNameIlikeOrUsernameIlikeAndDestinationFalse(String name,String username, Pageable from)
```

But the existing query seems to work fine.

### Steps To Reproduce

Any query

### Environment Information

openjdk version "17.0.2" 2022-01-18
OpenJDK Runtime Environment Homebrew (build 17.0.2+0)
OpenJDK 64-Bit Server VM Homebrew (build 17.0.2+0, mixed mode, sharing)

### Version

2.5.13

**Comment by dstepanov** [comment]
Please try it in the latest version

**Comment by nhandev552** [comment]
The same issue and I also get the issue `JsonParseException: JSON reader was expecting a value but found 'SELECT'.` when using MongoDB for simple query `findById`
