### ISSUE TITLE
@DateCreated not to work correctly during update in Mongo

### ISSUE THREAD

**Issue by o-shevchenko** [micronaut-projects/micronaut-data#1523]
### Expected Behavior

1. For `create()` both `created` and `updated` have the same time.
2. For `update()` `created` field is not changed, `updated` field is updated.

### Actual Behaviour

1. For `create()` both `created` and `updated` have the same time.
2. For `update()` `created` both fields are updated.

1. Created:
```
created:2022-05-16T09:26:38.212+00:00
updated:2022-05-16T09:26:38.212+00:00
```
2. Updated:
```
created:2022-05-16T09:28:10.216+00:00
updated:2022-05-16T09:28:10.217+00:00
```

### Steps To Reproduce

```kotlin
@MappedEntity
data class Entity(
    @field:Id
    @GeneratedValue
    var id: ObjectId = ObjectId(),
    val name: String,
    @DateCreated
    var created: LocalDateTime = LocalDateTime.now(ZoneOffset.UTC),
    @DateUpdated
    var updated: LocalDateTime = LocalDateTime.now(ZoneOffset.UTC)
)

 @MongoRepository
interface EntityRepository : CrudRepository<Entity, ObjectId>

repository.update(entity)
```

1. Invoke repository create(Entity)
2. Invoke repository update(Entity)

### Version

3.4.1

**Comment by dstepanov** [comment]
I have tried to reproduce it and it works fine for me. Can you provide a sample project? It might be related to Kotlin's immutable fields

**Comment by dstepanov** [comment]
I have tried to reproduce it and it works fine for me. Can you provide a sample project? It might be related to Kotlin's immutable fields

**Comment by radovanradic** [comment]
I tried with both Kotlin and Java and could not reproduce.
