### ISSUE TITLE
JPA: RXjavaRepository and Transactional - PersistenceException after save()

### ISSUE THREAD

**Issue by svepemar** [micronaut-projects/micronaut-data#153]
Hello,

I'm using MicronautData with JPA together with RXjavaCRUD repository and I'm not able to get to work findById()+save() when using RXjava repository (even with @Transactional as mentioned in documentation).

**Entity class:**
```
@Entity
public class Pet {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    long id;

    @Column(name = "name")
    String name;

    //  constructors and getters/setters
}
```

**Controller:**
```
@Controller("/pet")
public class PetController {

    @Inject
    private PetStorage petStorage;

    @Transactional
    @Put(value = "/rx/{id}", produces = MediaType.APPLICATION_JSON)
    Single<HttpResponse<Pet>> updateRx(long id) {
        return petStorage.updatePetRx(id)
                .map((Function<Pet, HttpResponse<Pet>>) HttpResponse::ok)
                .switchIfEmpty(Maybe.just(HttpResponse.notFound()))
                .toSingle();
    }

    @Transactional
    @Put(value = "/{id}", produces = MediaType.APPLICATION_JSON)
    HttpResponse<Pet> update(long id) {
        Pet pet = petStorage.updatePet(id);
        if (pet != null) {
            return HttpResponse.ok(pet);
        }
        return HttpResponse.notFound();
    }
}
```

**Repositories:**
```
@Repository
interface PetRepository extends CrudRepository<Pet, Long> {}

@Repository
interface PetRxRepository extends RxJavaCrudRepository<Pet, Long> {}
```

**Storage:**
```
@Singleton
class PetStorage {

    @Inject
    private PetRepository petRepository;

    @Inject
    private PetRxRepository petRxRepository;

    Maybe<Pet> updatePetRx(long id) {
        return petRxRepository.findById(id).flatMap(
                pet -> {
                    if (pet == null) {
                        return Maybe.empty();
                    }
                    pet.setName("second");
                    return petRxRepository.save(pet).toMaybe();
                });
    }

    Pet updatePet(long id) {
        Pet pet = petRepository.findById(id).orElse(null);
        if (pet != null) {
            pet.setName("second");
            return petRepository.save(pet);
        }
        return null;
    }
}
```

In this example, blocking update works (thanks to @transactional) but RX version does not work (throws java.util.concurrent.CompletionException: javax.persistence.PersistenceException: org.hibernate.PersistentObjectException: detached entity passed to persist: com.appdynamics.marek.test.proj.Pet).
Please, is it possible to get it to work with RXjava repository?

Thank you very much
Kind regards
Marek

**Comment by svepemar** [comment]
Thank you @graemerocher . It is mentioned in 4.10 in the documentation
https://micronaut-projects.github.io/micronaut-data/latest/guide/#reactive
but your explanation helped a lot. Maybe your example would improve the documentation (4.10 section). Thanks!

**Comment by RaviH** [comment]
@graemerocher I understand that above is by design. But, doesn't it have the effect of making things complex for the end user? For instance: if we look at the example you provided above, we would need to create 2 repositories: one for async and one for sync just to carry out an update? 

Please correct me if I am wrong but it seems like we can't update using async repositories since find would be 1 operation and update would be another?

**Comment by RaviH** [comment]
Hey @graemerocher,

I understand this is by design.  However, it would be really helpful if there was a way to do find and update in 1 transaction in reactive/rx way. My 2 cents.

**Comment by StephenOTT** [comment]
+1 on this to have some better pattern helper

**Comment by StephenOTT** [comment]
@graemerocher is your example above to suggest that a RX and non-RX repository is currently required to be used to do FindById + Save/Update?
