### ISSUE TITLE
Unable to implement Repository method: class Type$TypeVar cannot be cast to class Element

### ISSUE THREAD

**Issue by eratio08** [micronaut-projects/micronaut-data#1545]
### Issue description

We are currently trying to upgrade from Micronaut `3.1.4` to `3.5.0`. Doing so yields the following exception 
```
Unable to implement Repository method: SomeRepository.findAll(Sort sort). class com.sun.tools.javac.code.Type$TypeVar cannot be cast to class javax.lang.model.element.Element (com.sun.tools.javac.code.Type$TypeVar is in module jdk.compiler of loader 'app'; javax.lang.model.element.Element is in module java.compiler of loader 'platform')
```
I can't seem to find the cause for this because I do not understand the exception and what I can infer from this message. Do you have any insights what could be the cause?

```kotlin
@Repository
interface SomeRepository : PageableRepository<SomeEntity, SomeEntityIdentifier>

@Entity
class SomeEntity(...) : AbstractEntity<SomeEntityIdentifier>(SomeEntityIdentifier())

@MappedSuperclass
abstract class AbstractEntity<ID : AbstractEntityIdentifier>(
	@EmbeddedId
	val identifier: ID,
)

@Embeddable
class SomeEntityIdentifier(id: UUID = randomId()) : AbstractEntityIdentifier(id)

@MappedSuperclass
abstract class AbstractEntityIdentifier(
	@field:JsonProperty("id")
	@Column(name = "id", unique = true, updatable = false, nullable = false)
	val value: UUID,
) : Serializable { ... }
```

```
java=17.0.3-tem
kotlin=1.6.21
```

Thanks a lot!

**Update**
The `ClassCastException` is thrown in `io.micronaut.annotation.processing.visitor.AbstractJavaElement#resolveDeclaringTypeName` in the else-branch. `this` is a `class io.micronaut.annotation.processing.visitor.JavaGenericPlaceholderElement`. `this.getNativeType()` yields `ID` of type `class com.sun.tools.javac.code.Type$TypeVar` which is then attempted to be casted to `javax.lang.model.element.Element` which fails.

**Comment by graemerocher** [comment]
@dstepanov can you take a look?
