### ISSUE TITLE
Join fetch returns duplicate results

### ISSUE THREAD

**Issue by kirans9731** [micronaut-projects/micronaut-data#156]
Hello,

Join fetch on a Repository returns duplicate entities depending on the number of records in the one to many association

Example project here - https://github.com/kirans9731/repo-join-fetch.git

```
@Entity
@Table(name = "customer")
public class Customer {

    private Long id;
    private String name;
    private String email;
    private String address;

    private Set<Order> orders = new HashSet<>();

    ....

    @OneToMany (mappedBy = "customer", cascade = CascadeType.ALL, fetch = FetchType.LAZY, orphanRemoval = true)
    public Set<Order> getOrders() {
        return orders;
    }
}

@Entity
@Table(name = "orders")
public class Order {

    private Long id;
    private String product;

    private Customer customer;

    ....
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "customer_id")
    public Customer getCustomer() {
        return customer;
    }
}

@Repository
public interface CustomerRepository extends CrudRepository<Customer, Long> {

    @Join(value = "orders", type = Join.Type.FETCH)
    Collection<Customer> findByName(String name);
}

@MicronautTest
public class CustomerRepositoryTest {

    @Inject
    CustomerRepository customerRepository;

    @BeforeEach
    public void init() {

        Customer customer = new Customer();
        customer.setName("Kiran");
        customer.setAddress("USA");
        customer.setEmail("user.name@email.com");

        Order order1 = new Order();
        order1.setCustomer(customer);
        order1.setProduct("Prod1");

        Order order2 = new Order();
        order2.setCustomer(customer);
        order2.setProduct("Prod2");

        Order order3 = new Order();
        order3.setCustomer(customer);
        order3.setProduct("Prod1");

        customer.getOrders().add(order1);
        customer.getOrders().add(order2);
        customer.getOrders().add(order3);

        customerRepository.save(customer);
    }

    @Test
    public void test_findByName() {

        Collection<Customer> customers = customerRepository.findByName("Kiran");
        Assertions.assertEquals(1, customers.size()); // this is 3
    }
}
    
```

**Comment by lehotskysamuel** [comment]
I think I have the same or similar problem, was just about to open new issue. Here is my code:

Parent entity:
```
@MappedEntity
public class ManagedComponentInstance {

    @Id
    @AutoPopulated
    private UUID id;

    @Relation(value = Relation.Kind.ONE_TO_MANY, mappedBy = "managedComponentInstance")
    private List<ManagedComponentInstanceLabel> labels;

    @Relation(value = Relation.Kind.ONE_TO_MANY, mappedBy = "managedComponentInstance")
    private List<ManagedComponentInstanceTemplateValue> templateValues;

    //other fields, getters and setters
}
```

Children:
```
@MappedEntity
public class ManagedComponentInstanceLabel {

    @Id
    @AutoPopulated
    private UUID id;

    @Relation(Relation.Kind.MANY_TO_ONE)
    private ManagedComponentInstance managedComponentInstance;

    //other fields, getters and setters
}
```

```

@MappedEntity
public class ManagedComponentInstanceTemplateValue {

    @Id
    @AutoPopulated
    private UUID id;

    @Relation(Relation.Kind.MANY_TO_ONE)
    private ManagedComponentInstance managedComponentInstance;

    //other fields, getters and setters
}
```

Repository:
```

@JdbcRepository(dialect = Dialect.POSTGRES)
public abstract class ManagedComponentInstanceRepository implements RxJavaCrudRepository<ManagedComponentInstance, UUID> {

    @Join(value = "labels", alias = "label_")
    @Join(value = "templateValues", alias = "template_value_")
    public abstract Flowable<ManagedComponentInstance> findBySpaceIdAndTemplateId(@NotNull UUID spaceId, @Nullable String templateId);

    //other methods
}
```

I have 2 entries in database for each child but this query returns all labels and templateValues twice.

If I comment out one of the joins, I get correct number of records (2 labels + 2 templateValues). If I have both joins, I get 4+4.

I've tried with different types of joins but it's always duplicated.

**Comment by graemerocher** [comment]
This is because of the cartesian product and how SQL behaves. When doing multiple joins on collections it produces a row that combines the data from 3 tables and has to duplicate rows for each associations. In this case instead of join you probably want an additional query to fetch the data you need.

**Comment by kirans9731** [comment]
@graemerocher Thanks for checking. Per 'fetch' join, I was expecting the 'orders' collection to be initialized along with 'customer' using a single select. Please let me know if this is not the case and if there is a way to achieve this in micronaut-data.

**Comment by graemerocher** [comment]
@kirans9731 This has nothing to do with Micronaut Data as such it is how Hibernate/JPA behaves when doing a join that results in the cartesian product of several tables. See the following post which is a good article / explanation https://allaroundjava.com/hibernate-cartesian-product-problem/

Generally you would fetch the associations with separate additional queries.

**Comment by kirans9731** [comment]
Thank you @graemerocher

**Comment by psoares** [comment]
@graemerocher Although your explanation makes perfect sense, I think either micronaut-data should handle the initialization of collection properties in a simpler manner, or the docs should have more examples of how to handle different situations. From the docs, I find it hard to understand that the `@Join` annotation can be used in a `@ManyToOne` or `@OneToOne` relationships, but not in a `@OneToMany`.

**Comment by graemerocher** [comment]
@psoares I agree we need to make this easier, but altering the behaviour of `@Join(..)` is not the correct thing to do and will create more confusion since for me `@Join(..)` by its name indicates you want to perform a join query (`INNER JOIN`, `LEFT JOIN` etc.)

My current plan is to add an additional annotation probably named `@Select(..)` that will allow you to give a hint to Micronaut Data to perform an additional select to retrieve the association as well in cases where you need it.

**Comment by psoares** [comment]
For the time being, I did a "dirty" trick consisting of having my repository method return a Flux, and invoking the `distinct` method on it at the service level.

e.g.:
```
@Repository
interface BookRepository extends CrudRepository<Book, Long> {

    @Join(value = "chapters", type = Join.Type.FETCH)
    Flux<Book> list();
}

@Singleton
public class BookService {

    BookRepository bookRepository;

    public BookService(BookRepository bookRepository) {
        this.bookRepository = bookRepository;
    }

    @Transactional
    @ReadOnly
    public Flux<Book> list() {
        return bookRepository.list().distinct();
    }
}
```
