### ISSUE TITLE
Deserializing from MongoDB breaks with Micronaut 3.5.1 in some situation

### ISSUE THREAD

**Issue by ckosmowski** [micronaut-projects/micronaut-data#1571]
### Expected Behavior

Classes annotated with @Introspected and additionally with @SerdeImport should be Deserialzable from MongoDB

### Actual Behaviour

Since (at least) Micronaut 3.5.1 Trying to deserialize Classes annotated with @Introspected and additionally with @SerdeImport leads to an Exception stating that deserializable Introspection was not found.

### Steps To Reproduce

- Create a data class annotated with @Introspected
- Use @SerdeImport to import that same class somewhere in the project
- Try to deserialize that class from a MongoDB Repository
- Works with 3.4.4
- Breaks with 3.5.1

### Environment Information

- Micronaut 3.4.4 (Good)
- Micronaut 3.5.1 (Bad)
- Mironaut data 3.4.1 and 3.4.2 (Both the same behaviour)

### Example Application

https://github.com/ckosmowski/micronaut-examples/tree/issues/mongodb/introspected

### Version

3.5.1

**Comment by dstepanov** [comment]
Can you please set up your project with testcontainers? Also, the Gradle build you have is very messy. Please don't specify single versioned dependencies, just use BOMs everywhere because somehow when I run the app it says `Micronaut (v3.4.4)`

**Comment by ckosmowski** [comment]
Hi,

In our real projects we use our own gradle plugin. This simplified setup
was intended to rule out every complexity possible. And using the versions
that do actually cause the problem.

However at the time of writing micronaut data 3.4.2 was not automatically
used from the bom. That's why it's hardcoded. Everything else should be
pulled from the BOM.

We Plan to use Testcontainers in the future but we are currently not able
to use them for licensing reasons. We would need docker Desktop for this
but are in a process of switching to a Unix environment so things have been
postponed. Short answer: would love to, but can't.

The correct branch should be mongodb/introspected by the way since the link
seems to leed to the master branch for me.

Hope this helps

Denis Stepanov ***@***.***> schrieb am Fr., 24. Juni 2022,
14:14:

**Comment by dstepanov** [comment]
I understand, but it would be nice if you can set up the example project using testcontaienrs so I don't need to start additional databases.

**Comment by ckosmowski** [comment]
I also understand your point but currently Testcontainers depends on docker desktop on windows (which needs a license) that i do not have or otherwise on a complicated setup running a docker deamon inside WSL2 which requires privileges i don't have.

So i would if i could but i just cannot add Testcontainers as of now. If this is a show stopper we need to postpone the ticket at a few weeks more.

**Comment by ckosmowski** [comment]
Still no Testcontainers in use but i found the code that breaks things for us:

https://github.com/micronaut-projects/micronaut-data/blob/71476f7d00e740bd2e73b24a28245165fdb8a9a3/data-mongodb/src/main/java/io/micronaut/data/mongodb/serde/DataCodecRegistry.java#L73

there is this check for the entities list that is injected from the DataCodecRegistryBuilder. In case there is a packageName configuration (which there is allthough i did not specify one) the packages are scanned for Serdeable annotations which i dont use (i use @SerdeImport). And in addition the packageNames only contains a junit package and the package that the integrationTest resides in.

If nothing is found still the empty list is passed to the above code and the get() method returns null and everything in the dataSerdeRegistry that might be there (@SerdeImport) is ignored which was not the case in pre 3.5. versions.

**Comment by dstepanov** [comment]
I see, you need to define which packages should be used for the mongo integration:
```
mongodb:
   package-names:
        - abc
        - xyz
```

**Comment by ckosmowski** [comment]
Oh thanks a lot! That solves it!
Just for the record for multiple servers it must be specified seperately:

```yaml
mongodb:
  servers:
    serverone:
      package-names: de.package.name
      uri: mongodb://...
      database: ...
    servertwo:
      package-names: de.package.name
      uri: mongodb://...
      database: ...
```

It would have been a great help if this was reflected somewhere in the documentation or the release notes it was really hard to find why this was broken between 3.4.4 and 3.5.1 version change. 

I think this gets especially significant in integration tests because the default package is then the package of the test class and does not necessarily include the entity classes. In a non-test environment i guess this is just not significant because the default package is the package of the application class which usually includes everything :-)

**Comment by dstepanov** [comment]
Thanks for the feedback. We need some documentation improvements :)
