### ISSUE TITLE
Query with RETURNING statement crashes due to using executeUpdate instead of execute

### ISSUE THREAD

**Issue by Dattish** [micronaut-projects/micronaut-data#1572]
### Expected Behavior

The query should return the updated rows.

This seems to have been [fixed a long time ago](https://github.com/micronaut-projects/micronaut-data/issues/324) but might have broken at some point since.

### Actual Behaviour

Crashes with `Error executing SQL UPDATE: A result was returned when none was expected`

### Steps To Reproduce

1. Create a db and a table.
2. Create a repository with a method with the following kind of query `@Query(value = "update ... where ... returning *", readOnly = false)`
3. Insert some data
4. Call the method

### Environment Information

OS: macOS Monterey 12.4, Windows 10 19044.1706
JDK: OpenJDK 17+35-2724

### Example Application

https://github.com/Dattish/micronaut-data-repro

### Version

3.5.1

**Comment by dstepanov** [comment]
The referenced issue has a simple query so it works but the update is a different thing. We would need to add a bit different API to support this kind of return.

**Comment by Discordia** [comment]
I am also running into this issue. Any status update on this?

**Comment by pixnbit** [comment]
Same here, it's still not fixed

**Comment by RonBarkan** [comment]
If you are using the 3.x releases and want to workaround this issue, you can do the following query instead:

```
WITH realQuery AS (
  UPDATE/INSERT/DELETE ..
  RETURNING ...
)
SELECT ... FROM realQuery
...
```

You'll need to mark the method `@Transactional` and you can even do extra operations, such as aggregation, in the select, that are not allowed with `RETURNING`.

**Comment by temofey1989** [comment]
This is not working any more... I test it with Micronaut 4.7.1+

**Comment by radovanradic** [comment]
What is not working? I tried repro example (little bit updated test) and it seems to be working 

[mn-update-returning.zip](https://github.com/user-attachments/files/19536967/mn-update-returning.zip)

Can you add example that is not working?
