### ISSUE TITLE
Cannot query entity [xxxEntity] on non-existent property: id

### ISSUE THREAD

**Issue by muyu66** [micronaut-projects/micronaut-data#159]
Unable to use lombok's **@Data** annotation in the **Entity** definition of micronaut-data.

**Error message**

    > Task :compileJava FAILED
		Error: Unable to implement Repository method: UserFieldHistoryDao.findById(Object arg0). Cannot query entity [UserFieldHistoryEntity] on non-existent property: id
		Error: Unable to implement Repository method: UserFieldHistoryDao.existsById(Object arg0). Cannot query entity [UserFieldHistoryEntity] on non-existent property: id
		Error: Unable to implement Repository method: UserFieldHistoryDao.deleteById(Object arg0). Cannot query entity [UserFieldHistoryEntity] on non-existent property: id

**Core code**

    @Entity
	@Data
	public class UserFieldHistoryEntity {

	    @Id
	    @GeneratedValue()
	    private String id;
	
	    private String name;
	
	    public UserFieldHistoryEntity() {
	    }
	
		//    public String getId() {
		//        return id;
		//    }
		//
		//    public void setId(String id) {
		//        this.id = id;
		//    }
		//
		//    public String getName() {
		//        return name;
		//    }
		//
		//    public void setName(String name) {
		//        this.name = name;
		//    }
	}

**Dependencies **

    dependencies {
    annotationProcessor platform("io.micronaut:micronaut-bom:$micronautVersion")
    annotationProcessor "io.micronaut:micronaut-inject-java"
    annotationProcessor "io.micronaut:micronaut-validation"
    annotationProcessor 'io.micronaut.data:micronaut-data-processor:1.0.0.M1'
    implementation platform("io.micronaut:micronaut-bom:$micronautVersion")
    implementation "io.micronaut:micronaut-inject"
    implementation "io.micronaut:micronaut-validation"
    implementation "io.micronaut:micronaut-runtime"
    implementation "javax.annotation:javax.annotation-api"
    implementation "io.micronaut:micronaut-http-server-netty"
    implementation "io.micronaut:micronaut-http-client"
    implementation "io.micronaut.configuration:micronaut-hibernate-jpa"
    implementation "io.micronaut.configuration:micronaut-jdbc-hikari"
    implementation 'io.micronaut.data:micronaut-data-hibernate-jpa:1.0.0.M1'
    runtimeOnly "ch.qos.logback:logback-classic:1.2.3"
    runtimeOnly "com.h2database:h2"
    testAnnotationProcessor platform("io.micronaut:micronaut-bom:$micronautVersion")
    testAnnotationProcessor "io.micronaut:micronaut-inject-java"
    testImplementation platform("io.micronaut:micronaut-bom:$micronautVersion")
    testImplementation "org.junit.jupiter:junit-jupiter-api"
    testImplementation "io.micronaut.test:micronaut-test-junit5"
    testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine"
	}

**Minimize mirroring**
https://github.com/muyu66/micronaut-data-issue-1

**How to minimize mirroring**
Normal: UserFieldHistoryEntity file, retaining manually written getter setter and @Data
Exception: UserFieldHistoryEntity file, delete manually written getter setter, only @Data

**related problem**
https://github.com/micronaut-projects/micronaut-data/issues/126

**Comment by graemerocher** [comment]
The issue here is that the lombok processor has to be configured prior to Micronaut's processor. The Gradle plugin you are using is not doing this correctly. The following diff resolves the issue:

```diff
diff --git a/build.gradle b/build.gradle
index 3c378bc..9a4dda2 100644
--- a/build.gradle
+++ b/build.gradle
@@ -2,7 +2,7 @@ plugins {
     id "net.ltgt.apt-eclipse" version "0.21"
     id "com.github.johnrengelman.shadow" version "5.0.0"
     id "application"
-    id "io.franzbecker.gradle-lombok" version "3.1.0"
+    // id "io.franzbecker.gradle-lombok" version "3.1.0"
 }


@@ -22,6 +22,8 @@ configurations {
 }

 dependencies {
+    compileOnly 'org.projectlombok:lombok:1.16.20'
+    annotationProcessor "org.projectlombok:lombok:1.16.20"
     annotationProcessor platform("io.micronaut:micronaut-bom:$micronautVersion")
     annotationProcessor "io.micronaut:micronaut-inject-java"
     annotationProcessor "io.micronaut:micronaut-validation"
```

I have also updated the docs to reflect this.

**Comment by orbfish** [comment]
@graemerocher I'm seeing this happen also - I changed the buildfile as you suggest, still had the problem, then suddenly *didn't* have the problem. Added another entity, had the problem again, now I can't shake it.

This might be something in IntelliJ, able to start up on the command line. Have you heard of any issues? Or do you have any advice. I use Lombok all the time in our production projects, trying to do a quick prototype to demonstrate how easy it might be to port our existing SpringBoot projects over to Micronaut.

**Comment by shnkar007** [comment]
> The issue here is that the lombok processor has to be configured prior to Micronaut's processor. The Gradle plugin you are using is not doing this correctly. The following diff resolves the issue:
> 
> ```diff
> diff --git a/build.gradle b/build.gradle
> index 3c378bc..9a4dda2 100644
> --- a/build.gradle
> +++ b/build.gradle
> @@ -2,7 +2,7 @@ plugins {
>      id "net.ltgt.apt-eclipse" version "0.21"
>      id "com.github.johnrengelman.shadow" version "5.0.0"
>      id "application"
> -    id "io.franzbecker.gradle-lombok" version "3.1.0"
> +    // id "io.franzbecker.gradle-lombok" version "3.1.0"
>  }
> 
> 
> @@ -22,6 +22,8 @@ configurations {
>  }
> 
>  dependencies {
> +    compileOnly 'org.projectlombok:lombok:1.16.20'
> +    annotationProcessor "org.projectlombok:lombok:1.16.20"
>      annotationProcessor platform("io.micronaut:micronaut-bom:$micronautVersion")
>      annotationProcessor "io.micronaut:micronaut-inject-java"
>      annotationProcessor "io.micronaut:micronaut-validation"
> ```
> 
> I have also updated the docs to reflect this.

What dependencies do I have to add in case of maven?

**Comment by mackatozis** [comment]
For Maven you need the lombok dependency

```
<dependency>
	<groupId>org.projectlombok</groupId>
	<artifactId>lombok</artifactId>
	<scope>provided</scope>
</dependency>
```

and inside the `maven-compiler-plugin` configuration, make sure that:

1. the `combine.children` attribute of the tag `annotationProcessorPaths` is set to `"override"`
2. the lombok plugin is configured prior to Micronaut's processor

```
  
<build>
	<plugins>
		<plugin>
			<groupId>org.apache.maven.plugins</groupId>
			<artifactId>maven-compiler-plugin</artifactId>
			<configuration>
				<annotationProcessorPaths combine.children="override">
					<path>
						<groupId>org.projectlombok</groupId>
						<artifactId>lombok</artifactId>
						<version>${lombok.version}</version>
					</path>
					<path>
						<groupId>io.micronaut</groupId>
						<artifactId>micronaut-inject-java</artifactId>
						<version>${micronaut.version}</version>
					</path>
					<path>
						<groupId>io.micronaut.data</groupId>
						<artifactId>micronaut-data-processor</artifactId>
						<version>${micronaut.data.version}</version>
					</path>
                                        ...
				</annotationProcessorPaths>
				...
			</configuration>
		</plugin>
                ...
	</plugins>
</build>
```
