### ISSUE TITLE
Datatransformer and where clause

### ISSUE THREAD

**Issue by tahvane1** [micronaut-projects/micronaut-data#1601]
### Expected Behavior

 I have defined such data definition using transformer to convert data (from byte array to UUID and vice versa)

@Id @DataTransformer(read = "BIN_TO_UUID(@.tenant_id)", write = "UUID_TO_BIN(?)") UUID applicationId

When I do delete (or any other sql operation) it should translate to something like 

"DELETE FROM xxxx WHERE application_id = UUID_TO_BIN(?) "
 

### Actual Behaviour

Queries are translated to format like
"DELETE FROM xxxx WHERE BIN_TO_UUID(application_id) = ?"

which leads to that that queries do not use indexes at all and are very slow.

### Version

3.5.2

**Comment by tahvane1** [comment]
Any news on this? This is pretty annoying...

**Comment by JesusMetapack** [comment]
We have exactly the same issue

**Comment by tahvane1** [comment]
This works as expected
`package xxx;
import io.micronaut.core.convert.ConversionContext;
import io.micronaut.data.model.runtime.convert.AttributeConverter;

//import javax.persistence.Converter;
import java.nio.ByteBuffer;
import java.util.UUID;

import jakarta.inject.Singleton;

@Singleton
public class MySqlUUIDBinaryConverter implements AttributeConverter<UUID, byte[]> {

    @Override
    public byte[] convertToPersistedValue(UUID uuid, ConversionContext context) {
        if (uuid == null) {
            return null;
        }
        ByteBuffer bb = ByteBuffer.wrap(new byte[16]);
        bb.putLong(uuid.getMostSignificantBits());
        bb.putLong(uuid.getLeastSignificantBits());
        return bb.array();
    }

    @Override
    public UUID convertToEntityValue(byte[] bytes, ConversionContext context) {
        if (bytes == null) {
            return null;
        }
        if (bytes.length != 16) {
            throw new IllegalArgumentException();
        }
        int i = 0;
        long msl = 0;
        for (; i < 8; i++) {
            msl = (msl << 8) | (bytes[i] & 0xFF);
        }
        long lsl = 0;
        for (; i < 16; i++) {
            lsl = (lsl << 8) | (bytes[i] & 0xFF);
        }
        return new UUID(msl, lsl);
    }
}`

` @TypeDef(type = DataType.BYTE_ARRAY, converter = MySqlUUIDBinaryConverter.class)
                          UUID applicationId,`

**Comment by radovanradic** [comment]
Done, should be released in 3.9.x (not sure when)
