### ISSUE TITLE
Support cascading save in Micronaut JDBC

### ISSUE THREAD

**Issue by lehotskysamuel** [micronaut-projects/micronaut-data#162]
Hi,
I am not able to save 2 related tables with Micronaut but maybe it's just something I am doing wrong. Could you please advise?

I have a parent entity

```
@Entity
public class ManagedComponentInstance {

    @Id
    @AutoPopulated
    private UUID id;

    @OneToMany(mappedBy = "managedComponentInstance",
            cascade = CascadeType.ALL, fetch = FetchType.EAGER)
    private List<ManagedComponentInstanceLabel> labels;
...
}
```

and a child entity

```
@Entity
public class ManagedComponentInstanceLabel {

    @Id
    @AutoPopulated
    private UUID id;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "managed_component_instance_id")
    private ManagedComponentInstance managedComponentInstance;
...
}
```

One Instance should have multiple Labels, so it's one-to-many relation.

I was expecting that after adding Labels to Instance (via ```setLabels(listWithLabels)```) and calling InstanceRepository.save(), that Micronaut Data would also save labels. This is not the case, however. I have tried saving labels prior to saving instance but they are saved with managed_component_instance_id == null even though I do set parent on the entity before saving.

I've also tried using Micronaut annotations but the behaviour was the same.

```
@MappedEntity
public class ManagedComponentInstance {

    @Id
    @AutoPopulated
    private UUID id;

    //    @Relation(value = Relation.Kind.ONE_TO_MANY, mappedBy = "managedComponentInstance")
    @Relation(value = Relation.Kind.ONE_TO_MANY)
    private List<ManagedComponentInstanceLabel> labels;
...
}

@MappedEntity
public class ManagedComponentInstanceLabel {

    @Id
    @AutoPopulated
    private UUID id;

    @MappedProperty(value = "managed_component_instance_id")
    @Relation(Relation.Kind.MANY_TO_ONE)
    private ManagedComponentInstance managedComponentInstance;
...
}
```

I am using Micronaut Data JDBC.

Is cascading saves like this unsupported? If it should work, is there a problem with my code above? There are some examples in documentation but a complete working example would be nice.

Thanks.

**Comment by graemerocher** [comment]
Currently the JDBC implementation does not support cascading inserts or updates and it is up to you to manually code those. We may support this at some point but we don't really have the intention for Data JDBC to become a full ORM solution and it is about giving you more control than an ORM traditionally would.

**Comment by lehotskysamuel** [comment]
Ok, thanks for clearing this out. Can I ask what is the purpose of @Relation then?

What is the recommended procedure here? Should I have a direct reference to related entity's ID?
```
    private UUID managedComponentInstanceId;
```

I have no problems saving an entity if I only use such IDs. But then the problems are with reads. What if I also want a getter/setter for the related entity itself? Should I add @Transient field and set it myself after loading it?

```
    @Transient
    private ManagedComponentInstance managedComponentInstance;

    ....

    entity.setManagedComponentInstance( repository.find(entity.getManagedComponentInstanceId()) )
```

Ideally, I'd like this to be done automatically.

**Comment by graemerocher** [comment]
The purpose of `@Relation` is to allow the specification of joins in query methods. See https://micronaut-projects.github.io/micronaut-data/snapshot/guide/#jdbcJoinQueries

You don't need a direct reference to the related entities ID, you can just as easily have a real reference it is just a matter of ordering your inserts correctly so the parent is saved first in your code and then the children (with the association set).

**Comment by lehotskysamuel** [comment]
This has pointed me in the right direction, I managed to get it working. The problem was I'd been trying to save children before the parent, which, in retrospect, doesn't really make sense. Thanks for the advice.

**Comment by graemerocher** [comment]
Basic support for cascading saves if you declare

```java
@OneToMany(cascade = CascadeType.PERSIST)
    private List<Page> pages = new ArrayList<>();
```

Has been added in master. Cascading deletes have to be done manually still, that is probably a separate issue.

**Comment by matt-snider** [comment]
Hi @graemerocher, thanks for all your work on this project.

Is there an example or any documention out there for this? I've been trying to get this working with something like the following:

```
@Data
@NoArgsConstructor
@AllArgsConstructor
@MappedEntity(value = "orders")
public class Order {
    @Id
    @GeneratedValue
    private Long id;

    @Column(name = "address_id")
    @OneToOne(cascade = CascadeType.PERSIST)
    private Address deliveryAddress;
}

@Data
@NoArgsConstructor
@AllArgsConstructor
@MappedEntity(value = "addresses")
public class Address {
    @Id
    @GeneratedValue
    private Long id;
    private String name;
    private String line1;
    private String line2;
    private String city;
    private String postalCode;
}


// In controller
var order = new Order(someNewAddress);
orderRepository.save(order);
```

This results in a SQL error  

> SQL Error executing INSERT: Column 'address_id' cannot be null

since the orders insert occurs without saving the address first. Should this sort of cascading save work?

**Comment by graemerocher** [comment]
@matt-snider seems like a bug worthy of an issue report

**Comment by matt-snider** [comment]
@graemerocher Thanks for the quick response, I just wanted to make sure I wasn't doing it wrong. I'll open up an issue report

**Comment by matt-snider** [comment]
@graemerocher I added #815
