### ISSUE TITLE
Using Propagation.REQUIRES_NEW leaves synchronousTransactionState null after commit

### ISSUE THREAD

**Issue by eratio08** [micronaut-projects/micronaut-data#1630]
### Expected Behavior

In Mirconaut `3.1.4` using the following construct

```kotlin
synchronousTransactionManager.execute(TransactionDefinition.of(TransactionDefinition.Propagation.REQUIRES_NEW)) {
    block(it)
}
```
did not cause any issues. 

### Actual Behaviour

After upgrading to `3.5.2` this will cause a `java.lang.IllegalStateException: Transaction state is not initialized!`. If this construct was called in a transactional context e.g. a `@MicronautTest`.

After checking the code a bit it looks like in `io.micronaut.transaction.support.AbstractSynchronousStateTransactionManager#cleanupAfterCompletion` if a state has suspended resources, these are not resumed if `status.isNewTransaction()`. I would expect the suspended transaction getting resumed after the current transaction was commited.

### Steps To Reproduce

```kotlin
@MicronautTest
class ExampleIntegrationTest {

	@Inject
	private lateinit var synchronousTransactionManager: SynchronousTransactionManager<Connection>

	@Test
	fun `reproduce issues`() {
		synchronousTransactionManager.execute(TransactionDefinition.of(TransactionDefinition.Propagation.REQUIRES_NEW)) {
			it.connection.prepareStatement(
				"""
			CREATE TABLE test (id bigserial NOT NULL PRIMARY KEY);
			""".trimIndent(),
			).use { ps -> ps.executeUpdate() }
		}
	}
}
```

### Environment Information

java=17.0.3-tem
kotlin=1.7.10

### Version

3.5.2

**Comment by dstepanov** [comment]
Can you please try Micronaut 3.5.3?

**Comment by eratio08** [comment]
Looks good so far! Looks like the `else if` -> `if` in `io.micronaut.transaction.support.AbstractSynchronousStateTransactionManager#cleanupAfterCompletion` now resumes suspended transactions again THX!
