### ISSUE TITLE
@Transient not working with Kotlin data class

### ISSUE THREAD

**Issue by GeitV** [micronaut-projects/micronaut-data#1633]
### Expected Behavior

When annotating field with `@Transient` in Kotlin data class, this field would be ignored and Repository fetch would still work.

### Actual Behaviour

Gets an exception

```kotlin
DataAccessException: SQL Error preparing Query: Constructor argument [children] for type [com.binderr.csp.automation.db.model.AutomationNode] must have an associated getter
```

### Create entity
note - this is done this way because we couldn't understand how could we relate to the same table as "child". If anyone has idea, how to make `@Relation` to itself (eg. `AutomationNode` has field `children: List<AutomationNode>`) work, then please let us know :) )

```kotlin
@MappedEntity
data class AutomationNode(
    @field:Id
    @GeneratedValue
    val id: UUID? = null,
    
    @Relation(Relation.Kind.ONE_TO_MANY, mappedBy = "automationNode")
    val childrenIds: List<AutomationNodeChild>?,

    @Transient
    val children: List<AutomationNode>? = null
)

@MappedEntity
data class AutomationNodeChild(
    @field:Id
    @GeneratedValue
    val id: UUID? = null,
    @Relation(Relation.Kind.MANY_TO_ONE)
    val automationNode: AutomationNode?,
    val childId: UUID
)
```

### Create repository
```kotlin
@JdbcRepository(dialect = Dialect.POSTGRES)
interface AutomationNodeRepository : CrudRepository<AutomationNode, UUID> {

    @JoinSpecifications(
        Join(value = "childrenIds", type = Join.Type.LEFT_FETCH)
    )
    fun findAll(): List<AutomationNode>
}
```

### Call the method
And get the error

### Environment Information

- JDK 17
- Kotlin 1.6.10
- Micronaut 3.4.4 (cannot upgrade, getting issues because of **micronaut-serialization** package, which fix is marked for 3.6.0 release)
- Non-native

### Version

3.4.4

**Comment by dstepanov** [comment]
It might need to be `@field:Transient`

**Comment by GeitV** [comment]
Hey @dstepanov, thanks for quick reply - sadly, this did not change the outcome.

**Comment by GeitV** [comment]
I tried that as well, but it still gave the same error - I read that issue as well, but it didn't seem to use Kotlin data class, instead I think it used Java record class.

**Comment by GeitV** [comment]
That did indeed work - seems like I tried to use `@Creator` incorrectly before, my bad!

Thanks for such a quick help, will close this task as there's then nothing to fix
