### ISSUE TITLE
Azure CosmosDB integration

### ISSUE THREAD

**Issue by haris-zynka** [micronaut-projects/micronaut-data#164]
Will it be possible later to integrate this with Cosmos DB? I'm more exited if the annotations get there to support things like gremlin and document store at the same time but more importantly to at least be able to resolve gremlin relationships.

Given class A that has the edge to class B it would be great if a repository could at the query time resolve edges from A -> B and inject B.Id into A.relatedId. Or at least if putting fromId and toId inside edge would be resolve automatically so I don't have to write specific queries to fetch ids for certain types. This relates only to things we know we would have only 1 relationship. Example we know that class Page has only 1 edge towards Book and we only need 1 bookId when fetching Page.

**Comment by graemerocher** [comment]
Support for more NoSQL stores is planned yes

**Comment by radovanradic** [comment]
Done earlier in 3.9 via SQL api.
