### ISSUE TITLE
`@ColumnTransformer` with a parameter expansion fails

### ISSUE THREAD

**Issue by Steven-M-Brown** [micronaut-projects/micronaut-data#1640]
### Expected Behavior

The following code results in `IllegalStateException` for the generated `update` on repositories:
```java
  @ColumnTransformer(
      read =
          "pgp_sym_decrypt(column_name::bytea, '${config.key}')",
      write = "pgp_sym_encrypt(?, '${config.key}')")
```

It correctly generates the query, writes it out to the introspection class file, reads it from the introspection file, and substitutes the value.

After stepping through it things go wrong in `AnnotationValue#resolveStringValues()` because the value mapper defined in `AbstractEnvironmentAnnotationMetadata#stringValues()` sees the commas in the query elements (see image below for example), sets `expandValues` to true, then expands the array into a jumbled mess with too many elements causing a throw of an `IllegalStateException` while building the `StoredSqlOperation`.

### Actual Behaviour

Substitute the value into the query and not throw an `IllegalStateException`

### Steps To Reproduce

1) Latest micronaut + micronaut-data + postgres.

2) Put this on a entity column:
```java
  @ColumnTransformer(
      read =
          "pgp_sym_decrypt(column_name::bytea, '${config.key}')",
      write = "pgp_sym_encrypt(?, '${config.key}')")
```

3) Use the default crud repository to read/write it to the table.

4) Fails with `IllegalStateException`

### Version

3.3.4 (corresponds to data version 3.2.2)

### Images
<img width="314" alt="image" src="https://user-images.githubusercontent.com/52847291/179815017-b4d3a9c9-47ad-4719-ac67-15ef4fd87d39.png">

**Comment by dstepanov** [comment]
I don't think we want to support this way. In the future, I will introduce `... #myParam ...` which will be a way to bind values provided by some services.

**Comment by Steven-M-Brown** [comment]
I was able to duplicate the issue on both Micronaut Data BoM version 3.4.3 and 3.5.0.

Depending on what that test does you may not see the issue. As I mentioned in the original comment:
* The query generates correctly
* The query is written correctly to the introspection file
* The query loads correctly from the introspection file
* The query substitutes the placeholder correctly up until a certain point in code
* When you try and _use_ the query it fails for `update`

**Comment by dstepanov** [comment]
Can you please create a simple reproducer?

**Comment by Steven-M-Brown** [comment]
While creating a reproducer I learned that it requires an "expandable" field to be present; I am not sure what that means but it seems `@DateUpdated` is one.

Here is the reproducer: https://github.com/Steven-M-Brown/brokenquery

**Comment by dstepanov** [comment]
This was fixed, but issue remained open
