### ISSUE TITLE
Remove excessive commit statements

### ISSUE THREAD

**Issue by prokop7** [micronaut-projects/micronaut-data#1642]
### Feature description

Here is some example of Micronaut trace of querying 6 consecutive selects without updates/deletes/inserts

![image](https://user-images.githubusercontent.com/16087095/179863829-96e11242-933f-4002-b195-fe8b7b0e3867.png)

Nonetheless, Micronaut sends commit after each operation when it is not required (i.e. in PostgreSQL)

This doubles the amount of queries and if a connection to a DB has high latency that would cause performance degradation.
In fact, Spring solves this problem with creation of a mock transaction info that does not hold an actual transaction
![image](https://user-images.githubusercontent.com/16087095/179864254-82b629ff-928e-425e-b022-6e8e662efffd.png)

Same request with Spring
![image](https://user-images.githubusercontent.com/16087095/179865054-e88392c0-0a59-4068-963f-424a24cea5f3.png)

I would gladly see something like this in Micronaut

**Comment by dstepanov** [comment]
There are two options you can set on every datasource:
- `transaction-per-operation` - will not open a TX on operation - (default true)
- `allow-connection-per-operation` - will open a connection on operation (default false)

**Comment by dstepanov** [comment]
Please try with the latest version. It would be nice to have an example app to check.
