### ISSUE TITLE
Unable to build using GraalVM native-image tool

### ISSUE THREAD

**Issue by ivangfr** [micronaut-projects/micronaut-data#166]
Hi, I am trying to use **GraalVM native-image tool** to build a simple **Micronaut** application, but I am getting an exception.

The application is a simple `book-api` and its source-code is: https://github.com/ivangfr/graalvm-micronaut-springboot-comparison/tree/master/book-api. You can use it in case you want to replicate the exception.

Below is the exception that I am getting
```
Error: Classes that should be initialized at run time got initialized during image building:
 org.springframework.jdbc.datasource.ConnectionProxy the class was requested to be initialized at build time (from the command line). com.sun.proxy.$Proxy355 caused initialization of this class with the following trace: 

com.oracle.svm.core.util.UserError$UserException: Classes that should be initialized at run time got initialized during image building:
 org.springframework.jdbc.datasource.ConnectionProxy the class was requested to be initialized at build time (from the command line). com.sun.proxy.$Proxy355 caused initialization of this class with the following trace: 

        at com.oracle.svm.core.util.UserError.abort(UserError.java:65)
        at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.checkDelayedInitialization(ConfigurableClassInitialization.java:494)
        at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.duringAnalysis(ClassInitializationFeature.java:188)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$8(NativeImageGenerator.java:711)
        at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:63)
        at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:711)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:526)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:444)
        at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error: Image build request failed with exit status 1
```

I am using the following arguments in `native-image.properties`
```
Args = -H:IncludeResources=logback.xml|application.yml \
       -H:Name=micronaut-book-api \
       -H:Class=com.mycompany.micronautbookapi.Application \
       -H:+TraceClassInitialization \
       -H:+ReportExceptionStackTraces \
       --initialize-at-run-time=java.sql.DriverManager \
       --initialize-at-run-time=org.springframework.jdbc.datasource.ConnectionProxy
```

Thanks!

**Comment by ivangfr** [comment]
@graemerocher 

After the changes you did, I am still facing the same problem.
I have updated my `build.gradle`

from
```
set('micronautVersion', '1.2.2')
set('micronautDataVersion', '1.0.0.M1')
```

to
```
set('micronautVersion', '1.2.3')
set('micronautDataVersion', '1.0.0.M2')
```

Should I do any other changes in my code?

**Comment by graemerocher** [comment]
Ah I see you are using the JPA impl 

The fix only applies to the JDBC impl. As a workaround you can copy this class into your project until I add the equivalent one for JPA:

https://github.com/micronaut-projects/micronaut-data/blob/master/data-jdbc/src/main/java/io/micronaut/data/jdbc/graal/DataSourceTransactionManagerFactorySubstitutions.java

Sorry about that

**Comment by graemerocher** [comment]
Fixed this for good in master by removing Spring for transaction management

**Comment by ivangfr** [comment]
Hey @graemerocher 

I've updated the `build.gradle` file of my project  https://github.com/ivangfr/graalvm-micronaut-springboot-comparison/tree/master/book-api

from
```
set('micronautVersion', '1.2.2')
set('micronautDataVersion', '1.0.0.M1')
```

to
```
set('micronautVersion', '1.2.3')
set('micronautDataVersion', '1.0.0.M3')
```
> I haven't commit the code, but that is the only change.

And I am getting
```
HTTP/1.1 500 Internal Server Error
{
    "message": "Internal Server Error: Error instantiating bean of type  [io.micronaut.data.hibernate.operations.HibernateJpaOperations]\n\nMessage: Missing bean argument value: transactionOperations\nPath Taken: new HibernateJpaOperations(SessionFactory sessionFactory,[TransactionOperations transactionOperations],ExecutorService executorService)"
}
```

The application is so simple that there is no need to add transactions to it.

I've seen some comments on Gitter, but I haven't got exactly what to do. I am following the https://micronaut-projects.github.io/micronaut-data/latest/guide/ and I believe my app is configured correctly. Maybe, I am missing something.

Thanks!

**Comment by graemerocher** [comment]
Please see https://github.com/micronaut-projects/micronaut-data/tree/master/examples/example-jpa for a working example with the correct dependencies

**Comment by ivangfr** [comment]
Hey

I've used the [example-jpa](https://github.com/micronaut-projects/micronaut-data/tree/master/examples/example-jpa) as a base for fixing my project and it works now.

However, I needed to change many things like, add some Hibernate configuration in `build.gradle`, [replace micronaut-jdbc-hikari with micronaut-jdbc-tomcat](https://github.com/micronaut-projects/micronaut-data/issues/200) and [use H2 instead of MySQL](https://bugs.mysql.com/bug.php?id=91968). I also needed to [disable the micrometer](https://github.com/micronaut-projects/micronaut-data/issues/199)
