### ISSUE TITLE
@Query annotation: WHERE IN(:values) queries are not transforming values

### ISSUE THREAD

**Issue by charlie-harvey** [micronaut-projects/micronaut-data#1660]
### Expected Behavior

Values in the `IN(:values)` clause should be transformed - they used to.

```kotlin
    @Query(
        """
            SELECT *
            FROM userAccount
            WHERE siteId = :siteId
            AND id IN(:ids)
        """
    )
    suspend fun findByIdsIn(
        siteId: Int,
        ids: Collection<OptimizedUUID>
    ): List<UserAccount>
```

### Actual Behaviour

```
Error invoking doInTransaction handler: Cannot convert type [class java.util.ArrayList] to target type: class [B. Considering defining a TypeConverter bean to handle this case.
```

### Steps To Reproduce

https://github.com/charlie-harvey/micronaut-kotlintransactions-2

Run `./gradlew build` and test will fail.

### Environment Information

Operating System: MacOS
JDK: corretto-17
Micronaut: 3.5.3
Micronaut-Data: 3.5.0

### Example Application

https://github.com/charlie-harvey/micronaut-kotlintransactions-2

### Version

3.5.3

**Comment by Goldmensch** [comment]
You should try to let Micronaut generate this query for you, something like `findBySiteIdAndIdsIn(siteId: Int, ids: Collection<OptimizedUUID>): List<UserAccount>` could work. Alternatively expandable queries or an (sql) array could be used:
https://micronaut-projects.github.io/micronaut-data/latest/guide/#sqlExpandableQueries

**Comment by charlie-harvey** [comment]
This was a simplified example. I already had the generated one, and it works great:

```kotlin
    suspend fun findBySiteIdAndIdIn(siteId: Int, ids: Collection<OptimizedUUID>): List<UserAccount>

    @Query(
        """
            SELECT *
            FROM userAccount
            WHERE siteId = :siteId
            AND id IN(:ids)
        """
    )
    suspend fun findByIdsIn(
        siteId: Int,
        ids: Collection<OptimizedUUID>
    ): List<UserAccount>
```

But the larger example was like this:
```kotlin
    @Query(
        """
            SELECT latestSetting.*
            FROM settings latestSetting
            WHERE siteId = :siteId
            AND settingCode = :settingCode
            AND userId IN(:userIds)
            AND NOT EXISTS(
               SELECT 1 
               FROM settings
               WHERE settings.settingCode = :settingCode
               AND settings.userId = latestSetting.userId
               AND settings.lastSetAt > latestSetting.lastSetAt
            )
        """
    )
    fun findLatestSettingRecordForUsers(
        siteId: Int,
        settingCode: SettingCodes,
        userIds: Collection<OptimizedUUID>
    ): Collection<Setting>
```

This query was working with Micronaut Data 3.4.3 (and below) and just stopped working in 3.5.0.

**Comment by dstepanov** [comment]
Can you try to annotate the parameter with https://github.com/micronaut-projects/micronaut-data/blob/master/data-model/src/main/java/io/micronaut/data/annotation/Expandable.java

**Comment by Goldmensch** [comment]
Or you could try to build something with the @Where Annotation, but I'm not sure how far you can and should go with it.

**Comment by charlie-harvey** [comment]
Now things just got even weirder. Here is the change to the code:
```kotlin
    @Query(
        """
            SELECT *
            FROM userAccount
            WHERE siteId = :siteId
            AND id IN(:ids)
        """
    )
    suspend fun findByIdsIn(
        siteId: Int,
        @Expandable ids: Collection<OptimizedUUID>
    ): List<UserAccount>
```

Now the error is completely ridiculous:
```
Rolling back transaction: UserAccountRepository.findByIdsIn on error: Table 'test.userAccount' doesn't exist for dataSource accounts-async-datasource
    io.r2dbc.spi.R2dbcBadGrammarException: Table 'test.userAccount' doesn't exist
        at dev.miku.r2dbc.mysql.ExceptionFactory.createException(ExceptionFactory.java:81)
        at dev.miku.r2dbc.mysql.TextQueryHandler.accept(QueryFlow.java:317)
        at dev.miku.r2dbc.mysql.TextQueryHandler.accept(QueryFlow.java:292)
        at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:176)
        at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
        at dev.miku.r2dbc.mysql.util.DiscardOnCancelSubscriber.onNext(DiscardOnCancelSubscriber.java:70)
        at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onNext(FluxPeekFuseable.java:854)
        at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onNext(MonoFlatMapMany.java:250)
        at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:200)
        at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:126)
        at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onNext(FluxPeekFuseable.java:854)
        at reactor.core.publisher.EmitterProcessor.drain(EmitterProcessor.java:491)
        at reactor.core.publisher.EmitterProcessor.tryEmitNext(EmitterProcessor.java:299)
        at reactor.core.publisher.InternalManySink.emitNext(InternalManySink.java:27)
        at reactor.core.publisher.EmitterProcessor.onNext(EmitterProcessor.java:265)
```

Am I using the annotation correctly?

**Comment by Goldmensch** [comment]
Please try to use a native query `@Quere(nativeQuery = true)`

**Comment by charlie-harvey** [comment]
I am having a few other issues too that are making this hard to debug:

1. If you use migrations AND have a named datasource ("accounts-datasource") instead of "default", then you essentially have two datasources with the same name, one for R2DBC and one for JDBC. They collide and you get errors.
    - I "fixed" this by giving the R2DBC datasource a distinct name: "accounts-async-datasource"
2. If you use migrations AND want to use Testcontainers, you can't. The "tc" url to the JDBC database is different from the "tc" url to the R2DBC database. So you get two databases. And the migrations only run on the JDBC database.
    - I "fixed" this by creating a `TestMySQLContainer` that extends `MySQLContainer` and a Kotest Extension that runs this container. The container dumps the host/port/username/password into the environment. Those values are ready by Micronaut in the yml files.

**Comment by charlie-harvey** [comment]
> Please try to use a native query `@Quere(nativeQuery = true)`

No dice. Same error.

**Comment by Goldmensch** [comment]
> > Please try to use a native query `@Quere(nativeQuery = true)`
> 
> No dice. Same error.

As mentioned before, you can try to use a @Where annotation, but have you tried to use `@TypeDef(type = DataType.STRING_ARRAY)` as mentioned here: https://micronaut-projects.github.io/micronaut-data/latest/guide/#sqlExpandableQueries as a tip

**Comment by charlie-harvey** [comment]
I am already using:

```
@TypeDef(type = DataType.BINARY_ARRAY)
```

**Comment by dstepanov** [comment]
```
Rolling back transaction: UserAccountRepository.findByIdsIn on error: Table 'test.userAccount' doesn't exist for dataSource accounts-async-datasource
    io.r2dbc.spi.R2dbcBadGrammarException: Table 'test.userAccount' doesn't exist
```
This indicated that the query is property created but the database is not populated.

**Comment by charlie-harvey** [comment]
If I remove the ***@***.***` then I get the original error. And I can see
in the logs that the migrations ran. And the other test, `findByUsername`
works just fine.

**Comment by charlie-harvey** [comment]
More digging! I _think_ this is only a problem with columns like BINARY_ARRAY.

So for `@Query()` and for `CriteriaApi` queries, anything with a `WHERE IN` clause is not generating the right SQL.

Here is an example:

```
UPDATE `userAccounts` SET `active`=?,`tobedeleted`=? WHERE (`firstName` IN (?))
```
Should look like this:
```
UPDATE `userAccounts` SET `active`=?,`tobedeleted`=? WHERE (`firstName` IN (?, ?, ?, ?))
```

Code:
```
        UpdateSpecification { root, query, criteriaBuilder ->
            query.set(root[UserAccount::active], false)
            query.set(root[UserAccount::tobedeleted], true
            val fNameExp = criteriaBuilder.`in`(root[UserAccount::firstName]).value("pants").value("shirts").value("vests").value("socks")
            println(" **** fNameExp: $fNameExp")
            val fNamePredicate = root[UserAccount::firstName].`in`("pants", "shirts", "vests", "socks")
            // query.where(root[UserAccount::firstName].`in`("pants", "shirts", "vests", "socks"))
            println(" **** fNamePredicate: $fNamePredicate")
            query.where(fNameExp)
            // query.where(fNamePredicate)
            null
       }
```

No matter how I work it I always get the same result. I think this is a bug.

**Comment by dstepanov** [comment]
@charlie-harvey Can we close this one? Or is there something that doesn't work?

**Comment by charlie-harvey** [comment]
With this fix and the use of `@Expandable` everything seems to be working. It can be closed.

Thanks so much!
