### ISSUE TITLE
Loading nested oneToMany relations

### ISSUE THREAD

**Issue by alberto-pelosi** [micronaut-projects/micronaut-data#167]
Hi,

I have a Class A in oneToMany relation with class B.
Class B is in oneToMany relation with class C.
On db there are table A, A_B, B, B_C and C.
findById on repository A is defined as follow:
```
 @Join(value = "...", type = Join.Type.LEFT_FETCH)
    public abstract Optional<...> findById(Long id);
```
In the same way I have defined findById on repository B.
In this way, when I call findById on repository A I get an object of class A with the right references to the associated objects of class B, but these objects has null reference to objects of class C.
I suppose this is the desidered behaviour, but how can I obtain the resolution of all my inner objects?

Thanks,

Alberto

**Comment by graemerocher** [comment]
Specify the full path in the join. For example `@Join("b.c")`

**Comment by alberto-pelosi** [comment]
Hi,

thank you for your answer.

Using 

```
@Join("b.c")
```

Seems to generate a query like:


SELECT ... FROM 
A aliasA 
LEFT JOIN 
A_B aliasA_B
ON aliasA.id = aliasA_B._id
LEFT JOIN 
B aliasB
ON aliasA_B.B_id = aliasB.id
LEFT JOIN 
B_C aliasB_C
***ON aliasA.id = aliasB_C.B_id***
LEFT JOIN ...


But I would like to have something like:

SELECT ... FROM 
A aliasA 
LEFT JOIN 
A_B aliasA_B
ON aliasA.id = aliasA_B.A_id
LEFT JOIN 
B aliasB
ON aliasA_B.B_id = aliasB.id
LEFT JOIN 
B_C aliasB_C
***ON aliasB.id = aliasB_C.B_id***
LEFT JOIN ...

**Comment by graemerocher** [comment]
hmm seems like a bug. Please provide an example that reproduces.

**Comment by alberto-pelosi** [comment]
Hi,

here an example.

A Shelf has many Book(s), a Book has many Page(s).

```
import lombok.Data;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import java.util.List;

@Entity
@Data
public class Shelf {

    @Id
    @GeneratedValue
    private Long id;

    private String shelfName;

    @OneToMany
    private List<Book> books;


}
```

```
import lombok.Data;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import java.util.List;

@Entity
@Data
public class Book {

    @Id
    @GeneratedValue
    private Long id;


    private String title;

    @OneToMany
    private List<Page> pages;
}
```

```
import lombok.Data;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

@Entity
@Data
public class Page {
    @Id
    @GeneratedValue
    private Long id;


    private Integer num;
}
```

```
import com.codermine.dispatcher.models.Shelf;
import io.micronaut.data.annotation.Join;
import io.micronaut.data.jdbc.annotation.JdbcRepository;
import io.micronaut.data.model.query.builder.sql.Dialect;
import io.micronaut.data.repository.CrudRepository;

import java.util.Optional;

@JdbcRepository(dialect = Dialect.POSTGRES)
public abstract class ShelfRepository implements CrudRepository<Shelf, Long> {

    @Join(value = "books.pages", type = Join.Type.LEFT_FETCH)
    public abstract Optional<Shelf> findById(Long id);
}

```

Query:

io.micronaut.data.query - Executing Query: 


SELECT shelf_.id,shelf_.shelf_name,shelf_books_pages_.id AS _books_pages_id,shelf_books_pages_.num AS _books_pages_num 

FROM shelf shelf_ 

LEFT JOIN shelf_book shelf_books_shelf_book_ 

ON shelf_.id=shelf_books_shelf_book_.shelf_id  

LEFT JOIN book shelf_books_ 

ON shelf_books_shelf_book_.book_id=shelf_books_.id 

LEFT JOIN book_page shelf_books_pages_book_page_ 

**ON shelf_.id=shelf_books_pages_book_page_.book_id**

LEFT JOIN page shelf_books_pages_ 

ON shelf_books_pages_book_page_.page_id=shelf_books_pages_.id 

WHERE (shelf_.id = ?)

See attach

[library.zip](https://github.com/micronaut-projects/micronaut-data/files/3651041/library.zip)

**Comment by graemerocher** [comment]
Thanks will take a look
