### ISSUE TITLE
Micronaut Data with Native Query and limit

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-data#1676]
Use Micronaut Data JPA with H2

The following query will fail:

```
@Query(nativeQuery = true, value = "select * from project limit 1")    
Project findSingleProject();
```

```
- Syntax error in SQL statement "SELECT * FROM PROJECT LIMIT 1 LIMIT[*] ?"; SQL statement:
select * from project limit 1 limit ? [42000-200]

javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: could not prepare statement
```

It seems Micronaut Data adds `limit`. I think if the query native contains a `limit` we should not add an extra limit keyword.

**Comment by graemerocher** [comment]
I don't understand this issue report, a native query means a SQL query and you have the `limit` in your query definition?

**Comment by ngulyaev** [comment]
@graemerocher Yes, I have the same issue, I have tried to use the native query for refreshing a materialized view, but the limit parameter was added to the end of the query automatically
