### ISSUE TITLE
Kotlin+Maven+Hibernate not working out of the box

### ISSUE THREAD

**Issue by RiccardoManzan** [micronaut-projects/micronaut-data#1687]
### Expected Behavior

After generating the launch project, it should be ready out of the box

### Actual Behaviour

Unable to compile the code, here's the exception:
```log
user@ubuntu$ ./mvnw  mn:run
[INFO] Scanning for projects...
[INFO]
[INFO] --------------------------< com.example:demo >--------------------------
[INFO] Building demo 0.1
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] >>> micronaut-maven-plugin:3.4.0:run (default-cli) > process-classes @ demo >>>
[INFO]
[INFO] --- kotlin-maven-plugin:1.6.10:kapt (kapt) @ demo ---
[WARNING] 'tools.jar' was not found, kapt may work unreliably
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.664 s
[INFO] Finished at: 2022-08-09T17:32:41+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.jetbrains.kotlin:kotlin-maven-plugin:1.6.10:kapt (kapt) on project demo: Plugin not found: jpa: java.util.NoSuchElementException
[ERROR]       role: org.jetbrains.kotlin.maven.KotlinMavenPluginExtension
[ERROR]   roleHint: jpa
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

Searching on the net it looks it's missing the following dependency in kotlin-maven-plugin dependencies section
```pom.xml
<dependency>
 <groupId>org.jetbrains.kotlin</groupId>
 <artifactId>kotlin-maven-noarg</artifactId>
 <version>${kotlinVersion}</version>
</dependency>
```
Adding this, actually there are other errors due to missing entities in application, but that's ok i guess

### Steps To Reproduce

1. Download the project from https://micronaut.io/launch?type=DEFAULT&name=demo&package=com.example&javaVersion=JDK_11&lang=KOTLIN&build=MAVEN&test=JUNIT&features=data-jpa&features=jdbc-hikari&features=h2&version=3.6.0
2. Extract the zip
3. CD into demo folder
4. try compiling with `./mvnw clean install` or `./mvnw mn:run`

### Environment Information

- Ubuntu 20.04
- Java 11
- Kotlin+Micronaut

### Example Application

Download the project from https://micronaut.io/launch?type=DEFAULT&name=demo&package=com.example&javaVersion=JDK_11&lang=KOTLIN&build=MAVEN&test=JUNIT&features=data-jpa&features=jdbc-hikari&features=h2&version=3.6.0

### Version

3.6.0

**Comment by radovanradic** [comment]
@RiccardoManzan Have you tried it with 3.6.1? I tried today and didn't get the error you pasted above.
Just got this demo project from https://micronaut.io/launch?type=DEFAULT&name=demo&package=com.example&javaVersion=JDK_11&lang=KOTLIN&build=MAVEN&test=JUNIT&features=data-jpa&features=jdbc-hikari&features=h2&version=3.6.1 and added this entity to src/main/kotlin/com/example 

```
package com.example

import javax.persistence.Entity
import javax.persistence.GeneratedValue
import javax.persistence.Id

@Entity
data class Book(@Id
                @GeneratedValue
                var id: Long,
                var title: String,
                var pages: Int = 0)

```
and `./mvnw clean install` completed successfully.

**Comment by RiccardoManzan** [comment]
Awesome, i think this is resolved then.
