### ISSUE TITLE
NotFound micronaut-data-hibernate-jpa in Maven repo

### ISSUE THREAD

**Issue by muyu66** [micronaut-projects/micronaut-data#169]
In the picture below, there should be "**micronaut-data-hibernate-jpa**" package.
![image](https://user-images.githubusercontent.com/20837526/65502291-190ac200-def5-11e9-9bb5-0191ba72eccf.png)

https://repo.maven.apache.org/maven2/io/micronaut/data/micronaut-data-hibernate-jpa/1.0.0.M1/micronaut-data-hibernate-jpa-1.0.0.M1.pom

![image](https://user-images.githubusercontent.com/20837526/65502319-23c55700-def5-11e9-89c3-4edd71f62b87.png)

**Comment by graemerocher** [comment]
Thanks for reporting this. It is available in JCenter http://jcenter.bintray.com/io/micronaut/data/micronaut-data-hibernate-jpa/1.0.0.M1/

For some reason the JCenter to Maven Central sync is failing at the validation step but only for this module. We are investigating

**Comment by muyu66** [comment]
> Thanks for reporting this. It is available in JCenter http://jcenter.bintray.com/io/micronaut/data/micronaut-data-hibernate-jpa/1.0.0.M1/
> 
> For some reason the JCenter to Maven Central sync is failing at the validation step but only for this module. We are investigating

After using the above scheme, it has returned to normal.

Previously

    Repositories {
		mavenCentral()
	}

it is ... now

    Repositories {
	     mavenCentral()
	     jcenter()
	}

**Comment by shubhwip** [comment]
For maven users please follow this link
```
        <profile>
            <repositories>
                <repository>
                    <snapshots>
                        <enabled>false</enabled>
                    </snapshots>
                    <id>central</id>
                    <name>bintray</name>
                    <url>https://jcenter.bintray.com</url>
                </repository>
            </repositories>
            <pluginRepositories>
                <pluginRepository>
                    <snapshots>
                        <enabled>false</enabled>
                    </snapshots>
                    <id>central</id>
                    <name>bintray-plugins</name>
                    <url>https://jcenter.bintray.com</url>
                </pluginRepository>
            </pluginRepositories>
            <id>bintray</id>
        </profile>
```
