### ISSUE TITLE
JPA Specification Ordering by nullable entity.field do not includes null joined results

### ISSUE THREAD

**Issue by RiccardoManzan** [micronaut-projects/micronaut-data#1703]
### Expected Behavior

It's not so simple to explain this issue, sorry for the confusion then

Let's say we have two entities, one is product and one is vendor which are linked together with a many-to-one relationship.
Let's say that we could have generic products that do not rely on any specific vendor

So we would have something like this: 

```kotlin
@Entity
data class Product (
  @field:Id
  @field:GeneratedValue(strategy = GenerationType.AUTO, generator = "native")
  @field:GenericGenerator(name = "native", strategy = "native")
  val id: Long,
  val name: String,
  @ManyToOne(optional=true)
  val vendor: Vendor? = null
)

@Entity
data class Vendor (
  @field:Id
  @field:GeneratedValue(strategy = GenerationType.AUTO, generator = "native")
  @field:GenericGenerator(name = "native", strategy = "native")
  val id: Long,
  val name: String,
)
```

Let's populate data using this example set:
* Vendors: VendorA, VendorB
* Products: 
  | Name | Vendor |
  | --- | --- |
  | Cardboard Box | none |
  | Water Bottle | VendorA |
  | Sugar | Vendor B | 
  | Salt | VendorA |

And now let's filter this using a `JpaSpecificationExecutor` repository:

```kotlin
val result = productsRepository.findAll(
  Specification.where(null), // this is an example but you may want to do some filtering here
  Pageable.from(
    0,
    10,
    Sort.of( Order( "name", Order.Direction.ASC ) )
  )
)
```
then i expect to obtain the list:
  | Name | Vendor |
  | --- | --- |
  | Cardboard Box | none |
  | Salt | VendorA |
  | Sugar | Vendor B | 
  | Water Bottle | VendorA |

and that's exactly what happens.

What if we do the following query?

```kotlin
val result = productsRepository.findAll(
  Specification.where(null), // this is an example but you may want to do some filtering here
  Pageable.from(
    0,
    10,
    Sort.of( Order( "vendor.name", Order.Direction.ASC ) )
  )
)
```
then i would expect to obtain the list:

  | Name | Vendor |
  | --- | --- |
  | Cardboard Box | none |
  | Water Bottle | VendorA |
  | Salt | VendorA |
  | Sugar | Vendor B | 

or maybe

  | Name | Vendor |
  | --- | --- |
  | Water Bottle | VendorA |
  | Salt | VendorA |
  | Sugar | Vendor B | 
  | Cardboard Box | none |

### Actual Behaviour

The results of that query are:

  | Name | Vendor |
  | --- | --- |
  | Water Bottle | VendorA |
  | Salt | VendorA |
  | Sugar | Vendor B | 
  
Futhermore, as you can see, here we have 3 results, but `result.totalSize` is valorized to 4, which actually is the count of the results without sorting or with a simpler sorting.

### Steps To Reproduce

See _Expected Behavior_ section

### Environment Information

- Ubuntu 20.04
- JDK 11
- micronaut-data + micronaut-data-hibernate-jpa + micronaut-jdbc-hikari + h2

### Version

3.6.0

**Comment by dstepanov** [comment]
Please check what SQL Hibernate is generating. I suspect that you are missing the JOIN. Hibernate would do some weird CROSS JOIN in that case.

**Comment by RiccardoManzan** [comment]
Thanks @dstepanov, i was just about to add that debugging more in detail, it looks that this is caused because the system generates a query that uses a `cross join` instead of a `left outer join`.

The query looks like this:
```sql
select some, fields from product cross join vendor where product.vendor_id=vendor.id order by vendor.name asc limit ?
```
Then yeah the problem looks be the type of the join. I hope there's some magic annotation that says to hibernate what join to do.
So yeah, this is not something due to micronaut data.

**Comment by RiccardoManzan** [comment]
@dstepanov, i looked at criteriaBuilder of Specification "toPredicate" method and i cannot figure out what to do.
I tried adding a specification like this:
```kotlin
Specification<Product> { root, query, criteriaBuilder ->
  query.from(Product::class.java).join<Product, Vendor>(Product::vendor.name, JoinType.LEFT).on
}
```
But it happens that 2 joins are made:
```sql
select productFields from product product0 cross join product product1 left outer join vendor vendor2 on product1.vendor_id=vendor2.id cross join vendor vendor3 where product.vendor_id=vendor3.id order by vendor3.name asc limit ?
```
Could you please make an example on how it should be done?

**Comment by RiccardoManzan** [comment]
Ok, i was doing some mess,
It works this way:
```kotlin
val result = productsRepository.findAll(
  Specification.where(
    Specification<Product> { root, query, criteriaBuilder ->
      root.join<Product, Vendor>(Product::vendor.name, JoinType.LEFT).on
    }
  ), // here you can add some other specification using .and function
  Pageable.from(
    0,
    10,
    Sort.of( Order( "vendor.name", Order.Direction.ASC ) )
  )
)
```
Thankyou again for your help.

**Comment by dstepanov** [comment]
Great to know! Thanks!
