### ISSUE TITLE
data-mongodb: Properties marked with `@JsonView` in a mapped entity are skipped by the Mongo repository implementation 

### ISSUE THREAD

**Issue by rohitkumbhar** [micronaut-projects/micronaut-data#1729]
### Expected Behavior

Any properties marked with `@JsonView` in a mapped entity are loaded  by the Mongo repository 

### Actual Behaviour

Any properties marked with `@JsonView` in a mapped entity are skipped  by the Mongo repository 

Any `@MappedEntity` is not loaded correctly by MappedEntityCodec because of `@JsonView` annotation on properties. This check in `SpecificObjectDeserializer` causes the property top be skipped because `DataDecoderContext` does not override `hasView` method
```
if (property.views != null && !decoderContext.hasView(property.views)) {
       objectDecoder.skipValue();
       continue;
}
``` 

Similar behavior is seen while serializing to Mongo. `DataEncoderContext` skips over any property.

Potential solution:
Implement the `hasView` method in `DataEncoderContext` and  `DataDecoderContext` classes to return true.

Assumption:
Data loading logic does not really care about any `@JsonView` annotations on the mapped entity

Patch:
```
Index: data-mongodb/src/main/java/io/micronaut/data/mongodb/serde/DataDecoderContext.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/data-mongodb/src/main/java/io/micronaut/data/mongodb/serde/DataDecoderContext.java b/data-mongodb/src/main/java/io/micronaut/data/mongodb/serde/DataDecoderContext.java
--- a/data-mongodb/src/main/java/io/micronaut/data/mongodb/serde/DataDecoderContext.java	(revision 862b9421d372fccedb2e75bfbaea6208af635f8d)
+++ b/data-mongodb/src/main/java/io/micronaut/data/mongodb/serde/DataDecoderContext.java	(date 1662666776618)
@@ -210,4 +210,10 @@
     public void popManagedRef() {
         parent.popManagedRef();
     }
+
+    @Override
+    public boolean hasView(Class<?>... views) {
+        return true;
+    }
+
 }
Index: data-mongodb/src/main/java/io/micronaut/data/mongodb/serde/DataEncoderContext.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/data-mongodb/src/main/java/io/micronaut/data/mongodb/serde/DataEncoderContext.java b/data-mongodb/src/main/java/io/micronaut/data/mongodb/serde/DataEncoderContext.java
--- a/data-mongodb/src/main/java/io/micronaut/data/mongodb/serde/DataEncoderContext.java	(revision 862b9421d372fccedb2e75bfbaea6208af635f8d)
+++ b/data-mongodb/src/main/java/io/micronaut/data/mongodb/serde/DataEncoderContext.java	(date 1662668181150)
@@ -86,7 +86,7 @@
 
     @Override
     public boolean hasView(Class<?>... views) {
-        return parent.hasView(views);
+        return true;
     }
 
     @Override


```

I've verified that the patch works as expected locally.

### Steps To Reproduce

1. Create new micronaut app
2. Enable JSON Views and MongoDB
3. Create entity and repository
4. Create class for JSON view scope
5. Create entity and map properties with @JSONView
6. Load entity using injected repository

### Environment Information

```
jackson:
  serializationInclusion: ALWAYS
  json-view:
    enabled: true
  mapper:
    default-view-inclusion: false

mongodb:
  uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/mydb

```

### Version

3.6.1 , micronaut-data-mongodb:3.7.2

**Comment by dstepanov** [comment]
We don't use Jackson for this use case, so not sure what's the point of the configuration.

**Comment by rohitkumbhar** [comment]
The Jackson configuration is for the controller to support Json Views

**Comment by rohitkumbhar** [comment]
Example application: https://github.com/rohitkumbhar/mongo-json-view-bug

**Comment by rohitkumbhar** [comment]
Version 3.7.4 on Micronaut Data - MongoDB adds a new configuration that will not cause this issue.
```
micronaut:
  data:
    mongodb:
      ignore-json-views: true
```
