### ISSUE TITLE
Support specifying schema with @MappedEntity

### ISSUE THREAD

**Issue by jnunderwood** [micronaut-projects/micronaut-data#1731]
### Feature description

Currently in Micronaut, there is no way to specify a schema when using the `@MappedEntity` annotation. The only work-around that I am aware of is to use the `@javax.persistence.Table` annotation instead. However, I only want to use Micronaut Data JDBC and not JPA.

Please implement support for specifying a schema with `@MappedEntity`, similar to `@Table`.

Thank you.

**Comment by Goldmensch** [comment]
I suppose that `schema.table` as `MappedEntity#value()` should work.

**Comment by jnunderwood** [comment]
Thank you for your suggestion. I have tried that, but I get the following error:

`Unexpected error occurred: SQL Error executing Query: Invalid object name 'schema_name.table_name'.`

It is certainly possible I have something misconfigured, but it is a relatively simple application.

**Comment by dstepanov** [comment]
We need to introduce a new annotation for specifying the schema for SQL implementations.

**Comment by Goldmensch** [comment]
Why do we have to introduce a new annotation? A simple new field should do the job.

**Comment by dstepanov** [comment]
Because we also use `MappedEntity` for NoSQL, there schema doesn't make any sense.

**Comment by graemerocher** [comment]
probably just makes sense to add `schema` to the annotation and document it only applies to supported databases
