### ISSUE TITLE
Incorrect nullability handling in postgresql

### ISSUE THREAD

**Issue by rlconst** [micronaut-projects/micronaut-data#1741]
### Expected Behavior

you could correctly set null value for special cases like UUID

### Actual Behaviour

Currently postgresql reported error that it can't deduce type of parameter $123

### Steps To Reproduce

This is very similar to https://github.com/jOOQ/jOOQ/issues/7351

Relevant code is https://github.com/micronaut-projects/micronaut-data/blob/master/data-runtime/src/main/java/io/micronaut/data/runtime/operations/internal/sql/AbstractSqlRepositoryOperations.java#L235
and https://github.com/micronaut-projects/micronaut-data/blob/master/data-runtime/src/main/java/io/micronaut/data/runtime/mapper/QueryStatement.java#L116

### Version

3.5.1

**Comment by rlconst** [comment]
As a fallback I'm using
```
(:var= '00000000-0000-0000-0000-000000000000' OR cls.id = :var)
```

**Comment by Goldmensch** [comment]
Can you please provide the error along the entities and the repository you're using.

**Comment by rlconst** [comment]
@Goldmensch Take a look at PR with fix and demo https://github.com/rlconst/micronaut-playground/

**Comment by dstepanov** [comment]
This was fixed
