### ISSUE TITLE
Add support for hibernate-core's Postgres JSONB support in micronaut-data-hibernate-jpa.

### ISSUE THREAD

**Issue by NadeemShakya** [micronaut-projects/micronaut-data#1742]
### Feature description

The latest version of `micronaut-data-hibernate-jpa` is `3.7.3` which uses `hibernate-core` version `5.6.10.Final`.

The latest version of `hibernate-core` available is `6.1.3.Final`. As Hibernate 6 supports Postgres JSONB, having the update would make hibernate's Postgres JSONB support available to `micronaut-data` as well.

**Comment by dstepanov** [comment]
We plan to introduce Hibernate 6 support

**Comment by NadeemShakya** [comment]
Thanks for the response @dstepanov. When can we expect to have it?

**Comment by Hc747** [comment]
Bump @dstepanov, any idea when Hibernate 6 support will be arriving? Encountering the same issue/use case as the users above.

**Comment by dstepanov** [comment]
It will be released as part of Micronaut 4 in a month or two

**Comment by aozmen121** [comment]
@dstepanov Is there any update regarding this release?

**Comment by radovanradic** [comment]
Micronaut 4 is released with Hibernate 6

**Comment by radovanradic** [comment]
This is supported now.
