### ISSUE TITLE
DefaultSqlStoredQuery#bindParameter runs converter twice on property annotated with @AutoPopulated with Micronaut R2DBC.

### ISSUE THREAD

**Issue by nenad-kosanovic-tam** [micronaut-projects/micronaut-data#1759]
### Expected Behavior

When entity primary key property is annotated with:
```
    @Id
    @AutoPopulated
    @MappedProperty(definition = "binary(16)")
    @TypeDef(type = DataType.BYTE_ARRAY, converter = MySqlUuidBinaryConverter.class) 
```

On update of entity, converter should be executed just once.

### Actual Behaviour

In class DefaultSqlStoredQuery, method bindParameter converter is executed twice. First execution will crete byte[] from UUID, second execution will fails, as it will try to pass byte[] to converter which expects UUID.

### Steps To Reproduce

Checkout example github repository.
Run test in ExampleEntityRepositoryTest class.

### Example Application

https://github.com/nenad-kosanovic-tam/micronaut-converter-issue

### Version

3.6.0

**Comment by nenad-kosanovic-tam** [comment]
@radovanradic In which version will this be available?

**Comment by radovanradic** [comment]
I suppose in 3.8.1
