### ISSUE TITLE
Add a @NoExpand tag for Iterables that don't need to be expanded

### ISSUE THREAD

**Issue by h2rashee** [micronaut-projects/micronaut-data#1761]
### Expected Behavior

When passing an iterable to be written to a JSON field for an UPDATE SQL query, it writes the entire collection to the single field.

### Actual Behaviour

When passing an iterable that is being written into a JSON field, the iterable gets expanded for an UPDATE SQL query but doesn't for a CREATE SQL query.

For the UPDATE SQL query, the individual collection's values are written to other fields in the query and result in a mismatch of number of values being inserted into the number of fields available on the database record.

### Steps To Reproduce

https://gitter.im/micronautfw/questions?at=5e8674d53c6c42277aef4f32

### Environment Information

N/A

### Version

3.2.2

**Comment by dstepanov** [comment]
That code was changed some time ago. Please test with the latest version.

**Comment by radovanradic** [comment]
This appears to be fixed. [Here is the test](https://github.com/micronaut-projects/micronaut-data/blob/master/data-tck/src/main/groovy/io/micronaut/data/tck/tests/AbstractJSONSpec.groovy#L244) showing it.
In case the issue is still there, please reopen this with the reproducible example.
