### ISSUE TITLE
CrudRepository.saveAll throws exception if empty list provided

### ISSUE THREAD

**Issue by ideadapt** [micronaut-projects/micronaut-data#1772]
### Expected Behavior

No implementation of the CrudRepository.saveAll method should throw an exception, if the first and only argument is an empty list.

### Actual Behaviour

CrudRepository.saveAll throws exception if empty list provided.

This should not happen, because neither CrudRepository.saveAll nor io.micronaut.data.operations.RepositoryOperations.persistAll (which is used by many repository implementations) have this behaviour documented. It's also cumbersome for clients to always check the list size before calling saveAll.

### Steps To Reproduce

1. Create a CrudRepository
2. Call `saveAll(emptyList())` on an instance of that repository
3. Exception IllegalStateException("Entities cannot be empty") gets thrown (either by io.micronaut.data.runtime.operations.internal.AbstractReactiveEntitiesOperations or io.micronaut.data.runtime.operations.internal.AbstractSyncEntitiesOperations depending on the database driver in use)

I suggest that micronaut-data just accepts empty list arguments without throwing an exception. If an empty list is given, no change should be applied to the underlying data source. If you also have this understanding, I am happy to submit a pull request.

### Environment Information

- MacOS
- JDK 17

### Version

3.8.1

**Comment by radovanradic** [comment]
@ideadapt If you are willing to contribute, the PR is welcome.
Thanks!
