### ISSUE TITLE
MongoRepository with custom "in" query does not work with one parameter

### ISSUE THREAD

**Issue by braeluca** [micronaut-projects/micronaut-data#1788]
### Expected Behavior

When using a MongoRepository with an custom @MongoFindQuery with an "in" filter, it should be possible to supply only one entry in the list to the repository method. However, supplying a list with more than one entry works.

### Actual Behaviour

The following exception is thrown:

`Query failed with error code 2 with name 'BadValue' and error message '$in needs an array' on server localhost:51157
com.mongodb.MongoQueryException: Query failed with error code 2 with name 'BadValue' and error message '$in needs an array' on server localhost:51157` 

### Steps To Reproduce

1. Create MongoRepository
2. Create Method with custom Query with an "in" filter: `@MongoFindQuery(filter = "{'name': {'\$in': :names}}")
    fun findByNameInList(names: List<String>): List<TestDocument>`
3. Only supply a list with one entry to the method

Or run MicronautMongodbDemoTest from the example

### Environment Information

- Operating System: Windows 10 Pro Version 21H2 Nuild 19044.1889
- JDK Version: Corretto-17.0.4.8.1

### Example Application

https://github.com/braeluca/micronaut-mongodb-demo/tree/query-in-bug

### Version

3.7.1

**Comment by radovanradic** [comment]
@braeluca 

Try with this filter, it should work
```
@MongoFindQuery(filter = "{'name': {'$in': [:names]}}")
```

**Comment by braeluca** [comment]
@radovanradic Yeah that works. Thanks!

**Comment by katoquro** [comment]
Hello!
@radovanradic,  will it be changed/fixed in the future releases? IMHO it looks very counterintuitive. I even created a small separate project to understand the case 😅

**Comment by radovanradic** [comment]
@katoquro Probably won't as it would involve changes for some common code and it works with this option (or workaround).

**Comment by katoquro** [comment]
@radovanradic I see. How about adding of compilation error? As I understood case w/o `[]` isn't valid and they must be used every time when we use something with array (e.g. `$in`)

**Comment by radovanradic** [comment]
@katoquro Not sure, maybe could add some notes to the docs or something. Or you could open a ticket, @dstepanov do you think this needs to be fixed/changed?

**Comment by dstepanov** [comment]
Maybe it's possible to detect this case during the compilation

**Comment by radovanradic** [comment]
This workaround should not be necessary after #1829 was fixed (in 3.8.2 or some release coming after 3.8.1)
