### ISSUE TITLE
Task :kaptGenerateStubsKotlin task failed when upgrading to Micronaunt Data 3.8

### ISSUE THREAD

**Issue by hantsy** [micronaut-projects/micronaut-data#1803]
### Expected Behavior

I works well in the previous versions.

### Actual Behaviour

```
warning: unknown enum constant When.MAYBE

  reason: class file for javax.annotation.meta.When not found
error: Unable to implement Repository method: PostRepository.exists(QuerySpecification spec). Cannot query persistentEntity [Post] on non-existent property: spec
Note: Creating bean classes for 4 type elements
```

### Steps To Reproduce

See the build messages on Github actions.

https://github.com/hantsy/micronaut-sandbox/actions/runs/3350338917/jobs/5551075561#step:6:24

### Environment Information

-OS: Windows 10 Pro
-JDK: 17

### Example Application

https://github.com/hantsy/micronaut-sandbox/tree/master/data-jdbc-kotlin
https://github.com/hantsy/micronaut-sandbox/blob/master/data-r2dbc-kotlin-co

### Version

Micronaut Data 3.8.1

**Comment by radovanradic** [comment]
@hantsy This looks similar to https://github.com/micronaut-projects/micronaut-data/issues/1877 
Is this still happening, if not can we close this issue?

**Comment by radovanradic** [comment]
This should be resolved, if you see the error again please reopen the ticket.
