### ISSUE TITLE
TransactionEventListener AFTER_COMPLETION never fires

### ISSUE THREAD

**Issue by diamondq** [micronaut-projects/micronaut-data#1819]
### Expected Behavior

When using a @TransactionEventListener with the value set to AFTER_COMPLETION, based on the documentation, it should be called after a COMMIT or a ROLLBACK. 

### Actual Behaviour

However, it's generally never called.

https://github.com/micronaut-projects/micronaut-data/blob/e78b6a2acfd2cab2e2d859d75e2c5b4ca610d86e/data-tx/src/main/java/io/micronaut/transaction/interceptor/TransactionalEventInterceptor.java#L115

I'm guessing that this code should be outside the switch (or the ROLLED_BACK and COMMITTED case statements were meant to fall through).

### Version

3.8.0

**Comment by radovanradic** [comment]
Fixed in https://github.com/micronaut-projects/micronaut-data/pull/1863
