### ISSUE TITLE
CoroutinePageableCrudRepository#findAll() is returning a Flow but is a suspended function

### ISSUE THREAD

**Issue by macmillan78** [micronaut-projects/micronaut-data#1836]
Is this a bug here or is there a special reason why a method returning a Flow is marked suspended?

https://github.com/micronaut-projects/micronaut-data/blob/e9e80d64f1e5733f166bdfdfe06c1f5f09908e93/data-model/src/main/kotlin/io/micronaut/data/repository/kotlin/CoroutinePageableCrudRepository.kt#L39

**Comment by dstepanov** [comment]
Looks like a mistake
