### ISSUE TITLE
io.micronaut.context.exceptions.BeanInstantiationException

### ISSUE THREAD

**Issue by hantsy** [micronaut-projects/micronaut-data#1837]
### Expected Behavior

Micronaunt Data 3.8.1, R2dbc, R2dbc PostgreSQL 1.0.0 

https://github.com/hantsy/micronaut-sandbox/tree/master/data-r2dbc
https://github.com/hantsy/micronaut-sandbox/tree/master/data-r2dbc-kotlin-co

### Actual Behaviour

The original tests failed.

```bash
ApplicationTest > initializationError FAILED
    io.micronaut.context.exceptions.BeanInstantiationException at DefaultBeanContext.java:2367
        Caused by: java.lang.IllegalStateException at DefaultTestTransactionExecutionListener.java:74

CustomerControllerTest > initializationError FAILED
    io.micronaut.context.exceptions.BeanInstantiationException at DefaultBeanContext.java:2367
        Caused by: java.lang.IllegalStateException at DefaultTestTransactionExecutionListener.java:74
```

### Steps To Reproduce

Check the stack result of Github Action workflow file.

https://github.com/hantsy/micronaut-sandbox/actions/runs/3442477635/jobs/5743096728

### Environment Information

Windows 10 Pro 22H2
JDK 17

### Example Application

https://github.com/hantsy/micronaut-sandbox/tree/master/data-r2dbc

### Version

3.7.2

**Comment by dstepanov** [comment]
It might be the exception that I added to alert that MicronautTest doesn’t support transactional processing for R2DBC (It is enabled by default)

**Comment by hantsy** [comment]
It is a bug? or is there a workaround for it?

**Comment by dstepanov** [comment]
Try to add MicronautTest(transactional=false)

**Comment by hantsy** [comment]
In the data-r2dbc-kotlin-co [PostControllerTest](https://github.com/hantsy/micronaut-sandbox/blob/master/data-r2dbc-kotlin-co/src/test/kotlin/com/example/PostControllerTest.kt), I added the `transactional=true`, but it still failed.(all tests are failed without `transactional=false`)

In the data-r2dbc [CustomerControllerTest](https://github.com/hantsy/micronaut-sandbox/blob/master/data-r2dbc/src/test/java/com/example/CustomerControllerTest.java) and [ApplicationTest](https://github.com/hantsy/micronaut-sandbox/blob/master/data-r2dbc/src/test/java/com/example/ApplicationTest.java), add `transactional=false`, they are passed.

But for my opinion, adding `transactional=false` to controller test which used mockito to mock the repository is reasonable. In other tests, eg the above `ApplicationTest` is an integration like test run on an embedded application, the transaction should be enabled.

**Comment by radovanradic** [comment]
@dstepanov There is code that checks and throws exception in this case
```
if (transactionManager instanceof SynchronousFromReactiveTransactionManager) {
            throw new IllegalStateException("Transaction mode is not supported when the synchronous transaction manager is created using Reactive transaction manager!");
        }
```
in `io.micronaut.transaction.test.DefaultTestTransactionExecutionListener` so not sure how this can be fixed.

**Comment by dstepanov** [comment]
The code throws and error when it’s not possible to use TX propagation for tests like when reactive TX manager is used

**Comment by hantsy** [comment]
Still failed in the newest stack: https://github.com/hantsy/micronaut-sandbox/actions/runs/4194200544/jobs/7272052986

**Comment by radovanradic** [comment]
@hantsy Have you checked this with `micronautVersion=4.0.0-M4`?
It seems `BeanInstantiationException` exception is not being thrown anymore.

**Comment by hantsy** [comment]
remove transational from @MicroautTest, it seems it is ok, but this new 4.0.0-M4 introduced new issue, https://github.com/micronaut-projects/micronaut-test/issues/796

**Comment by radovanradic** [comment]
Ok, since we have opened issue https://github.com/micronaut-projects/micronaut-test/issues/796 and https://github.com/micronaut-projects/micronaut-data/issues/2373 I think this one can be closed because original issue is not actual anymore in 4.0
