### ISSUE TITLE
DTO projection with properties from joined entities

### ISSUE THREAD

**Issue by cgrim-cz** [micronaut-projects/micronaut-data#184]
It would be nice to be able to project also properties from joined entity into DTO.

Imagine that I have two entities:
```java
@Entity
public class Recipe {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;
    private String name;
    private String sourceUrl;
    @ElementCollection
    private List<String> steps;
    private LocalDateTime createdOn;
// + getters and setters
}
```
```java
@Entity
public class ParseError implements Serializable {
    @Id
    @ManyToOne(fetch = FetchType.LAZY)
    private Recipe recipe;
    @Id
    private String problemArea;
    private String message;
// + getters and setters
}
```
Then I would like to have DTO for `ParseError` like this:
```java
@Introspected
public class ParseErrorDto {
    private Integer recipeId;
    private String recipeName;
    private String problemArea;
    private String message;
// + getters and setters
}
```
Where the framework can translate `recipeId` DTO property into entity path `recipe.id`. If it is too complex to resolve it automatically then at least using `@Value("#{recipe.id}")` annotation as it is in Spring Data.

Or it can be like this:
```java
@Introspected
public class ParseErrorDto {
    private RecipeDto recipe;
    private ParseError.ProblemArea problemArea;
    private String message;
    // + getters and setters
}
```
Where `Recipe recipe` property from entity is mapped into `RecipeDto recipe` property in DTO. And DTO for `Recipe` entity can look like this:
```
@Introspected
public class RecipeDto {
    private Integer id;
    private String name;
    // + getters and setters
}
```
Does it make sense? 
Would it be possible?

Thank you.

**Comment by graemerocher** [comment]
It does make sense and would potentially be possible. Thanks for the feedback.

**Comment by MC1RX2** [comment]
Hi @graemerocher - I was a big fan of Grails and now loving Micronaut so far but also realise the important of being able to use nested DTOs. Would be great to get this feature in. Look forward to it.

**Comment by graemerocher** [comment]
Yeah I will be looking at improving DTOs soon

**Comment by mattlong-finocomp** [comment]
Any updates on this?

**Comment by graemerocher** [comment]
It's hard 😄

Will take another stab soon

**Comment by joellp** [comment]
Is there any progress on this? I would like this enhancement very much :)
