### ISSUE TITLE
Support for Collection Types in Query methods 

### ISSUE THREAD

**Issue by mrduckieduck** [micronaut-projects/micronaut-data#185]
Hi, 

Would be nice to add support for `List` & `Set` as default result in the `Query Methods`. Currently is only supported by adding the `@Query` annotation or using an `Iterable<E>`,  `Page<E>` or `Slice<E>`, i mean something like 

```java 
List<E> findAllBy...(...);
Set<E> findDistinct...(...);
```

**Comment by graemerocher** [comment]
`List<E>` is already supported

**Comment by mrduckieduck** [comment]
Amazing! can you share the doc? i didn't find it and let me close this :)

**Comment by graemerocher** [comment]
It is mentioned here https://micronaut-projects.github.io/micronaut-data/latest/guide/#querying

with an example

**Comment by mrduckieduck** [comment]
Amazing! Thanks!
