### ISSUE TITLE
Kapt complier error

### ISSUE THREAD

**Issue by dstepanov** [micronaut-projects/micronaut-data#1877]
### Discussed in https://github.com/micronaut-projects/micronaut-data/discussions/1802

<div type='discussions-op-text'>

<sup>Originally posted by **hantsy** October 29, 2022</sup>
Upgrade [my example project(Data R2dbc/Kotlin Coroutines)](https://github.com/hantsy/micronaut-sandbox/tree/master/data-r2dbc-kotlin-co) to the latest stack, and  I encountered the following exceptions. 

```bash 
error: Unable to implement Repository method: PostRepository.exists(QuerySpecification arg0).
 Cannot query persistentEntity [Post] on non-existent property: arg0
Note: Creating bean classes for 6 type elements
```</div>

**Comment by radovanradic** [comment]
I was not able to reproduce the error and was able to run tests successfully in that user module. Not sure if I have some different setup or something, but I am also not getting error when compiling project for the other Kotlin reported issue.

**Comment by dstepanov** [comment]
@hantsy Can you please help?

**Comment by hantsy** [comment]
Not see this issue now in my Github actions, it could be the incompatible versions of Micronaut  Data and Micronaut application in the past moment.
