### ISSUE TITLE
Publish TransactionDefinition from the TransactionalInterceptor

### ISSUE THREAD

**Issue by mathwizard** [micronaut-projects/micronaut-data#1895]
### Feature description

We are using Postgres DB and have a reader and writer instances. We are trying to implement functionality that will direct read only transactions towards the reader instance. Implementing a switching data source wrapper is easy, however we are trying to get the current transaction info. The `io.micronaut.transaction.interceptor.TransactionalInterceptor` already includes all logic necessary for keeping the current transaction definition in the `TransactionInfo` object. All of this is however final, private and inaccessible. 

We propose to publish the `TransactionInfo` or just the `TransactionDefinition` objects so that they can be retrieved by code in own logic.

**Comment by dstepanov** [comment]
I think now you can do `TransactionalInterceptor.currentTransactionStatus()`, and it's probably going to be `io.micronaut.transaction.support.DefaultTransactionStatus` where you can access `isReadOnly` etc. We can probably add `isReadOnly()` or `getTransactionDefinition()` to the `TransactionStatus` if needed.

**Comment by dstepanov** [comment]
Included in `TransactionOperations#findTransactionStatus` `TransactionStatus#getTransactionDefinition`
