### ISSUE TITLE
Inconsistent null field behaviour

### ISSUE THREAD

**Issue by dstepanov** [micronaut-projects/micronaut-data#190]
M2

I have one `VARCHAR (255)` field `agentRef` in Postgres table.

`.findAllByAgentRef(null)` return 0 when agentRef in null in DB
`.findAllByAgentRefIsNull()` return 1 when agentRef in null in DB

I would expect both examples to return the same value.
I think its framework should use JDBC's setNull method when the value is actually null.

**Comment by graemerocher** [comment]
If `setNull` works then ok, otherwise this will be dificult to support because the queries are precomputed and cannot be altered based on the value at runtime

**Comment by graemerocher** [comment]
As far as I can see it is already using `statement.setNull(..)` as the break point hits `JdbcQueryStatement` line 42. The right fix would be to use `IS NULL` or `IS NOT NULL` in the SQL but that would require compiling 2 different queries and switching between which I don't think it is worth it for this feature.

**Comment by dstepanov** [comment]
I'm sorry for misleading you, the "problem" was with Hibernate implementation.
Actually this is normal Postgres behaviour, I had to write custom JPA query: 

`(agentRef = :agentRef OR agentRef IS NULL AND :agentRef IS NULL)` or native query with: `X IS NOT DISTINCT FROM Y`.

Maybe Micronaut can somehow help with this since the argument is annotated with `@Nullable`.

I think you can close this issue.

**Comment by graemerocher** [comment]
No worries. Thanks for the feedback!
