### ISSUE TITLE
IgnoreCase not working when using Micronaut Mongo module

### ISSUE THREAD

**Issue by nikhmalh** [micronaut-projects/micronaut-data#1902]
Hi,

We are using the Micronaut Mongo DB module.
We need to find the user in a case-insensitive way from the database.
We are using the following method in the repository for finding the user by Email.
@Executable
  Optional<UserEntity> findByEmailIgnoreCase(String email);

This complies well but does not work as expected. When trying to find the user in a case-insensitive way it does not work.

**Here is the stacktrace:**

4:46:36.419 [default-nioEventLoopGroup-1-4] DEBUG i.m.security.filters.SecurityFilter - Authorized request GET /backup/management/api/v1/users/NIKHIL.M.MALHOTRA@ORACLE.COM. The rule provider io.micronaut.security.rules.SecuredAnnotationRule authorized the request.
14:46:36.421 [io-executor-thread-8] DEBUG i.m.d.m.t.MongoSynchronousTransactionManager - Creating new transaction: [name='BackupManagementServiceController.getUserAsAdmin']
14:46:36.421 [io-executor-thread-8] DEBUG i.m.d.m.t.MongoSynchronousTransactionManager - Acquired ClientSession for MongoDB transaction [BackupManagementServiceController.getUserAsAdmin] of datasource: [atpmongo]
14:46:36.421 [io-executor-thread-8] DEBUG i.m.d.m.t.MongoSynchronousTransactionManager - Starting MongoDB transaction [BackupManagementServiceController.getUserAsAdmin] of datasource: [atpmongo]
14:46:36.421 [io-executor-thread-8] DEBUG i.m.d.m.t.MongoSynchronousTransactionManager - Participating in existing transaction
14:46:36.422 [io-executor-thread-8] DEBUG io.micronaut.data.query - Executing Mongo 'find' with filter: {"email": {"$eq": "NIKHIL.M.MALHOTRA@ORACLE.COM"}}
14:46:36.659 [io-executor-thread-8] DEBUG i.m.d.m.t.MongoSynchronousTransactionManager - Initiating transaction rollback on application exception
io.micronaut.http.exceptions.HttpStatusException: null
        at com.oracle.ee.backupsvc.BackupManagementServiceController.getUserAsAdmin(BackupManagementServiceController.java:393)
        at com.oracle.ee.backupsvc.$BackupManagementServiceController$Definition$Intercepted.$$access$$getUserAsAdmin(Unknown Source)

### Environment Information

- **Operating System**:  Linux
- **Micronaut Version:**  
    micronautVersion="3.7.0"
    micronautDataVersion="3.8.0"
- **JDK Version:**  JDK 17

**Comment by radovanradic** [comment]
Until this issue is fixed, this custom query can be used as workaround:
```
@MongoFindQuery("{email: {\"$regex\": :email, \"$options\": \"i\"}}")
Optional<User> getUserByEmailCaseInsensitive(String email);
```

**Comment by nikhmalh** [comment]
The provided workaround is also not working:
@MongoFindQuery("{email: {\"$regex\": :email, \"$options\": \"i\"}}")
Optional<User> getUserByEmailCaseInsensitive(String email);

**Comment by radovanradic** [comment]
> The provided workaround is also not working: @MongoFindQuery("{email: {"$regex": :email, "$options": "i"}}") Optional getUserByEmailCaseInsensitive(String email);

It kind of works, you can check it [here](https://github.com/radovanradic/mongo-ignore-case/blob/main/src/test/java/com/example/MongoIgnoreCaseTest.java). But it also works with partial search which is not actually 'equals' operator.
There is a test with it  but also another (not ideal I know) workaround using findByRegex where user needs to pass regex like this `^(?i)Radovan.Radic@oracle.com$` to match case insensitive email.

Repo with the example is here: https://github.com/radovanradic/mongo-ignore-case

**Comment by nikhmalh** [comment]
Hi,
Both the workarounds are not working for me. 
In my case, our actual database is Oracle ATP but behind the mongo translation layer. Is this the same for you?
Is this making any difference?

**Comment by radovanradic** [comment]
Right, it could be incompatible. In the example I used, just mongo server is started via mn testresources.

**Comment by nikhmalh** [comment]
Would this scenario (ATP behind Mongo translation) be fixed in this bug?

**Comment by radovanradic** [comment]
Since the fix would probably include using regex, something similar in the example app I showed, then it sounds like it wouldn't fix it for you. Perhaps you could create case insensitive index and try it that way, as talked about here: https://www.mongodb.com/developer/products/mongodb/schema-design-anti-pattern-case-insensitive-query-index/
