### ISSUE TITLE
Keep getting error "Unable to implement Repository method: RepoClass.updateAll(Iterable arg0). No possible implementations found."

### ISSUE THREAD

**Issue by ethanhere** [micronaut-projects/micronaut-data#1904]
### Issue description

Using Micronaut data v3, I created the following simple classes:
MyEntity.java
package test;
import io.micronaut.data.annotation.GeneratedValue;
import io.micronaut.data.annotation.Id;
import io.micronaut.data.annotation.MappedEntity;

@MappedEntity
public class MyEntity {
    @Id
    @GeneratedValue(GeneratedValue.Type.AUTO)
    private Long id;

    private String name;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}

MyRepo.java:
package test;
import io.micronaut.data.jdbc.annotation.JdbcRepository;
import io.micronaut.data.model.query.builder.sql.Dialect;
import io.micronaut.data.repository.CrudRepository;

@JdbcRepository(dialect = Dialect.MYSQL)
public interface MyRepo  extends CrudRepository<MyEntity, Long> {
}

The project can build without above 2 classes. Once I add these 2 classes, I got the error
java: Unable to implement Repository method: MyRepo.updateAll(Iterable arg0). No possible implementations found.

I searched online and I think I followed some examples that I found. I don't understand what went wrong. Can someone enlighten me?

**Comment by radovanradic** [comment]
Hi @ethanhere ,

Not sure if what you pasted here is exact the same class you are using, seems like this one is missing getters that are needed by the Micronaut Data (as you could see in all the examples).
[Here](https://github.com/radovanradic/entity-repo-example) is sample repo with Micronaut Data 3.7.4 that is building successfully and `EntityRepoExampleTest.testRepo` method is also passing.

**Comment by ethanhere** [comment]
@radovanradic That's a good point. The same code built with Micronaut 1.x. I followed the example you gave: make sure the directory structure includes resources/db/schema.sql resources/application.yml. I modified the java code, basically copied the example code. But I still fail to build, and ended up with the same error ...

**Comment by radovanradic** [comment]
Can you please share example so we can look and try to figure out what is the error?

**Comment by ethanhere** [comment]
@radovanradic the example is, (I use intelliJ) creating a maven project with all micronuat dependencies:
        
        <dependency>
            <groupId>io.micronaut.sql</groupId>
            <artifactId>micronaut-jdbc-hikari</artifactId>
        </dependency>

        <dependency>
            <groupId>io.micronaut.data</groupId>
            <artifactId>micronaut-data-jdbc</artifactId>
        </dependency>

        <dependency>
            <groupId>io.micronaut</groupId>
            <artifactId>micronaut-jdbc</artifactId>
        </dependency>

        <dependency>
            <groupId>io.micronaut.data</groupId>
            <artifactId>micronaut-data-hibernate-jpa</artifactId>
        </dependency>

        <dependency>
            <groupId>io.micronaut</groupId>
            <artifactId>micronaut-core</artifactId>
        </dependency>

        <dependency>
            <groupId>io.micronaut</groupId>
            <artifactId>micronaut-inject</artifactId>
        </dependency>

        <dependency>
            <groupId>io.micronaut</groupId>
            <artifactId>micronaut-validation</artifactId>
        </dependency>

        <dependency>
            <groupId>io.micronaut</groupId>
            <artifactId>micronaut-aop</artifactId>
        </dependency>

        <dependency>
            <groupId>jakarta.inject</groupId>
            <artifactId>jakarta.inject-api</artifactId>
        </dependency>

Then added 2 java files I put in the original post.

Then use IntelliJ menu Build->build <project name>, it will ends up with the "Unable to implement Repository method" error

**Comment by ethanhere** [comment]
@radovanradic in the example https://github.com/radovanradic/entity-repo-example, did you generate the project using mn cli? Can you generate the same project that uses maven? I like to compare the differences...

**Comment by radovanradic** [comment]
@ethanhere 
I have created it here in the [Micronaut Launch UI](https://micronaut.io/launch)
Here is [maven version](https://github.com/radovanradic/entity-repo-maven-demo) that I created now (with H2 for easier testing, compile and tests are working)

**Comment by radovanradic** [comment]
@ethanhere awesome, thanks for the update. I am closing this issue now.

**Comment by matiry321** [comment]
> Thanks @radovanradic. I resolved the problem. The root cause is annotationProcessorPaths in POM. My project is to upgrade Micronaut 1.x to 3.x. In the POM's annotationProcessorPaths, micronaut-data-processor version needs to update.

@ethanhere can you please tell which version of micronaut-data-processor did you use to resolve this error because i'm facing the same.
