### ISSUE TITLE
Method findBy with a field of type List cannot be implemented

### ISSUE THREAD

**Issue by cosmin-marginean** [micronaut-projects/micronaut-data#1909]
### Expected Behavior

Having he following document

```kotlin
@Serdeable
@MappedEntity
data class Document(
    val firstName: String,
    val tags: List<String>,

    @field:Id
    val id: String = UUID.randomUUID().toString()
)
```

It should be possible to create a find method that searches for occurrences in the `tags` field as follows:

```kotlin
@MongoRepository
interface DocumentRepository : PageableRepository<Document, String> {
    fun findByTags(tag:String): List<Document>
}
```

### Actual Behaviour

An error is thrown at build time:

```
error: Unable to implement Repository method: DocumentRepository.findByTags(String tag). Parameter [java.lang.String tag] is not compatible with property [java.util.List tags] of entity: com.test.Document
    public abstract java.util.List<com.test.Document> findByTags(@org.jetbrains.annotations.NotNull
```

### Steps To Reproduce

Checkout repo https://github.com/cosmin-marginean/micronaut-mongo-find-in-array

### Environment Information

JDK17

### Example Application

https://github.com/cosmin-marginean/micronaut-mongo-find-in-array

### Version

3.7.4

**Comment by radovanradic** [comment]
@cosmin-marginean After this fix is released (perhaps in 3.9.2) then this should be achievable by method like this for your entity example: 
```
findByTagsCollectionContains(String tag);
```

**Comment by radovanradic** [comment]
Done in https://github.com/micronaut-projects/micronaut-data/pull/1932

**Comment by cosmin-marginean** [comment]
Great stuff! Thank you so much!

**Comment by cosmin-marginean** [comment]
@radovanradic I've updated to 3.9.2 which seems to contain this fix now and have patched the repo here: https://github.com/cosmin-marginean/micronaut-mongo-find-in-array

The error is now

```
Unable to implement Repository method: DocumentRepository.findByTagsCollectionContains(String tag). Cannot query entity [Document] on non-existent property: TagsCollection
```

I'm not sure, but I believe it tries to find a `tagsCollection` field which doesn't exist. Let me know if we need to reopen this or if I'm missing something.

**Comment by radovanradic** [comment]
3.9.2 is not released, it failed. You might check with 3.9.2-SNAPSHOT and it should work

**Comment by cosmin-marginean** [comment]
Thanks for the prompt reply! It fails with snapshot as well, so I'll leave it until this release is finalised in that case. Sorry for the hassle!

**Comment by cosmin-marginean** [comment]
Ah, ignore me, I only updated the dependency but not the annotation processor
As an FYI, it works with this `kapt 'io.micronaut.data:micronaut-data-document-processor:3.9.2-SNAPSHOT'`

**Comment by radovanradic** [comment]
@cosmin-marginean Just fyi, 3.9.3 has been released successfully and it should contain fix for this issue.
