### ISSUE TITLE
io.micronaut.spring.tx.annotation.Transactional

### ISSUE THREAD

**Issue by alberto-pelosi** [micronaut-projects/micronaut-data#191]
Hi,

on 1.0.0.BUILD-SNAPSHOT @Transactional annotation (io.micronaut.spring.tx.annotation.Transactional) is no more present.

Should I  use javax.transaction.Transactional ?

Thanks

Alberto

**Comment by graemerocher** [comment]
Yes just use `javax.transaction.Transactional`
