### ISSUE TITLE
Deserializing Maps with MongoDB

### ISSUE THREAD

**Issue by cosmin-marginean** [micronaut-projects/micronaut-data#1922]
### Expected Behavior

Deserializing an object with a map field should deserialize entries with the correct type.

Given the following entity
```kotlin
@Serdeable
@MappedEntity
data class Parent(
    val firstName: String,
    val lastName: String,
    val children: Map<String, Child>,

    @field: Id
    val id: String = UUID.randomUUID().toString()
)

@Serdeable
data class Child(val location: String)
```

The following test should pass
```kotlin
val id = repository.save(Parent("a", "b", mapOf("child" to Child("nowhere")))).id
val record = repository.findById(id).get()
assertEquals(Child::class, record.children["child"]!!::class)
```

### Actual Behaviour

The map value is deserialized as `Document`. And the test fails with
```
expected: <class com.test.Child> but was: <class org.bson.Document>
```

### Steps To Reproduce

Run tests here https://github.com/cosmin-marginean/micronaut-data-mongo-maps

### Environment Information

JDK17

### Example Application

https://github.com/cosmin-marginean/micronaut-data-mongo-maps

### Version

3.7.4

**Comment by cosmin-marginean** [comment]
Not sure if this helps, but I had a look at `CoreDeserializers` and then changed the type of the property to
```kotlin
val children: LinkedHashMap<String, Child>,
```

with the assumption that in this case a specific serializer would be picked up (`LinkedHashMapDeserializer`).

This however yields the following:

```
io.micronaut.core.reflect.exception.InstantiationException: Invalid argument [{child=Document{{location=nowhere}}}] specified for argument: LinkedHashMap children
```

**Comment by radovanradic** [comment]
Closed by https://github.com/micronaut-projects/micronaut-data/pull/1948

**Comment by cosmin-marginean** [comment]
I can confirm this works fine after the 3.9.4 release. Thank you so much!
