### ISSUE TITLE
Initial schema from H2 SQL file in Micronaut Data

### ISSUE THREAD

**Issue by rjtmahinay** [micronaut-projects/micronaut-data#1925]
### Issue description

I'm trying to load a data from data.sql and/or schema using schema.sql in H2 using Micronaut Data. Is this a supported feature or not? I've tried to read the Micronaut Data documentation but didn't saw mentioning this kind of capability.

**Comment by braldanago** [comment]
> ### Issue description
> I'm trying to load a data from data.sql and/or schema using schema.sql in H2 using Micronaut Data. Is this a supported feature or not? I've tried to read the Micronaut Data documentation but didn't saw mentioning this kind of capability.

Make sure hibernate auto property is set to create or create-drop in application.yml and name file import.sql. See https://docs.spring.io/spring-boot/docs/2.1.1.RELEASE/reference/html/howto-database-initialization.html works for micronaut as well

**Comment by rjtmahinay** [comment]
Thanks for the suggestion @braldanago. I think I need to use the JdbcRepository instead. Closing this issue.
