### ISSUE TITLE
@MongoFindQuery and @MongoAggregateQuery should support Pageable 

### ISSUE THREAD

**Issue by volnei** [micronaut-projects/micronaut-data#1929]
### Feature description

I have tried in many wayts to paginate mongo predefined queries, and when using Page<> as result, the document does no recognize query.

**Comment by radovanradic** [comment]
Hi @volnei ,

I am not sure what is your exact issue, maybe you could show what you are trying to implement?
Here is an example with paging that is supported in Micronaut Data MongoDB
```
// repository method definition
Page<Document> findAll(Pageable pageable);

// method call
documentRepository.findAll(Pageable.from(1, 5))
```
which executes this command against MongoDb
```
'{"find": "document", "filter": {}, "skip": 5, "limit": 5, "$db": "test"...
```

or this one 
```
Page<Document> findAllByTitleStartingWith(String title, Pageable pageable);

documentRepository.findAllByTitleStartingWith("Doc", Pageable.from(0, 2))
```
which sends this command to MongoDb
```
'{"find": "document", "filter": {"title": {"$regularExpression": {"pattern": "^Doc", "options": ""}}}, "limit": 2, "$db": "test", ...
```

**Comment by alexnhm1** [comment]
``Hi, this is an old ticket but I think it's still relevant - the queries you have given above as examples work well, and allow automatic pageable population etc. However, when using the @MongoFindQuery annotation, it is not possible to automatically populate a page object - I receive a 
`
17:45:38.676 [default-nioEventLoopGroup-2-3] ERROR i.m.http.server.RouteExecutor - Unexpected error occurred: No query present in method
java.lang.IllegalStateException: No query present in method
`
error when trying to do so. Is there some form of notation that I'm missing such that this isn't possible? Thanks
`    
@MongoFindQuery(
      "{" +
          "$and: [" +
              "{survey_id: {$eq: :surveyId}}," +
              "{ $or: [" +
                  "{sample_date: {$gte: :startDate, $lte: :endDate}}," +
                  "{sample_start_datetime: {$gte: :startDate, $lte: :endDate}}," +
                  "{sample_end_datetime: {$gte: :startDate, $lte: :endDate}}" +
              "]}" +
          "]" +
      "}"
  )
  Page<Sample> findBySurveyIdAndProvidedDateRange(
          String surveyId,
          LocalDate startDate,
          LocalDate endDate,
          Pageable pageable
  );
`

**Comment by radovanradic** [comment]
Yes, I realized the different thing was requested and it requires some more code changes.

**Comment by alexnhm1** [comment]
Thank you @radovanradic  + @dstepanov for taking the time to resolve this, I look forward to being able to use this to remove lines of unnecessary code paging lists in our code base. Cheers 😊
