### ISSUE TITLE
Bean definition [io.micronaut.data.mongodb.init.MongoCollectionsCreator] could not be loaded: com/mongodb/reactivestreams/client/MongoDatabase

### ISSUE THREAD

**Issue by hantsy** [micronaut-projects/micronaut-data#1942]
### Expected Behavior

My example project only used the sync drivers, the example is working well in before versions, but not sure why `MongoCollectionCreator` requires the reactive streams drivers in the latest updates.

### Actual Behaviour

When running the tests [CustomerRepositorySpec](https://github.com/hantsy/micronaut-sandbox/blob/master/data-mongodb-groovy/src/test/groovy/com/example/CustomerRepositorySpec.groovy) it failed due to the following exceptions.

```
Bean definition [io.micronaut.data.mongodb.init.MongoCollectionsCreator] could not be loaded: 
com/mongodb/reactivestreams/client/MongoDatabase
io.micronaut.context.exceptions.BeanInstantiationException: 
Bean definition [io.micronaut.data.mongodb.init.MongoCollectionsCreator] could not be loaded: 
com/mongodb/reactivestreams/client/MongoDatabase
```

### Steps To Reproduce

1. Checkout https://github.com/hantsy/micronaut-sandbox/blob/master/data-mongodb-groovy/
2. Run the tests

### Environment Information

Windows 10 pro
Java 17 

All failed in the Github actions, https://github.com/hantsy/micronaut-sandbox/actions/runs/3774284424/jobs/6416292971

### Example Application

https://github.com/hantsy/micronaut-sandbox/blob/master/data-mongodb-groovy/

### Version

3.7.5

**Comment by radovanradic** [comment]
Fixed in https://github.com/micronaut-projects/micronaut-data/pull/1943
