### ISSUE TITLE
R2DBC Rolling back transaction  - Micronaut Data method is missing compilation time query information.

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-data#1957]
### Issue description

Steps to reproduce: 

pull the latest of [micronaut-projects/micronaut-guides](https://github.com/micronaut-projects/micronaut-guides) and run `./gradlew micronautDataR2dbcRepositoryBuild`

You will see

```
Rolling back transaction: GenreRepository.saveWithException on error: Error invoking doInTransaction handler: Micronaut Data method is missing compilation time query information. Ensure that the Micronaut Data annotation processors are declared in your build and try again with a clean re-build. for dataSource default
io.micronaut.transaction.exceptions.TransactionSystemException: Error invoking doInTransaction handler: Micronaut Data method is missing compilation time query information. Ensure that the Micronaut Data annotation processors are declared in your build and try again with a clean re-build.
We have a method which raises on purpose an exception. But the error, seems to indicate the rollback fails.
```

any idea what's going on?

once you have run `micronautDataR2dbcRepositoryBuild`, you could go to an individual project `build/code/micronaut-data-r2dbc-repository/micronaut-data-r2dbc-repository-gradle-kotlin`

**Comment by radovanradic** [comment]
@sdelamo I checked this in latest micronaut-guides and looks like not failing anymore. Can you re-check?

**Comment by sdelamo** [comment]
> @sdelamo I checked this in latest micronaut-guides and looks like not failing anymore. Can you re-check?

Yes, it seem fine now.
