### ISSUE TITLE
Hibernate+JPA native-image building fails due to missing Spring class

### ISSUE THREAD

**Issue by otbe** [micronaut-projects/micronaut-data#196]
Hi

I recently added micronaut-data to my project and now I cant build a native image anylonger. I think its somehow related to the new version (M3) where Spring dependencies were completly removed.

```
Error: Error parsing reflection configuration in jar:file:/home/application/target/foo-0.1.jar!/META-INF/native-image/io.micronaut/configuration-hibernate-jpa-graal/reflection-config.json:
Class org.springframework.orm.hibernate5.SpringSessionContext not found
Verify that the configuration matches the schema described in the -H:PrintFlags=+ output for option ReflectionConfigurationResources.
Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1
```

I re-used my example repo from the other issue: https://github.com/otbe/micronaut-aws-graal-example

Thank you!

**Comment by graemerocher** [comment]
You need to use this until Micronaut 1.2.4 is out:

```xml
    <dependency>
        <groupId>io.micronaut.configuration</groupId>
        <artifactId>micronaut-hibernate-jpa</artifactId>
        <version>1.2.1</version>
        <scope>compile</scope>
        <exclusions>
          <exclusion>  <!-- declare the exclusion here -->
            <groupId>io.micronaut.configuration</groupId>
            <artifactId>micronaut-hibernate-jpa-spring</artifactId>
          </exclusion>
        </exclusions> 
    </dependency> 
```

**Comment by graemerocher** [comment]
There is a native image example here https://github.com/micronaut-projects/micronaut-data/tree/master/examples/example-jpa with working builds for Maven and Gradle

**Comment by otbe** [comment]
You're absolutely right! I saw the example but I thought that `io.micronaut.configuration:micronaut-hibernate-jpa` is already in (with the exclusion).

Thank you very much!
