### ISSUE TITLE
Missing `arrayFilters` as an attribute for either `MongoUpdateQuery` or `MongoUpdateOptions`

### ISSUE THREAD

**Issue by adrianoluis** [micronaut-projects/micronaut-data#1973]
### Feature description

As part of update queries in mongo, is possible to define `arrayFilters` as an Option but is it not possible to have that behavior using `io.micronaut.data:micronaut-data-mongodb`.

Reference: https://www.mongodb.com/docs/manual/reference/operator/update/positional-filtered/

**Comment by dstepanov** [comment]
How would you like to use it?

**Comment by adrianoluis** [comment]
Yes, I'd like to. I've tried to implement the change on MongoUpdateOptions
but I need to pass a dynamic argument but there's no binding i the Options
processor

**Comment by adrianoluis** [comment]
Basically whenever we're using placeholders in a query we need to replace it with the real data using `arrayFilters` like:
```
db.collection.updateMany(
  { 'internal.document.id': <id> },
  { $addToSet: { 'internal.document[doc].attachment': <something> } },
  { arrayFilters: [ { 'doc': document.id } ] }
)
```
