### ISSUE TITLE
Allow custom INSERTs to return a value for databases that support RETURNING statement

### ISSUE THREAD

**Issue by edeesis** [micronaut-projects/micronaut-data#2005]
### Feature description

PostgreSQL supports a RETURNING syntax on insert statements that can return a select list of the row inserted. However, if you try to implement a custom insert method, you get this error:

Unable to implement Repository method: UserRepository.createOrUpdate(User user). Invalid result type: com.test.model.User for 'INSERT' operation
tests.ledger  |     public abstract java.lang.Object createOrUpdate(@org.jetbrains.annotations.NotNull

Example Repository (with an upsert method, but it's not necessary for this particular issue):

```
@R2dbcRepository(dialect = Dialect.POSTGRES)
interface UserRepository : CoroutineCrudRepository<User, Int> {
  @Query("""  
  INSERT INTO users (id, username, last_logged_in) 
  VALUES (:id, :username, :last_logged_in) 
  ON CONFLICT 
  ON CONSTRAINT username_uniq 
  DO UPDATE SET last_logged_in = :last_logged_in
  RETURNING users.*
  """)
  suspend fun createOrUpdate(user: User)

**Comment by adamkobor** [comment]
Is there any update on this? Even a "we will think about it" (or not) would be a huge hint :)

**Comment by dstepanov** [comment]
I'm planning it after the v4 release, probably 4.1

**Comment by edeesis** [comment]
I'm not currently in a position to test this, but can this be closed as fixed by https://github.com/micronaut-projects/micronaut-data/pull/2544
