### ISSUE TITLE
Missing bean argument value: transactionOperations

### ISSUE THREAD

**Issue by lehotskysamuel** [micronaut-projects/micronaut-data#202]
Hi,
I have following simple repository that stopped working after migrating to M3 (it worked with M1 and M2).

```
@JdbcRepository(dialect = Dialect.POSTGRES)
public abstract class ApplicationRepository implements RxJavaCrudRepository<Application, UUID> {

    public abstract Flowable<Application> findBySpaceId(@NotNull UUID spaceId);

}
```

Exception I get after calling the above method is:
```
ERROR [N] io.micronaut.http.server.netty.RoutingInBoundHandler - Unexpected error occurred: Error instantiating bean of type  [io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations]

Message: Missing bean argument value: transactionOperations
Path Taken: new DefaultJdbcRepositoryOperations(String dataSourceName,DataSource dataSource,[TransactionOperations transactionOperations],ExecutorService executorService,BeanContext beanContext,List codecs)
Error instantiating bean of type  [io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations]
```

I guess this is somehow related to change in transaction management. Is there a change in setup requirements?

Adding following dependency fixes the issue but I was expecting that no additional dependencies would be required: 

```
        <dependency>
            <groupId>io.micronaut.data</groupId>
            <artifactId>micronaut-data-spring</artifactId>
            <version>${micronaut-data.version}</version>
        </dependency>
```

In other repositories we are occasionaly using javax Transactions.

**Comment by graemerocher** [comment]
Please see https://github.com/micronaut-projects/micronaut-data/tree/master/examples/example-jdbc for a correctly configured example. You need `micronaut-data-tx`

**Comment by lehotskysamuel** [comment]
Hi, removing data-spring and replacing it with data-tx you mentioned above produces the same error as when having no dependecy at all. Also, the example-jdbc has no data-tx dependency in pom.xml nor in build.gradle.

**Comment by graemerocher** [comment]
My reference to the examples was to point you to correctly configured projects which you can use as a reference to setting up your own project.

**Comment by lehotskysamuel** [comment]
Ok, my configuration corresponds to the example's one. I still have the above problem that was introduced with M3, though.

**Comment by graemerocher** [comment]
In that case feel free to provide an example that reproduces the issue and attach it to this issue

**Comment by graemerocher** [comment]
Closing this since it is definitely an issue with the dependencies. If you have `micronaut-hibernate-jpa` declared in your dependencies please remove that.

**Comment by nhoughto** [comment]
does this mean you can't have data-jdbc and hibernate-jpa in the same project?

**Comment by ebomitali** [comment]
I had the same issue and I had both

implementation("io.micronaut.data:micronaut-data-hibernate-jpa:2.2.4")

and

implementation("io.micronaut.data:micronaut-data-jdbc")

in the dependencies closure.
Removing the hibernate-jpa removed the error
