### ISSUE TITLE
MongoDB update wih @MongoUpdateQuery doesn't return updated entities

### ISSUE THREAD

**Issue by cosmin-marginean** [micronaut-projects/micronaut-data#2022]
### Expected Behavior

Having the following

```kotlin
@Serdeable
@MappedEntity
data class Book(
    val title: String,

    @field: Id
    val id: String = UUID.randomUUID().toString()
)

@MongoRepository
interface BookRepository : CrudRepository<Book, String> {
    @MongoUpdateQuery(filter = "{_id: {\$eq: :id}}", update = "{\$set:{title: \"New title\" }}")
    fun updateTitle(id: String): List<Book>
}
```

it's expected that a call to `updateTitle` would return the updated document(s).

### Actual Behaviour

A call to `updateTitle` returns null. I've created a test in the repository mentioned below which reproduces this

``` kotlin
        val book = repository.save(Book(title = "notitle"))
        val updatedBook = repository.updateTitle(book.id)

        // This passes
        assertEquals("New title", repository.findById(book.id).get().title)

        // This fails
        assertNotNull(updatedBook)
```

### Steps To Reproduce

Check out https://github.com/cosmin-marginean/micronautdata-mongodb-cutomupdatequery and run tests with Gradle

### Environment Information

Micronaut 3.7.6
Micronaut Data 3.9.6

### Example Application

https://github.com/cosmin-marginean/micronautdata-mongodb-cutomupdatequery

### Version

3.7.6

**Comment by graemerocher** [comment]
could be wrong but in general if this works the same way as SQL batch updates don't return the updated objects as that would require an additional query and the drivers don't have a way to know what was updated. If this works the same way with MongoDB then this should in fact be a compilation error and unsupported.

**Comment by cosmin-marginean** [comment]
That's correct in general, but [certain](https://mongodb.github.io/mongo-java-driver/3.6/javadoc/?com/mongodb/client/MongoCollection.html) MongoDB updates return the updated document which is important for some use cases.

Now `findOneAndUpdate` is clearly not implemented (I'll raise another ticket for that). However there are examples provided where this is supposed to work according to such an interface: https://github.com/micronaut-projects/micronaut-data/blob/master/doc-examples/mongo-example-java/src/main/java/example/BookRepository.java#L109

```java
    @MongoUpdateQuery(filter = "{title:{$regex: :t}}", update = "{$set:{name: 'tom'}}")
    List<Book> customUpdate(String t);
```

So I'm a bit confused about the circumstances when @MongoUpdateQuery would return a `List<Book>` as per above example.

**Comment by radovanradic** [comment]
Yes, looks like this method from examples 
```
@MongoUpdateQuery(filter = "{title:{$regex: :t}}", update = "{$set:{name: 'tom'}}")
    List<Book> customUpdate(String t);
```
is misleading. That doesn't work and I checked quickly, that is not being used or called in the tests. We could remove that from the repository or change to return void.

**Comment by cosmin-marginean** [comment]
Thanks for looking into this! Yes, either of those options seem sound. There _might_ be people using this and ignoring the response, which might weigh more towards leaving it in, and returning void (if it actually works and does the job).

**Comment by radovanradic** [comment]
Fixed just documentation example part to avoid confusion, find and update issue #2023 to be done later.
