### ISSUE TITLE
same domain with jdbc,jpa the create table not the same

### ISSUE THREAD

**Issue by ibmsoft** [micronaut-projects/micronaut-data#203]
i have a doman 
`
public class Person {

    @Id

    @GeneratedValue

    private String id;

    String fdate ;
`

the fdate column  in jdbc 

fdate        varchar(255) not  null,

the fdate column  in jpa 

fdate        varchar(255)  null,

**Comment by graemerocher** [comment]
hbm2ddl and Micronaut Data JDBC's schema generator are different tools and will never have the exact behaviour. In fact the latter is not recommended for production usage and is only for quick tests as per the documentation. You should use a schema migration tool like Flyway or Liquibase to manage your schema.
