### ISSUE TITLE
CriteriaQuery applying DISTINCT to each field

### ISSUE THREAD

**Issue by 0x000bff** [micronaut-projects/micronaut-data#2081]
### Expected Behavior

I cannot for the life of me figure out how to apply a simple distinct clause using the Criteria API, and the closest I can get from following various docs is this multiselect and distinct method like so:
```java
        public static QuerySpecification<QcFlag> distinct() {
            return (root, query, criteriaBuilder) -> {
                query.multiselect(root.get("id"), root.get("createdAt")).distinct(true);
                return null;
            };
        }
```

### Actual Behaviour

However, when trying this in a Micronaut Data app, the resulting query wraps every field in a DISTINCT like so:
```sql
SELECT DISTINCT(qc_flag_."id"),DISTINCT(qc_flag_."created_at") FROM "qc_flag" qc_flag_ LIMIT 100;
```
Which throws an error.

Am I doing something wrong? Am I missing some documentation somewhere?
Any help is greatly appreciated.

### Version

3.7.4

**Comment by 0x000bff** [comment]
Traced it down to [this](https://github.com/micronaut-projects/micronaut-data/blob/13019488216e048def6002e6a18951ce9662d742/data-model/src/main/java/io/micronaut/data/model/query/builder/AbstractSqlLikeQueryBuilder.java#L706) line in **AbstractSqlLikeQueryBuilder**, where the fields are each coming in as a **DistinctPropertyProjection** and getting wrapped in a DISTINCT.

It looks like the only other option for a distinct query, is on [line 681](https://github.com/micronaut-projects/micronaut-data/blob/13019488216e048def6002e6a18951ce9662d742/data-model/src/main/java/io/micronaut/data/model/query/builder/AbstractSqlLikeQueryBuilder.java#L681) of that file, but that wraps the entire table alias in a distinct function which returns a single aggregated column instead of the expected result set shape.

**Comment by 0x000bff** [comment]
Yes exactly, that's what I would expect.

Although to be clear, I'm still not sure if my example is a proper way to apply a distinct within a predicate method, I'm having a hard time finding examples online.

**Comment by radovanradic** [comment]
Closed via https://github.com/micronaut-projects/micronaut-data/pull/2335
