### ISSUE TITLE
Array parameter in native query is not working

### ISSUE THREAD

**Issue by noeliajimenezg** [micronaut-projects/micronaut-data#2115]
### Expected Behavior

Given this query, I expect the array is created and the query is returning a resultset.

```
@Query(
      value =
          "with table_temp (my_id) as (select distinct unnest(array[:ids])) select * from item_raw r inner join table_temp p on r.my_id = p.my_id",
      nativeQuery = true)
  List<MyEntity> findByMyIdWith(String[] ids);
```

### Actual Behaviour

In Postgres, the query is received like this. You can see there is an array with () inside which provokes a failure.
```
with table_temp (my_id) as (select distinct unnest(array[($1, $2)])) select * from item_raw r inner join table_temp p on r.my_id = p.my_id
```
Workaround is to initialize the array like this 
```
@Query(
      value =
          "with table_temp (my_id) as (select distinct unnest(:ids\\:\\:varchar[])) select * from item_raw r inner join table_temp p on r.my_id = p.my_id",
      nativeQuery = true)
  List<MyEntity> findByMyIdWith(String ids);
```
where ids contains this format: 
'{d46abfae-ee62-5321-bcde-8d0ac9713552,0f6f48a1-4d75-5ff2-8701-7d5655c84589}'

### Version

3.8.1

**Comment by dstepanov** [comment]
I might need to add `@TypeDef(type = DataType.STRING_ARRAY)`

**Comment by noeliajimenezg** [comment]
@radovanradic I modified your project and added the case that fails and the case that works.
[pg-demo-with-bug.zip](https://github.com/micronaut-projects/micronaut-data/files/11141562/pg-demo-with-bug.zip)

@dstepanov I tried to add it in the params declaration of the method but it changed nothing.

Thanks both for your help!

**Comment by radovanradic** [comment]
I am not sure we should change code for that special case. How about creating function in postgres something like this (maybe not optimal, not very familiar with postgres):
```
CREATE OR REPLACE FUNCTION list_to_array(variadic list varchar[]) 
RETURNS varchar[] AS
$$
DECLARE 
   result varchar[];
BEGIN
  result = array[]::varchar[];
  FOR i IN 1 .. array_upper(list, 1) LOOP
    result = array_append(result, list[i]);
  END LOOP;
  RETURN result;
END;
$$
LANGUAGE plpgsql;
```
and then change repository method that is not working as expected to this:
```
@Query(
            value =
                    "with table_temp (my_id) as (select distinct unnest(list_to_array(:ids))) select * from pgdemo r inner join table_temp p on r.my_id = p.my_id\\\\:\\\\:varchar",
            nativeQuery = true)
    List<MyEntity> findByMyIdWithFails(String[] ids);
```

**Comment by njimenezotto** [comment]
Thanks @radovanradic for the alternative. I think I will stick to my workaround as it does not requires any action on Postgres side.

**Comment by radovanradic** [comment]
Since this is sort of corner case and it has one or more workarounds, we are not planning on adding fix for it.
