### ISSUE TITLE
Error creating tables with JDBC using Oracle

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-data#212]
There is an error while creating tables using Micronaut Data JDBC and Oracle database.

This is the error:
```
23:53:33.357 [main] DEBUG io.micronaut.data.query - Creating Table: 
CREATE TABLE owner (id BIGINT AUTO_INCREMENT PRIMARY KEY,age INT NOT NULL,name VARCHAR(255) NOT NULL);
23:53:33.359 [main] WARN  io.micronaut.data.query - Create Table Failed: ORA-00907: missing right parenthesis

23:53:33.361 [main] DEBUG io.micronaut.data.query - Creating Table: 
CREATE TABLE pet (id VARCHAR(255) NOT NULL,owner_id BIGINT,name VARCHAR(255) NOT NULL,type VARCHAR(255) NOT NULL);
23:53:33.365 [main] WARN  io.micronaut.data.query - Create Table Failed: ORA-00911: invalid character
```

To reproduce the issue clone this repo https://github.com/micronaut-graal-tests/micronaut-data-jdbc-graal and use branch `oracle`. Follow the instructions in the README to start Oracle XE in Docker.
Then run the application using the JVM (no the native-image).

**Comment by graemerocher** [comment]
Fixed by 5f63fc64471d6c07e8f596dccba761e5f4557845
