### ISSUE TITLE
@AutoPopulated doesn't work when using partial save() repository methods

### ISSUE THREAD

**Issue by hex-agon** [micronaut-projects/micronaut-data#2127]
### Expected Behavior

Given a mapped entity:
```java
@MappedEntity("account")
public record TestRecord(
        @Id @AutoPopulated UUID uuid,
        String username,
        String email,
        @GeneratedValue String emailStatus,
        byte[] password,
        @GeneratedValue OffsetDateTime registeredAt
) {}
```

And a jdbc repository defined as:

```java
@JdbcRepository
public interface TestRecordRepository extends GenericRepository<TestRecord, UUID> {

    TestRecord save(String username, byte[] password, String email);
}
```

When calling `TestRecordRepository.save(username, password, email)` the entity is created successfully.

### Actual Behaviour

Calling `TestRecordRepository.save(username, password, email)` causes an exception to be thrown:

```
io.micronaut.core.reflect.exception.InstantiationException: Null argument specified for [uuid]. If this argument is allowed to be null annotate it with @Nullable
	at io.micronaut.inject.beans.AbstractInitializableBeanIntrospection.instantiate(AbstractInitializableBeanIntrospection.java:255)
	at io.micronaut.core.beans.BeanIntrospection.instantiate(BeanIntrospection.java:81)
	at io.micronaut.data.runtime.intercept.AbstractQueryInterceptor.instantiateEntity(AbstractQueryInterceptor.java:513)
	at io.micronaut.data.runtime.intercept.DefaultSaveOneInterceptor.intercept(DefaultSaveOneInterceptor.java:48)
	at io.micronaut.data.runtime.intercept.DataIntroductionAdvice.intercept(DataIntroductionAdvice.java:83)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
	at com.example.TestRecordRepository$Intercepted.save(Unknown Source)
```

### Steps To Reproduce

* Clone the example application linked
* Run the application
* Call the endpoint `POST http://localhost:8080/record`

### Environment Information

- Windows
- Java 17

### Example Application

https://github.com/hex-agon/micronaut-data-issue

### Version

3.8.8

**Comment by hex-agon** [comment]
Hello everyone,

The documentation around these features is a bit dubious so i'm not sure if this is a supported usecase or not, looking at section 6.5.3 it states `Automatically assigned UUIDs are also supported by adding a property annotated with @Id and @AutoPopulated.` which leads me to believe that it is but looking at section 3.3.1 it states `In this case, when update of whole entity is intended, you must specify parameters for all properties other than those that are declared as @Nullable or as a @GeneratedValue, if you do not a compilation error will occur.` it doesn't mention `@AutoPopulated` at all but the repository compiles without any issues.

**Comment by dstepanov** [comment]
I think we should be able to support it

**Comment by hex-agon** [comment]
Hey, thank you for looking into this! It has been a while but i do recall trying with classes and having a similar result, in the end i ended up just working around the issue by initializing an `Account` record myself and then using a `save(entity)` method:
```java
    default Account save(String username, byte[] password, String email) {
        // Workaround micronaut-data
        return save(new Account(null, username, email, null, password, null));
    }

    Account save(Account account);
 ```
