### ISSUE TITLE
Unable to fetch data using reactive streams -No reactive transaction management has been configured. Ensure you have correctly configured a reactive capable transaction manager

### ISSUE THREAD

**Issue by nasreenazamkhan** [micronaut-projects/micronaut-data#2134]
### Issue description

Created 2 entities Team and Team Members with one to many relationship between them  as Team has many team Members.
Trying to fetch all the team members using reactive streams ->ReactiveStreamsCrudRepository<TeamMembers, Long> 
Flux<TeamMembers> findAll();

But getting the below error:
No reactive transaction management has been configured. Ensure you have correctly configured a reactive capable transaction manager.
How to handle one to many relationships with reactive streams.

Annotated the service method with @Transactional -import javax.transaction.Transactional;
below is the service method:
 @Override
    @Transactional
    public Flux<EmployeeDTO> fetchAllTeamMembers(Long id) {
        Flux<EmployeeDTO> employees = teamRepository.findAll().map(teamMember->{
            EmployeeDTO employee=new EmployeeDTO();
            employee.setName(teamMember.getMemberName());
            employee.setEmployeeId(teamMember.getMemberEmployeeId());
            return employee;
        });
        return employees;
       }

Environment :Java 17,Oracle DB ,Maven,JPA
PFA
[pom.docx](https://github.com/micronaut-projects/micronaut-core/files/11207146/pom.docx)
[application_yml.docx](https://github.com/micronaut-projects/micronaut-core/files/11207152/application_yml.docx)
[Team.docx](https://github.com/micronaut-projects/micronaut-core/files/11207156/Team.docx)
[TeamMember.docx](https://github.com/micronaut-projects/micronaut-core/files/11207164/TeamMember.docx)
[TeamRepository.docx](https://github.com/micronaut-projects/micronaut-core/files/11207168/TeamRepository.docx)

**Comment by dstepanov** [comment]
Please create a project on GitHub

**Comment by raghu298** [comment]
same issue i am facing and i have below dependencies:

```
implementation(libs.micronaut.data.jdbc)
    implementation(libs.micronaut.data.r2dbc)
    implementation("org.postgresql:postgresql")
    implementation(libs.micronaut.jdbc.hikari)
      annotationProcessor(libs.micronaut.data.processor)
```

**Comment by Sleepy-GH** [comment]
I'm having the same issue. Anyone had any progress with this?

**Comment by dstepanov** [comment]
Please create a reproducer with a test

**Comment by Sleepy-GH** [comment]
Alright, while fiddling around I figured out what was wrong in my case.

We use a specific Micronaut environment to enable test-containers backed integration tests. The configuration for all this was located in `src/test/resources/application-tc.yml`. The contents looking like:
```
test-resources:
  containers:
    mysql:
      image-name: mysql/mysql-server:8.0.27
      db-name: some-value

# For Flyway
datasources:
  avatar:
    db-type: mysql
    db-name: some-value

r2dbc:
  datasources:
    avatar:
      db-type: mysql
      dialect: MYSQL
      db-name: some-value
```

In `src/test/resources/application-test.yml` we had no configuration for any datasources.
After moving the `datasources` and `r2dbc` config sections to `src/test/resources/application-test.yml` the error disappeared for me.

I guess something between Micronaut 3 and 4 changed in behaviour here.

**Comment by dstepanov** [comment]
Thanks, closing it
