### ISSUE TITLE
Unable to start Hibernate app with Micronaut v4

### ISSUE THREAD

**Issue by sgammon** [micronaut-projects/micronaut-data#2197]
### Expected Behavior

1. Micronaut data should scan for, and find, my Hibernate entities
2. It seems to scan them with KSP and generate metadata
3. ... see next

### Actual Behaviour

4. But it either does not generate introspection references properly or can't find them at runtime

### Steps To Reproduce

1. Clone project
2. `./gradlew run`
3. See README for diagnosis notes

### Environment Information

- OS:
```
macOS Ventura 13.3.1
M2 Max (16-inch, 2023)
```

- JVM:
```
java version "19.0.2" 2023-01-17
Java(TM) SE Runtime Environment GraalVM EE 22.3.1 (build 19.0.2+7-jvmci-22.3-b11)
Java HotSpot(TM) 64-Bit Server VM GraalVM EE 22.3.1 (build 19.0.2+7-jvmci-22.3-b11, mixed mode, sharing)
```

### Example Application

https://github.com/sgammon/micronaut-4-hibernate-bug

### Version

`4.0.0-Mx`

**Comment by sgammon** [comment]
i've now tried this on Zulu 11 and got the same issue -- it's worth noting that Graal may be involved, since some of the metadata collision exceptions mention `io.micronaut.graal`.

**Comment by sgammon** [comment]
@graemerocher / @radovanradic i tried to upgrade my micronaut v3 codebase to Kotlin 1.9.0-Beta and it broke in this same way. i'm not sure if that helps (obviously kapt/ksp are different) but i found it interesting enough to report

**Comment by sgammon** [comment]
@graemerocher / @radovanradic filed the Kotlin v1.9.0-Beta issue as micronaut-projects/micronaut-core#9364

**Comment by radovanradic** [comment]
@sgammon Could you please update `gradle.properties` file in your sample project to

```
micronautVersion=4.0.0-M3
micronautLatest=4.0.0-M7
kotlinVersion=1.8.22
```

It appears this issue has been fixed in the latest micronaut version. At least in this example here https://github.com/micronaut-projects/micronaut-data/pull/2198
