### ISSUE TITLE
Add support for MongoDB

### ISSUE THREAD

**Issue by olivierboudet** [micronaut-projects/micronaut-data#220]
I would like to port some app (currently running on Spring Boot 2) to Micronaut but I am using Spring Data MongoDB.
Can it be possible to have MongoDB support in micronaut-data ?

**Comment by graemerocher** [comment]
MongoDB support is planned but not implemented yet

**Comment by KangoV** [comment]
@graemerocher What timescale are we looking at. I'm about to start a new job where MongoDB/Spring Boot. Can't wait to recommend Micronaut :)

**Comment by KangoV** [comment]
A lot of our clients use MongoDB. I can't wait to be able to suggest Micronaut instead of Sprint Boot :)

**Comment by mkfuri** [comment]
¿@graemerocher do you think that is a good approach start with [Micronaut MongoDB 1.3.0](https://micronaut-projects.github.io/micronaut-mongodb/latest/guide/index.html) and then I can migrate to Micronaut Data with Mongo Support?

**Comment by graemerocher** [comment]
Sure

**Comment by ghahramani** [comment]
@graemerocher Any updates on this?
If not, would it be possible to give me some resources that I can start implementing it myself?

**Comment by jntakpe** [comment]
Please, can you provide an update regarding Micronaut Data Mongo release date?  It's critical for us to be able to adopt micronaut

**Comment by graemerocher** [comment]
Right now, no progress. Hopefully by the end of the year. In the meantime using the MongoDB API directly is a pretty nice experience anyway. See https://dzone.com/articles/micronaut-mongodb for an example

**Comment by keilw** [comment]
Did you consider [Jakarta NoSQL](https://jakarta.ee/specifications/nosql/)? As I understand, there are other Jakarta EE Specs, especially Servlet or JMS where Micronaut provides an implementation or supports it by integrating a well-known implementation like ActiveMQ, etc. Jakarta NoSQL and its current implementation (called JNoSQL, the name is a bit close to the spec and we consider changing that) are somewhat close to Spring Data and its authors also provided feedack for the design, so it is possible Spring Data might at some later point also use it. We're doing a NoSQL comparison for a couple of conferences from next week on and so far I tested support for MongoDB or Neo4j also in Micronaut. It works but it is far less portable and consistent especially if an application has to work with multiple DB systems across different NoSQL types like document, graph or colum-based technologies. While Spring Data or Jakarta NoSQL help to make this very seamless and a lot easier to migrate entire applications with very little code or just configuration changes.

**Comment by oanedchenko** [comment]
> Right now, no progress. Hopefully by the end of the year. In the meantime using the MongoDB API directly is a pretty nice experience anyway. See https://dzone.com/articles/micronaut-mongodb for an example

yes, but it doesn't support declarative transactions

**Comment by vijayanaklak** [comment]
@graemerocher Any updates on Micronaut data support for Mongo DB ?
