### ISSUE TITLE
Using Kotlin, the custom converter was not used when serialising object 

### ISSUE THREAD

**Issue by antondelpiero** [micronaut-projects/micronaut-data#221]
When trying to save a property (on my case, the name is `payload`) of type map, an exception `Caused by: java.sql.SQLException: Incorrect string value: '\xAC\xED\x00\x05sr...' for column 'payload' at row 1` was thrown.
I use micronaut version 1.2.3 (also tried with 1.2.5 and this problem still exists), mysql 8.0.17, Kotlin 1.3.50 and Micronaut Data 1.0.0.M3

How to reproduce:
1. create a class with at least one property of type map and annotate with `@TypeDef(type = DataType.STRING)` or use my prepared repo https://github.com/antondelpiero/kotlin-map-converter
2. prepare the mysql DB with the utf8mb and utf8mb_bin collations. if my repo is used: create user with (user: user and password: pass), create schema `test` and the table `event` with 3 column: `id`, `name` and `payload`. 
3. start the app and fire a post request to `http://localhost:8080/events` with arbitrary json string in the body e.g. `{"a":"a"}`
4. an exception was thrown.

**Comment by graemerocher** [comment]
We have already resolved this. You can declare `payload` as a map and add `@TypeDef(type=DataType.JSON)` and it will be read as JSON

**Comment by antondelpiero** [comment]
I've just double checked it again, I still got the error even though using the `@TypeDef(type=DataType.JSON)`

**Comment by graemerocher** [comment]
Yeah I hit this problem too with MySQL it is due to https://bugs.mysql.com/bug.php?id=93052
