### ISSUE TITLE
PreUpdate not  trigger

### ISSUE THREAD

**Issue by funnyleolee** [micronaut-projects/micronaut-data#2212]
### Expected Behavior

The code `void update(@Id Long id, String title)` was not trigger `@PreUpdate`  annotation method.But for code ` RefreshTokenEntity save(Long id, String username, String refreshToken, Boolean revoked)` can be trigger `@PrePersist`  annotation method.

### Version

3.9.1

**Comment by dstepanov** [comment]
Events are not supported for batch operations or operations without entities. `PrePersist` works because internally we create and entity
