### ISSUE TITLE
Pageable sort by date: incompatible data type in operation in statement

### ISSUE THREAD

**Issue by SergiusSidorov** [micronaut-projects/micronaut-data#222]
I caught the following issue:
When I try to call repository findAll(Pageable) with sorting by the date, the exception is throwing:

incompatible data type in operation in statement [select .... from TEST_TABLE test_table0_ order by **lower**(test_table0_.created_date) asc offset ? limit ?]

micronaut-data version: 1.0.0.M3

```sql
CREATE TABLE IF NOT EXISTS
TEST_TABLE(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(20),
    created_date DATE NOT NULL,

    CONSTRAINT pk_test PRIMARY KEY(id)
);
```

```java
@Data
@Entity
@Table(name = "TEST_TABLE")
public class TestTable {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    private String name;
    @NotNull
    @Column(nullable = false, name = "created_date")
    private LocalDate createdDate;
}

@Repository
public interface TestTableRepository extends GenericRepository<TestTable, Long> {
    TestTable save(TestTable entity);
    Page<TestTable> findAll(Pageable pageable);
}

```

**Comment by graemerocher** [comment]
Using JDBC or JPA?

**Comment by SergiusSidorov** [comment]
JPA

**Comment by graemerocher** [comment]
I pushed a test for this and wasn't able to reproduce, so maybe it has been fixed already. If you encounter an issue with RC1 then attach an example to a new issue https://github.com/micronaut-projects/micronaut-data/commit/15acb9cd4dce3eb140910d8f3c2bad17b43cc2b8
