### ISSUE TITLE
GeneratedValue annotation doesn't update kotlin data class while insert

### ISSUE THREAD

**Issue by piotrwalkusz1** [micronaut-projects/micronaut-data#224]
```
@MappedEntity
data class Model(@Id @GeneratedValue val id: Long, val name: String)

@JdbcRepository(dialect = Dialect.H2)
interface Repository {
    fun save(model: Model): Single<Model>
}

val savedModel = repository.save(Model(id = 0, name = "Test")).blockingGet()
```

`savedModel.id` is always 0. Changing `val id: Long` to `var id: Long` or even `var id: Long?` doesn't work. I have to move `id` parameter to mutable `id` field:

```
@MappedEntity
data class Model(val name: String) {
    @Id @GeneratedValue var id: Long = 0
}
```

**Comment by graemerocher** [comment]
I believe this works if you apply the Kotlin JPA plugin and use JPA annotations instead. Something about the way Kotlin generates byte code for data classes is incompatible without this combination.

**Comment by piotrwalkusz1** [comment]
Unfortunately, adding dependency `compileOnly 'jakarta.persistence:jakarta.persistence-api:2.2.2'` and using `javax.persistence.Entity` instead of `io.micronaut.data.annotation.MappedEntity` doesn't work.

**Comment by graemerocher** [comment]
You probably also need to apply the JPA plugin to your Kotlin compiler. See https://kotlinlang.org/docs/reference/compiler-plugins.html

**Comment by piotrwalkusz1** [comment]
I forgot to write that I added JPA plugin too:
```
plugins {
  id "org.jetbrains.kotlin.plugin.jpa" version "1.3.50"
}
```
Decompilation of Kotlin class shows that no-arg constructor was generated. After more investigation, I found out that code:
```
@Entity
data class Model(@Id @GeneratedValue val id: Long, val name: String)
```
compiles to:
```
public final class Model {
   @GeneratedValue
   private final long id;
   ...
   public Model(@Id long id, @NotNull String name) {
      ...
   }
   ...
   public Model() {
   }
```
and code:
```
@Entity
data class Model(val name: String) {
    @Id
    @GeneratedValue
    var id: Long = 0
}
```
compiles to:
```
public final class Model {
   @Id
   @GeneratedValue
   private long id;
   ...
   public Model(@NotNull String name) {
      ...
   }
   ...
   public Model() {
   }
```
In the first case, annotations `@Id` and `@GeneratedValue` are on the field and the argument, in the second case, both annotations are on the field.

**Workaround**

The correct workaround that works for me is:
```
@Entity
data class Model(@field:Id @GeneratedValue var id: Long? = null, val name: String)
```
Please notice `@field:Id` instead of `@Id`. But still `id` field has to be mutable...

**Comment by graemerocher** [comment]
The `id` field does need to be mutable since in order for Micronaut Data to be able to set it on the object following an insert it has to be mutable. The alternative is for you to refresh the object from the database after an insert but that requires an additional query.
