### ISSUE TITLE
@DateCreated field unpopulated after save

### ISSUE THREAD

**Issue by jamesdh** [micronaut-projects/micronaut-data#2342]
### Expected Behavior

When performing a `CrudRepository.save()`, the returned object represents the actual saved state.

### Actual Behaviour

`@DateCreated` and `@DateUpdated` fields are null. Performing a `findById` immediately after saving does return the correct saved state. 

The behavior is inconsistent with the [documentation](https://micronaut-projects.github.io/micronaut-data/latest/api/io/micronaut/data/repository/CrudRepository.html#save(S)):
> Saves the given valid entity, returning a possibly new entity representing the saved state.

### Steps To Reproduce

1. Check out the example repo
2. `gradle test`

### Environment Information

- macOS 13.4
- Java 19.0.2

### Example Application

https://github.com/jamesdh/MicronautSaveBehavior

### Version

4.0.0 M5

**Comment by radovanradic** [comment]
Changing test to `@MicronautTest(transactional = false)` will make it pass. It would probably work also via controller create method test. Timestamp events that populate datecreated, dateupdated fields are fired after the transaction it seems, this is why, since test is transactional, it won't be fired after save.

**Comment by radovanradic** [comment]
Considering that test works with transactional = false, same as [test in micronaut code](https://github.com/micronaut-projects/micronaut-data/blob/master/data-hibernate-jpa/src/test/groovy/io/micronaut/data/hibernate/AutoTimestampSpec.groovy#L27) and this would not be an issue in actual controller that creates an entity, I think it can be closed.

**Comment by jamesdh** [comment]
Thanks for the clarification @radovanradic!
