### ISSUE TITLE
Error generating schema from inherited domain classes when using Groovy

### ISSUE THREAD

**Issue by joe-crawford** [micronaut-projects/micronaut-data#2349]
### Expected Behavior

When domain classes are defined using inheritance using the Groovy language, Micronaut Data R2DBC should generate the schema successfully when the `schema-generate: CREATE_DROP` option is used.

### Actual Behaviour

With some domain classes, an error occurs when generating the repository on application startup:

```
11:50:32.868 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Bean definition [io.micronaut.data.r2dbc.config.R2dbcSchemaGenerator] could not be loaded: Error instantiating bean of type  [io.micronaut.data.r2dbc.config.R2dbcSchemaGenerator]

Message: Unable to create table column for property [finalised] of entity [uk.ac.ox.softeng.folder.Folder] with unknown data type: OBJECT
Path Taken: new R2dbcSchemaGenerator(List configurations,R2dbcSchemaHandler schemaHandler)
io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [io.micronaut.data.r2dbc.config.R2dbcSchemaGenerator] could not be loaded: Error instantiating bean of type  [io.micronaut.data.r2dbc.config.R2dbcSchemaGenerator]
```

A fix is to add a `@MappedProperty` annotation to the field mentioned in the error message, however I don't believe this should be needed explicitly.

Also I have tried recreating the example in Java instead of Groovy, and the issue did not occur.

### Steps To Reproduce

1. Pull https://github.com/joe-crawford/micronaut-data-groovy-inheritance
2. Start the application - the error above occurs
3. After uncommenting the `@MappedProperty` annotation boolean field in the `Model` class, the error is fixed

### Environment Information

- Operating System: Mac OS X 13.0.1 (x86_64)
- JDK: 17.0.3 (Temurin)

### Example Application

https://github.com/joe-crawford/micronaut-data-groovy-inheritance

### Version

3.9.4

**Comment by radovanradic** [comment]
Just to note that this seems to be fixed in Micronaut 4. Can be checked with 4.0.0-M5, if that works for you.

**Comment by joe-crawford** [comment]
@radovanradic, that's great, I can confirm your upgrade to 4.0.0-M5 fixes the issue, thanks!

**Comment by radovanradic** [comment]
Great, thanks for confirming.
