### ISSUE TITLE
PostRemove not triggered when calling deleteById

### ISSUE THREAD

**Issue by simonreye-4tel** [micronaut-projects/micronaut-data#2356]
### Expected Behavior

When deleteById is called a PostRemove event should be triggered on objects listening for this event.

### Actual Behaviour

PostRemove is not triggered.

### Steps To Reproduce

Create a bean with a @PostRemove function for your desired entity
Delete an instance of the entity using deleteById

Note that `repository.findById( id ).ifPresent( repository::delete );` works

### Environment Information

Windows
JDK17

### Version

4.0.0-M8

**Comment by graemerocher** [comment]
currently `deleteById` works by issuing a batch delete query and doesn't load the entity, hence this behaviour. For `PostRemove` to be triggered the entity has to be deleted (which is why `delete` works)

**Comment by dstepanov** [comment]
Events are only supported for operations that are working with entities. `deleteById` doesn't create an entity before it's deleted
