### ISSUE TITLE
NPE when left outer joining two or more one-to-many tables with @Query

### ISSUE THREAD

**Issue by RonBarkan** [micronaut-projects/micronaut-data#2363]
### Expected Behavior

Custom @Query to load DTO entities just fine, when left-joining any number of one-to-many tables.

### Actual Behaviour

Null pointer exception 
io.micronaut.data.exceptions.DataAccessException: SQL Error executing Query: null
	at app//io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.findStream(DefaultJdbcRepositoryOperations.java:513)
	at app//io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.lambda$findAll$6(DefaultJdbcRepositoryOperations.java:539)
	at app//io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.lambda$executeRead$18(DefaultJdbcRepositoryOperations.java:708)
	at app//io.micronaut.transaction.support.AbstractSynchronousStateTransactionManager.execute(AbstractSynchronousStateTransactionManager.java:145)
	at app//io.micronaut.transaction.support.AbstractSynchronousStateTransactionManager.executeRead(AbstractSynchronousStateTransactionManager.java:160)
	at app//io.micronaut.transaction.support.AbstractSynchronousTransactionManager.executeRead(AbstractSynchronousTransactionManager.java:150)
	at app//io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.executeRead(DefaultJdbcRepositoryOperations.java:705)
	at app//io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.findAll(DefaultJdbcRepositoryOperations.java:538)
...
Caused by: java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:208)
	at io.micronaut.data.runtime.mapper.sql.SqlResultEntityTypeMapper.readChildren(SqlResultEntityTypeMapper.java:329)
	at io.micronaut.data.runtime.mapper.sql.SqlResultEntityTypeMapper.readChildren(SqlResultEntityTypeMapper.java:341)
	at io.micronaut.data.runtime.mapper.sql.SqlResultEntityTypeMapper.access$400(SqlResultEntityTypeMapper.java:76)
	at io.micronaut.data.runtime.mapper.sql.SqlResultEntityTypeMapper$2.processRow(SqlResultEntityTypeMapper.java:302)
	at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.findStream(DefaultJdbcRepositoryOperations.java:447)

### Steps To Reproduce

Environment:
Postgres / Java / Linux / Micronaut

DB Tables: at least 3 tables joined in this manner
@Query("""
Select ...
From A
Left Join B on ...   -- one-to-many
Left Join C on ...   -- one-to-many
Where ...
""")
@Join(value = "b", alias = "b_", type = Join.Type.LEFT_FETCH) // Also with the default
@Join(value = "c", alias = "c_", type = Join.Type.LEFT_FETCH) // Also with the default
public abstract List<A> findBlah(...);

@Introspected
@Table(schema = "schema")
@MappedEntity("A")
public class A {
...
 @Relation(Relation.Kind.ONE_TO_MANY)
 @Nullable
 List%lt;B%gt; b;
 
  @Relation(Relation.Kind.ONE_TO_MANY)
  @Nullable 
  List%lt;C%gt; c;
}

@Introspected
@Table(schema = "schema")
@MappedEntity("B")
public class B { ... }

@Introspected
@Table(schema = "schema")
@MappedEntity("C")
public class C { ... }

materializes when there are two or more one-to-many left outer joins. When one of the outer joins **is not null,** the other **is null** AND there's more than one output row. An NPE will be thrown for such a case, except for the first row of the root entity.

In the above example, the query result set should be
| A | B | C |
|---|---|---|
| a1| b1| c1|
| a1| b2|null| 

The null is due to the left join.

With one-to-many join, the columns of the 'one' side will be duplicated for each row of the 'many' side. If it is an outer join and there is no match, there will be exactly one row in the result-set for a single root entity, with the joined columns being null.
If there are two outer joined tables, there could be up to NxM rows in the result-set for a single root entity. If one of the outer joins results in null, then the row count becomes Nx1 (N for the table of the non-null joined rows).

The Micronaut reading path diverges [here](https://github.com/micronaut-projects/micronaut-data/blob/master/data-runtime/src/main/java/io/micronaut/data/runtime/mapper/sql/SqlResultEntityTypeMapper.java#L294). One path handles reading the root entity + child entities. The other is used when the root entity has already been processed. The latter is the problem path.
On the first row, when reading the root entity + child entities, the code will actually correctly handle a null joined table just fine. [It reads in a null child entityId](https://github.com/micronaut-projects/micronaut-data/blob/master/data-runtime/src/main/java/io/micronaut/data/runtime/mapper/sql/SqlResultEntityTypeMapper.java#L535-L542), and discards the null entity [read here](https://github.com/micronaut-projects/micronaut-data/blob/master/data-runtime/src/main/java/io/micronaut/data/runtime/mapper/sql/SqlResultEntityTypeMapper.java#L399-L402).
On subsequent rows, it will [throw an NPE](https://github.com/micronaut-projects/micronaut-data/blob/master/data-runtime/src/main/java/io/micronaut/data/runtime/mapper/sql/SqlResultEntityTypeMapper.java#L322) here if the child entity of the joined table is null.

### Environment Information

Postgres / Java JDK 17 / Linux / Micronaut 3.9.6

### Example Application

[GitHub DoubleJoinBug project](https://github.com/RonBarkan/doublejoinbug)

### Version

Micronaut Data 3.9.6

**Comment by RonBarkan** [comment]
With a lot of effort, I have added an example failing test case

**Comment by RonBarkan** [comment]
I mostly concentrated on the NPE, but the other possibility is as bad.
If the null happens to appear first, followed by non null data, then I believe the data for C will be ignored and not be populated into entities.
|A|B|C|
|-|-|-|
|a1|b2|null|
|a1|b1|c1|

**Comment by radovanradic** [comment]
Thanks for the example, it's easier to see what's the issue.
While trying to reproduce with some of our existing models, I noticed this doesn't reproduce if we have mappedBy attribute of `Relation` annotation. Something like this in your model 
```
@Relation(value = Relation.Kind.ONE_TO_MANY, mappedBy = "aId")
@Nullable
public List<B> b = new ArrayList<>();

@Relation(value = Relation.Kind.ONE_TO_MANY, mappedBy = "aId")
@Nullable
public List<C> c = new ArrayList<>();
```
and test would look like this
```
@Test
    void testDoubleJoin() {
      A a = new A();
      a.setName("a1");
      a = aTable.save(a);

      C c1 = new C();
      c1.setAId(a.getAId());
      c1.setCProp("c1");
      //cTable.save(c1);

      B b1 = new B();
      b1.setAId(a.getAId());
      b1.setBProp("b1");
      b1.setReqProp("c1");
      //bTable.save(b1);

      B b2 = new B();
      b2.setAId(a.getAId());
      b2.setBProp("b2");
      //bTable.save(b2);

        a.b.add(b1);
        a.b.add(b2);
        a.c.add(c1);
        aTable.save(a);

      List<A> as = aTable.findBlah(a.getAId());
      Assertions.assertEquals(1, as.size());
    }
```
 If that's ok with your model then the issue would be resolved. However, we will try to working on reproducer, test and fix for the issue.

**Comment by RonBarkan** [comment]
After adding `mappedBy` and slightly changing the test-case above to this:

```
  @Test
  void testDoubleJoinMappedBy() {
    A a = new A();
    a.setName("a1");
    a = aTable.save(a);

    C c1 = new C();
    c1.setAId(a.getAId());
    c1.setCProp("c1");
    //cTable.save(c1);

    B b1 = new B();
    b1.setAId(a.getAId());
    b1.setBProp("b1");
    b1.setReqProp("c1");
    //bTable.save(b1);

    B b2 = new B();
    b2.setAId(a.getAId());
    b2.setBProp("b2");
    //bTable.save(b2);

    a.setB(List.of(b1, b2));
    a.setC(List.of(c1));
    aTable.save(a);

    List<A> as = aTable.findNPE(a.getAId());
    Assertions.assertEquals(1, as.size());
    Assertions.assertEquals(2, as.get(0).b.size());  <=== fails here
    Assertions.assertEquals(1, as.get(0).c.size());

    as = aTable.findIgnoreC(a.getAId());  // Currently, this will completely ignore C column
    Assertions.assertEquals(1, as.size());
    Assertions.assertEquals(2, as.get(0).b.size());
    Assertions.assertEquals(1, as.get(0).c.size());
  }
  ```

The test fails with B table not being read (C is not read either).
