### ISSUE TITLE
Page response does not include some attributes when running as a GraalVM Native Image

### ISSUE THREAD

**Issue by montesmoci** [micronaut-projects/micronaut-data#2386]
### Expected Behavior

When returning an `io.micronaut.data.model.Page` object from a controller method the following attributes are included totalPages, pageNumber, empty, size, offset in the HTTP response JSON object.

### Actual Behaviour

When building/running as a GraalVM Native Image, the application does not include the aforementioned attributes (or from the looks of it io.micronaut.data.model.Slice)

### Steps To Reproduce

1. Build an application that includes Micronaut Data dependency and either H2 or MySql datasource defined (issue confirmed for both)
2. Call an endpoint that returns a Page
3. Observe totalPages property among others are not included in the response.

### Environment Information

- OpenJDK Runtime Environment GraalVM CE 22.3.1 (build 11.0.18+10-jvmci-22.3-b13)

### Example Application

https://github.com/montesmoci/issue-mn-data-page-graalvm

### Version

3.8.9

**Comment by radovanradic** [comment]
@montesmoci Please try upgrading to latest Micronaut, should resolve the issue.
Here is upgraded version from your example 
[issue-mn4-data-page-graalvm.zip](https://github.com/micronaut-projects/micronaut-data/files/12883733/issue-mn4-data-page-graalvm.zip)
