### ISSUE TITLE
NamingStrategy doesn't work on Micronaut 4.0.0 and Native Image

### ISSUE THREAD

**Issue by joaorodrigo** [micronaut-projects/micronaut-data#2391]
### Expected Behavior

I tried to migrate my application from 3.9.4 to 4.0.0, but in Native mode GraalVM stopped working the namingStrategy in MappedEntity.

When I run it in JVM mode, it doesn't show an error and I don't need to map column by column, but in native mode it doesn't work anymore and it tries to map in the pattern with _. Example:
Field: patientId error occurs:
Caused by: java.sql.SQLException: Column 'patient_id' not found

Any solutions before I need to go back to 3.9.4?

### Version

4.0.0

**Comment by radovanradic** [comment]
@joaorodrigo Yes, this is regression in 4.0 and we will fix it soon.
In the meantime, can you try adding `@TypeHint(YourNamingStrategy.class)` somewhere in your code and make sure micronaut-graal annotation processor is configured in the module where you add this annotation.
