### ISSUE TITLE
Nullable java.lang.Object does not deserialize correctly

### ISSUE THREAD

**Issue by Geoffrynagy** [micronaut-projects/micronaut-data#2403]
### Expected Behaviour

Consider the following embeddable entity:

```
@Embeddable
@Serdeable
public class Coffee {
    private String color;
    private String somethingElse;

    @Nullable
    private Object temperature;

    public Coffee(final String color, final String somethingElse, final @Nullable Object temperature) {
        this.color = color;
        this.somethingElse = somethingElse;
        this.temperature = temperature;
    }

    // getters and setters
}
```

When persisting a `Coffee` with `temperature` set to `null`, then it should work as intended.
When retrieving a `Coffee` with `temperature` is `null`, then it deserializes correctly.

### Actual Behaviour

Deserialization fails because serde thinks that the nullable property is required.

```
Caused by: io.micronaut.serde.exceptions.SerdeException: Unable to deserialize type [com.example.Coffee]. Required constructor parameter [Object temperature] at index [2] is not present or is null in the supplied data
```

### Steps To Reproduce

See unit tests in https://github.com/Geoffrynagy/micronaut-nullable-object-deserialization-demo to reproduce.

### Example Application

https://github.com/Geoffrynagy/micronaut-nullable-object-deserialization-demo

### Version

4.0.1

**Comment by radovanradic** [comment]
I think it is because of `temperature` field which is of type `Object` and it causes bug in deserialization. This might need fix in serde library.

**Comment by Geoffrynagy** [comment]
> I think it's because Lombok is not coping the field annotations. Please try your example without Lombok.

Hi @dstepanov ; I removed lombok entirely from the example repo and the problem is still there.

**Comment by radovanradic** [comment]
Yes, changing from `Object` to `List<Integer>` would resolve the error but I guess that's not suitable solution so it needs fix in serde.

**Comment by Geoffrynagy** [comment]
> Yes, changing from `Object` to `List<Integer>` would resolve the error but I guess that's not suitable solution so it needs fix in serde.

Correct! Any other type works but not if the field is of type `java.lang.Object`

**Comment by radovanradic** [comment]
Fixed in https://github.com/micronaut-projects/micronaut-serialization/pull/530 and will be available in upcoming patch releases. Or most likely in serde 2.1.2

**Comment by radovanradic** [comment]
@Geoffrynagy Just a minor note, I ran tests and now equals fails in your tests since Lombok was removed, so equals/hashCode need to be implemented.

**Comment by Geoffrynagy** [comment]
Thank you for the quick response and fix!
