### ISSUE TITLE
lessThanOrEqualTo predicate behaves like lessThan

### ISSUE THREAD

**Issue by drzpk** [micronaut-projects/micronaut-data#2404]
### Expected Behavior

The `lessThanOrEqualTo` predicate defined in `KCriteriaBuilderExt` should match values that are less than **or equal to** the specified value.

### Actual Behaviour

The `lessThanOrEqualTo` predicate behaves like `lessThan`, the "orEqualTo" part doesn't work.

I'm using a bit outdated version of `micronaut-data-runtime` (3.7.2), but the predicate looks exactly the same on master:
```kotlin
infix fun <Y : Comparable<Y>> Expression<out Y?>.lessThanOrEqualTo(other: Y) = addComparablePredicate(criteriaBuilder::lessThan, other)
infix fun <Y : Comparable<Y>> Expression<out Y?>.lessThanOrEqualTo(other: Expression<out Y?>) = addComparablePredicate(criteriaBuilder::lessThan, other)
```

### Steps To Reproduce

```kotlin
fun findSomething(date: Instant) = repository.findAll(where {
    and {
        root[Example::status] eq 'status'
        root[Example::updatedAt] lessThanOrEqualTo date
    }
})

@MappedEntity("example")
data class Example(
    @BsonRepresentation(BsonType.STRING)
    @field:Id val id: String,
    val status: String,
    val updatedAt: Instant
)

@MongoRepository
interface ExampleRepository : CoroutineCrudRepository<Example, String>, CoroutineJpaSpecificationExecutor<Example>
```

### Version

3.7.2

**Comment by dstepanov** [comment]
Offtopic, using equals with dates in the databases might be a bit problematic.
