### ISSUE TITLE
Injecting EntityManager for a specific data source not possible

### ISSUE THREAD

**Issue by mynecker** [micronaut-projects/micronaut-data#2419]
### Expected Behavior

Using 2..n JPA datasources in parallel and injecting an EntityManager for a specific datasource into a service class.

```
    @Inject
    @PersistenceContext(name = "db1")
    lateinit var entityManager: EntityManager
```

### Actual Behaviour

When defining 2 datasources and trying to inject a specific one ends with this excpetion.

Maybe some misconfiguration? Should it be possible to inject an EntityManager with a specific PersistenceContext name?

```
Message: Multiple possible bean candidates found: [io.micronaut.configuration.hibernate.jpa.TransactionalSession$Intercepted, io.micronaut.configuration.hibernate.jpa.TransactionalSession$Intercepted]
Path Taken: new MultidatasourcesCommand() --> MultidatasourcesCommand.service1 --> $Service1$Definition$Intercepted.entityManager
	at picocli.CommandLine$DefaultFactory.create(CommandLine.java:5687)
	at picocli.CommandLine$Model$CommandUserObject.getInstance(CommandLine.java:12262)
	at picocli.CommandLine$Model$CommandSpec.userObject(CommandLine.java:6437)
	at picocli.CommandLine$Interpreter.clear(CommandLine.java:13466)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:13512)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:13501)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:13396)
	at picocli.CommandLine.parseArgs(CommandLine.java:1552)
	at picocli.CommandLine.execute(CommandLine.java:2169)
	at io.micronaut.configuration.picocli.PicocliRunner.run(PicocliRunner.java:137)
	at io.micronaut.configuration.picocli.PicocliRunner.run(PicocliRunner.java:114)
	at demo.MultidatasourcesCommand$Companion.main(MultidatasourcesCommand.kt:29)
	at demo.MultidatasourcesCommand.main(MultidatasourcesCommand.kt)
Caused by: io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for field [entityManager] of class: demo.persistence.$Service1$Definition$Intercepted
```

### Steps To Reproduce

Issue can be reproduced with the sample repository

### Example Application

https://github.com/mynecker/micronaut-multidatasource-sample

### Version

3.10.0

**Comment by graemerocher** [comment]
try using `@Named("db1")`

**Comment by mynecker** [comment]
Adapting to 

```
@Singleton
open class Service1 {

    @Inject
    @Named("db1")
    @PersistenceContext
    lateinit var entityManager: EntityManager

    @TransactionalAdvice("db1")
    @Transactional
    open fun doSomething(){
        //sql will fail, just to have some entityManager sample code
        entityManager.createNativeQuery("SELECT * from universe")
    }

}
```

yield to the same exception.

**Comment by radovanradic** [comment]
Can you try Micronaut 4? Seems like it does not throw the error there.

**Comment by mynecker** [comment]
please have a look at https://github.com/mynecker/micronaut-multidatasource-sample/tree/mircronaut4 

Tried to define 2 datasources with Micronaut4 (4.0.4 for *.data.*) and still fails, might be still a configuration issue on my end.

 As soon as there is a second JPA configuration in application.yml an exception is thrown. 

`Message: Multiple possible bean candidates found: [JpaConfiguration, JpaConfiguration]`

A second datasource is no problem, naming datasource and JPA configuration is no problem and getting the named datasource / spa configuration injected into repositories etc. works well, too.

**Comment by mynecker** [comment]
Applied the patch and enhanced the demo a little bit to simulate a more realistic use case. The demo is updated and in main branch https://github.com/mynecker/micronaut-multidatasource-sample

 Same issue as in https://github.com/mynecker/micronaut-multidatasource-sample/tree/mircronaut4 

`Message: Multiple possible bean candidates found: [JpaConfiguration, JpaConfiguration]`

**Comment by radovanradic** [comment]
Looks like adding this line to application-test.properties

```
jpa.default.properties.hibernate.hbm2ddl.auto=auto
```

makes test pass. It might be a workaround for now.

**Comment by mynecker** [comment]
Thanks for pointing to the solution and I can confirm: with one `default`datasouce in place, multiple datasources can be defined. The sample got updated accordingly.

**Comment by mynecker** [comment]
Working sample can be found here for Micronaut 4.0.2
https://github.com/mynecker/micronaut-multidatasource-sample
