### ISSUE TITLE
Ability to set createdDate on @Entity object

### ISSUE THREAD

**Issue by niravassar** [micronaut-projects/micronaut-data#242]
The `@DateCreated` annotation will automatically populate a field with a timestamp with `Instant` type.  In `EventIntegrator:86`, `timestampIfNecessary` uses the introspected annotated field `dateCreated` to eventually set it to now. See line :126.

We can enhance this by allowing developers to configure there own implementation of a `DateTimeProvider`, by providing an interface which is injected into `EventIntegrator`. Micronaut Data can have its own default implementation.

I ran into this case when writing a test case where I wanted to configure the dateCreated timestamp for a previously configured date. I was unable to override the current `now()` date. The above would prove valuable in this case. 

See springs version in JPA: https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/auditing/DateTimeProvider.html

**Comment by graemerocher** [comment]
Sure seems reasonable

**Comment by niravassar** [comment]
Here is a workaround i did currently using micronaut data

https://github.com/niravassar/jhipster-sample-app-micronaut/blob/d156427644a986f4bfc4b567e20139d29aa0f2b0/src/test/java/io/github/jhipster/sample/service/UserServiceIT.java#L166
