### ISSUE TITLE
missing compilation time query information

### ISSUE THREAD

**Issue by pditommaso** [micronaut-projects/micronaut-data#243]
Creating a basic project following the instructions in the docs fails with the following error message: 

```
java.lang.IllegalStateException: Micronaut Data method is missing compilation time query information. Ensure that the Micronaut Data annotation processors are declared in your build and try again with a clean re-build.
	at io.micronaut.data.intercept.DataIntroductionAdvice.intercept(DataIntroductionAdvice.java:82)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:69)
	at mn.data.BookRepositoryTest.should save book(BookRepositoryTest.groovy:21)
```

I've created a [repo replicating this issue](https://github.com/pditommaso/mn-data-issue).

**Comment by graemerocher** [comment]
For Groovy the Micronaut processors need to all be in `compileOnly` scope: https://github.com/pditommaso/mn-data-issue/blob/master/build.gradle#L32

**Comment by pditommaso** [comment]
Ouch! confirming that now works fine. Thanks.
