### ISSUE TITLE
CoroutineCrudRepository.findAll() results in conversion error from FluxLift -> Flow

### ISSUE THREAD

**Issue by jleskovar-tyro** [micronaut-projects/micronaut-data#2443]
### Expected Behavior

Hi there,

I'm trying to use the `findAll()` method on an instance of `CoroutineCrudRepository`. This method returns a `Flow<T>`. I would expect this method to return a `Flow<T>`

### Actual Behaviour

Instead, `findAll()` throws an exception. After stepping through, I can see the following exception (this actually gets swallowed and shadowed by a more generic exception):

```
java.lang.IllegalArgumentException: Cannot convert reactive type [class reactor.core.publisher.FluxLift] to type [interface kotlinx.coroutines.flow.Flow]. Ensure that you have the necessary Reactive module on your classpath. For example for Reactor you should have 'micronaut-reactor'.
```

Adding `micronaut-reactor` to classpath does not resolve issue

### Version

Micronaut Data 3.10.0

**Comment by dstepanov** [comment]
You need to add `micronaut-kotlin`

**Comment by jleskovar-tyro** [comment]
I hate to be a bother, but could you provide the exact module names? I already have the following `implementation` level dependencies:

```
micronautKotlinExtensionFunctions = { module = "io.micronaut.kotlin:micronaut-kotlin-extension-functions" }
micronautKotlinRuntime = { module = "io.micronaut.kotlin:micronaut-kotlin-runtime" }
```

**Comment by jleskovar-tyro** [comment]
All good - I think I need to upgrade to micronaut-kotlin 4.0.1, as the issue was only fixed here https://github.com/micronaut-projects/micronaut-kotlin/pull/455
