### ISSUE TITLE
Micronaut Data V1.0.0.M4 jdbc with quotes

### ISSUE THREAD

**Issue by kukoots** [micronaut-projects/micronaut-data#245]
Micronaut Data V1.0.0.M4 jdbc creates query with quotes like `... FROM "ucs_users" user_ WHERE ...` instead `ucs_user` without quotes like Micronaut Data V1.0.0M3 . Is there some config to change?

**Comment by kukoots** [comment]
Found the solution here
https://github.com/micronaut-projects/micronaut-data/issues/140#issuecomment-529862905
It's related to `@MappedEntity(escape=false)`

**Comment by graemerocher** [comment]
Should be fixed in M5 without that
