### ISSUE TITLE
@RequestScope is missing inside @Transactional methods in combination with micronaut-data-hibernate-reactive

### ISSUE THREAD

**Issue by s-af** [micronaut-projects/micronaut-data#2458]
### Expected Behavior

Hello,

During migration from Micronaut 3 to Micronaut 4 I faced with missing context issue. I have seen that in Micronaut 4 some magic related to context propagation in Reactor was removed, but it is a bit unclear if (a)RequestScope should work in combination with (a)Transactional and Hibernate Reactive. In my example I have added dependency io.micrometer:context-propagation. So I expected that RequestScoped beans will be available inside (a)Transactional methods, kindly correct me if I am wrong.

### Actual Behaviour

When attempting access (a)RequestScope bean values inside (a)Transactional method next exception appear:
`Caused by: java.lang.IllegalStateException: No request present
	at io.micronaut.runtime.http.scope.RequestCustomScope.getScopeMap(RequestCustomScope.java:78)
	at io.micronaut.context.scope.AbstractConcurrentCustomScope.getOrCreate(AbstractConcurrentCustomScope.java:127)
	at io.micronaut.context.DefaultBeanContext.getOrCreateScopedRegistration(DefaultBeanContext.java:3017)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2943)
	at io.micronaut.context.DefaultBeanContext.getProxyTargetBean(DefaultBeanContext.java:1474)`

### Steps To Reproduce

1. Clone repository https://github.com/s-af/reactive-data.git and checkout branch 'request-scope-test'
2. Run `mvnw.bat clean verify`
3. Check test result

### Environment Information

- OS Win 10
- JDK 17

### Example Application

https://github.com/s-af/reactive-data.git

### Version

4.0.4

**Comment by dstepanov** [comment]
That's a bit complicated case. You might want to add Micrometer Context propagation to restore the previous behavior https://docs.micronaut.io/latest/guide/#reactorContextPropagation

**Comment by s-af** [comment]
Do you mean I have to add dependency to
```
    <dependency>
      <groupId>io.micrometer</groupId>
      <artifactId>context-propagation</artifactId>
    </dependency>
```
Or should I propagate context manually using Mono.contextWrite(...) ?

**Comment by dstepanov** [comment]
That should be enough

**Comment by s-af** [comment]
It is already in pom

**Comment by s-af** [comment]
@dstepanov, kindly confirm if it is expected behavior and we should care about context propagation in this case somehow manually or (a)RequestScope should work out of box in Micronaut in combination with (a)Transactional methods?

**Comment by dstepanov** [comment]
It is expected. Unfortunately, the propagation in Reactive is complicated. Did you try to add the dependency I suggested? It should fix your problem.

**Comment by s-af** [comment]
Dependency on io.micrometer:context-propagation was in my example from the beginning, I mentioned it in description. Kindly check linked repository. Unfortunately, dependency is not something what may @RequestScope work inside (a)Transactional. 

There is a list of dependences:
```
  <dependencies>
    <dependency>
      <groupId>org.yaml</groupId>
      <artifactId>snakeyaml</artifactId>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>io.micronaut</groupId>
      <artifactId>micronaut-http-server-netty</artifactId>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>io.micronaut.reactor</groupId>
      <artifactId>micronaut-reactor</artifactId>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>io.micronaut.reactor</groupId>
      <artifactId>micronaut-reactor-http-client</artifactId>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>io.micronaut</groupId>
      <artifactId>micronaut-jackson-databind</artifactId>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>io.micrometer</groupId>
      <artifactId>context-propagation</artifactId>
    </dependency>

    <!-- Hibernate deps -->
    <dependency>
      <groupId>io.micronaut.data</groupId>
      <artifactId>micronaut-data-hibernate-reactive</artifactId>
    </dependency>
    <dependency>
      <groupId>io.vertx</groupId>
      <artifactId>vertx-mssql-client</artifactId>
    </dependency>

    <!-- Liquibase deps -->
    <dependency>
      <groupId>io.micronaut.liquibase</groupId>
      <artifactId>micronaut-liquibase</artifactId>
    </dependency>
    <dependency>
      <groupId>io.micronaut.sql</groupId>
      <artifactId>micronaut-jdbc-tomcat</artifactId>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>com.microsoft.sqlserver</groupId>
      <artifactId>mssql-jdbc</artifactId>
    </dependency>

    <dependency>
      <groupId>ch.qos.logback</groupId>
      <artifactId>logback-classic</artifactId>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>io.micronaut</groupId>
      <artifactId>micronaut-http-client</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.micronaut</groupId>
      <artifactId>micronaut-inject-groovy</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.micronaut.test</groupId>
      <artifactId>micronaut-test-spock</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.spockframework</groupId>
      <artifactId>spock-core</artifactId>
      <scope>test</scope>
      <exclusions>
          <exclusion>
            <groupId>org.apache.groovy</groupId>
            <artifactId>groovy-all</artifactId>
          </exclusion>
        </exclusions>
    </dependency>
    <dependency>
      <groupId>org.testcontainers</groupId>
      <artifactId>mssqlserver</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>
```

**Comment by s-af** [comment]
@dstepanov, do you have an ideas of when it might be fixed?
