### ISSUE TITLE
Custom save method fails when (not auto generated) id passed

### ISSUE THREAD

**Issue by radovanradic** [micronaut-projects/micronaut-data#2531]
### Expected Behavior

Having entity like this 
```
@MappedEntity
class MyEntity {
  @Id
  private Long id;
  private String name; 
  ...
  public Long getId() { return id; }
  public void setId(Long id) { this.id = id; }
  public String getName() { return name; }
  ...
}
```
Repository:
```
@JdbcRepository(dialect = Dialect.H2)
interface MyRepository extends CrudRepository<MyEntity, Long> {
  MyEntity save(Long id, String name);
}
```
calling `myRepository.save(1, 'Item1')` should create new entity with id 1 and name `Item1`.

### Actual Behaviour

An exception is thrown

>Error executing PERSIST: NULL not allowed for column "ID"; SQL statement:
INSERT INTO `my_entity` (`id`,`name`,...) VALUES (?, ?)

Because id is not being bound during an insert operation.

### Steps To Reproduce

Follow steps from Expected Behavior section.

### Environment Information

Any

### Version

4.0.0

**Comment by radovanradic** [comment]
Ok, will have to use Oracle Free 23.2 docker image because with latest (which is 23.3 at the moment) Json View insert fails with:

> Caused by: Error : 1804, Position : 0, SQL = BEGIN INSERT INTO "STUDENT_VIEW" VALUES (:1 ) RETURNING JSON_VALUE(DATA,'$.id') INTO :2 ; END;, Original SQL = BEGIN INSERT INTO "STUDENT_VIEW" VALUES (?) RETURNING JSON_VALUE(DATA,'$.id') INTO ?; END;, Error Message = ORA-01804: failure to initialize timezone information |  
-- | --
  | at app//oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:710)

Perhaps once we move to Oracle 23.3 Jdbc driver we can update back to latest.

**Comment by dstepanov** [comment]
Aren't we use `oracle-free` by default?

**Comment by radovanradic** [comment]
No, only for Json View tests. For the rest we use `gvenzl/oracle-xe`
