### ISSUE TITLE
Order with Embedded not working in JPA

### ISSUE THREAD

**Issue by jayeshkapadnis** [micronaut-projects/micronaut-data#2549]
### Expected Behavior

Correct JPQL should be generated when a column is part of `Embeddable` and used as part of  `Sort` order. 

### Actual Behaviour

`Audit` is an `Embeddable` embedded in `User` entity. Following is a stacktrace while calling `findAll(Sort)` using a property `audit.createdAt`
```
org.hibernate.query.sqm.InterpretationException: Error interpreting query [SELECT user_ FROM com.sort.User AS user_ ORDER BY user_.createdAt DESC]; this may indicate a semantic (user query) problem or a bug in the parser [SELECT user_ FROM com.sort.User AS user_ ORDER BY user_.createdAt DESC]
Caused by: java.lang.IllegalArgumentException: org.hibernate.query.SemanticException: Could not resolve attribute 'createdAt' of 'com.sort.User'
```

This issue is caused due to the changes as part of PR #2414 to resolve the issue #2412.

### Steps To Reproduce

1. `git clone git@github.com:jayeshkapadnis/sort-issue.git`
2. Run `com.sort.SortIssueTest`
3. See the error

### Environment Information

- Operating System : macOS 13.3.1 (a)
- JDK : 17

### Example Application

[sort-issue](https://github.com/jayeshkapadnis/sort-issue)

### Version

4.1.3

**Comment by radovanradic** [comment]
Done via #2550 , should be released in micronaut-data 4.1.4
