### ISSUE TITLE
@Query annotation does not work with question mark '?' in query

### ISSUE THREAD

**Issue by pablobenitezperez** [micronaut-projects/micronaut-data#2582]
### Expected Behavior

When using this:

```
 @Query(value = "select * from connection_provider.connection c, jsonb_array_elements(c.payment_methods) payment_method" +
    "          where last_status = :lastStatus" +
    "           and payment_method ? :paymentMethod ",
    nativeQuery = true)
```

This is translated to a query expecting 2 input parameters but it's translated to a query expecting 3 input parameters.

### Actual Behaviour

When using this:

```
 @Query(value = "select * from connection_provider.connection c, jsonb_array_elements(c.payment_methods) payment_method" +
    "          where last_status = :lastStatus" +
    "           and payment_method ? :paymentMethod ",
    nativeQuery = true)
```

This is translated to a query expecting 3 input parameters instead of 2 input parameters.

` Executing Query: select * from connection_provider.connection c, jsonb_array_elements(c.payment_methods) payment_method          where last_status = ?  and payment_method ? ? `

The problem is the question mark '?' inside the query.

### Steps To Reproduce

@JdbcRepository(dialect = Dialect.POSTGRES)
Micronaut version: 3.8.1

### Version

3.8.1

**Comment by radovanradic** [comment]
Can you try using `??` in your statement instead of single `?`, would it work then?
It's stated [here](https://jdbc.postgresql.org/documentation/query/#using-the-statement-or-preparedstatement-interface) it could work

**Comment by radovanradic** [comment]
Escaping like this should work:

```
@Query(value = "select * from connection_provider.connection c, jsonb_array_elements(c.payment_methods) payment_method" +
    "          where last_status = :lastStatus" +
    "           and payment_method \\?\\? :paymentMethod ",
    nativeQuery = true)
```

**Comment by pablobenitezperez** [comment]
First solution worked @radovanradic .

Thanks a lot for the reply. Appreciate it

**Comment by radovanradic** [comment]
Glad it worked, will close this now if you don't mind.
