### ISSUE TITLE
No bean of PrimaryRepositoryOperations exists

### ISSUE THREAD

**Issue by boomermath** [micronaut-projects/micronaut-data#2584]
### Expected Behavior

Micronaut R2DBC should run without any PrimaryRepositoryOperations bean being missing.

### Actual Behaviour

I have a [project](https://github.com/boomermath/farmed) that uses micronaut data r2dbc with postgresql with the following config for the database: 

```yaml
flyway:
  datasources:
    default:
      enabled: true
      baseline-on-migrate: false
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/farmed
    username: boomermath
    password: REDACT
r2dbc:
  datasources:
    default:
      db-type: postgresql
      url: r2dbc:postgresql://localhost:5432/farmed
      username: boomermath
      password: REDACT
```

When I start the application and try to run my endpoint, which calls `UserRepository` I get the following error:

```
io.micronaut.context.exceptions.NoSuchBeanException: No bean of type [io.micronaut.data.operations.PrimaryRepositoryOperations] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
	at io.micronaut.context.DefaultBeanContext.newNoSuchBeanException(DefaultBeanContext.java:2773)
	at io.micronaut.context.DefaultApplicationContext.newNoSuchBeanException(DefaultApplicationContext.java:303)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2735)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1693)
	at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:89)
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2165)
	... 19 common frames omitted
```

So for some reason, this bean isn't being created when the application starts.

### Steps To Reproduce

1. Running my project with data-r2dbc in postgresql produces this error.
2. Note: my database uses flyway to migrate schema. Currently there are two tables: user and identity with a one-to-one relationship

### Environment Information

- Operating system: WSL Ubuntu 20.04
- JDK: 17

### Example Application

http://github.com/boomermath/farmed

### Version
JDK: 17.0.6
Micronaut: 4.1.5

**Comment by rorueda** [comment]
Have you tried with `@R2dbcRepository(dialect = Dialect.POSTGRES)`? If I'm not mistaken, the `@Repository` annotation is meant for Hibernate/JPA.

**Comment by radovanradic** [comment]
Yes, and maybe this is just to show or reproduce the issue but `PrimaryRepositoryOperations` should not be used to inject and operate with but just as a marker as per [docs](https://micronaut-projects.github.io/micronaut-data/4.1.4/api/io/micronaut/data/operations/PrimaryRepositoryOperations.html).

**Comment by boomermath** [comment]
> Have you tried with `@R2dbcRepository(dialect = Dialect.POSTGRES)`? If I'm not mistaken, the `@Repository` annotation is meant for Hibernate/JPA.

Yep. That was the problem. Thank you very much for solving this issue quickly!
