### ISSUE TITLE
@Embedded support for Micronaut JDBC

### ISSUE THREAD

**Issue by ArthurHarkivsky** [micronaut-projects/micronaut-data#2595]
### Feature description

Please, add @Embedded support for Micronaut JDBC. @Embeddable with @EmbeddedId is not enough.

**Comment by dstepanov** [comment]
What exactly is missing?

**Comment by ArthurHarkivsky** [comment]
As I see, it is unable to use Embedded like in Micronaut JPA, if I am right, there is a possibility only to use EmbeddedId in Micronaut JDBC. Or no?

**Comment by dstepanov** [comment]
It should be possible to use it. What problem are you hitting?

**Comment by ArthurHarkivsky** [comment]
Embedded annotation is from persistence package, does Micronaut JDBC mixes javax.persistence with internal annotations of Micronaut JDBC?

**Comment by dstepanov** [comment]
You can use Jakarta/Javax persistence annotations or our own `@Relation(value=EMBEDDED)` to define an embedded relation.

**Comment by ArthurHarkivsky** [comment]
Mixing works, THANK YOU!
