### ISSUE TITLE
Micronaut Data What's New 4.2.0 documentation lacks links

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-data#2621]
### Issue description

> Micronaut Data 4.2
> Procedure invocations in repositories
> Added possibility to have associations (JOINs) in DTOs> 
> Support for inserts, updates and deletes with RETURNING clause in repositories
> MongoDB: Support arrayFilters
> Kotlin: New coroutine variations of connection / transaction operations: io.micronaut.data.connection.kotlin.CoroutineConnectionOperations, io.micronaut.transaction.kotlin.CoroutineTransactionOperations
> R2DBC: New connection status callback. Corrected cancellation.

---

Where should `Procedure invocations in repositories` link to so that user can learn more?  https://micronaut-projects.github.io/micronaut-data/latest/guide/#hibernateProcedures or https://micronaut-projects.github.io/micronaut-data/latest/guide/#dbcProcedures. One section is in Micronaut Data data JPA and the other is in Micronaut Data JDBC.  

---

We don't have any docs about this ? [Added possibility to have associations (JOINs) in DTOs ](https://github.com/micronaut-projects/micronaut-data/issues/2618).

---
For: 

> MongoDB: Support arrayFilters

We don't have any example in the documentation. We should have documentation. But as a minimum can we at least link to the mongo docs: https://www.mongodb.com/docs/manual/reference/operator/update/positional-filtered/

---

For 

> R2DBC: New connection status callback. 

Should we link to this javadoc? https://micronaut-projects.github.io/micronaut-data/latest/api/io/micronaut/data/connection/reactive/ReactiveConnectionSynchronization.html

**Comment by dstepanov** [comment]
1. We can add both links with JPA and JDBC/R2DBC links
2. We can add a note, many devs assumed that this will work before
3. It's missing
4. We can
