### ISSUE TITLE
AsyncCrudRepository.findById does not return an Optional

### ISSUE THREAD

**Issue by witi83** [micronaut-projects/micronaut-data#263]
### Steps to Reproduce
1. Implement the `AsyncCrudRepository`, e.g. `interface UserRepository extends AsyncCrudRepository<User, Long>`
2. Implement a controller where you call `findById`, e.g.
```java
    @Get(value = "/{id}")
    CompletableFuture<User> get(long id) {
        return repo.findById(id);
    }
```
3. Call this interface-method with a non-existent id, e.g. `localhost:8080/users/1`

### Expected Behaviour
When trying to retrieve a non-existent entity, I expect to get the HTTP code 404, the same behaviour when implementing the blocking interface `CrudRepository`.

### Actual Behaviour

Actually, there are two different problems:
Firstly, when you try to retrieve a non-existent entity, you will get 500 Internal Server Error with the following stacktrace:
```
[pool-1-thread-4] ERROR i.m.h.s.netty.RoutingInBoundHandler - Unexpected error occurred: 
io.micronaut.data.exceptions.EmptyResultException: Query produced no result
java.util.concurrent.CompletionException: io.micronaut.data.exceptions.EmptyResultException: Query produced no result
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1702)
        at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:52)
        at io.micronaut.http.context.ServerRequestContext.lambda$instrument$0(ServerRequestContext.java:68)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)  
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)  
        at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:52)
        at io.micronaut.http.context.ServerRequestContext.lambda$instrument$0(ServerRequestContext.java:68)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

Secondly, which is the root cause, the return type of `findById` (`CompletableFuture<E>`) is wrong and should be `CompletableFuture<Optional<E>> findById(@NotNull @NonNull ID id);`. In this case it is pretty obvious that the implementation should not throw an `EmptyResultException`, but return e.g. `Optional.empty()`.

### Environment Information

- **Operating System**: Windows 10
- **Micronaut Version:** 1.2.6
- **Micronaut Data Version:** 1.0.0.M5
- **JDK Version:** OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.5+10, mixed mode)

### Example Application

https://github.com/witi83/micronaut-data-async-issue

**Comment by graemerocher** [comment]
This one requires a bug fix upstream to generics handling in Micronaut core. Other than that I am not sure about changing the default signature at this stage. I think once the upstream bug is fixed it may be better to add a new method with the alternative signature.

In the meantime you can always using `exceptionally` to handle `EmptyResultException` in your code. I have fixed the javadoc to clarify that as well https://github.com/micronaut-projects/micronaut-data/commit/cfe9b272864e5421e34af6e15139889e7a732267#diff-5ba6eae9ff8f448ebc74a1e6e8a4c876R53

**Comment by witi83** [comment]
Hey @graemerocher

Thanks for your response and your bug fix!

To be honest, IMHO I really don't believe that's the right decision. As a user I would like to be able switching implementations as easy as possible: Replace the CrudRepository, change to return-type in the controller and that's it.

The `RxJavaCrudRepository` is a perfect example (controller code: `Maybe<ComplaintDocument> get(final long id) { return repository.findById(id); }`): If the result is empty, you receive a 404, otherwise a 200.

FWIW, I see the same issue in the `ReactiveStreamsCrudRepository`.
* `ReactiveStreamsCrudRepository.findById` does not return an `Optional` as the docs states, but rather an empty array: `Publisher<ComplaintDocument> get(final long id) { return repository.findById(id); }` Additionally, if the result is non-empty, you receive an array instead of a single object. Should I open a new issue for this problem?

BR Witi

**Comment by graemerocher** [comment]
At some point once the upstream problem is resolved we can support a method variation that is `CompletableFuture<Optional<T>>`, right now that isn't doable.

As for reactive types. It is level for a `Publisher` to be empty (see `Flowable.empty()`, and `Flux.empty()`) so there is no need for a `Publisher<Optional<T>>` variant

As for receiving an array that is because the interface `Publisher` does not specify whether it is a single or many results, so the default is to assume it is many. You can add a `@SingleResult` annotate to the controller method to indicate that the result is a single.

**Comment by witi83** [comment]
Thanks again for your explanations!
