### ISSUE TITLE
Introspection @Transient tests fail with 4.20 

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-data#2638]
### Expected Behavior

see https://github.com/micronaut-projects/micronaut-data/pull/2629/commits/16a44dae5e43c80ded44d1e2d8054e9b7d21aee4

### Version

4.2.0

**Comment by richardwilko** [comment]
This is causing issues for us too. Previously we were able to override the `excludedAnnotations` field in the introspection we explicitly define on our class to be `{} `, but seems this has stopped working.
