### ISSUE TITLE
@Async function does not open a new transaction when transaction marked as required new in TransactionalEventListener

### ISSUE THREAD

**Issue by andrejBel** [micronaut-projects/micronaut-data#2656]
### Expected Behavior

I expect a new transaction to be opened when a method is anotated with
@Async
and
 @Transactional(propagation = TransactionDefinition.Propagation.REQUIRES_NEW)
 in method @TransactionalEventListener(TransactionalEventListener.TransactionPhase.AFTER_COMMIT)
 
 

### Actual Behaviour

Asynchronous thread errors with **Session/EntityManager is closed message**. Removing the **@Async** annotation prevents the error from happening but the execution is not asynchronous as desired. A new transaction shall be opened for asynchronous  thread. It worked well for Micronaut 3.*

I tried to do workaround found in
https://github.com/micronaut-projects/micronaut-data/issues/2446
but it did not help

### Steps To Reproduce

1. Run the application server from the linked
2. Make an POST request to  http://localhost:80/book with sample payload:
`{
    "name": "aa",
    "isbn": "123"
}`
3. Request finishes suceessfully
4. In the logs, you can see that the asynchronous processing fails.

Can be also reproduced by running AppTest.

### Environment Information

- Operating System: Windows 11
- Java version: 17

### Example Application

https://github.com/andrejBel/micronaut-data-async-session-after-commit-closed-problem

### Version

4.2.0

**Comment by radovanradic** [comment]
Can you try micronaut-data 4.3.1 version? It has got fix for another issue related to transaction invocation.

**Comment by andrejBel** [comment]
Hi @radovanradic . I can see that version 4.3.1 is used by project. I expilcitly set version to 4.3.1 and it did not help.

**Comment by radovanradic** [comment]
Looking at suggested workaround from #2446 event listener should be annotated with transactional and REQUIRES_NEW
```
@Transactional(propagation = TransactionDefinition.Propagation.REQUIRES_NEW)
  @EventListener
  public void exceptionOnEvent(NewBookCreatedEvent newBookCreatedEvent) {
```
so changing your example and `exceptionOnEvent` method as suggested there
```
@TransactionalEventListener(TransactionalEventListener.TransactionPhase.AFTER_COMMIT)
  @Transactional(propagation = TransactionDefinition.Propagation.REQUIRES_NEW)
  public void exceptionOnEvent(NewBookCreatedEvent newBookCreatedEvent) {
      exceptionOnTransaction(newBookCreatedEvent);
  }
```
seems to fix the issue.

**Comment by andrejBel** [comment]
@radovanradic 
it works like this:

```
@Singleton
public class BookEventListener {

  private static final Logger LOG = LoggerFactory.getLogger(BookEventListener.class);

  private final BookHistoryRepository bookHistoryRepository;

  public BookEventListener(BookHistoryRepository bookHistoryRepository) {
    this.bookHistoryRepository = bookHistoryRepository;
  }

  @Transactional(propagation = TransactionDefinition.Propagation.REQUIRES_NEW)
  @TransactionalEventListener(TransactionalEventListener.TransactionPhase.AFTER_COMMIT)
  public void exceptionOnEvent(NewBookCreatedEvent newBookCreatedEvent) {
      exceptionOnTransaction(newBookCreatedEvent);
  }

  @Async
  @Transactional(propagation = TransactionDefinition.Propagation.REQUIRES_NEW)
  protected void exceptionOnTransaction(NewBookCreatedEvent newBookCreatedEvent) {
    try {
      LOG.info("Saving into history: " + newBookCreatedEvent.bookId());
      Thread.sleep(TimeUnit.SECONDS.toMillis(5));
      bookHistoryRepository.save(new BookHistory(newBookCreatedEvent.bookId()));
      LOG.info("Saved into history: " + newBookCreatedEvent.bookId());
    } catch (Exception e) {
      LOG.error(e.getMessage(), e);
    }
  }

}
```

I had to add
`@Transactional(propagation = TransactionDefinition.Propagation.REQUIRES_NEW)`
on both methods:

`exceptionOnEvent` and `exceptionOnTransaction`

Thanks for  suggestion for workaround.

I would still suggest to fix it properly
