### ISSUE TITLE
Slow compilation

### ISSUE THREAD

**Issue by horiavmuntean** [micronaut-projects/micronaut-data#268]
Hi,

The annotation processor seems to be relative slow in generating the supporting classes.
A simple bean with many methods annotated with `@Transactional @Singleton` can take a long time to build. In my tests a bean with 400 one-line methods can take up to 40 seconds to build.

Example below:

<code>
package many;

import javax.inject.Singleton;
import javax.sql.DataSource;
import javax.transaction.Transactional;

@Singleton
@Transactional
public class Facade {
    private DataSource ds;

    public Facade(DataSource ds) {
        this.ds = ds;
    }

    public void insert1(int i) {
        System.out.println("hello" + i);
    };

    //follows insert2, insert3, .... insert400
}
</code>

It would be great to cut down this time as long compilation times are not productive.

Thank you

**Comment by horiavmuntean** [comment]
More on this, if on the side there is another bean also `@Transactional @Singleton` with only few methods, every time something changes on this bean the build process seems to analyze the big bean as well making the build process even more lengthy.

**Comment by graemerocher** [comment]
Thanks for the report. I am looking into this now. We have some inefficiencies for this case that I think can be addressed, although it requires larger changes so will likely land in 1.3

**Comment by horiavmuntean** [comment]
If I can help with anything let me know.

**Comment by graemerocher** [comment]
I have been working on this, the changes are not ready for the prime time yet but it is happening on this branch https://github.com/micronaut-projects/micronaut-core/tree/annotation-metadata-optimization

I have cut the numbers of classes generated significantly and ops/s goes from `0.043 ops/sec` to `3.136 ops/s` which is a significant improvement. The branch is still broken for some cases so still needs time to stabilize

**Comment by graemerocher** [comment]
Compiler performance improvements have been included in 1.3 master of `micronaut-core`
