### ISSUE TITLE
AbstractCriteriaBuilder#function() not Supported

### ISSUE THREAD

**Issue by elzayakm** [micronaut-projects/micronaut-data#2693]
### Feature description

I would like to be able to build queries with JSON functions supported by my DB with Micronaut's `QueryBuilder`.

My repository implements the `CoroutineJpaSpecificationExecutor` and is configured to use the `JpaQueryBuilder`class, as shown in the code snippet below.

```
@Repository
@RepositoryConfiguration(queryBuilder = JpaQueryBuilder::class)
interface ScheduledUpdateRepository : CoroutinePageableCrudRepository<X, Long>, CoroutineJpaSpecificationExecutor<X>
```

To do this, I need the `function()` method which is obviously not supported yet as shown in the code snippet below taken from the `AbstractQueryBuilder` class.

```
    @Override
    @NonNull
    public <T> Expression<T> function(@NonNull String name, @NonNull Class<T> type, @NonNull Expression<?>... args) {
        throw notSupportedOperation();
    }
```
If any additional info is required, please reach out to me on kareem.elzayat@uberall.com. Thanks!

**Comment by elzayakm** [comment]
@dstepanov is it possible that this ticket gets prioritized? My team is building a feature that will highly depend on this method.

**Comment by dstepanov** [comment]
Sure, it should use Hibernate's criteria builder in this case.

**Comment by elzayakm** [comment]
Do you have an example on how to use it? I am not able to get my Micronaut app configured to use it instead of the `RuntimeCriteriaBuilder`.

**Comment by dstepanov** [comment]
For now, you can inject `JpaRepositoryOperations` and use `getEntityManagerFactory`, `getEntityManagerFactory` to build queries. I will try to fix it to be used in the repositories for the next release.

**Comment by elzayakm** [comment]
Cool then! I prefer to wait for your release so that we don't pollute our code. Thanks a lot for your help!

I will follow-up regarding the status of this within two weeks after the new year. Is that ok?

**Comment by dstepanov** [comment]
Yes, looking to fix it in 4.3.0 https://github.com/micronaut-projects/micronaut-core/discussions/10137

**Comment by elzayakm** [comment]
Awesome! Thanks a lot!

**Comment by kareemelzayat** [comment]
Hello @dstepanov, reaching out again regarding this. You told me you were looking to fix it in 4.3.0 released today. Still, I see that the method still throws an `UnsupportedExcpetion`.  Are there any updates?

Thank you, and best regards 🙏

**Comment by dstepanov** [comment]
If you use Hibernate it should use the criteria builder from it.

**Comment by radovanradic** [comment]
Not sure if that fix is released yet, maybe can try with the 4.4.1-SNAPSHOT?

**Comment by kareemelzayat** [comment]
My repository extends the CoroutineJpaSpecificationExecutor, which allows implementations of the `PredicateSpecification` and `QuerySpecification` interfaces only. Those interfaces are always intercepted by the `AbstarctSpecificationInterceptor`, which I believe does NOT use the HibernateCriteriaBuilderDelegate, rather the AbstractCriteriaBuilder; which is what I am reporting in this ticket.

**Comment by voronaam** [comment]
Does anybody have a working example of using a different criteria builder? We are not using Hibernate and trying to work with JSONB in postgresql. So I either need to figure out how to use custom operator `->` or function `jsonb_extract_path`

Since we have no Hibernate, the `AbstractCriteriaBuilder` is the only implementation I see on my class path.

I would very much appreciate a way to call a custom operator or a function. Please help.

Trying to add `io.micronaut.data:micronaut-data-jpa` library and injecting `JpaRepositoryOperations` to get a different criteria builder via `jpaRepositoryOperations.getEntityManagerFactory().getCriteriaBuilder()` only lead to this error:

```
No bean of type [io.micronaut.data.jpa.operations.JpaRepositoryOperations] exists.
```

**Comment by dstepanov** [comment]
I will take a look to support custom functions

**Comment by varvay** [comment]
This is pretty bad, even such simple operation like concat, coalesce, lower and upper aren't supported yet by the `AbstractCriteriaBuilder`. Luckily in my case, I was able to fulfil my need for "case-insensitive like" operation using the `ilikeString` method, but I believe sooner or later, these operations will be demanded, since not everyone are using Hibernate. I hope these operations will be available soon.

**Comment by dstepanov** [comment]
I'm working on a query builder rewrite that should enable the quick addition of more criteria features.

Please create an additional issue of what operations are needed to assess what is wanted.

**Comment by varvay** [comment]
Sure @dstepanov I've opened a feature request issue in #2975.

**Comment by dstepanov** [comment]
Already supported in the latest version

**Comment by elzayat-qr** [comment]
@dstepanov I think I am facing a similar issue on a new project I am working on using Micronaut Hibernate Reactive; The `CriteriaQuery` interface is defaulting to the `RuntimePersistentEntityCriteriaQuery` implementation, when it is expected to default to Hibernate's `SqmSelectStatement` implementation.

This leads to a method like `Subquery::correlate` throwing a NotSupportedOperation Exception.

Would you like me to create a new issue?

CC @radovanradic

**Comment by dstepanov** [comment]
Sure

**Comment by elzayat-qr** [comment]
@dstepanov here you go: https://github.com/micronaut-projects/micronaut-data/issues/3641
