### ISSUE TITLE
countDistinct() not working

### ISSUE THREAD

**Issue by elzayakm** [micronaut-projects/micronaut-data#2695]
### Expected Behavior

If query.distinct(true) is used, I am expecting the count query to be count(distinct(...)) instead of count(...).

### Actual Behaviour

From `AbstractSpecificationInterceptor.java`. Notice the never changing `criteriaQuery.select(criteriaBuilder.count(root))`; It should be `criteriaQuery.select(criteriaBuilder.countDistinct(root)))` if `query.isDistinct()`

```
    private <E> StoredQuery<E, ?> buildCount(MethodInvocationContext<T, R> context, QueryBuilder sqlQueryBuilder) {
        StoredQuery<E, ?> storedQuery;
        Class<E> rootEntity = getRequiredRootEntity(context);
        QuerySpecification<E> specification = getQuerySpecification(context);
        PersistentEntityCriteriaQuery<Long> criteriaQuery = criteriaBuilder.createQuery(Long.class);
        Root<E> root = criteriaQuery.from(rootEntity);

        if (specification != null) {
            Predicate predicate = specification.toPredicate(root, criteriaQuery, criteriaBuilder);
            if (predicate != null) {
                criteriaQuery.where(predicate);
            }
        }
        criteriaQuery.select(criteriaBuilder.count(root));
        QueryResult queryResult = ((QueryResultPersistentEntityCriteriaQuery) criteriaQuery).buildQuery(sqlQueryBuilder);
        storedQuery = QueryResultStoredQuery.count(context.getName(), context.getAnnotationMetadata(), queryResult, rootEntity);
        return storedQuery;
    }
```

### Version

4.2

**Comment by dstepanov** [comment]
@radovanradic Can you please take a look?

**Comment by radovanradic** [comment]
Sure

**Comment by radovanradic** [comment]
@elzayakm Just to ask, you said: ```If query.distinct(true) is used```. Can you provide a test with what are you trying to do?

**Comment by elzayakm** [comment]
Hello @radovanradic,

So here is my `Specification` which I use along with a `Pageable` interface to get paginated results:

```
class MySpecification(private val idsList: List<Long>) : QuerySpecification<MyEntity> {
   override fun toPredicate(
        root: Root<MyEntity>,
        query: CriteriaQuery<*>,
        criteriaBuilder: CriteriaBuilder
    ): Predicate {
        val isCountQuery: Boolean = query.resultType == Long::class.javaObjectType
        val join: ListJoin<MyEntity, MyEntityChildren> = if (isCountQuery) {
            query.distinct(true)
            root.joinList("children")
        } else {
            root.joinList("children", JoinType.INNER)
        }
        
        normalizedScheduledUpdates.get<Long>("id").`in`(idsList)
```
This results in two queries as expected: one to get results, one to count result (to get the total count for pagination).

While everything is ok with the results query (I don't use distinct() there because it returns correct results without it); the count query is the following:

```select count(s1_0.id) from my_entity s1_0 join my_entity_children n1_0 on s1_0.id=n1_0.parent_id where n1_0.id in (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) limit ?```
which results in a wrong total count; e.g. 10 instead of 7.


The expected query should be:
```select count(distinct(s1_0.id)) from my_entity s1_0 join my_entity_children n1_0 on s1_0.id=n1_0.parent_id where n1_0.id in (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) limit ?```
