### ISSUE TITLE
After upgrade Micronaut version can't compile project - unable to implement Repository method for projection Entity with embedded ID

### ISSUE THREAD

**Issue by alapierre** [micronaut-projects/micronaut-data#2705]
### Expected Behavior

project should compile and runs like in MN 4.1.3

### Actual Behaviour

I upgraded Micronaut from 4.1.3 to 4.2.2 and my project stop compile with error:

```
Unable to implement Repository method: InvoiceRepository.findByTimestampBetween(OffsetDateTime from,OffsetDateTime to,Pageable pageable). Cannot apply a column alias: id with expanded property: io.micronaut.data.model.PersistentAssociationPath@64918740
```

method looks like that:

```
Page<SalesInvoiceShortDto> findByTimestampBetween(OffsetDateTime from, OffsetDateTime to, Pageable pageable);
```

and it use projections from Entity class to DTO. Entity has composite EmbeddedId key `InvoiceId`

```
@Data
@Embeddable
@Builder
public class InvoiceId implements Serializable {

    @Size(max = 256)
    @NotEmpty
    private String number;

    @Size(max = 15)
    @NotEmpty
    private String nip;

    @Tolerate
    public InvoiceId() {
    }
}
```

SalesInvoiceShortDto
```
@Introspected
@Value
public class SalesInvoiceShortDto {

    InvoiceId id;

    OffsetDateTime timestamp;

    OffsetDateTime lastUpdated;

    ProcessingStatusEnum processingStatus;

    String invoiceReferenceNumber;

    @Nullable
    String ksefNumber;

    @Nullable
    OffsetDateTime acquisitionTimestamp;

    @Nullable
    String buyerIdentifier;

    @Nullable
    String buyerName;
```

Invoice
```
@Entity
@Data
@Builder
@DynamicUpdate
class Invoice implements Serializable {

    @Tolerate
    public Invoice() {
    }

    @EmbeddedId
    private InvoiceId id;

...
```

When I remove `InvoiceId id` property from `SalesInvoiceShortDto` it works - but it is not what I want to do...

### Environment Information

JDK 17

### Version

4.2.2

**Comment by radovanradic** [comment]
Looks like introduced here https://github.com/micronaut-projects/micronaut-data/pull/2495 with DTO association support

**Comment by radovanradic** [comment]
@alapierre Can you please submit simple app that reproduces the error?
I have tried to reconstruct the app from the classes you pasted 
[mn-data-dto-projection.zip](https://github.com/micronaut-projects/micronaut-data/files/13951689/mn-data-dto-projection.zip)
but I am not getting compiler error. Apparently it is missing something, so please take a look and if possible reupload app that reproduces the error. Thanks

**Comment by alapierre** [comment]
yest, sure. I will prepare demo app for you.

**Comment by radovanradic** [comment]
Ok, I was able to reproduce. It happens with `@Repository` and not with `@JdbcRepository` it seems.

**Comment by alapierre** [comment]
after upgrading to Micronaut to `4.3.1` I've got the same error in different place

````
Unable to implement Repository method: InvoiceRepository.findBySessionIdAndIdTenant(String sessionId,String tenant). Cannot apply a column alias: id with expanded property: io.micronaut.data.model.PersistentAssociationPath@f6aa60a
````

Repository method:

````
@Repository
public interface InvoiceRepository extends CrudRepository<Invoice, InvoiceId> {

    List<InvoiceIdocId> findBySessionIdAndIdTenant(String sessionId, String tenant);

....
}
````

````
@Value
@Introspected
public class InvoiceIdocId {

    InvoiceId id;
    String idocId;

}
````

Embedded Id:

````
@Data
@Embeddable
@Builder
@AllArgsConstructor
public class InvoiceId implements Serializable {


    @Size(max = 64)
    @NotEmpty
    private String tenant;

    @Size(max = 256)
    @NotEmpty
    private String number;
````

````
@Entity
@Data
@Builder
public class Invoice {
    @EmbeddedId
    private InvoiceId id;

....

````

The workaround is to use old fason new operator in query

**Comment by alapierre** [comment]
yes, workaround is only to solve problem now. Let me know if I can help with that in any way. Thank you.
