### ISSUE TITLE
Joined entities are not loaded

### ISSUE THREAD

**Issue by lmachacek** [micronaut-projects/micronaut-data#2706]
### Expected Behavior

Joined entities should be loaded.

### Actual Behaviour

See the example project https://github.com/lmachacek/micronaut-joined-entity

There is a relation defined by column `organization_id` in table `tenants`, which references record in
table `organizations` with primary key `id`. 
In Kotlin entity `Organization` has a field `tenants`, which defines _OneToMany_ relation with _EAGER_ fetch type. When the `Organization` and `Tenant` entities are saved, then when loading the `Organization` entity it should have set of related tenants loaded in the `tenants` field.

The last version of Micronaut where the example is working is 3.6.6 and in any other higher version it fails, where the
problem is that joined entities are not loaded. 

I also tried it with the latest Micronaut 4.2.2 (branch 4-2-2 in the example project) and it also does not load joined entities.

We would like to upgrade to more recent version of Micronaut but this blocks us.

Thank you for any help.

### Steps To Reproduce

1. Execute test by `./gradlew clean test --info` and the test is successful.
2. Switch branch `git checkout upgrade` to use more recent Micronaut.
3. Execute the test again `./gradlew clean test --info` and it fails.

### Environment Information

- OS: Fedora 38 
- JDK: openjdk 17.0.9

### Example Application

https://github.com/lmachacek/micronaut-joined-entity

### Version

3.7 and any other higher

**Comment by radovanradic** [comment]
Looks like it is broken in 3.7.4, maybe this PR https://github.com/micronaut-projects/micronaut-data/pull/1707

**Comment by radovanradic** [comment]
Or https://github.com/micronaut-projects/micronaut-data/pull/1723 because when I add `transactional = false` to the test then it is passing.

**Comment by lmachacek** [comment]
Thank you for very quick response. It seems that the problem is only in tests and not in runtime, so I added `transactional = false` in all failing tests and now everything is green.

It would be probably good to document that behavior in Micronaut documentation/guides.

**Comment by dstepanov** [comment]
Not sure why is that happening. You can use pure Hibernate and see if it's the Hibernate-specific behavior.

**Comment by radovanradic** [comment]
> Not sure why is that happening. You can use pure Hibernate and see if it's the Hibernate-specific behavior.

After changes in data-tx 3.7.3->3.7.4 something has changed in behavior. When organization entity is saved in hibernate it keeps cached in session (without tenants). Tenants are saved later and when findById for organization repository is called then an entity present in the session is returned, without fetching tenants collection because entity is found in session. When transactional is false, then entity is not present in the session. Not sure about whole flow and whether we can fix that, or just add a note about testing in hibernate.

**Comment by radovanradic** [comment]
Added one line to the docs about testing in this PR https://github.com/micronaut-projects/micronaut-data/pull/2728
and closing this since no other code changes needed at the moment.
