### ISSUE TITLE
Limit is not applied when using @Query annotation in Kotlin

### ISSUE THREAD

**Issue by steventen** [micronaut-projects/micronaut-data#2727]
### Expected Behavior

It should return number of records based on the `limit` specified in the sql query.

### Actual Behaviour

Only 1 record is returned no matter what number is set in the `limit`

### Steps To Reproduce

I have created a github repo to reproduce the issue: https://github.com/steventen/micronaut-data-sql-query-bug

To reproduce:
1. Start the database through docker: `docker-compose up`
2. Run server: `./gradlew run`
3. Visit the endpoint: [http://localhost:8080/companies](http://localhost:8080/companies)

It only returns 1 record.

More details:

The endpoint calls the `getAllLimit` method in the `CompanyRepository` to get a list of companies.

The getAllLimit uses `@Query` annotation with a sql query like this:

```kotlin
@Query(
    """
    select
        v_sum.org_id,
        v_sum.company_name as name,
        v_sum.value,
        rank() over (order by v_sum.value desc) as value_rank
    from (
        select v.org_id, v.company_name, sum(v.company_value) as value
        from companies v
        where
            v.org_id = :orgId
            and v.process_date >= :from
            and v.process_date <= :to
            group by v.org_id, v.company_name
    ) v_sum order by value_rank limit :limit
"""
)
fun getAllLimit(orgId: String, from: LocalDate, to: LocalDate, limit: Int = 5): List<Company>
```
Which basically sums the value in `company_value` column, then do a `rank()`, and return the top 5 in the rank.

The sample data lives in the [init.sql](https://github.com/steventen/micronaut-data-sql-query-bug/blob/main/config/init.sql)

Based on the log, I can see the query is fired with correct parameters. But not sure why it just always return only 1 record.

Note that the same code has been working in previous versions like v4.1.x

### Environment Information

- JDK 17

### Example Application

https://github.com/steventen/micronaut-data-sql-query-bug

### Version

4.2.3

**Comment by radovanradic** [comment]
There have been changes how results are read in 4.2.0 and it may or may not need to be fixed, but this is some specific case and this result returns some data that does not really fit into the entity that is used. Here are the results
```
org_id     name                value       value_rank
"abc"	"company c"	300.03	1
"abc"	"company d"	200.02	2
"abc"	"company a"	100.01	3
"abc"	"company b"	100.01	3
"abc"	"company e"	100.01	3
```
so these records all have the same id. Better solution might be to return results into DTO like this:
```
@Serdeable
data class CompanyDto(

    val name: String,

    val value: BigDecimal?,

    val valueRank: Int
)
```
since org_id for this repo method will be the same, DTO does not need it and then if you change repo method and controller to return `CompanyDto` instead of `Company` it would return appropriate number of recrods.

**Comment by steventen** [comment]
Interesting, so the new change seems to be stricter on the uniqueness of the id for the entity since 4.2. Just curious, is there any benefit to this change?

For our real use case, we don't really have an id column for each table, since most of them are aggregated analytic data. We specified the `@Id` to bypass the primary key requirement and it's been working fine.

I guess we will have to either migrate to use the DTO projection as you mentioned, or EmbededId on multiple columns.

**Comment by radovanradic** [comment]
Not sure, probably was code improvement done in https://github.com/micronaut-projects/micronaut-data/pull/2495 but from this example, looks like we might get into similar issues if result returns entities with same ids.
Maybe that's not real use case for us, not sure, but definitely for this example a DTO is way to go to return query result.

**Comment by dstepanov** [comment]
Your case is a bit strange; the field you marked as an ID is not actually an ID of the company but an organization. By definition, entities are usually identical if the ID matches.

**Comment by steventen** [comment]
yeah, the Id is just unnecessary to our use case. In our case, it is mostly just a simple data mapping from data source to entity or different DTOs. And there're only read/select actions, no update or delete.

I think we will just try to use DTO projection in our case as @radovanradic  suggested. On the other hand, I do wish the Id could be optional, and then the Entity could just be used as the default DTO 😄
