### ISSUE TITLE
parameter binding for countby Query for expandable types in where clause

### ISSUE THREAD

**Issue by rupimunjal** [micronaut-projects/micronaut-data#2739]
### Expected Behavior

The parameter binding for expandable types in where clause for a countBy query should happen correctly.  it is happening correctly for the findBy query where the prepared statement is created for expandable types. 

### Actual Behaviour

JPA Query:findBySourceInListAndProcessingStatusInListAndRetryCountGreaterThanEquals

 Executing Query: SELECT incident_event_."id",incident_event_."record_id",incident_event_."event_id",incident_event_."transaction_type",incident_event_."transaction_amount",incident_event_."service_response_code",incident_event_."source",incident_event_."processing_status",incident_event_."retry_count",incident_event_."create_timestamp",incident_event_."update_timestamp",incident_event_."event_timestamp" FROM "incident_event" incident_event_ WHERE (incident_event_."source" IN (?,?) AND incident_event_."processing_status" IN (?,?) AND incident_event_."retry_count" >= ?)
[TRACE] 2024-01-03 11:36:27,923 pool-1-thread-1 io.micronaut.data.query - {} - Binding parameter at position 1 to value XYZ with data type: STRING
[TRACE] 2024-01-03 11:36:27,923 pool-1-thread-1 io.micronaut.data.query - {} - Binding parameter at position 2 to value ABC with data type: STRING
[TRACE] 2024-01-03 11:36:27,924 pool-1-thread-1 io.micronaut.data.query - {} - Binding parameter at position 3 to value REPUBLISHING with data type: STRING
[TRACE] 2024-01-03 11:36:27,924 pool-1-thread-1 io.micronaut.data.query - {} - Binding parameter at position 4 to value NOT_PROCESSED with data type: STRING
[TRACE] 2024-01-03 11:36:27,924 pool-1-thread-1 io.micronaut.data.query - {} - Binding parameter at position 5 to value 2 with data type: INTEGER

countBySourceInListAndProcessingStatusInListAndRetryCountGreaterThanEquals

Executing Query: SELECT COUNT(*) FROM "incident_event" incident_event_ WHERE (incident_event_."source" IN (?) AND incident_event_."processing_status" IN (?) AND incident_event_."retry_count" >= ?)
[TRACE] 2024-01-03 13:37:05,377 pool-1-thread-1 io.micronaut.data.query - {} - Binding parameter at position 1 to value XYZ with data type: STRING
[TRACE] 2024-01-03 13:37:05,378 pool-1-thread-1 io.micronaut.data.query - {} - Binding parameter at position 2 to value ABC with data type: STRING
[TRACE] 2024-01-03 13:37:05,378 pool-1-thread-1 io.micronaut.data.query - {} - Binding parameter at position 3 to value REPUBLISHING with data type: STRING
[TRACE] 2024-01-03 13:37:05,378 pool-1-thread-1 io.micronaut.data.query - {} - Binding parameter at position 4 to value NOT_PROCESSED with data type: STRING
[DEBUG] 2024-01-03 13:37:05,401 pool-1-thread-1 io.micronaut.data.connection.jdbc.operations.DefaultDataSourceConnectionOperations - {} - Setting JDBC Connection [HikariProxyConnection@1671707188 wrapping org.postgresql.jdbc.PgConnection@552fee7a] read-only [false]
[ERROR] 2024-01-03 13:37:05,406 pool-1-thread-1 paydata.recon.api.application.service.PaymentRetryService - {} - Failed to fetch StuckEvents from Database , exception:io.micronaut.data.exceptions.DataAccessException: Unable to set PreparedStatement value: The column index is out of range: 4, number of columns: 3.
	at io.micronaut.data.jdbc.mapper.JdbcQueryStatement.newDataAccessException(JdbcQueryStatement.java:325)
	at io.micronaut.data.jdbc.mapper.JdbcQueryStatement.setString(JdbcQueryStatement.java:214)
	at io.micronaut.data.jdbc.mapper.JdbcQueryStatement.setString(JdbcQueryStatement.java:37)
	at io.micronaut.data.runtime.mapper.QueryStatement.setDynamic(QueryStatement.java:76)
	at io.micronaut.data.jdbc.mapper.JdbcQueryStatement.setDynamic(JdbcQueryStatement.java:114)
	at io.micronaut.data.jdbc.mapper.JdbcQueryStatement.setDynamic(JdbcQueryStatement.java:37)
	at io.micronaut.data.runtime.operations.internal.sql.AbstractSqlRepositoryOperations.setStatemenXYZrameter(AbstractSqlRepositoryOperations.java:269)
	at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.access$1100(DefaultJdbcRepositoryOperations.java:139)
	at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations$JdbcParameterBinder.bindOne(DefaultJdbcRepositoryOperations.java:1058)
	at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations$JdbcParameterBinder.bindMany(DefaultJdbcRepositor

### Steps To Reproduce

At one time use a findBy query with expandables in the where clause. At the other time use countBy query with expandables

### Environment Information

Mac Ventura 13.6.1
JDK 17

### Version

3.9.0

**Comment by radovanradic** [comment]
Reproducible in latest too, investigating.
