### ISSUE TITLE
`FindPageSpecificationInterceptor`: `countDistinct` not working

### ISSUE THREAD

**Issue by kareemelzayat** [micronaut-projects/micronaut-data#2764]
### Expected Behavior

If `query.distinct(true)` is used, I am expecting the count query to be `count(distinct(...))` instead of `count(...)`.

### Actual Behaviour

From `FindPageSpecificationInterceptor.java`. Notice line 110 which builds the count query as part of a findPage method call. It always call `countQuery.select(criteriaBuilder.count(countRoot))`; Instead, it should be `countQuery.select(criteriaBuilder.countDistinct(countRoot))` if `query.isDistinct()`.

Ironically, the query generated is `select distinct count(entity.id) from entity_class entity...` Notice the `distinct` keywords just after the `select` and before the actual `count`.

Check the screenshot below for reference

The issue is very similar to https://github.com/micronaut-projects/micronaut-data/issues/2695

![Screenshot 2024-01-30 at 09 07 23](https://github.com/micronaut-projects/micronaut-data/assets/22935087/ab8ea274-af9f-4488-a0e9-f8cbb83b41aa)

![Screenshot 2024-01-30 at 09 10 12](https://github.com/micronaut-projects/micronaut-data/assets/22935087/277e157d-d6ec-49c1-920d-c3dbfa57e69a)

### Version

Micronaut Data 4.5.0

**Comment by radovanradic** [comment]
First `distinct` in the query is because of `query.distinct(true)` and this is delegated to Hibernate so their query engine will apply distinct for selection, even for count. It won't be an issue if we apply fix and do `count distinct`.
