### ISSUE TITLE
`CoroutineJpaSpecificationExecutor` does not accept `Specification`

### ISSUE THREAD

**Issue by kareemelzayat** [micronaut-projects/micronaut-data#2765]
### Expected Behavior

Using kotlin and Micronaut JPA, I would expect to be able to use the `Specification` interface with the `CoroutineJpaSpecificationExecutor`.

__

### Actual Behaviour

`CoroutineJpaSpecificationExecutor` only accepts `PredicateSpecification` and `QuerySpecification` which do not behave well with Micronaut JPA because of https://github.com/micronaut-projects/micronaut-data/issues/2763.

It is also impossible, according to the current configuration, to alter the interface in the `io.micronaut.data.repository.jpa.kotlin` package to include `Specification` of the `io.micronaut.data.jpa.repository.criteria` package.

### Version

Micronaut Data 4.5.0

**Comment by kareemelzayat** [comment]
To be honest, I am not even sure why we have that `Specification` interface. Wouldn't the `QuerySpecification` be adequate to replace it?

**Comment by dstepanov** [comment]
Yes, but `Specification` used `Javax` before Hibernate switched to Jakarta annotations and `QuerySpecification` was introduced to be used with Jakarta criteria for Micronaut Data JDBC / R2DBC etc.
We should deprecate `Specification` as there is an alternative to it.

**Comment by kareemelzayat** [comment]
Agreed! We just need to make sure that `QuerySpecification` is completely compatible with Micronaut Data JPA/Hibernate as well.

**Comment by dstepanov** [comment]
I think this can be closed
