### ISSUE TITLE
Query  projection will failed if the length of entity member name >= 8

### ISSUE THREAD

**Issue by shawnone** [micronaut-projects/micronaut-data#278]
### Steps to Reproduce

1. Create a member with long name(>=8)  in entity class 
```
@MappedEntity
public class Movie {
    @Id
    private int id;
    private String publishId;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getPublishId() {
        return publishId;
    }

    public void setPublishId(String publishId) {
        this.publishId = publishId;
    }
}
```
2. Projection query in repository
```
@JdbcRepository(dialect= Dialect.MYSQL)
public interface MovieRepository extends CrudRepository<Movie, Integer> {
    Optional<String> findPublishIdById(int id);
}
```
3. Build

### Expected Behaviour

Build success

### Actual Behaviour
Error message:

> Unable to implement Repository method: MovieRepository.findPublishIdById(int id). Cannot project on non-existent property d

### Environment Information

- **Operating System**: Mac OS 10.15.1
- **Micronaut Version:** 1.0.0.M5
- **JDK Version:** 11

**Comment by graemerocher** [comment]
Thanks!
