### ISSUE TITLE
Documentation section "Build Configuration" is not correct w.r.t. JPA.

### ISSUE THREAD

**Issue by ysb33r** [micronaut-projects/micronaut-data#280]
### User experience

I implemented a Micronaut app with Micronaut Data & jpa. However I got the following error

```
Message: Missing bean argument value: transactionOperations
Path Taken: new HibernateJpaOperations(SessionFactory sessionFactory,[TransactionOperations transactionOperations],ExecutorService executorService)
io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [io.micronaut.data.hibernate.operations.HibernateJpaOperations]
```

I appears that I had 

```
    implementation "io.micronaut.configuration:micronaut-hibernate-jpa"
    implementation "io.micronaut.data:micronaut-data-hibernate-jpa:${micronautDataVersion}"
```

in my `build.gradle` file. Having remove the first line, the problem disappeared.

The reason why I had it like that in the first place is that the documentation states _Once this is in place if you wish to use Hibernate / JPA you must include the dependency on the_ `micronaut-data-hibernate-jpa` and `micronaut-hibernate-jpa` _module_

![image](https://user-images.githubusercontent.com/907624/69347015-1669e600-0c74-11ea-9701-dff9e5fbc753.png)

### Expected

Either the documentation is wrong, so maybe just drop the wording? (Hopefully this is not an actual bug).

**Comment by sjivan** [comment]
I ran into the same issue. As noted, removing the "io.micronaut.configuration:micronaut-hibernate-jpa" dependency resolves the issue.
