### ISSUE TITLE
Referential integrity constraint violation occurs during storing object with many to many relation.

### ISSUE THREAD

**Issue by WIERZMA1** [micronaut-projects/micronaut-data#2809]
### Expected Behavior

I created simple service to handle book entities from Google Books API.
Book entities have relations many to many with Author and Category entities.
I want to be able to make CRUD operations on these entities.

### Actual Behaviour

When I try to store Book entity a "Referential integrity constraint violation" occurs.
I used the same setup in different repository build with Spring framework (https://github.com/WIERZMA1/Spring-Book-Manager) which works for me without issues.

Many to many implementation in Book (owning) enitity:
```
@Fetch(FetchMode.SELECT)
    @ManyToMany(fetch = FetchType.EAGER, cascade = {CascadeType.DETACH, CascadeType.MERGE, CascadeType.PERSIST, CascadeType.REFRESH})
    @JoinTable(
            name = "books_authors",
            joinColumns = @JoinColumn(name = "author_name"),
            inverseJoinColumns = @JoinColumn(name = "book_id")
    )
    private Set<Author> authors;
```

Mamy to many implmentation in Author entity:
```
@ManyToMany(fetch = FetchType.EAGER, mappedBy = "authors", targetEntity = Book.class)
    @Column(name = "books")
    private Set<Book> booksList;
```

### Steps To Reproduce

1. Run application from this repo: https://github.com/WIERZMA1/Micronaut-Book-Manager
2. Try to post Book entity under: http://localhost:8080/api/v1/book
3. Example Book entity:
```
    {
        "id": "1234567890123",
        "title": "Some title",
        "subtitle": "Some subtitle",
        "publisher": "MW",
        "publishedDate": "2024",
        "description": "Some description",
        "pageCount": 1000000,
        "thumbnailUrl": "http://mw.com",
        "language": "pl",
        "previewLink": "http://mw.com/preview",
        "rating": 5.0,
        "authorsIds": [
            "WIERZMA"
        ],
        "categoriesIds": [
            "Stuff"
        ]
    }
```

### Environment Information

- Operating system: Windows 10
- JDK: 21
- Micronaut version: 4.3.1
- Micronaut data version: 4.6.2

### Example Application

https://github.com/WIERZMA1/Micronaut-Book-Manager

### Version

4.3.1

**Comment by roar-skinderviken** [comment]
After starting your app, table AUTHORS contains no records, hence I believe the referential integrity constraint violation is valid unless you're populating your db manually before running the post request.

I'll recommend you to write tests about the issue.

I'm not a member of the MN-team.

Changes made for accessing the H2 console on http://localhost:8082/:

In Application.java:
```
package org.book.manager;

import io.micronaut.runtime.Micronaut;
import org.h2.tools.Server;

public class Application {

    public static void main(String[] args) throws Exception {
        Server.createWebServer().start();
        Micronaut.run(Application.class);
    }
}
``

In POM:
```
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
        </dependency>
```

**Comment by radovanradic** [comment]
Looks like you have mapped `JoinTable` and `inverseJoinColumns` incorrectly (at least not matching with flyway schema).
Try changing this 
```
@Fetch(FetchMode.SELECT)
    @ManyToMany(fetch = FetchType.EAGER, cascade = {CascadeType.DETACH, CascadeType.MERGE, CascadeType.PERSIST, CascadeType.REFRESH})
    @JoinTable(
            name = "books_authors",
            joinColumns = @JoinColumn(name = "book_id"),
            inverseJoinColumns = @JoinColumn(name = "author_name")
    )
    private Set<Author> authors;

    @Fetch(FetchMode.SELECT)
    @ManyToMany(fetch = FetchType.EAGER, cascade = {CascadeType.DETACH, CascadeType.MERGE, CascadeType.PERSIST, CascadeType.REFRESH})
    @JoinTable(
            name = "books_categories",
            joinColumns = @JoinColumn(name = "book_id"),
            inverseJoinColumns = @JoinColumn(name = "category_name")
    )
    private Set<Category> categories;
```
Here is similar example https://www.javaguides.net/2023/07/jpa-jointable-annotation.html

**Comment by WIERZMA1** [comment]
@radovanradic - ahh, I must have missed that... 🤦‍♂️ That solution combined with Flyway fix the flow, thank you very much! 😄
