### ISSUE TITLE
Same ID entities are not returned by @Query

### ISSUE THREAD

**Issue by balapal** [micronaut-projects/micronaut-data#2842]
### Expected Behavior

This should return two books, especially when it is mapped to a DTO and not an entity

```
package micronaut.reproduce;

import io.micronaut.data.annotation.Query;
import io.micronaut.data.model.query.builder.sql.Dialect;
import io.micronaut.data.r2dbc.annotation.R2dbcRepository;
import io.micronaut.data.repository.reactive.ReactiveStreamsCrudRepository;

import io.micronaut.data.annotation.Id;
import io.micronaut.data.annotation.MappedEntity;
import io.micronaut.serde.annotation.Serdeable;
import reactor.core.publisher.Flux;

@R2dbcRepository(dialect = Dialect.H2)
public interface BookRepository extends ReactiveStreamsCrudRepository<Book, Integer> {
    @Query("""
            SELECT 1 AS id, 'Title #1' AS title
            UNION ALL
            SELECT 1 AS id, 'Title #2' AS title
            """)
    Flux<Book> getBooks();

    @Query("""
            SELECT 1 AS id, 'Title #1' AS title
            UNION ALL
            SELECT 1 AS id, 'Title #2' AS title
            """)
    Flux<BookDto> getBooksAsDto();
}


@Serdeable
@MappedEntity
public class Book {

    @Id
    private Integer id;
    private String title;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }
}

@Serdeable
public record BookDto(
        Integer id,
        String title
) {
}
```

The following test passes on micronaut-parent 4.2.4 and fails with micronaut 4.3.x

```
package micronaut.reproduce;

import io.micronaut.test.extensions.junit5.annotation.MicronautTest;
import jakarta.inject.Inject;
import org.junit.jupiter.api.Test;
import reactor.test.StepVerifier;

import static org.junit.jupiter.api.Assertions.assertEquals;

@MicronautTest(transactional = false)
class BookRepositoryTest {
    @Inject
    private BookRepository bookRepository;

    @Test
    void testGetBooks() {
        StepVerifier.create(bookRepository.getBooks())
                .assertNext(book -> assertEquals("Title #1", book.getTitle()))
                .assertNext(book -> assertEquals("Title #2", book.getTitle()))
                .verifyComplete();
    }

    @Test
    void testGetBooksDto() {
        StepVerifier.create(bookRepository.getBooksAsDto())
                .assertNext(book -> assertEquals("Title #1", book.title()))
                .assertNext(book -> assertEquals("Title #2", book.title()))
                .verifyComplete();
    }
}

```

### Actual Behaviour

When upgrading to micronaut-parent 4.3.x the following query will no longer return two rows

### Steps To Reproduce

See the example project at https://github.com/balapal/micronaut-query-result-issue

### Environment Information

Windows
JDK 17

### Example Application

https://github.com/balapal/micronaut-query-result-issue

### Version

4.3.6

**Comment by radovanradic** [comment]
This is similar to the issue https://github.com/micronaut-projects/micronaut-data/issues/2727, please look at comments there.
Basically, an entity (or dto representing entity) is identified with the id and can't have more than one instance with the same id.

**Comment by balapal** [comment]
Thanks @radovanradic.
I understand that for an entity it makes sense.
But in my example I have a the BookDto which happen to have a field called id which is the same as the `@Id` field in the `@MappedEntity Book`.
So I think it is an unwanted side effect.
To represent the issue I updated the example application with `BookDto2` where I called the column `id_renamed`, so for that Dto I get two rows back.

**Comment by balapal** [comment]
Also I wonder if there is a way to use the `@Query` annotation without implementing even a `@GenericRepository`.
Cause we have a use case where we don't use any of the capabilities of the Repository, just need some custom queries that we implement using `@Query`

**Comment by radovanradic** [comment]
There is no much use of `@Query` if you wouldn't use it through repository operations I suppose, then can just implement custom jdbc/r2dbc repository and execute queries you need and fetch data manually using jdbc/r2dbc api.

**Comment by balapal** [comment]
We use `@Query`, because:
- no need to deal with the underlying connection and participation in the correct transaction
- queries with lots of parameters are bound automatically based on parameter names
- Type mapping: For example we use `@TypeDef(type = DataType.STRING_ARRAY) Set<String> references` to map it to an `ref_column = ANY(:references)`

**Comment by balapal** [comment]
But back to my original point.
It is fine that for the `@MappedEntity Book` we only get back a single entity with the same id.
But I still think it shouldn't have a side effect on DTOs. Like the BookDto with a field called `id`.
I think it is not expected behaviour and an unwanted side effect just because two fields are named the same.
I think this scenario is a genuine bug.
