### ISSUE TITLE
Discrepancy between documentation and pre-generated-project using wizard

### ISSUE THREAD

**Issue by EnriqueWood** [micronaut-projects/micronaut-data#2857]
### Issue description

According to the documentation, you should add this dependency using "annotationProcessor" (https://micronaut-projects.github.io/micronaut-data/snapshot/guide/#dbc)

![image](https://github.com/micronaut-projects/micronaut-data/assets/22996504/09009f82-88cd-4db2-a7e9-1a6f662c17dd)

However, when you go to the wizard and generate a pre-configured project using the link https://micronaut.io/launch?features=data-jdbc&lang=GROOVY&build=GRADLE  it has that same dependency marked as "compileOnly"
![image](https://github.com/micronaut-projects/micronaut-data/assets/22996504/70b49886-9cc7-46a5-a1ce-9f7aa5bc6b94)

**Comment by dstepanov** [comment]
Groovy doesn't have a concept of annotation processors, because it's dynamic it uses compile plugins

**Comment by EnriqueWood** [comment]
Thanks for pointing out the reasons why it's that way it's implemented in the wizard.

To improve the clarity of the projects' documentation, it would be beneficial to specify that for Groovy-based projects, dependencies should be declared as `compileOnly` instead of `annotationProcessor`.  This clarification will help anyone integrating micronaut-data into their existing projects, instead of using the wizard to start from scratch. This could prevent potential confusion and ensure smoother integration for these users.

 I hope you'll consider making this change as it could help avoid confusions in the integration process

**Comment by sdelamo** [comment]
@wetted revise our documentation in every module that adds an annotation processor and add an asciidoc callout.  

> NOTE: For Kotlin, add the `REPLACE_ANN_ARTIFACT_ID` dependency in https://docs.micronaut.io/4.4.3/guide/#kaptOrKsp[`kapt` or `ksp` scope], and for Groovy add `REPLACE_ANN_ARTIFACT_ID ` in `compileOnly` scope.

**Comment by wetted** [comment]
> @wetted revise our documentation in every module that adds an annotation processor and add an asciidoc callout.
> 
> >

I have completed this for all the modules I found with docs for annotation processors.
