### ISSUE TITLE
[Docs] Clarify if programmatic transactions work with repositories and entities and how

### ISSUE THREAD

**Issue by RonBarkan** [micronaut-projects/micronaut-data#2860]
### Expected Behavior

Looking at the docs https://micronaut-projects.github.io/micronaut-data/latest/guide/index.html#programmaticTransactions
It should be clear if `TransactionOperations` and/or `SynchronousTransactionManager` can be used correctly with Repositories, e.g. `CrudRepository`  database methods.

### Actual Behaviour

Looking at the docs alone (and even trying to poke at some classes), the reader has no idea if these things are compatible.
Even if a small test seems to work, there's no gained certainty it is not a fluke.

### Steps To Reproduce

n/a

### Environment Information

n/a

### Version

3.10.1 and 4.x

**Comment by sdelamo** [comment]
@radovanradic could you clarify the documentation?

**Comment by radovanradic** [comment]
Done in https://github.com/micronaut-projects/micronaut-data/pull/2946
