### ISSUE TITLE
Documentation section 6.5.13 is missing source code snippet

### ISSUE THREAD

**Issue by mikehearn** [micronaut-projects/micronaut-data#2896]
### Expected Behavior

Section 6.5.13 says "The following record class demonstrates this capability" and should be followed by a source snippet.

### Actual Behaviour

No source code is visible, although the annotations are.

### Steps To Reproduce

https://micronaut-projects.github.io/micronaut-data/latest/guide/#javaRecords

### Example Application

https://micronaut-projects.github.io/micronaut-data/latest/guide/#javaRecords

### Version

Current

**Comment by radovanradic** [comment]
I can see it
![Screenshot 2024-04-19 at 11 27 10 AM](https://github.com/micronaut-projects/micronaut-data/assets/10271067/3ecd2586-5cb3-4401-8251-3b21fa6d5132)

**Comment by mikehearn** [comment]
I see. If you select Kotlin for a code snippet earlier up the page, then it disappears, presumably because there's no Kotlin equivalent for this section but the js code assumes there always will be.

**Comment by radovanradic** [comment]
It appears to be fixed by https://github.com/micronaut-projects/micronaut-build/pull/684
