### ISSUE TITLE
bug with getOrders()

### ISSUE THREAD

**Issue by kareemelzayat** [micronaut-projects/micronaut-data#2911]
### Expected Behavior

With every sorting property, the path should start from the root

### Actual Behaviour

The path starts from where it last ended

### Version

4.4.0

**Comment by kareemelzayat** [comment]
@dstepanov critical issue! MR to review: https://github.com/micronaut-projects/micronaut-data/pull/2912/files

**Comment by dstepanov** [comment]
Please include a test

**Comment by radovanradic** [comment]
Closed by https://github.com/micronaut-projects/micronaut-data/pull/2912
