### ISSUE TITLE
Problem with embedded key as inner class

### ISSUE THREAD

**Issue by jachinte** [micronaut-projects/micronaut-data#295]
If I use a static inner class to create an embedded key, micronaut cannot generate the repository. If I move the embedded key to a public class, everything works.

In the example application, If I use `OwnerPetKey` instead of `OwnerPet.InnerOwnerPetKey` in repository `OwnerPetRepository` and in entity `OwnerPet`, the project compiles without any errors.

### Task List

- [X] Steps to reproduce provided
- [X] Stacktrace (if present) provided
- [X] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. ./gradlew compileJava

### Expected Behaviour

Micronaut should be able to generate repository `OwnerPetRepository` for entity `OwnerPet`.

### Actual Behaviour

When compiling, I get these error messages:

```
error: Could not resolved root entity. Either implement the Repository interface or define the entity as part of the signature
error: Unable to implement Repository method: OwnerPetRepository.existsById(Object arg0). Unable to establish persistent entity to query for method: existsById
```

Standard output:
```
> Task :compileJava
Caching disabled for task ':compileJava' because:
  Build cache is disabled
Task ':compileJava' is not up-to-date because:
  Task has failed previously.
All input files are considered out-of-date for incremental task ':compileJava'.
Full recompilation is required because no incremental change information is available. This is usually caused by clean builds or changing compiler arguments.
Compiling with JDK Java compiler API.
error: Could not resolved root entity. Either implement the Repository interface or define the entity as part of the signature
error: Unable to implement Repository method: OwnerPetRepository.existsById(Object arg0). Unable to establish persistent entity to query for method: existsById
Note: Writing native-image.properties file to destination: META-INF/native-image/example/domain/native-image.properties
Note: Writing reflection-config.json file to destination: META-INF/native-image/example/domain/reflection-config.json
Note: Creating bean classes for 11 type elements
2 errors
```

### Environment Information

- **Operating System**: macOS Catalina
- **Micronaut Version:** 1.2.6
- **JDK Version:** "1.8.0_111

### Example Application

https://github.com/jachinte/micronaut-predator-issue/tree/mn-inner-embedded-key

(Notice the example is in branch `mn-inner-embedded-key`)

**Comment by marifsami** [comment]
Any update on this?

**Comment by graemerocher** [comment]
A PR has been submitted to Micronaut core for this https://github.com/micronaut-projects/micronaut-core/pull/4347
