### ISSUE TITLE
Enhancement: Add ability to create interceptor on save/update/delete

### ISSUE THREAD

**Issue by simplemes-old** [micronaut-projects/micronaut-data#296]
I am trying to switch from Hibernate to Micronaut-Data.  It is very close to what I need, but I need the ability to run an interceptor on save/update/delete, before the transaction commit.  This interceptor will need to do some additional database work in the transaction.

This is what messes me up in Hibernate.  It is a nightmare to do DB work in an interceptor since they are executed in the flush logic.  I am very annoyed at the Hibernate session/flush weirdness.

I looked at abstract repositories with a method for the save().  This method can't call any super (or similar element) since there really is no super-class.

I looked at modifying the operations used as a sub-interface of JdbcOperations.  That has the same problem.  No concrete implementation of the persist() method to access.

I am looking at adding an interceptor of my own, but that seems like digging into the internals too much.

Any ideas?  or does this require an enhancement?

Thanks.

**Comment by simplemes** [comment]
One addition:  I sub-classed DefaultJdbcRepositoryOperations and seem to have access to the operations.  I plan to add additional logic after the core persist/update operations to perform the additional logic.

Is this a reasonable way to handle this?  If so, then this enhancement is no longer needed.

**Comment by graemerocher** [comment]
It is our intention to at some point add an interceptor API but in the meantime yes what you are doing is probably the only way to go

**Comment by simplemes** [comment]
Thanks.  Since there is a way to solve my needs, this is a low priority.
