### ISSUE TITLE
Enhancement: type safe querries

### ISSUE THREAD

**Issue by kivan-mih** [micronaut-projects/micronaut-data#298]
In Spring Data JPA I used Spring-Querydsl connector to allow typesafe compile-time queries and out of the box IDE autocompletion. Is there anything like this in Micronaut? If no, plugging in something like Querydsl probably will be a good move.

**Comment by graemerocher** [comment]
So there are many different implementations of this (Querydsl, requery, etc. ) at some point we do plan to add support for them, but after 1.0

**Comment by dstepanov** [comment]
Closing as we already have those

**Comment by kivan-mih** [comment]
@dstepanov could you give reference to documentation?

**Comment by dstepanov** [comment]
https://micronaut-projects.github.io/micronaut-data/latest/guide/#typeSafeJava
