### ISSUE TITLE
`alias` attribute from `@MappedEntity` is not working

### ISSUE THREAD

**Issue by Nahuel92** [micronaut-projects/micronaut-data#3004]
### Expected Behavior

As per the [documentation](https://micronaut-projects.github.io/micronaut-data/latest/guide/#sqlNaming) (please scroll down to `Overriding default query alias`, a future docs. improvement is to provide anchors to every item):

> The default query alias is the table name followed by an underscore. If you want to change it, specify it  in the [@MappedEntity](https://micronaut-projects.github.io/micronaut-data/latest/api/io/micronaut/data/annotation/MappedEntity.html) annotation:
> @MappedEntity(alias="my_table_")

### Actual Behaviour

Setting `@MappedEntity(alias = "any_value", value = "any_entity") class MyEntity { }` doesn't work when defining query as `@Query("SELECT * FROM any_value") MyEntity findAll();`.

I wonder if it's a documentation mistake or a bad usage from my part.

### Steps To Reproduce

1. Create any Micronaut Data JDBC.
2. Create a basic entity and annotate it with `@MappedEntity(alias = "my_alias", values = my_entity)`.
3. Create a repository interface and annotate it with `JdbcRepository()`. Set the appropriate dialect.
4. Create a custom repository method: `@Query("SELECT * FROM my_alias) MyEntity findAll();`.
5. Create a `@MicronautTest`-annotated test class, inject the repository, create a test and call the repository method created above.
6. Test will fail as the `my_alias` table doesn't exist.

Please see the attached app that uses Liquibase to create the table and insert the test data. Let me know if anything else is needed. Thanks.

### Environment Information

- OS: Any.
- JDK: 21.

### Example Application

~https://github.com/Nahuel92/micronaut-data-alias-bug~

### Version

4.5.0

**Comment by dstepanov** [comment]
You cannot use it as a table name, alias means the table alias when used in sql

**Comment by Nahuel92** [comment]
> You cannot use it as a table name, alias means the table alias when used in sql

Hi @dstepanov, thanks for your prompt answer.

I see, so my assumption about that possibility was wrong. I'll go ahead and close this (not anymore) issue then.

Thanks again!
