### ISSUE TITLE
Tests break when disabling datasources

### ISSUE THREAD

**Issue by miguelaferreira** [micronaut-projects/micronaut-data#3036]
### Expected Behavior

I would expected that setting `datasources.enabled: false` would prevent Micronaut Data resources from being loaded during tests.

### Actual Behaviour

The defualt `testItWorks` test breaks with `datasources.enabled: false`.

### Steps To Reproduce

1. Create a demo app with Micronaut Data JDBC
2. Add a repository and an entity
3. Add a test that uses the repository
4. Configure `application-test.yml` with `datasources.enabled: false`
5. The default `testItWorks` breaks

### Environment Information

- Operating System: macOS 14.5 (23F79)
- JDK: OpenJDK Runtime Environment GraalVM CE 21.0.2+13.1 (build 21.0.2+13-jvmci-23.1-b30)

### Example Application

https://github.com/miguelaferreira/micronaut-data-disable-datasources

### Version

4.5.0

**Comment by graemerocher** [comment]
there is no code in the referenced example

**Comment by miguelaferreira** [comment]
My bad, forgot to push. The code is there now.

**Comment by radovanradic** [comment]
The error occurs in `SchemaGenerator` which tries to run schema updates but there is no data source available

**Comment by radovanradic** [comment]
There is another issue with this approach to disable datasources. When there are tests with test-resources, the test resources resolver tries to resolve properties for datasource `enabled` considering `datasource.enabled=false` another datasource definition. Don't know if approach should be reconsidered, or add workaround in test resources not to resolve properties in this case.

**Comment by miguelaferreira** [comment]
> There is another issue with this approach to disable datasources. When there are tests with test-resources, the test resources resolver tries to resolve properties for datasource enabled considering datasource.enabled=false another datasource definition.

Thanks @radovanradic. This is exactly the problem I'm facing in a project. I was trying to reproduce it in a small example but missed the need for test-resources.

**Comment by radovanradic** [comment]
Resolved by https://github.com/micronaut-projects/micronaut-sql/pull/1388 and https://github.com/micronaut-projects/micronaut-data/pull/3066

**Comment by miguelaferreira** [comment]
Thanks for the fix @radovanradic!
