### ISSUE TITLE
Support for Kotlin Coroutines

### ISSUE THREAD

**Issue by damianw** [micronaut-projects/micronaut-data#304]
Similar to [the related issue in the micronaut-kotlin repository](https://github.com/micronaut-projects/micronaut-kotlin/issues/4), adding Kotlin coroutines support would greatly improve utility of micronaut-data for Kotlin users. Specifically, this would involve adding support for:
- `Deferred<T>` return type
- `Flow<T>` return type
- `suspend fun` finder methods
- possibly other things I may have missed

Relevant links:
- micronaut-projects/micronaut-kotlin#4
- micronaut-projects/micronaut-core#2308
- micronaut-projects/micronaut-core#2340

**Comment by dstepanov** [comment]
Is it something that makes sense https://github.com/micronaut-projects/micronaut-data/blob/master/data-model/src/main/kotlin/io/micronaut/data/repository/kotlin/CoroutineCrudRepository.kt ?
