### ISSUE TITLE
Unable to eagerly retrieve joined element with CoroutineCrudRepository

### ISSUE THREAD

**Issue by opaquot** [micronaut-projects/micronaut-data#3069]
### Expected Behavior

Let's say you have the following two entities and repository:
```
@Introspected
@Serdeable
@MappedEntity
data class A(
    @field:Id
    val id: Long,
    @OneToMany(cascade = [CascadeType.ALL], fetch = FetchType.EAGER)
    val b: List<B>
)

@Introspected
@Serdeable
@MappedEntity
data class B(
    val field: Int,
){
    @Id
    @GeneratedValue(GeneratedValue.Type.SEQUENCE)
    var uid: Long? = null
}

@R2dbcRepository(dialect = Dialect.POSTGRES)
interface APostgresRepository : CoroutineCrudRepository<A, Long>

```

Even though the relation between A and B is marked as eager, when retrieving A with a CoroutineCrudRepository, b is null.

### Actual Behaviour

When retrieving A with a CoroutineCrudRepository, b is null.

### Steps To Reproduce

Using micronaut 4.2.1, with Postgres and Micronaut kotlinx-coroutines-reactor

### Environment Information

OS: Ubuntu 22.04.4 LTS
JDK: temurin-21
Kotlin: 1.9.21

### Version

4.2.1

**Comment by opaquot** [comment]
Hi.

Is there any update on this?

Thanks!

**Comment by dstepanov** [comment]
We don't support `FetchType.EAGER` at this moment, you can annotate your repository with `@Join`

**Comment by opaquot** [comment]
Thanks for the information. Annotating the repository with @Join seems to work but significantly slows down the query. Especially if we have multiple @Join. Is there a way to improve the performance?

**Comment by dstepanov** [comment]
Make sure you have indexes. How did you think it will work differently with EAGER?

**Comment by opaquot** [comment]
Indeed thanks.
