### ISSUE TITLE
Delete method not correctly generated for Entities with @EmbeddedId

### ISSUE THREAD

**Issue by ckosmowski** [micronaut-projects/micronaut-data#309]
DELETE  FROM ShipmentService  WHERE (shipmentServiceId ?$IN(1))

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
       Left open for now. Unfortunately i can't upload the actual code because it is confidential. If it is absolutely necessary to find the issue, we will create such a github project.
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create an entity with an EmbeddedId that contains more than one field
2. Create a @JdbcRepository for this Entity
3. Try to use the method "deleteAll(Iterable<T>)" on this repository

### Expected Behaviour

The generated JdbcRepository contains the correct code to execute the said deleteAll method and deletes the given entities that match the embedded Id from the database.

### Actual Behaviour

Debugging the code showed, that the generated Query for the deleteAll method seems to be : "DELETE  FROM ShipmentService  WHERE (shipmentServiceId ?$IN(1))"
where shipmentServiceId is the field annotated with @EmbeddedId.

This results in a SQLSyntaxException with the following Stacktrace:

 ```
result = {StackTraceElement[22]@7609} 
 0 = {StackTraceElement@7558} "io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.lambda$executeUpdate$7(DefaultJdbcRepositoryOperations.java:413)"
 1 = {StackTraceElement@7559} "io.micronaut.transaction.support.AbstractSynchronousTransactionManager.executeWrite(AbstractSynchronousTransactionManager.java:177)"
 2 = {StackTraceElement@7560} "io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.executeUpdate(DefaultJdbcRepositoryOperations.java:406)"
 3 = {StackTraceElement@7561} "io.micronaut.data.runtime.intercept.DefaultDeleteAllInterceptor.intercept(DefaultDeleteAllInterceptor.java:51)"
 4 = {StackTraceElement@7562} "io.micronaut.data.runtime.intercept.DefaultDeleteAllInterceptor.intercept(DefaultDeleteAllInterceptor.java:36)"
 5 = {StackTraceElement@7563} "io.micronaut.data.intercept.DataIntroductionAdvice.intercept(DataIntroductionAdvice.java:84)"
 6 = {StackTraceElement@7564} "io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:69)"
 7 = {StackTraceElement@7565} "de.example.for.github.adapter.repository.ShipmentServiceRepository$Intercepted.deleteAll(Unknown Source)"
 8 = {StackTraceElement@7566} "de.example.for.github.adapter.jdbc.ShipmentServiceDatabaseAdapter.addShipmentServices(ShipmentServiceDatabaseAdapter.java:31)"
 9 = {StackTraceElement@7567} "de.example.for.github.application.service.ShipmentServiceService.receiveShipmentServicesForAddition(ShipmentServiceService.java:30)"
 10 = {StackTraceElement@7568} "de.example.for.github.adapter.kafka.KafkaShipmentServiceReceiveAdapter.receiveShipmentService(KafkaShipmentServiceReceiveAdapter.java:41)"
 11 = {StackTraceElement@7569} "de.example.for.github.adapter.kafka.$KafkaShipmentServiceReceiveAdapterDefinition$$exec1.invokeInternal(Unknown Source)"
 12 = {StackTraceElement@7570} "io.micronaut.context.AbstractExecutableMethod.invoke(AbstractExecutableMethod.java:145)"
 13 = {StackTraceElement@7571} "io.micronaut.core.bind.DefaultExecutableBinder$1.invoke(DefaultExecutableBinder.java:109)"
 14 = {StackTraceElement@7572} "io.micronaut.configuration.kafka.processor.KafkaConsumerProcessor.lambda$process$7(KafkaConsumerProcessor.java:496)"
 15 = {StackTraceElement@7573} "io.micrometer.core.instrument.composite.CompositeTimer.record(CompositeTimer.java:79)"
 16 = {StackTraceElement@7574} "io.micrometer.core.instrument.Timer.lambda$wrap$0(Timer.java:144)"
 17 = {StackTraceElement@7575} "java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)"
 18 = {StackTraceElement@7576} "java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)"
 19 = {StackTraceElement@7577} "java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)"
 20 = {StackTraceElement@7578} "java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)"
 21 = {StackTraceElement@7579} "java.base/java.lang.Thread.run(Thread.java:830)"
```

### Environment Information

- **Operating System**: Microsoft Windows 10
- **Micronaut Version:** 1.0.0.M3
- **JDK Version:** 1.8

### Example Application

See above, left open for now

**Comment by ckosmowski** [comment]
It works now, but its performance is poor. The deleteAll method generated for Entities with @EmbeddedIds seem to iterate over the entities and execute one single delete query per Entity. While with an ordinary ID deletes are properly batched with IN like this:

`15:46:22.379 [pool-2-thread-2] DEBUG io.micronaut.data.query - Executing Query: DELETE  FROM `ShipmentService`  WHERE (id IN(?,?,?,?))`

Since many databases support multiple columns in IN statements, would it be possible to use IN for entities with EmbeddedIds ?

Reopen this ticket or file a new one?

**Comment by graemerocher** [comment]
new ticket makes sense to me
