### ISSUE TITLE
Add support for soft-delete

### ISSUE THREAD

**Issue by raderio** [micronaut-projects/micronaut-data#31]
In many cases, people will want to soft-delete records instead of hard-deleting them, i.e. execute:
```
-- This:
UPDATE t SET t.deleted = true WHERE t.id = ?

-- Instead of this:
DELETE t WHERE t.id = ?
```

**Comment by YoKv** [comment]
additionally, multi-tenant application will use tenantId every sql command.
is it possible that custom operations like:
```
select: add deleted and tenantId condition
insert: add insert_user_id
update: update update_user_id
```

**Comment by graemerocher** [comment]
Yes support for both multi-tenancy and soft deletes is planned, plus general customization of the generated query statements

**Comment by graemerocher** [comment]
Support for soft delete can be achieved with the new `@Where` annotation. See https://micronaut-projects.github.io/micronaut-data/snapshot/guide/#whereAnnotation

**Comment by raderio** [comment]
@graemerocher is the `@Where` annotation also works for `JOIN ... ON` criteria?

**Comment by graemerocher** [comment]
Good question, probably should
