### ISSUE TITLE
Batch Update fails after update to 1.0.0.M5

### ISSUE THREAD

**Issue by ckosmowski** [micronaut-projects/micronaut-data#310]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [] Example that reproduces the problem uploaded to Github
     Left open for now, please request if definetly needed
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create an Entity and a corresponding JdbcRepository
2. Use the "saveAll" method of the repository to store multiple Entities

### Expected Behaviour
The entities are correctly inserted into the database

### Actual Behaviour
A batch exception is thrown:

Caused by: java.sql.BatchUpdateException: (conn=12223) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '"ShipmentService" ("valueCurrency","valueAmount","valueInDefaultCurrencyCurrency' at line 1

### Additional information

With 1.0.0.M3 the query that gets generated and logged is:

```sql
INSERT INTO ShipmentService (valueCurrency,valueAmount,[.....]) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
```
with 1.0.0.M5 it is like this:
```
INSERT INTO "ShipmentService" ("valueCurrency","valueAmount",",[....]) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
```
(Everything is quoted now)

I also tried to set the "dialect" property of the datasource to different values but without success

### Environment Information

- **Operating System**: Microsoft Windows 10
- **Micronaut Version:** 1.0.0.M5
- **JDK Version:** 1.8

### Example Application
Left open for now, please request if definetly needed

**Comment by ckosmowski** [comment]
I just checked 1.0.0.M4 and it behaves the same as 1.0.0.M5 (error case)

**Comment by graemerocher** [comment]
What does your repository interface look like?

**Comment by ckosmowski** [comment]
```java
@JdbcRepository
public abstract class ShipmentServiceRepository implements CrudRepository<ShipmentServiceEntity, String> {
    public abstract void deleteByShipmentHash(String shipmentHash);
}
```

**Comment by graemerocher** [comment]
Can you try specify the dialect `@JdbcRepository(dialect=Dialect.MYSQL)`

**Comment by ckosmowski** [comment]
It works perfectly with the dialect inside the annotation. How should it look like when configured for a datasource in the configuration?

**Comment by graemerocher** [comment]
Unfortunately the dialect has to be specified on the annotation since the queries are computed at compilation time

**Comment by ckosmowski** [comment]
Okay thanks for the fast reaction!
