### ISSUE TITLE
Error saving BigDecimal with too many diggits

### ISSUE THREAD

**Issue by tucker-eventpipe** [micronaut-projects/micronaut-data#3129]
### Expected Behavior

I should have a way to store a BigDecimal as a String, or something that doesn't have an error.

### Actual Behaviour

When you try to save a BigDecimal that has too many decimal places I get an error:
Caused by: java.lang.NumberFormatException: Conversion to Decimal128 would require inexact rounding of 9.6438461538461538461538461538461538461538

See the full stack trace in the readme of the sample app.  I worked around this by rounding when I queried because at the time I didn't need the percission, and didn't have the time to create a sample app.

### Steps To Reproduce

1. Run the docker instance in the read me
2.  Comment out the first TestContent testContent and comment in the second one in TestStartupService.groovy.
3. Run the app using the run task
4. note the error in the console
5. Shut the docker instance down with the command in the readme.

### Environment Information

- operating system: PopOS(Linux)
- JDK: 21.0.3 temurin

### Example Application

https://github.com/tucker-eventpipe/sampleApp

### Version

4.4.3 +

**Comment by dstepanov** [comment]
It looks like a correct error; it notifies you that you will lose data because the number is higher than the possible number in the database. Strip it or store it as a String if you need complete precision.
