### ISSUE TITLE
How to use UpdatedBy and CreatedBy annotations on entities?

### ISSUE THREAD

**Issue by alapierre** [micronaut-projects/micronaut-data#3135]
### Issue description

I look around and can't found how to use `@UpdatedBy` and `@CreatedBy` annotations. There is closed issue: https://github.com/micronaut-projects/micronaut-data/issues/506 but with no description.

I have a `BaseEntity`:

```java
@Getter
@Setter
@ToString
@MappedSuperclass
public class BaseEntity implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    protected UUID id;

    @CreationTimestamp
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @UpdateTimestamp
    private LocalDateTime lastUpdated;

    @CreatedBy
    private String createdBy;

    @UpdatedBy
    private String updatedBy;

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        BaseEntity that = (BaseEntity) o;
        return Objects.equals(id, that.id);
    }

    @Override
    public int hashCode() {
        return Objects.hashCode(id);
    }
}
```
`io.micronaut.security.utils.DefaultSecurityService`  bean is available in context. User has Authentication but in database, columns `created_by` and `updated_by` are empty.

**Comment by dstepanov** [comment]
Looks like you are missing a getter / setter for createdBy / updatedBy

**Comment by alapierre** [comment]
there are `@Getter` and `@Setter` on class

**Comment by dstepanov** [comment]
Please create a sample app that reproduces the problem

**Comment by alapierre** [comment]
adding `@Introspected` on `BaseEntity` solves the problem

**Comment by alapierre** [comment]
`BaseEntity` needs `@Introspected` annotation (and clean and build project)
