### ISSUE TITLE
UpdateBy* doesn't work anymore in micronaut-data:4.8

### ISSUE THREAD

**Issue by FrogDevelopper** [micronaut-projects/micronaut-data#3139]
### Expected Behavior

When updating an entity using **`updateBy*`**, the entity is updated using the parameters as criteria

### Actual Behaviour

The entity is not updated anymore

### Steps To Reproduce

1. Clone repository https://github.com/FrogDevelopper/micronaut-4_5
2. Check in [gradle.properties](https://github.com/FrogDevelopper/micronaut-4_5/blob/master/gradle.properties) that micronaut version is **4.4.3** (= micronaut-data:4.7.1)
3. Run test `MyItemRepositoryTest#should_updateByField1` => test pass :white_check_mark:
4. Update [gradle.properties](https://github.com/FrogDevelopper/micronaut-4_5/blob/master/gradle.properties) to use micronaut version **4.5.1** (= micronaut-data:4.8.1)
5. Run again test `MyItemRepositoryTest#should_updateByField1` => test fails :x:

### Environment Information

JDK Version: 21

### Example Application

https://github.com/FrogDevelopper/micronaut-4_5

### Version

4.5.1

**Comment by radovanradic** [comment]
Fixed in https://github.com/micronaut-projects/micronaut-data/pull/3140
