### ISSUE TITLE
Enable support for TypeDef with JPA

### ISSUE THREAD

**Issue by StephenOTT** [micronaut-projects/micronaut-data#320]
Would be great if there was a way to have the dynamic support of the `@TypeDef` (which detects which specific value to use based on the dialect in the app config.

```
@TypeDef(type = DataType.JSON)
```
vs
```
@Column(columnDefinition = "json")
```

So that the columnDef does not have to be supplied

A good use case for this is in the latest release of H2 it supports the json column type.  But does not support jsonb.  Postgres does support jsonb,  So would be great to gain this dynamic selection of column support with the TypeDef usage

**Comment by graemerocher** [comment]
We can't control how Hibernate interprets annotations unfortunately
