### ISSUE TITLE
Cascade persist doesn't save child objects

### ISSUE THREAD

**Issue by kurtchak** [micronaut-projects/micronaut-data#321]
After saving the owning entity object which creates new child objects, a strange thing happens. Only the owning object is saved, though the SQL logs also shows inserts for the child entities.

**Team**

    @Data
    @EqualsAndHashCode(of = "id")
    @NoArgsConstructor
    @Entity
    public class Team implements Comparable<Team> {
        @Id
        @GeneratedValue
        private int id;
        private String name;
        @Relation(value = Relation.Kind.ONE_TO_MANY, cascade = Relation.Cascade.PERSIST, mappedBy = "team")
        private List<TeamPlayer> teamPlayers;
        private int givenGoals;
        private int gotGoals;
        private int points;
        @Relation(value = Relation.Kind.MANY_TO_ONE)
        private Tournament tournament;
    }

**TeamPlayer**

    @Data
    @EqualsAndHashCode(of = "id")
    @NoArgsConstructor
    @Entity
    public class TeamPlayer {
        @Id
        @GeneratedValue
        private int id;
        @Relation(value = Relation.Kind.MANY_TO_ONE)
        private Team team;
        @Relation(value = Relation.Kind.MANY_TO_ONE)
        private Player player;
    }

**Player**

    @Data
    @EqualsAndHashCode(of = "id")
    @NoArgsConstructor
    @Entity
    public class Player {
        @Id
        @GeneratedValue
        private int id;
        private String forename;
        private String surname;
        private int rank;
        @Relation(value = Relation.Kind.ONE_TO_ONE, cascade = Relation.Cascade.ALL)
        private User user;
    }

**TeamRepository**

    @JdbcRepository
    public interface TeamRepository extends CrudRepository<Team, Integer> {}

After saving the collection with
```teamRepository.saveAll(teams)```
the output is...

```
17:16:32.160 [pool-1-thread-11] DEBUG io.micronaut.data.query - Executing Batch SQL Insert: INSERT INTO "team" ("name","given_goals","got_goals","points","tournament_id") VALUES (?,?,?,?,?)
17:16:33.308 [pool-1-thread-11] DEBUG io.micronaut.data.query - Executing Batch SQL Insert: INSERT INTO "team_player" ("team_id","player_id") VALUES (?,?)
17:16:33.308 [pool-1-thread-11] DEBUG io.micronaut.data.query - Executing Batch SQL Insert: INSERT INTO "team_player" ("team_id","player_id") VALUES (?,?)
17:16:33.309 [pool-1-thread-11] DEBUG io.micronaut.data.query - Executing Batch SQL Insert: INSERT INTO "team_player" ("team_id","player_id") VALUES (?,?)
17:16:33.309 [pool-1-thread-11] DEBUG io.micronaut.data.query - Executing Batch SQL Insert: INSERT INTO "team_player" ("team_id","player_id") VALUES (?,?)
17:16:33.309 [pool-1-thread-11] DEBUG io.micronaut.data.query - Executing Batch SQL Insert: INSERT INTO "team_player" ("team_id","player_id") VALUES (?,?)
17:16:33.310 [pool-1-thread-11] DEBUG io.micronaut.data.query - Executing Batch SQL Insert: INSERT INTO "team_player" ("team_id","player_id") VALUES (?,?)
```

However only the Team is created in the database and no further error is shown.

**Comment by graemerocher** [comment]
Please provide an example that reproduces the issue, can't reproduce in master

**Comment by kurtchak** [comment]
After longer time I tried one more time to debug it and I realized that the cause was that IDs was defined by primitive int instead of object Integer.
