### ISSUE TITLE
IllegalMutationQueryException when using native "select for update" query

### ISSUE THREAD

**Issue by davidgiga1993** [micronaut-projects/micronaut-data#3247]
### Expected Behavior

The select statement should return data without failing

### Actual Behaviour

The select statement throws an exception as micronaut calls hibernate's `executeUpdate` instead of a select:

```
org.hibernate.query.IllegalMutationQueryException: Expecting a native mutation query, but found `SELECT * FROM task t WHERE t.request_id = :requestId AND t.status = :status
AND JSON_CONTAINS(t.parent_ids, :parentId) = true
FOR UPDATE
```

Downgrading to micronaut `4.6.0` (micronaut-data `4.9.0`) resolves the issue

### Steps To Reproduce

1. Create a repository with the following:
  ```java
  @Query(value = """
          SELECT * FROM task t WHERE t.request_id = :requestId AND t.status = :status
          AND JSON_CONTAINS(t.parent_ids, :parentId) = true
          FOR UPDATE
          """, nativeQuery = true)
      public abstract List<Task> tasksWithParentId(String requestId, String parentId, String status);
  ```

2. Execute the query with any parameters

### Environment Information

- Micronaut 4.7.1
- Micronaut data 4.10.4
- JDK 22

### Version

4.7.1

**Comment by radovanradic** [comment]
Regression from this https://github.com/micronaut-projects/micronaut-data/pull/3236
