### ISSUE TITLE
JPA docs refer to SynchronousTransactionManager<EntityManager> but should probably be Connection

### ISSUE THREAD

**Issue by esocode** [micronaut-projects/micronaut-data#325]
The JPA examples of the documentation section _6.1.1 Programmatic Transactions_  declare a `SynchronousTransactionManager<EntityManager>` but when running the code it is actually a `SynchronousTransactionManager<Connection>` as in the JDBC examples. I'm not sure if the documentation is wrong or if the intended type is really `EntityManager`in which case the different behavior would be a bug. If the `Connection` type is correct (as the `getConnection()` method suggests) the generic type should probably be constrained to `SynchronousTransactionManager<T extends Connection>` to prevent declaration errors and the documentation should be corrected.

**Comment by graemerocher** [comment]
Documentation error. Thanks
