### ISSUE TITLE
Handling null value with micronaut data

### ISSUE THREAD

**Issue by RobinB95** [micronaut-projects/micronaut-data#333]
Micronaut data-jdbc returns 0 for column where the value is null. This weird behavior comes from the jdbc driver. It should return null if the value is null because otherwise null values can't be used, making micronaut-data a bad fit for example working with mysql.

### Task List

- [x] Steps to reproduce provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. use docker-compose to launch containers
2. import example_database.sql to the docker mysql database
3. start the project via `./gradlew run`
3. Point your browser to "http://localhost:8080/users?id=1"

### Expected Behaviour

The Application should return an user, wich contains null for the column "number_column"

`{
    "id": 1,
    "numberColumn": null
}`

### Actual Behaviour

The Application returns an user, wich contains 0 for the column "number_column"

`{
    "id": 1,
    "numberColumn": 0
}`

### Environment Information

- **Operating System**: elementary OS 5.0 Juno
- **Micronaut Version:** 1.2.0
- **JDK Version:** openjdk 11.0.4 2019-07-16

### Example Application

https://github.com/kpro-media/micronaut-data-jdbc-null_value_handling.git

**Comment by devkev16** [comment]
Problem seems to rely on io/micronaut/data/runtime/mapper/ResultReader.java (readDynamic).

Made a fork: https://github.com/kpro-media/micronaut-data

Developed a possible fix, see: https://github.com/kpro-media/micronaut-data/commit/2d4cfcd5da79397c350c447ea35bbbe9fe17e95a

I would love to test this, but I am not aware of how to replace micronaut-data-runtime with the local built jar which contains the possible fix. I would appreciate any help on this :)

Can someone have a look at this?

**Comment by graemerocher** [comment]
Should just be able to run the test suite to test it

**Comment by devkev16** [comment]
Thanks for adding the label!

There is the need to add a spec for this. I am unfortunately not familiar with this. Tried to run MySqlRepositorySpec (project: micronaut-data-jdbc) and I run into this error:

```
io.micronaut.context.exceptions.NoSuchBeanException: No bean of type [io.micronaut.data.jdbc.mysql.MySqlBookRepository] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).

	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1986)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:622)
	at io.micronaut.data.jdbc.mysql.MySqlRepositorySpec.getBookRepository(MySqlRepositorySpec.groovy:53)
	at io.micronaut.data.tck.tests.AbstractRepositorySpec.setupData(AbstractRepositorySpec.groovy:75)
	at io.micronaut.data.tck.tests.AbstractRepositorySpec.setupSpec(AbstractRepositorySpec.groovy:67)
```
I don't know why it can't find the repository bean.

Maybe someone with more knowledge than I have in this field could add a spec for this.

**Comment by graemerocher** [comment]
Interesting error, not seen that before. Will take a look at this soon, although probably not until the new year with the holiday period coming up

**Comment by devkev16** [comment]
Was using Java 11 (don't know if this is officially supported). Now with Java 8 I got it working somehow.

I extended the Author class and added an age column which is nullable. Also got it managed to write a test but now it's complaining that there is no column "age". 

Do you know where I need to make a change that the field is actually generated into the schema?

I would like to fix this, because I would need this during the holidays and the null values error is blocking me. But if it's not possible I will have to work out an plan B

**Comment by devkev16** [comment]
Okay, I managed to work out how to publish this into my nexus and changed the dependencies in the demo project for the issue and tried it out. **The fix works** :)

Would be nice if someone could confirm this via testcase (I would if I could but I can't). For now I'm good with the local version.
