### ISSUE TITLE
@Transactional causes "Element extends or implements an internal or experimental API" warning during compilation

### ISSUE THREAD

**Issue by Uniqen** [micronaut-projects/micronaut-data#335]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Add `@Transactional`to a method using Micronaut 1.3.0.M2
2. Compile

### Expected Behaviour
There should be no warning about using deprecated API for the annotated method. 

### Actual Behaviour

I get the following warning similiar to micronaut-projects/micronaut-core#2508 but it is resolved in 1.3.0.M2 and I can only reproduce it using the `@Transactional` annotation:
```
> Task :compileJava
.../micronaut-data/examples/example-jpa/src/main/java/example/controllers/OwnerController.java:25: warning: Element extends or implements an internal or experimental API
    List<Owner> all() {
                ^
warning: Overriding an internal API may result in breaking changes in minor or patch versions of the framework. Proceed with caution!
```

### Environment Information

- **Operating System**: macOS 10.15.2
- **Micronaut Version:** 1.3.0.M2
- **Micronaut Data Version:** 1.0.0.M5
- **JDK Version:** AdoptOpenJDK 8.0.222

### Example Application

- Compile using: https://github.com/Uniqen/micronaut-predator/tree/issue_deprecated_api_warning
or just see commit https://github.com/Uniqen/micronaut-predator/commit/99753a737b4391dd56b1832e6bc5d24b0efaca0f

**Comment by graemerocher** [comment]
Fixed in Micronaut core and will be included in 1.3 RC1
