### ISSUE TITLE
Question : How to handle transaction in a Spock test ?

### ISSUE THREAD

**Issue by adbonnin** [micronaut-projects/micronaut-data#339]
### Task List

- [x] Steps to reproduce provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a test that call a transactional method 
2. Fetch data from a Controller
3. The data can't be retrieved because the statement has not be commited
(a complete explanation has been made on the README.md of the github example)

### Actual Behaviour

Transactional method are not commited in a test.

### Expected Behaviour

Statement should be commited in order to setup data for testing.

### Environment Information

- **Operating System**: Windows 10
- **Micronaut Version:** 1.2.8
- **Micronaut Data Version:** 1.0.0.M5
- **JDK Version:** 12.0.1

### Example Application

- https://github.com/adbonnin/micronaut-transaction-question
- launch the unit test `issue.web.rest.UserResourceSpec`

**Comment by graemerocher** [comment]
Use `@MicronautTest(transactional=false)`

**Comment by adbonnin** [comment]
@graemerocher Thank you 😄
