### ISSUE TITLE
Possible bug in cascaded insert

### ISSUE THREAD

**Issue by ooktay** [micronaut-projects/micronaut-data#345]
This line looks like a typo: entities should be entity
https://github.com/micronaut-projects/micronaut-data/blob/d194217a0cb5b84617a5abefba77646f69ed67ab/data-jdbc/src/main/java/io/micronaut/data/jdbc/operations/DefaultJdbcRepositoryOperations.java#L938

**Comment by graemerocher** [comment]
Good spot. Thanks
