### ISSUE TITLE
Support for @JoinTable annotation

### ISSUE THREAD

**Issue by zepfred** [micronaut-projects/micronaut-data#364]
Currently, the @JoinTable annotation seems to not be supported. So, there is not the possibility to specify the name and schema of the join table in @OneToMany association.

I started to work in a solution to this matter in my fork, do you have an interesting in analyzing if the code is viable for a future PR?

**Comment by graemerocher** [comment]
PRs welcome!

**Comment by graemerocher** [comment]
@dstepanov can this be closed?

**Comment by bacca87** [comment]
will this annotation ever be supported by micronaut-data?
This help a lot with many to many relations!

**Comment by dstepanov** [comment]
Yes, it's already supported

**Comment by bacca87** [comment]
> 
> 
> Yes, it's already supported

Yes i'ts already supported for JDBC only, if you use r2dbc is not available and you have to integrate JPA package just for joining tables.

Is it possible to add this annotation in the micronaut-data package in order to be available to all connection types?

**Comment by dstepanov** [comment]
Yes, we can do that. For now, you can have to add JDBC dependency.
