### ISSUE TITLE
GeneratedValue on non-primary key is not updated when saved (but is persisted)

### ISSUE THREAD

**Issue by iwarapter** [micronaut-projects/micronaut-data#371]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Define an entity with two generated UUID's (using the postgres uuid_generate_v4)
```java
@Entity
public class ExampleEntity {
  @Id
  @GeneratedValue
  @Column(nullable = false, unique = true, updatable = false, insertable = false, columnDefinition = "uuid DEFAULT uuid_generate_v4()")
  private UUID id;

  @GeneratedValue
  @Column(nullable = false, unique = true, updatable = false, insertable = false, columnDefinition = "uuid DEFAULT uuid_generate_v4()")
  private UUID anotherId;
  //getters etc
}
```
2. Create a simple crud/pageable repo
```java
@Repository
public interface ExampleRepository extends PageableRepository<ExampleEntity, UUID> {
  Optional<ExampleEntity> findByAnotherId(@NotNull UUID id);
}
```
3. Expect a save to have both UUID's available
```groovy

@MicronautTest(transactional = false)
class ExampleRepositorySpec extends Specification {

  @Inject
  ExampleRepository repository

  def "we should see both generated ID's"() {
    given:
    ExampleEntity entity = new ExampleEntity()

    when:
    def foo = repository.save(entity)

    then:
    entity.id != null
    entity.anotherId != null
  }
}
```

### Expected Behaviour

Both UUID's should be returned as they are persisted in the DB
```
$ docker exec -it determined_burnell psql -U test -d dir
psql (9.6.12)
Type "help" for help.
dir=# select * from example_entity;
                  id                  |              another_id              
--------------------------------------+--------------------------------------
 62ce9561-f47a-4962-827b-a81d8648b5df | 5d049ea4-767b-4474-b0a8-2e1f8eb0cb97
(1 row)

```

### Actual Behaviour

Only the primary key ID is returned, `anotherID` is null, however a `list` on the repo will find the correct data.

### Environment Information

- **Operating System**: macosx
- **Micronaut Version:** 1.2.10 mm-data 1.0.0.RC1
- **JDK Version:** 1.8

### Example Application

- https://github.com/iwarapter/mn-data-generate-value-issue

Complete demo example with postgres testcontainers

**Comment by iain-raidiam** [comment]
So as a follow up, i was originally doing this in 1.0.0.M5 with the hibernate specific annotation:
`@Generated(GenerationTime.INSERT)` which obviously picked up the change with an additional query, since RC1 doesn't have the hibernate libs anymore I'm assuming i'd have to handle this explicitly now.

**Comment by iwarapter** [comment]
So as a follow up, i was originally doing this in 1.0.0.M5 with the hibernate specific annotation:
`@Generated(GenerationTime.INSERT)` which obviously picked up the change with an additional query, since RC1 doesn't have the hibernate libs anymore I'm assuming i'd have to handle this explicitly now.

**Comment by graemerocher** [comment]
I think the issue is https://github.com/micronaut-projects/micronaut-data/issues/370

You should use the hibernate specific annotations
