### ISSUE TITLE
Doc Suggestion: @Transactional does not do anything outside of a bean

### ISSUE THREAD

**Issue by mphouston** [micronaut-projects/micronaut-data#374]
This is a suggested addition to the Micronaut-Data docs on @Transactional.  Please consider adding this note to section "6.1 Transactions":

NOTE: The javax.transaction.Transactional annotation is only supported in repositories and beans processed by Micronaut.  Using @Transactional on other methods/classes does not initiate a transaction.  See "Programmatic Transactions" for hints on how to use transactions in other places.

This is not a big deal, but it is very different from the Spring @Transactional behavior (it seems to work in most classes).

I found this out when I added @Transactional to a method in a support class for test.  It added no transaction logic.  

I ended up using the SynchronousTransactionManager directly in my own method (similar to GORM's withTransaction()).   I understand why this javax annotation does not work outside of the Micronaut processed classes.  It is just a marker annotation and needs some annotation processor to do something with it.

Thanks.

**Comment by graemerocher** [comment]
I'm not aware of a case where `@Transactional` doesn't work. The rule is it needs to be a bean, which is the same as spring
