### ISSUE TITLE
Unable to implement Repository method with java repository and Kotlin data class as Entity

### ISSUE THREAD

**Issue by braeluca** [micronaut-projects/micronaut-data#380]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create Micronaut Data application in Java
2. Create Kotlin data class as Entity
3. Create JdbcRepository for Entity in Java
4. Build project

### Expected Behaviour

Project should build without error.

### Actual Behaviour

Gradle build fails at step kaptKotlin with message:

```
> Task :kaptKotlin
e: error: Unable to implement Repository method: BookRepository.update(Object arg0). Invalid query method [update] of repository [de.braeluca.javakotlin.BookRepository]: No id found for name entity: null
> Task :kaptKotlin FAILED
```

### Environment Information

- **Operating System**: Windows 10 
- **Micronaut Version:** 1.3.0.RC1
- **JDK Version:** 1.8

### Example Application

- https://github.com/braeluca/micronaut-data-java-kotlin

However, if you replace @Id with @EmbeddedId and make corresponding changes to Entity and Repository, it will work just fine.

**Comment by outersky** [comment]
I copied your Entity and Repository, then tested with 'io.micronaut.data:data-jdbc:1.0.1.BUILD-SNAPSHOT' and micronautVersion=1.3.0, everything seems ok.

[demo project](https://github.com/outersky/micronaut-data-bug-mappedsuperclass)

**Comment by braeluca** [comment]
For me it still does not seem to work. In my example application i changed to version to 1.0.1.BUILD-SNAPSHOT but still get the error. Am I missing something?

**Comment by graemerocher** [comment]
The issue is that you have the Kotlin and Java sources both under `src/main/java`

Kotlin sources should be under `src/main/kotlin`

**Comment by braeluca** [comment]
Still does not work.

**Comment by graemerocher** [comment]
The annotation has to be applied to the field:

```kotlin
@field:Id
var id: String? = null
```

**Comment by braeluca** [comment]
Thanks it works now
