### ISSUE TITLE
Many to Many Relationship with additional properties

### ISSUE THREAD

**Issue by alberto-pelosi** [micronaut-projects/micronaut-data#381]
Hi,

I'm using micronaut data JDBC. How can I map a Many To Many relationship with additional properties:

Table A
id

Table A-B
id_a
id_b
additional_property

Table B

Thanks 

Alberto

**Comment by graemerocher** [comment]
Right now you would use a mapping class:

```
class A {
     @OneToMany    
     Set<AB> abs;
}
class AB {
    A a;
    B b;
    String additionalProperty;
}

class B {
     @OneToMany    
     Set<AB> abs;
}
```

**Comment by alberto-pelosi** [comment]
Ok, thank you very much!

Alberto
