### ISSUE TITLE
Mistake in a repository generates incorrect query

### ISSUE THREAD

**Issue by dstepanov** [micronaut-projects/micronaut-data#389]
`@Query("UPDATE NotificationStatus SET read = :read, readOn = :readOn WHERE id = :id and userId = :userId and read = FALSE")
    void updateNotificationReadStatus(@Id Long id, String userId, boolean read, LocalDateTime readOn);`

`@Id` is redundant and shouldn't be there, somehow all parameters saved as p1, p2.

**Comment by sdelamo** [comment]
@dstepanov  do you have a sample app? How does `NotificationStatus` entity look like?

**Comment by dstepanov** [comment]
```
public class NotificationStatus {
    @Id
    private Long id;
...
}
```
The bug here is that a query is defined and `@Id` doesn't make sense here and causes this problem.
