### ISSUE TITLE
[docs] Example on `Updating Data` is confusing and doesn't render properly

### ISSUE THREAD

**Issue by fredgalvao** [micronaut-projects/micronaut-data#392]
The example on https://micronaut-projects.github.io/micronaut-data/latest/guide/#dataUpdates, more specifically on `partial  updates`, is both confusing $1 and not rendering properly $2.

$1: How come the kotlin version of the `update` method accepts a nullable `id`? As I see it, the update method requires an identifier/finder to properly update anything, otherwise this could be a noop or failed operation. If any of these is the case, then maybe the docs could state so. If not, then the kotlin example needs to change, and maybe the groovy and java ones could use `@NotNull` too. The same underlying question applies to the version of `update` based on a "finder expression" (what happens if it doesn't find a target to update), but the answer in that case is more obvious: nothing, or `return 0`).

$2: The consecutive snippet tags at the end of `dataUpdates.adoc` are somehow creating two overlapping language selectors when rendered, and the examples are not rendering completely

![image](https://user-images.githubusercontent.com/616464/73836477-a4835080-480f-11ea-9888-89385926c128.png)

**Comment by graemerocher** [comment]
Fixed the rendering issue. As for why it has to be `id?` well I would have to ask you the same question as a Kotlin user. Seems that Kotlin represented nullable types different to normal types, so if I change it to just `id` a compilation error occurs.

The Koltlin JPA plugin seems to make the `id` of `Book` into a nullable type (as it should be) and for queries the types have to match. This is not an issue with Groovy and Java but something specific to Kotlin.

**Comment by fredgalvao** [comment]
My perspective was more towards how can I update a specific identifiable object if I provide a null identifier.
I understand that the modeling itself needs to account for unsaved instances and partial states, and thus the identifier itself (on the domain) needs to be nullable.
And I can now also see why it would be difficult to dissociate the identifier as a <parameter method> from the identifier as a <domain field>, but I figured it would be worth asking anyway.
If the method could assure that the <parameter method> is `@NotNull`, while still respecting/coexisting with the <domain field> being `@Null`, that would make for a better API for kotlin users, in my perspective. But it's definitely not "a bug".

Thanks for your time, @graemerocher !
