### ISSUE TITLE
Postgres auto-generated ID schema not working

### ISSUE THREAD

**Issue by lightbody** [micronaut-projects/micronaut-data#40]
I'll try to get a PR together soon, but just getting this recorded as a bug before I forget:

https://github.com/micronaut-projects/micronaut-predator/blob/233bbb94d3e8fe23fe089f1bdcbca7600d1f6659/predator-model/src/main/java/io/micronaut/data/model/query/builder/sql/SqlQueryBuilder.java#L245

The code clearly things the keyword "GENERATED" is the right way to declare an auto incrementing ID in Postgres. But that isn't true :) Instead, they recommend the data type be SERIAL or BIGSERIAL as per these docs:

https://www.postgresql.org/docs/8.1/datatype.html#DATATYPE-SERIAL

Unfortunately, the way the code is currently structured it makes it a bit hard to quickly patch this so I'll have to spent more time before I can send back a test + PR.

**Comment by graemerocher** [comment]
It is actually supported. See http://www.postgresqltutorial.com/postgresql-identity-column/

However only since Postgres 10, older versions are out of luck.

**Comment by graemerocher** [comment]
Support for sequences added in https://github.com/micronaut-projects/micronaut-data/commit/ac7560eb95c9ba8bee571259ada7bf5067827a7c
