### ISSUE TITLE
@EntityGraph not picked up if neither attributePaths is set nor @QueryHint isn't present as well

### ISSUE THREAD

**Issue by ThommyGo** [micronaut-projects/micronaut-data#406]
I was trying to add a load method to a repository that would actually have to fetch 2 levels of additional properties. 

For a better understanding let's reuse the example provided here: https://github.com/micronaut-projects/micronaut-data/issues/167#issuecomment-534889558
However, in contrast to the example I'm using a `JpaSpecificationExecutor<Shelf>`.

What didn't work:
- `@Join(value = "books.pages", type = Join.Type.LEFT_FETCH)` resulted in a query like `... JOIN shelf0_.pages as books_pages_` which clearly is wrong (and most likely an issue on its own).
- `@EntityGraph(attributePaths = {"books", "books.pages"})` or just `@EntityGraph(attributePaths = "books.pages")` resulted in attribute named "books.pages" not being found on `Shelf` (of course that doesn't exist because those are nested)

So I decided to use a proper `@NamedEntityGraph` and refer to that via `@EntityGraph(name="myNamedGraph")`.

Expected behavior: the named entity graph should be used

Actual behavior: the entity graph got ignored (verified by debugging `io.micronaut.data.hibernate.operations.HibernateJpaOperations.bindQueryHints(Query<?>, PagedQuery<T>, Session)`)

Workarounds:
1. add `attributePaths = ""` to `@EntityGraph`
2. add `@QueryHint( name = "javax.persistence.loadgraph", value = "dummy" )` (`"javax.persistence.fetchgraph` would work as well)

Used library versions:
- micronaut 1.3.0
- micronaut-data-hibernate-jpa 1.0.0
- micronaut-data-spring-jpa 1.0.0
- micronaut-data-spring 1.0.0

**Comment by dinesh-varyani** [comment]
@ThommyGo  - The workaround you provided works well with Micronaut 1.3.2. This approach doesnt work when i upgraded the Micronaut to 2.0. 
Is there any way around to make this work without making much changes to entities ?
