### ISSUE TITLE
GraalVM native-image build error

### ISSUE THREAD

**Issue by morki** [micronaut-projects/micronaut-data#409]
Building example https://github.com/micronaut-projects/micronaut-data/tree/master/examples/example-jpa with `native-image` produces binary (seems working) but shows errors.

### Steps to Reproduce

1. Checkout https://github.com/micronaut-projects/micronaut-data/tree/master/examples/example-jpa
2. run `./gradlew assemble`
3. run `native-image --no-server -cp build/libs/example-jpa-0.1-all.jar`

### Expected Behaviour

Binary is produced and no errors are reported.

### Actual Behaviour

Binary is produced and below errors are reported:

```
Error: Classes that should be initialized at run time got initialized during image building:
 org.jboss.logging.Slf4jLocationAwareLogger was unintentionally initialized at build time. To see why org.jboss.logging.Slf4jLocationAwareLogger got initialized use -H:+TraceClassInitialization
org.jboss.logging.Logger was unintentionally initialized at build time. To see why org.jboss.logging.Logger got initialized use -H:+TraceClassInitialization
org.hibernate.internal.CoreMessageLogger_$logger was unintentionally initialized at build time. To see why org.hibernate.internal.CoreMessageLogger_$logger got initialized use -H:+TraceClassInitialization
org.jboss.logging.LoggerProviders was unintentionally initialized at build time. To see why org.jboss.logging.LoggerProviders got initialized use -H:+TraceClassInitialization
org.jboss.logging.LoggingLocale was unintentionally initialized at build time. To see why org.jboss.logging.LoggingLocale got initialized use -H:+TraceClassInitialization
org.jboss.logging.DelegatingBasicLogger was unintentionally initialized at build time. To see why org.jboss.logging.DelegatingBasicLogger got initialized use -H:+TraceClassInitialization

Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1
```

### Environment Information

- **Operating System**: Linux Fedora
- **Micronaut Version:** 1.2.9
- **JDK Version:** 
```
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-b06)
OpenJDK 64-Bit GraalVM CE 19.3.1 (build 25.242-b06-jvmci-19.3-b07, mixed mode)
```

**Comment by graemerocher** [comment]
Rather than trying to fix since it appears to be a problem in a newer version of Hibernate I recommend we remove Micronaut's Hibernate metadata and use the new Hibernate GraalVM metadata https://in.relation.to/2020/02/14/hibernate-orm-5-4-12/

**Comment by morki** [comment]
@graemerocher is there something I can do to help with it?

**Comment by morki** [comment]
After adding dependency `implementation "org.hibernate:hibernate-graalvm:5.4.12.Final"` it fails fast with:

```
[example-jpa:26925]    classlist:  10,655.59 ms
[example-jpa:26925]        (cap):   1,289.40 ms
[example-jpa:26925]        setup:   2,841.39 ms
[example-jpa:26925]     analysis:  26,516.36 ms
Error: Classes that should be initialized at run time got initialized during image building:
 org.hibernate.internal.util.ReflectHelper was unintentionally initialized at build time. To see why org.hibernate.internal.util.ReflectHelper got initialized use -H:+TraceClassInitialization

Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1
```

**Comment by Uniqen** [comment]
@morki I recommend looking at https://github.com/micronaut-graal-tests/micronaut-data-jpa-graal/tree/h2 . Basically the same example but working with GraalVM.

**Comment by graemerocher** [comment]
Fixed using the snapshots, as a workaround you can add the following flags:

```
--initialize-at-build-time=org.jboss.logging,org.hibernate.internal,org.hibernate.jmx,org.hibernate.query
```
And also add `com.zaxxer.hikari.util.ConcurrentBag$IConcurrentBagEntry[]` in the @TypeHint annotation in Application.java.
