### ISSUE TITLE
Reactive sql support via r2dbc

### ISSUE THREAD

**Issue by drmaas** [micronaut-projects/micronaut-data#416]
I was reading about https://github.com/spring-projects/spring-data-r2dbc and I think a reactive sql dsl, mapper, and repository would be useful. This would probably leverage the same interfaces used by other reactive drivers for cassandra, mongo, elastic, etc.

**Comment by graemerocher** [comment]
Agreed it is planned

**Comment by graemerocher** [comment]
Done in https://github.com/micronaut-projects/micronaut-r2dbc
