### ISSUE TITLE
Using Micronaut Data in Spring app

### ISSUE THREAD

**Issue by raderio** [micronaut-projects/micronaut-data#421]
I am trying to define a repository and entity classes and use them in Spring app/context. After this I try to inject the repository in Spring Service but I receive an exception that bean for that repository can not be found.

Is there an example how to use Micronaut Data in Spring app/context?

**Comment by raderio** [comment]
@graemerocher so this is possible as I understand and just a documentation should be added?

**Comment by graemerocher** [comment]
You can probably do it with a custom spring configuration. Something like:

```
import org.springframework.context.annotation.*;

@Configuration
class SpringConfig {
       @Bean(destroyMethod="close")
       ApplicationContext context()  {
             return ApplicationContex.run()
        }

      @Bean
      MyRepository myRepository() {
           return context().getBean(MyRepository.class);
      }
}
```

Alternatively you could try to Micronaut parent context approach provided by Micronaut for Spring https://micronaut-projects.github.io/micronaut-spring/latest/guide/index.html#springParentContext
