### ISSUE TITLE
TransactionAwareDataSource incompatible with micronaut-flyway

### ISSUE THREAD

**Issue by lightoze** [micronaut-projects/micronaut-data#435]
While testing 1.0.1.BUILD-SNAPSHOT I found out that it breaks micronaut-flyway. It looks like `TransactionAwareDataSource` is implemented in such way that it counts on `getTransactionAwareConnection()` call being deferred (because that depends on proxied `Connection` bean which depends on `DataSource` bean which creates a loop).

Flyway `DataSourceMigrationRunner` is also implemented as `BeanCreatedEventListener<DataSource>` which executes after `TransactionAwareDataSource`, so it triggers `DataSource.getConnection()` immediately and goes into infinite loop which is only broken when DB connection limit is reached.

### Environment Information

- **Micronaut Version:** 1.3.2

**Comment by graemerocher** [comment]
I guess flyway needs to unwrap the datasource or run before `TransactionAwareDataSource`

**Comment by lightoze** [comment]
Is there a way to affect BeanCreatedEventListener ordering? Unwrapping would be nice but flyway integration knows nothing about data-tx API.

**Comment by graemerocher** [comment]
Yes they can be made to implemented `Ordered`
