### ISSUE TITLE
JDBC Mapping ManyToOne buggy for Null References

### ISSUE THREAD

**Issue by Danny02** [micronaut-projects/micronaut-data#466]
### Steps to Reproduce

1. use JDBC mapping
2. create entity with javax.persistence.ManyToOne Mapping to another Entity
3. make all entity properties final
3. save entity with relation property set to `null`

### Expected Behaviour

I should be able to save such an entity, load it from the database and be able to save it again to it with updated data.

### Actual Behaviour

Depending on what constructors are available in the base and related entity, some of the operations (insert,query,update) will fail with an exception or return different values.

* base entity has only a full constructor(all props). If the related Entity has an empty constructor, then there will be an exception on query. If the related Entity only has an full constructor, then a query return an entity with an related entity instance with its id field unset. Such an empty related entity can not be saved by an update repository method.
* if the base entity has an constructor without the related entity, then no exception are throw, but the relation is never set in a query even if the db has a value for it.

Everything seems to work, if all Entities use no immutable fields, have an empty constructor and setter for all fields.

### Solution
The mapper should preferably use the constructor with all properties and just set relation entities to the value `null` in the constructor.

### Environment Information

- **Operating System**: macos
- **Micronaut Version:** 1.3.3. data 1.0.1
- **JDK Version:** 11

### Example Application

https://github.com/Danny02/micronaut-date-manytoone-bug

**Comment by graemerocher** [comment]
Think this should be a compilation error. There shouldn't be a way to create a persistent entity that has no way to update a property

**Comment by radovanradic** [comment]
@graemerocher I looked at options to throw compilation error. However, unlike `RuntimePersistentEntity` that has got method `getConstructorArguments` that could be used here, if prop is readonly and not in constructor arguments then we can throw the error. Didn't find something similar in `SourcePersistentEntity` or `ClassElement` which has method to return default constructor with 0 parameters. 
That being said, I think this issue is mainly wrong configuration or mapping, simply changing constructors to accept final field would resolve the issue and also marking it as `@Nullable`.

**Comment by radovanradic** [comment]
Considering this is an old issue and can be resolved by changing configuration/mapping:
1. MyOther has got pk String with `@GeneratedValue` annotation which is not supported. Should be Long. 
2. Also MyEntity does not have setup cascade for MyOther entity and thus cannot be saved when saving MyEntity and it does not have join `@Join(value = "other", type = Join.Type.LEFT)` defined on repository.
3. Adding proper constructors with all final fields annotated potentially with `@Nullable` would resolve the issue, or change fields to not be readonly.

will close this issue now. If OP has questions we can send details how to resolve this via mapping changes and in Micronaut 4.x.
