### ISSUE TITLE
When save a persist entity,will create a new one,but not update the fields.

### ISSUE THREAD

**Issue by gwyenu** [micronaut-projects/micronaut-data#484]
Hi,we use Micronaut in our project.
Everything is well but except one thing that like the title,When save a persist entity,will create a new one,but not update the fields.
The operation is follow:
1.Declare a repository extends CrudRepository
2.Save a entity whatever it is
3.Select it,update single field like "one" -> "nine"
4.Use 'save' method

Then,we found a new entity in our DB.
I think it should be updated,not insert a new one.And in the micronaut-data guide page:
https://micronaut-projects.github.io/micronaut-data/latest/guide/#dataUpdates
I found the information like that it said:"
**To insert data the simplest form is to define a method that accepts the type of the entity, the same way as the CrudRepository interface does:

Book persist(Book entity);
The method must accept a single argument that is the entity and start with either save, persist, insert or store.**"

After this,I check the source code about micronuat-data,found this in RepositoryTypeElementVisitor:
 if (runtimeInterceptor.getSimpleName().startsWith("Save")) {
                                    try {
                                        QueryResult queryResult = queryEncoder.buildInsert(currentRepository.getAnnotationMetadata(), entity);

I debug the source code when debuging,it shows like the title descript.

**Comment by sdelamo** [comment]
Maybe,  `repository.update(entity.getId(), entity)` is what you are looking for.

**Comment by graemerocher** [comment]
Is this for JDBC or Hibernate?

**Comment by gwyenu** [comment]
That's micronaut jdbc



发自我的iPhone


------------------ Original ------------------

**Comment by graemerocher** [comment]
JDBC requires specific update methods since there is no dirty checking
