### ISSUE TITLE
Entity changes not picked up by IDE compiler

### ISSUE THREAD

**Issue by lightbody** [micronaut-projects/micronaut-data#49]
[hello-world.zip](https://github.com/micronaut-projects/micronaut-predator/files/3429028/hello-world.zip)

The attached project reliably demonstrates the problem I am facing when doing development in my IDE: IntelliJ IDEA 2019.2 (also verified same behavior in 2019.1).

In case the IDEA project file didn't come through, I did what the main [Micronaut instructions suggest](https://docs.micronaut.io/1.2.0.RC2/guide/index.html#ideSetup), namely ensuring that annotation processors are enabled.

The steps to reproduce are as follows:

First, to see this does not happen using the Gradle build run `./gradlew run` and note this log message:

> DEBUG io.micronaut.data.query - Executing SQL Insert: INSERT INTO book (title,id) VALUES (?,?)

Then, edit `src/main/java/hello/world/Book.java` and remove the `title` field by commenting the four areas identified. The result should be that the only reference to `title` remains as the second constructor argument.

Now re-run `./gradlew run` and note this log message:

> DEBUG io.micronaut.data.query - Executing SQL Insert: INSERT INTO book (id) VALUES (?)

This is expected: we've removed a field so the new schema is just a single column.

Next, demonstrate the problem in the IDE environment. Run `./gradlew clean` just to be sure there is no conflict with the IDE's build (it stores in `out` but this ensures no confusion). 

Now open the project in IntelliJ IDEA if you haven't already. Remove the comments you just added to the `Book` class so that it once again has two fields. Now find the `Application` class, right click, and run it. You will see the following log output:

> DEBUG io.micronaut.data.query - Executing SQL Insert: INSERT INTO book (title,id) VALUES (?,?)

Next, re-comment out those same lines in `Book` and re-run `Application`. Instead of the expected INSERT statement we saw above in the Gradle build, we instead see this error:

> 16:01:13.631 [main] DEBUG io.micronaut.data.query - Executing SQL Insert: INSERT INTO book (title,id) VALUES (?,?)
16:01:13.646 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: SQL Error executing INSERT: Column "TITLE" not found; SQL statement:
INSERT INTO book (title,id) VALUES (?,?) [42122-199]

What seems to be happening is that the IntelliJ IDEA build system and/or the annotation processors are not correctly doing the right thing once `Book.java` was changed. The `Book` class clearly gets recompiled, but it seems that some of the generated classes are not. The result is the Predator thinks there is still a `title` field when doing an insert, but not when creating the schema.

**Comment by graemerocher** [comment]
So the issue here is that simply changing the `Book` class is not enough. IntelliJ performs an incremental compile of just the `Book` class but not the `BookRepository` interface. The `BookRepository` interface continues to contain the precomputed queries for the previous state of the `Book` class. If you make any kind of modification to the `BookRepository` then  the issue is resolved.

Now this is not ideal, however I am unsure at this stage what can be done about it from our end.

**Comment by lightbody** [comment]
I figured it was something like that. Good to know that if I touch the Repository and the entity that should do it. Just curious: why does it work with the Gradle compiler?

**Comment by graemerocher** [comment]
Gradle is more conservative and recompiles more of the sources it seems. IntelliJ is more aggressive its incremental compilation handling and only recompiles the `Book` class
