### ISSUE TITLE
List params are not expanded in native queries

### ISSUE THREAD

**Issue by ctoestreich** [micronaut-projects/micronaut-data#496]
The query below is not expanded into for the list and an exception is thrown
```
  @Query(value = "select t.* from hcp_tenant t " +
            "join hcp_tenant_consumer tc on tc.tenant_id = t.id and tc.topic_id in :topicIds",
            nativeQuery = true)
    Set<HcpTenantDTO> findByConsumersTopicsIdInList(List<Long> topicIds);
```

I have tried `(:topicIds)` as well but same result as the expansion isn't happening

```
SELECT hcp_topic_.`id`,hcp_topic_.`name`,hcp_topic_.`partitions`,hcp_topic_.`config`,hcp_topic_.`email`,hcp_topic_.`ms_id`,hcp_topic_.`compatibility`,hcp_topic_.`aha_id` FROM `hcp_topic` hcp_topic_ INNER JOIN `hcp_org` hcp_topic_hcp_org_ ON hcp_topic_.`hcp_org_id`=hcp_topic_hcp_org_.`id` INNER JOIN `hcp_env` hcp_topic_hcp_org_env_ ON hcp_topic_hcp_org_.`env_id`=hcp_topic_hcp_org_env_.`id` WHERE (hcp_topic_hcp_org_env_.`id` = ?)
10:09:13.254 [pool-2-thread-7] DEBUG io.micronaut.data.query - Executing Query: select t.* from hcp_tenant t join hcp_tenant_consumer tc on tc.tenant_id = t.id and tc.topic_id in ?
10:09:13.290 [pool-2-thread-7] ERROR i.m.h.s.netty.RoutingInBoundHandler - Unexpected error occurred: Unable to set PreparedStatement value: Parameter index out of range (2 > number of parameters, which is 1).
io.micronaut.data.exceptions.DataAccessException: Unable to set PreparedStatement value: Parameter index out of range (2 > number of parameters, which is 1).
	at io.micronaut.data.jdbc.mapper.JdbcQueryStatement.newDataAccessException(JdbcQueryStatement.java:273)
	at io.micronaut.data.jdbc.mapper.JdbcQueryStatement.setLong(JdbcQueryStatement.java:139)
	at io.micronaut.data.jdbc.mapper.JdbcQueryStatement.setLong(JdbcQueryStatement.java:33)
	at io.micronaut.data.runtime.mapper.QueryStatement.setDynamic(QueryStatement.java:134)
	at io.micronaut.data.jdbc.mapper.JdbcQueryStatement.setDynamic(JdbcQueryStatement.java:92)
	at io.micronaut.data.jdbc.mapper.JdbcQueryStatement.setDynamic(JdbcQueryStatement.java:33)
...

Caused by: java.sql.SQLException: Parameter index out of range (2 > number of parameters, which is 1).
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.ClientPreparedStatement.checkBounds(ClientPreparedStatement.java:1402)
	at com.mysql.cj.jdbc.ClientPreparedStatement.getCoreParameterIndex(ClientPreparedStatement.java:1415)
	at com.mysql.cj.jdbc.ClientPreparedStatement.setLong(ClientPreparedStatement.java:1610)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.setLong(HikariProxyPreparedStatement.java)
	at io.micronaut.data.jdbc.mapper.JdbcQueryStatement.setLong(JdbcQueryStatement.java:137)
	... 127 common frames omitted


```

**Comment by ctoestreich** [comment]
This nested query using generated sql would not work due to #457

**Comment by ctoestreich** [comment]
On a positive note, I am able to work around this using the jdbc abstract pattern and the below code.

```java
@JdbcRepository(dialect = Dialect.MYSQL)
@AllArgsConstructor
public abstract class HcpTenantListRepository implements CrudRepository<HcpTenant, Long> {

    private final JdbcOperations jdbcOperations;

    public Set<HcpTenantDTO> findTenantsInTopicIds(List<Long> topicIds) {
        String sql = "select t.* from hcp_tenant t join hcp_tenant_consumer tc on tc.tenant_id = t.id and tc.topic_id in (:topicIds)";
        sql = sql.replace(":topicIds", String.join(",", Collections.nCopies(topicIds.size(), "?")));
        return jdbcOperations.prepareStatement(sql, statement -> {
            for (int i = 0, topicIdsSize = topicIds.size(); i < topicIdsSize; i++) {
                final Long topicId = topicIds.get(i);
                statement.setLong(i+1, topicId);
            }
            ResultSet resultSet = statement.executeQuery();
            return jdbcOperations.entityStream(resultSet, HcpTenantDTO.class).collect(Collectors.toSet());
        });
    }
}
```

**Comment by Deniz97** [comment]
I am facing the same problem:

```
@Query("SELECT DISTINCT b.* " +
         "FROM  (SELECT * " +
         "            FROM category " +
         "            WHERE id IN (:ids) ) as a " +
         "join category as b on a.parent_id = b.id or a.id = b.id ")
  List<Category> selectWithParents(Collection<Long> ids);
```

`io.micronaut.data.exceptions.DataAccessException: Unable to set PreparedStatement value: Invalid value "2" for parameter "parameterIndex" [90008-200]`

Any updates on this?

**Comment by nhoughto** [comment]
yeah this is annoying, i guess we are looking for `PreparedStatement setArray()`
https://docs.oracle.com/javase/8/docs/api/java/sql/PreparedStatement.html#setArray-int-java.sql.Array-

which JdbcQueryStatement class doesn't seem to expose, but you can do via JdbcOperations obviously, but if using Postgres you can use functions to split 1->N records

```
@Query("DELETE FROM table WHERE id = ANY(cast(string_to_array(:ids, ',') as bigint[]))")
    protected abstract Number deleteForIds(String commaDelimeteredIds);
```

other wise jdbcOperations is maybe a bit more straightforward:
```
protected Number deleteForIds(Set<Long> ids) {
        return jdbcOperations.prepareStatement("DELETE FROM table WHERE id = any (?)", statement -> {
            Array arrayOfIds = statement.getConnection().createArrayOf("bigint", userIds.toArray());
            statement.setArray(1, arrayOfIds);
            return statement.executeUpdate();
        });
    }
```

**Comment by nhoughto** [comment]
both approach seems to be vendor specific, not all databases support createArrayOf, and obviously the splitting and casting is vendor specific.. so not sure if this is solvable by upstream 🤔

**Comment by graemerocher** [comment]
Seems that `createArrayOf` is probably the way to go but we would have to add vendor specific hacks, like https://stackoverflow.com/a/7879073/259167

**Comment by cemo** [comment]
@graemerocher what about something like as in [spring](https://github.com/spring-projects/spring-framework/blob/master/spring-jdbc/src/main/java/org/springframework/jdbc/core/namedparam/NamedParameterUtils.java#L286-L310):

```
if (value instanceof Iterable) {
    Iterator<?> entryIter = ((Iterable<?>) value).iterator();
    int k = 0;
    while (entryIter.hasNext()) {
        if (k > 0) {
            actualSql.append(", ");
        }
        k++;
        Object entryItem = entryIter.next();
        if (entryItem instanceof Object[]) {
            Object[] expressionList = (Object[]) entryItem;
            actualSql.append('(');
            for (int m = 0; m < expressionList.length; m++) {
                if (m > 0) {
                    actualSql.append(", ");
                }
                actualSql.append('?');
            }
            actualSql.append(')');
        }
        else {
            actualSql.append('?');
        }
    }
}
```

**Comment by cemo** [comment]
I think it has already support for generated queries. Would you please guide me necessary changes to solve issue for not generated queries?

https://github.com/micronaut-projects/micronaut-data/blob/92b1787563836c82e3ecd789755e02db4f4a6a9f/data-jdbc/src/main/java/io/micronaut/data/jdbc/operations/DefaultJdbcRepositoryOperations.java#L849-L885

**Comment by nhoughto** [comment]
ah interesting..

so the regex is `Pattern.compile("\\s\\?\\$IN\\((\\d+)\\)")` which isn't what i'd expect, matches values like `.. $IN(1)`
with the literal `$`.. have to look at the tests i guess

**Comment by cemo** [comment]
This part is running after repository processed. The annotation processor must generate necessary replacement code as in this piece of code. I will take a look today. @graemerocher I will be glad if you point me necessary changes or where should I look.

**Comment by graemerocher** [comment]
I'm not sure myself :D 

I guess you would have to check if it is a native query and the parameter is a list or array then somehow create the necessary `createArrayOf` calls, however there would need to be custom code for Oracle where this is not supported

**Comment by cemo** [comment]
@graemerocher 

I had chance to understand internals of it. But still remaining little tricky part maybe you can suggest a better solution. First of all current implementation is almost ready to work. I added a test case like this.

https://github.com/cemo/micronaut-data/commit/a644d4fb0b0466e5a6f5e5af8d4f537e92f0330c

In order to make our test to work we need a some changes. The relevant change needs in before line 842.

https://github.com/micronaut-projects/micronaut-data/blob/41bf6cff900e08089d8681798e2dac9bd5fd4dba/data-runtime/src/main/java/io/micronaut/data/runtime/intercept/AbstractQueryInterceptor.java#L827-L852

I added a repository method as:

```
  @Query("SELECT * FROM person WHERE name != :names1 or name IN(:names3) or name IN(:names0)")
  List<Person> queryNames(List<String> names0, String names1, List<String> names2, List<String> names3);
```

The query is changed like this:

>   @Query("SELECT * FROM person WHERE name != ? or name IN(?) or name IN(?)")

However it must be changed like this since IN parameters must be delegated to runtime. 

>  @Query("SELECT * FROM person WHERE name != ? or name ?$IN(2) or name ?$IN(3)

This requires substantial knowledge of regex because of lookahead and lookbehind concepts. :) Do you have any idea to change into this easily 😂 

By the way for further reference you can see details in https://github.com/micronaut-projects/micronaut-data/blob/41bf6cff900e08089d8681798e2dac9bd5fd4dba/data-jdbc/src/main/java/io/micronaut/data/jdbc/operations/DefaultJdbcRepositoryOperations.java#L866

**Comment by cemo** [comment]
@haeken gave a try for regex part 🥇 I think it is ready to be reviewed.

**Comment by zhuravskiy** [comment]
bug still exists if your query with formating like `in (  :param)` or `in ( \n :param \n)` 

https://github.com/micronaut-projects/micronaut-data/pull/779/files#diff-baf2466cae22f30902d5253545dded463e5cde1135628ec712ba3e8fa948685fR852

your query should have strict formatting like `IN(:param)` and if you put space somewhere, the bug will be reproduced.

**Comment by cemo** [comment]
Would you give a try to fix regex @zhuravskiy?  :)
