### ISSUE TITLE
OR and AND in a query

### ISSUE THREAD

**Issue by ghahramani** [micronaut-projects/micronaut-data#507]
Hi,

I tried this combination with no success `findAllByWordContainsOrCommentContainsAndUser(x,x,y)` it shows me an error but as soon and I changed the `And` to `Or`; it works. But a combination of `OR` and `AND` does not work together. 

I thought it is supporting what Spring Data support, but it seems it has some limitation as I could easily query like that in Spring Data.

Any help with this?

**Comment by graemerocher** [comment]
so the question is (and I ask this of Spring Data as well) does that mean:

```
(word.contains(x) || comment.contains(x)) && user == y
```

Or does it mean:

```
word.contains(x) || (comment.contains(x) && user == y)
```

For me personally that method signature is ambiguous and could mean either hence why we (and GORM which Micronaut data is based on) don't support that.

**Comment by ghahramani** [comment]
Neither of them, it will be (no parentheses):

```
word.contains(x) || comment.contains(x) && user == y
```

And depends on database priority in precedence, it runs the query. For instance in SQL server, `AND` takes precedence over `OR`, so in my example, it will be like below in SQL server:
```
word.contains(x) || (comment.contains(x) && user == y)
```

**Comment by graemerocher** [comment]
seems a slippery slow but ok, the origins of this behaviour go back to GORM actually where we restricted the number of logical branches to avoid folks abusing finders and defining ridiculously long method names which become unreadable.

**Comment by ghahramani** [comment]
I think limiting to 4 conditions should be fine for most cases, or if it is possible, be configurable.
So, is there a way to support this right now? Or it will be released in future releases?

**Comment by graemerocher** [comment]
Not currently no, but we will consider it for a future release
