### ISSUE TITLE
Default Naming Strategy still not registering automatically

### ISSUE THREAD

**Issue by arnaldop** [micronaut-projects/micronaut-data#520]
This is based on https://github.com/micronaut-projects/micronaut-sql/issues/17 and https://github.com/micronaut-projects/micronaut-data/issues/103.

The DefaultPhysicalNamingStrategy, which is supposed to be registered by default, is still not being picked up automatically.

At the bottom of https://github.com/micronaut-projects/micronaut-data/issues/103, @lucasmogari pointed out that it's not working, and then provided the workaround of explicitly defining it. His solution is what works for me, but it should not be necessary with the "default" option.

### Task List
The primary thing I did to verify the process was to place a breakpoint at the class `DefaultPhysicalNamingStrategy`.  When I explicitly configure it:
```
jpa:
  default:
    properties:
      hibernate:
        physical_naming_strategy: "io.micronaut.data.hibernate.naming.DefaultPhysicalNamingStrategy"
```
it works. When I remove the configuration line, `DefaultPhysicalNamingStrategy` is no longer loaded.

I am using micronaut-data-hibernate-jpa v1.0.2, which contains the new naming strategy class.

### Steps to Reproduce

1. Exclude the `hibernate.physical_naming_strategy` property.
2. Define an @Entity with camel case convention, such as `ownerAge`.
3. Use Flyway to create the `owner` table with the field `owner_age`.
4. Hibernate/Flyway will have issues because of naming convention.

### Expected Behaviour
This should be seen in the logs without explicitly setting the naming strategy.
```
Hibernate: insert into owner (name, owner_age, id) values (?, ?, ?)
```

### Actual Behaviour
Instead, this appears in the logs. Note capitalization instead of underscores.
```
Hibernate: insert into Owner (name, ownerAge, id) values (?, ?, ?)
```
This becomes a problem creating the database using external means (i.e. Flyway).

### Environment Information

- **Operating System**: OSX 10.15.4
- **Micronaut Version:** 1.3.4
- **Micronaut Data Version:** 1.0.2
- **JDK Version:** openjdk 11.0.7 2020-04-14

### Example Application

- https://github.com/arnaldop/default-naming-strategy-problem

**Comment by graemerocher** [comment]
There is no release with this fix yet, that is why

**Comment by arnaldop** [comment]
The code is present in the 1.2.0 codebase. I can step into it in my IDE.

When you say there is no release, what do you mean?

**Comment by mattlong-finocomp** [comment]
I'm using micronaut-data 1.1.3 and im still seeing this behaviour. Had to use the mentioned workaround.
