### ISSUE TITLE
Extending Micronat Data Annotation

### ISSUE THREAD

**Issue by ghahramani** [micronaut-projects/micronaut-data#523]
Hi,

I tried to add my custom annotation to a property with `@AutoPopulated` in how you did for `@DateCreated`. I realized the magic happens in `setInsertParameters` method of `AbstractSqlRepositoryOperations` class; I tried to override it so I could add my custom annotation implementation but, unfortunately; it is marked as `final` 
```
protected final <T> void setInsertParameters(@NonNull StoredInsert<T> insert, @NonNull T entity, @NonNull PS stmt)
```
So I guess that is not the right way I am trying to do.

Could you please suggest me a way that I can add my annotation implementation and trigger it whenever save or update happens?
I am trying to create something similar to `@DateCreated` but for the creator, `@CreatedBy` which takes the current user as the creator and updates the field.

**Comment by graemerocher** [comment]
Currently the annotation types are not very extensible, partly for performance reasons. We will see if we can improve this in the next version. The idea is to add an event API

**Comment by dstepanov** [comment]
It's possible to implement it with the events API in the latest version.
