### ISSUE TITLE
Micronaut-data+RDS Graalvm native image not working with instance 

### ISSUE THREAD

**Issue by msandy10** [micronaut-projects/micronaut-data#536]
Hi Team,

We unable to run Micronaut(1.3.4) and micronaut-data(1.0.2) graalvm image on Lambda with RDS instance,RDS DB URL is working fine with micronaut local.

- DB Properties

`
datasources.default.driverClassName=org.mariadb.jdbc.Driver
datasources.default.url=jdbc:mysql://rdsurl
datasources.default.username=user
datasources.default.password=passcode
datasources.default.maxpoolsize=2
datasources.default.minidle=1
datasources.default.idletimeout=10000
`

- We are getting following error while running graalvm image on lambda 

`
Caused by: io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [javax.sql.DataSource] could not be loaded: Error instantiating bean of type [javax.sql.DataSource]: Failed to initialize pool: Could not connect to address=(host=rds-url)(port=3306)(type=master) : (conn=505562) Access denied for user 'sbx_user1051'@'IP-Address' (using password: NO) 
`

- Gradle dependency screenshot

![image](https://user-images.githubusercontent.com/25841451/82211933-5235ed80-992f-11ea-8ef0-dd98cd3bcbd3.png)

**Comment by ilopmar** [comment]
It seems the database is not reachable from AWS. Have you checked that all the permissions, VPC,... are correct?

**Comment by msandy10** [comment]
VPC Setting looks fine as we are able to use same RDS instance Native Image with micronaut-jdbc-hikari and spring-jdbc dependencies on Lambda

**Comment by graemerocher** [comment]
@msandy10 could you try run with the graalvm tracing agent to see if there is any reflective access going on in your application: https://medium.com/graalvm/introducing-the-tracing-agent-simplifying-graalvm-native-image-configuration-c3b56c486271

**Comment by msandy10** [comment]
@graemerocher We have run tracing agent and added generated reflection details but still getting the same error
[my-app-graal.zip](https://github.com/micronaut-projects/micronaut-data/files/4694110/my-app-graal.zip)

**Comment by cristianorvf** [comment]
arrived via google querying for 'sbx_user1051' (not using microunat.. but like it hehe) this problem happens with lots of JDBC based frameworks when the driver cannot get de credentials, it gets the current system user which in case of aws lambda is sbx_user1051.

problem is clear in the logs ```'sbx_user1051'@'IP-Address' (using password: NO)```  (no credentials)

ps: your application.yaml seems to be the culprit.

**Comment by bittsi-app** [comment]
> [msandy10](/msandy10)

Did you find any solution for your issues? We are facing the same issue.

**Comment by graemerocher** [comment]
As mentioned by @cristianorvf this is a configuration issue. The configuration is not being read with the credentials. If you set the credentials either as environment variables and/or make sure the static resources are included in the image it will be resolved
