### ISSUE TITLE
Document package scanning for JDBC

### ISSUE THREAD

**Issue by jameskleeh** [micronaut-projects/micronaut-data#550]
Looking at the impl, it seems its not necessary, but the option is there to limit the entities to a package. This should be documented outside of the config reference.

**Comment by graemerocher** [comment]
The only use case for this is to limit the entities that create tables which shouldn't be used in production anyway. I have improved the description within the config reference, I am unsure of the need to do anymore in this area as generally you would use a database migration tool and not this feature.
