### ISSUE TITLE
JDBC SQL Server sorts by id when other implementations don't

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-data#560]
After adding support for Micronaut Data JDBC SqlServer in GraalVM I've noticed that the test failed because of the generated query to fetch all the pets adds an "order by".

```sql
SELECT pet_.[name] FROM [pet] pet_ ORDER BY pet_.id ASC OFFSET 0 ROWS FETCH NEXT 100 ROWS ONLY
```

For the other four implementations (h2, oracle, mariadb and postgres) the queries are like:

```sql
SELECT pet_."name" FROM "pet" pet_ LIMIT 100
SELECT pet_."NAME" FROM "PET" pet_
...
```

### Steps to Reproduce

- `git clone https://github.com/micronaut-graal-tests/micronaut-data-jdbc-graal`
- `cd micronaut-data-jdbc-graal`
- `git checkout master_sqlserver`
- Start SQL server using Docker: `docker run -it --rm -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=My!Secret123' -e 'MSSQL_PID=Express' -p 1433:1433 mcr.microsoft.com/mssql/server:2017-latest-ubuntu`
- `./gradlew run`
- `curl localhost:8080/pets`

### Expected Behaviour

The result should be:
```json
[{"name":"Dino"},{"name":"Baby Puss"},{"name":"Hoppy"}]
```

### Actual Behaviour

As `Pet` entity is using an `UUID` as primary key, the order is not always the same and is based on the values generated every time we start the app.

### Environment Information

- **Operating System**: Linux
- **Micronaut Version:** 2.0.0.BUILD-SNAPSHOT
- **JDK Version:** 1.8

**Comment by graemerocher** [comment]
I don't believe there is anything we can do about this. SQL server doesn't allow pagination without order by. See https://stackoverflow.com/questions/42783379/sql-server-pagination-without-order-by-clause

**Comment by graemerocher** [comment]
If you want to make them consistent then don't pass a pageable to the query

**Comment by ilopmar** [comment]
Thanks, I'll do that.
