### ISSUE TITLE
i can't inject  class EntityManager into a subclass that inherits class UpdateEntityInterceptor

### ISSUE THREAD

**Issue by fuchanghai** [micronaut-projects/micronaut-data#568]
I want to inject class EntityManager into a subclass that inherits class UpdateEntityInterceptor，but when i Open the debug model in intellJ while told me class EntityManager  is null

**Comment by fuchanghai** [comment]
![1591239841(1)](https://user-images.githubusercontent.com/33984497/83710358-231fbb80-a653-11ea-9d5a-2c0c780ade37.jpg)

**Comment by graemerocher** [comment]
You can obtain a reference from the `JpaOperations` instance. See https://github.com/micronaut-projects/micronaut-data/blob/master/data-spring-jpa/src/main/java/io/micronaut/data/spring/jpa/intercept/CountSpecificationInterceptor.java for an example

**Comment by fuchanghai** [comment]
Thank you very much. It seems to be working now. By the way, I have to remind the person who posted this question that the update method must be annotated with @Transactional, otherwise it will report an error（Could not obtain transaction-synchronized Session for current thread）
