### ISSUE TITLE
Support for javax.persistence.AttributeConverter

### ISSUE THREAD

**Issue by lightbody** [micronaut-projects/micronaut-data#59]
It doesn't look like Predator supports it, but it sure would be nice

**Comment by graemerocher** [comment]
Currently no, however you can use the `TypeConverter` interface for custom types. See https://micronaut-projects.github.io/micronaut-predator/snapshot/guide/#jdbcDataTypes

**Comment by dstepanov** [comment]
Implemented in https://github.com/micronaut-projects/micronaut-data/pull/1151
