### ISSUE TITLE
Nondeterministic exception when injecting named DataSource

### ISSUE THREAD

**Issue by myles-anderson-ox** [micronaut-projects/micronaut-data#598]
### Steps to Reproduce
(Example app provided below)
1. Create app with these features: mn create-app -f application,http-server,http-client,jdbc-hikari,junit,liquibase,micrometer-prometheus  example.app
2. Add annotationProcessor "io.micronaut.data:micronaut-data-processor:1.0.2" and implementation "io.micronaut.data:micronaut-data-jdbc:1.0.2" to build.gradle
3. Add a class which injects a named data source and gets the connection
4. Add the data source to the config (it must be named something other than default)
5. Run it.
The issue is nondeterministic. Sometimes it will run fine 10 times and then failure 10 times. I can usually reproduce it by doing `gradle <run|test> --debug-jvm` and launching in Eclipse.

### Expected Behaviour

The connection can be collected

### Actual Behaviour

Exception: https://github.com/myles-anderson-ox/micronaut-data-tx-bug/blob/master/app/example-stacktrace

I did also notice that when the Hikari DataSource is created the `TransactionAwareDataSource` is triggered (because of the DataSource bean creation event) and in the `onCreated` the `String name = beanIdentifier.getName();` resolves to `Primary` even though the DataSource is qualified with a name other than default.

### Environment Information

- **Operating System**: MacOS
- **Micronaut Version:** 1.3.5 (also tested with 1.2.8)
- **JDK Version:** 1.8

### Example Application
Repo: https://github.com/myles-anderson-ox/micronaut-data-tx-bug
1. Run `gradle test`
There is an example failure log: https://github.com/myles-anderson-ox/micronaut-data-tx-bug/tree/master/app/failure-log

**Comment by graemerocher** [comment]
This was fixed in recent liquibase releases
