### ISSUE TITLE
Support for composite IDs / primary keys

### ISSUE THREAD

**Issue by lightbody** [micronaut-projects/micronaut-data#60]
It does not appear that Predator honors or respects the options for this, such as `@IdClass` or `@EmbeddedId`. It'd be nice if it did. Thanks!

**Comment by SergiusSidorov** [comment]
I looked into the commit and not found the implementation of @IdClass. It is not supported by micronaut data?

**Comment by graemerocher** [comment]
not currently that would be a separate feature, which I am not sure is necessary. Seems more like a nice to have.

**Comment by wilhg** [comment]
Hey @graemerocher , I would say for many company, this feature is a must-have.
If it can be implemented, micronaut-data gonna be used by more experimental project or startups. :)
