### ISSUE TITLE
Programmatic Transaction readonly does not work

### ISSUE THREAD

**Issue by franz-see** [micronaut-projects/micronaut-data#605]
For example, modifying the BookRepositorySpec (https://github.com/micronaut-projects/micronaut-data/blob/master/doc-examples/jdbc-example-java/src/test/java/example/BookRepositorySpec.java) and adding this

```
	@Test
	void readOnly() {
		try {
			transactionManager.executeRead(status -> {
				Book book = new Book("New Book", 10);
				return bookRepository.save(book);
			});
			fail("Should NOT have been able to save in a read only transaction");
		} catch (DataAccessException ignore) {

		}
	}
```

This test would fail.

**Comment by graemerocher** [comment]
read only currently only applies to hibernate and flush behaviour. There is nothing at the JDBC level that can be set avoid writes happening

**Comment by franz-see** [comment]
@graemerocher in my test project (wherein I use Spring+Boot with Micronaut-Data), I created my own Spring-based aspect to intercept method invocations (annotated with `@Transactional`). And in that aspect, it wraps that method invocation with micronaut transaction using `SynchronousTransactionManager<Connection>`

The way I worked around the readonly issue is by doing this

```
    /**
     * Workaround for https://github.com/micronaut-projects/micronaut-data/issues/605
     */
    private void workaroundForMicronautDataIssue605(DefaultTransactionDefinition transactionDefinition, TransactionStatus<Connection> status) throws SQLException {
        if (transactionDefinition.isReadOnly()) {
            status.getConnection().setReadOnly(true);
        }
    }
``` 

(see https://github.com/franz-see/spring-with-mn-data/blob/7e34de9042c28dffa35567059693d37d44a3d78b/src/main/java/com/example/springwithmndata/aspect/MicronautTransactionAspect.java#L66)

Can that be done in micronaut core and will that be respected across different database dialects?

**Comment by alejandropg** [comment]
I think this issue is already resolved, @graemerocher isn't it?

I mean, in method `DataSourceUtils::prepareConnectionForTransaction` the JDBC connection is already set to read only as @franz-see suggest

https://github.com/micronaut-projects/micronaut-data/blob/a166cf7769227df7824f28bdd148f71c4fb84ebf/data-tx/src/main/java/io/micronaut/transaction/jdbc/DataSourceUtils.java#L206

**Comment by graemerocher** [comment]
As far as I can see this is working as designed and `setReadOnly` is being called. Some drivers don't implement support for it though (like H2 / MS SQL)
