### ISSUE TITLE
Save method that returns void is rejected

### ISSUE THREAD

**Issue by jameskleeh** [micronaut-projects/micronaut-data#614]
In a JDBC repository, `void save(ExampleEntity exampleEntity);` does not compile, however `ExampleEntity save(ExampleEntity exampleEntity);` does. I think in most cases the provided entity is simply mutated to set the id, so it should not have to be returned. This issue is to request the method returning void to compile and function.

**Comment by dstepanov** [comment]
This should be possible to have in the latest version.
