### ISSUE TITLE
Required micronaut-inject-java processor 

### ISSUE THREAD

**Issue by cemo** [micronaut-projects/micronaut-data#626]
Micronaut Data requires `micronaut-inject-java` process to work. Is this expected? It is maybe better to state in the documentation as well.  Only this is stated: 

```
<annotationProcessorPaths>
    <path>
        <groupId>io.micronaut.data</groupId>
        <artifactId>micronaut-data-processor</artifactId>
        <version>1.1.1</version>
    </path>
</annotationProcessorPaths>
```
Better to include this part too
```
 <path> 
   <groupId>io.micronaut</groupId> 
   <artifactId>micronaut-inject-java</artifactId> 
   <version>${micronaut.version}</version> 
 </path> 
```

**Comment by graemerocher** [comment]
Yes this is expected, in order to create repositories micronaut-data depends on micronaut-core

**Comment by cemo** [comment]
I will open a PR for documentation. Is this OK?

**Comment by graemerocher** [comment]
Absolutely, PRs welcome
