### ISSUE TITLE
@DateUpdated vs Native Automatic Initialization

### ISSUE THREAD

**Issue by cemo** [micronaut-projects/micronaut-data#633]
`@DateUpdated` is a technique to initialise a field with some sensitive default data. However this technique has a drawback which is stated in the documentation:

> If you update the entity with an external SQL statement or custom logic you will need to update the underlying DateUpdated column manually.

On other side there is another option which is using native initialization. I prefer native codes as MySQL states in their documentation which is mostly bug free because nobody can forget them in the first place because there is no need to update or insert them. 

Native initialization brings a problem in micronaut sql query generation for insert or updates. The query generates explicitly null values for these fields which are `nullable false`.

For example: Let's say there is a field, `updatedAt`. This field must be null to set a default value or updated however Micronaut creates a query inside this field is set null which is an error on database level. The proper query must ignore these kind of fields to be used in query generation.

What is the proper way to handle it? 

https://dev.mysql.com/doc/refman/8.0/en/timestamp-initialization.html

**Comment by graemerocher** [comment]
This may work:

```
@MappedProperty(definition="TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP")
@GeneratedValue
private Timestamp ts;
```

**Comment by cemo** [comment]
@graemerocher this is working for insert but not update. Am I missing something?

**Comment by graemerocher** [comment]
Will look into it

**Comment by cemo** [comment]
You are simply 🚀

**Comment by cemo** [comment]
https://github.com/micronaut-projects/micronaut-data/blob/master/data-model/src/main/java/io/micronaut/data/model/query/builder/AbstractSqlLikeQueryBuilder.java#L1242

Here adding a `prop.isGenerated()` maybe like this? 

```
            if (prop == null || prop.isGenerated()) {
                continue;
            }
```

**Comment by graemerocher** [comment]
Looks like you are right, want to try send a PR?

**Comment by cemo** [comment]
Let me to test :) It was a blind guess. I want to understand little more. :)

**Comment by cemo** [comment]
I sent a PR. Please review it.

**Comment by graemerocher** [comment]
Thanks will have a look
