### ISSUE TITLE
Query projection not possible for embedded IDs

### ISSUE THREAD

**Issue by esocode** [micronaut-projects/micronaut-data#652]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

I have a child entity with an embedded ID field called `id`, containing two integer fields: `parentId`, `number`. I need to find the maximum number value for a certain parent ID. So I defined the following query method with a max projection on the ID's number:

```java
int findMaxIdNumberByIdParentId(int parentId);
```

When compiling this only yields an error message:

>Unable to implement Repository method: ChildRepository.findMaxIdNumberByIdParentId(int parentId). Cannot project on non-existent property idNumber

The only workaround at the moment is to build a native query with EntityManager as defining a method with an explicit query also doesn't work because of another bug (reported in #653).

### Steps to Reproduce

1. Define entity with embedded ID
2. Define repository query method with projection on ID field
3. compile => error

### Expected Behaviour

Projections on embedded ID should work

### Actual Behaviour

Compile error

### Environment Information

- **Operating System**: Windows 10
- **Micronaut Version:** 2.0.0 (data 1.1.1)
- **JDK Version:** 8

**Comment by jameskleeh** [comment]
Does `int findMaxNumberByParentId(int parentId);` work?

**Comment by esocode** [comment]
No. Sorry, I forgot to mention that one. It was actually my first try but it caused an error too. I have to check this, but as far as I remember it produced a hibernate runtime error that the field could not be found. I'll try tomorrow and provide the exact error message.

**Comment by esocode** [comment]
My first try was actually `findMaxNumberByIdParentId(int)` which yields the following exception at runtime:
>java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: org.hibernate.QueryException: could not resolve property: number of: sample.pkg.Child [SELECT MAX(child_.number) FROM sample.pkg.Child AS child_ WHERE (child_.id.parentId = :p1)]

Your variant `findMaxNumbeByParentId` fails on both attributes:
>java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: org.hibernate.QueryException: could not resolve property: number of: sample.pkg.Child [SELECT MAX(child_.number) FROM sample.pkg.Child AS child_ WHERE (childId_.parentId.parentId = :p1)]

The WHERE clause in the first variant is correctly mapped on the embedded ID (`child_.id.parentId`). I use this in several queries which work without problems. So I think that the bug is that the projection MaxIdNumber is not mapped in the same way as the criteria. Would that be mapped to `child_.id.number` the query should work.

**Comment by esocode** [comment]
I just noticed the same problem for deletes. The projection `deleteByIdParentId(int)` won't compile and the variant `deleteByParentId(int)`throws an exception at runtime. Is this the same problem or justifies it a separate issue? Or isn't it supported?

**Comment by graemerocher** [comment]
probably the same problem

**Comment by charlie-harvey** [comment]
Would this be the same problem if I was trying to project on a joined table/column?

```kotlin
@Entity
data class Product(
    @field:Id
    @field:GeneratedValue
    var id: Long?,
    var name: String,
    @field:Relation(value = Relation.Kind.MANY_TO_ONE)
    @field:MappedProperty("manufacturerId")
    var manufacturer: Manufacturer?
)

@Repository
@JdbcRepository(dialect = Dialect.MYSQL)
interface ProductRepository :CrudRepository<Product, Long> {
    fun findByManufacturerId(long manufacturerId): Product?
}
```

**Comment by Goldmensch** [comment]
Any update on this? I have the same problem with data jdbc.
