### ISSUE TITLE
Micronaut Data 1.1.2 release was not published

### ISSUE THREAD

**Issue by cemo** [micronaut-projects/micronaut-data#662]
It seems that the 1.1.2 could not be published yesterday since the errors. I am not sure why it is but can you cut a release again?

Maven Central:
https://search.maven.org/artifact/io.micronaut.data/micronaut-data-bom

Relevant Error Log:
https://github.com/micronaut-projects/micronaut-data/runs/890404321

**Comment by graemerocher** [comment]
Yeah we are aware

**Comment by graemerocher** [comment]
Will publish 1.1.3 to deal with this

**Comment by cemo** [comment]
@graemerocher can you please label issues for 1.1.4 for my spare times?

**Comment by graemerocher** [comment]
We have release notes generation which handles that https://github.com/micronaut-projects/micronaut-data/releases/tag/v1.1.3

**Comment by cemo** [comment]
I mean I would like to contribute for 1.1.4 and next releases. I see there is no issue now at 
https://github.com/micronaut-projects/micronaut-data/milestone/13. I would like you to prioritise issues and we can give a try to resolve them.

**Comment by graemerocher** [comment]
@cemo sounds great! I will assign some issues. Thanks for your contributions
