### ISSUE TITLE
Add support for JOOQ in abstract classes

### ISSUE THREAD

**Issue by raderio** [micronaut-projects/micronaut-data#67]
JOOQ is more concise than HQL, it will be a good alternative.
The query is also validated in compile time.

https://www.jooq.org/doc/3.11/manual/sql-building/sql-statements/select-statement/

**Comment by graemerocher** [comment]
I am not sure what this would do beyond what https://micronaut-projects.github.io/micronaut-sql/latest/guide/#jooq

already does
