### ISSUE TITLE
Loss of precision when using java.time.Instant in mapped entities

### ISSUE THREAD

**Issue by altery** [micronaut-projects/micronaut-data#676]
# Context
Micronaut 2.0.1 / Micronaut Data 1.1.3 (JDBC Flavor)

# Description of the issue
Java Instants support sub-millisecond precision. If a mapped entity with such an Instant is persisted in a DBMS that supports high-resolution TIMESTAMPs (for example Postgres), the Instant is truncated to milliseconds and persisted as such. This is not obvious, because Micronaut logs the bindings parameters before the conversion happens in AbstractSqlRepositoryOperations:

```
if (DataSettings.QUERY_LOG.isTraceEnabled()) {
    DataSettings.QUERY_LOG.trace("Binding value {} to parameter at position: {}", value, index);
}
if (value != null && dialect.requiresStringUUID(type)) {
    // ...
} else {
    // This is where the type conversion happens
    preparedStatementWriter.setDynamic(
            stmt,
            index,
            type,
            value
    );
}
```

# Expected behaviour
Ideally, an Instant that is stored to a DBMS that support high-resolution timestamp, no precission-loss should occur. At least, Micronaut should log the parameters after type conversion.

# Analysis
The behaviour originates form the default converter for Instant -> Date in io.micronaut.data.runtime.intercept.DataInitializer:

```
conversionService.addConverter(Instant.class, Date.class, instant -> new Date(instant.toEpochMilli()));
```

This converter is invoked because io.micronaut.data.runtime.mapper.QueryStatement converts all Types with target Type TIMESTAMP to java.util.Date:

```
case TIMESTAMP:
  if (value instanceof ZonedDateTime) {
    return setTimestamp(statement, index, convertRequired(value, Timestamp.class));
  } else if (value instanceof Date) {
    return setTimestamp(statement, index, ((Date) value));
  } else {
    return setTimestamp(statement, index, convertRequired(value, Date.class));
  }
```

Note: This is even the case if the SQL Dialect is explicitly specified on the repository:

`@JdbcRepository(dialect = Dialect.POSTGRES)`

# Suggested fix
Maybe the Instant could be converted to java.sql.Timestamp instead, that support nano-precision. Alternatively, the Instant could be converted to an ISO-8601 string (though, I'm not sure how portable that is among different DBMS).

**Comment by graemerocher** [comment]
Great diagnosis of the problem, would you be interested in submitting a PR?

**Comment by altery** [comment]
I created two separate PRs for each of the aspects of this issue.
