### ISSUE TITLE
Micronaut data overrides existing TypeConverter

### ISSUE THREAD

**Issue by altery** [micronaut-projects/micronaut-data#677]
# Context
Micronaut 2.0.1 / Micronaut Data 1.1.3 (JDBC Flavor)

# Description
While evaluating possible workarounds for [another issue](https://github.com/micronaut-projects/micronaut-data/issues/676), I discovered that Micronaut Data silently replaces custom TypeConverters. 

# Expected Behaviour

I would expect that custom Type Converters would take precedence over default one or at leat provide a configuration option wether existing converters should be overridden (maybe logging a warning?).

# Analysis

Micronaut Data does not register TypeConverters by exposing Beans of Type TypeConverter. Instead, a Context-Bean (io.micronaut.data.runtime.intercept.DataInitializer) explicitly registers default converts at the (shared) ConversionService. Because the DefaultApplicationContext first initialises all TypeConverters and then resumes the initialisation of all other beans, the custom type converters will be replaced again if source and target type collide with those provided by Micronaut Data:

```
@Override
protected void initializeContext(List<BeanDefinitionReference> contextScopeBeans, List<BeanDefinitionReference> processedBeans, List<BeanDefinitionReference> parallelBeans) {
  initializeTypeConverters(this);
  super.initializeContext(contextScopeBeans, processedBeans, parallelBeans);
}
```

# Suggested fixes

There are probably various options, that could be considered:

- Do not override existing TypeConverters at all (maybe emit a warning)
- Add a configuration option to disable override
- Publish Data TypeConverters as any other TypeConverters (as Beans, so they can be overridden selectively using standard mechanisms of the IoC container).

**Comment by graemerocher** [comment]
I think what probably makes sense is not to override global converters but instead to have its own implementation of `ConversionService` that delegates to the global one

**Comment by greenboxal** [comment]
It might be also interesting to allow the `ConversionService` to be configurable (per repository/entity/data source/something), that would allow proper scoping.

An example is that `DataType.JSON` currently seems to require a `String => T` converter, which doesn't make sense at all to exist other than to deserialize that particular field/type.

**Comment by graemerocher** [comment]
Yes I agree I think a unique `ConversionService` is required for data

**Comment by charlie-harvey** [comment]
This might be the problem I am running into. My UUID is getting converted, via a TypeConverter, into a byte[] when getting substituted into the query. But my byte[] is not being converted via a TypeConverter, into a UUID.

```kotlin
@Factory
open class UUIDConverters {

    @Singleton
    open fun uuidByteArrayTypeConverter(): TypeConverter<UUID, ByteArray> {
        println(" ***** constructing uuid to bytes converter")      // <- prints!
        return TypeConverter { uuidId, _, _ ->
            println(" ***** i am converting from uuid to bytes")    // <- prints!
            Optional.of(ToBytesTransformer.transform(uuidId))
        }
    }

    @Singleton
    open fun byteArrayUuidTypeConverter(): TypeConverter<ByteArray, UUID> {
        println(" ***** constructing bytes to uuid converter")      // <- prints!
        return TypeConverter { byteArrayId, _, _ ->
            println(" ***** i am converting from bytes to uuid")    // <- does not print
            Optional.of(ToBytesTransformer.parse(byteArrayId))
        }
    }
}
```
Is it because the second TypeConverter is being overwritten and never used? Or is it because fields are not being converted on the return trip from the database?

**Comment by graemerocher** [comment]
yes probably it its overwritten, we need a special ConversionService just for data I think

**Comment by dstepanov** [comment]
Fixed by https://github.com/micronaut-projects/micronaut-data/pull/1151
