### ISSUE TITLE
Add support for cursor pagination

### ISSUE THREAD

**Issue by raderio** [micronaut-projects/micronaut-data#68]
We usually use cursor pagination https://dev.to/jackmarchant/offset-and-cursor-pagination-explained-b89

**Comment by rafaelrenanpacheco** [comment]
Another reference: https://use-the-index-luke.com/no-offset

Endpoints that allow pagination may halt the database if a huge number for the offset value is used. Postgres has a documentation on offset and a [warning sessions](https://www.postgresql.org/docs/14/queries-limit.html) for huge offsets:

> The rows skipped by an OFFSET clause still have to be computed inside the server; therefore a large OFFSET might be inefficient.

The solution for this kind of pagination is the cursor strategy, and would be nice to see Micronaut and more frameworks having that out of the box.

[There is a discussion here](https://github.com/micronaut-projects/micronaut-data/discussions/1108) about this subject as well, but the developer created his own solution I think.

And there are huge players that only have cursor pagination on theirs API, like Stripe for instance.

**Comment by dstepanov** [comment]
Supported in the latest version
