### ISSUE TITLE
Default conversion of LocalDate to Date uses wrong timezone

### ISSUE THREAD

**Issue by Danny02** [micronaut-projects/micronaut-data#687]
### Steps to Reproduce

1. have a System ZoneId other then UTC i.e. "UTC+2"
2. Convert a LocalDate to java.util.Date (see DataInitializer) i.e. 1981-10-31

### Expected Behaviour
The converted Date value and there for the value saved in the database is the same date as the provided LocalDate.

### Actual Behaviour

java.time.Instant and java.util.Date both store time in the UTC timezone. The system default timezone is used In the conversion  LocalDate <-> Date. Which results in the following:

Althought a conversion LocalDate -> Date -> LocalDate is always correct. The intermediary Date value is different from the prvoided LocalDate. 
Other clients will therefor read a different value from the databse as what was indended to be written. 

e.g. LocalDate(1981-10-31) with UTC+2 will write Date(1981-10-30) to the database

### Solution

The conversion should use UTC instead of system default timezone

**Comment by Danny02** [comment]
why does micronaut convert everything to java.util.Date anyway? JDBC supports all the java.time primitives. See https://github.com/h2database/h2database/issues/2573

**Comment by graemerocher** [comment]
I don't believe this is implemented consistently across all drivers

**Comment by graemerocher** [comment]
Seems to be fixed by https://github.com/micronaut-projects/micronaut-data/pull/743
