### ISSUE TITLE
Batch Updates

### ISSUE THREAD

**Issue by cemo** [micronaut-projects/micronaut-data#690]
I am trying to understand how can I perform batch updates on Micronaut but I am little stuck. 

Documentation has a section about batch updates but I think what I want is not implemented yet. I need batch execution of multiple insert or updates. There is a  io.micronaut.data.repository.CrudRepository#saveAll but I need for custom query support too. 

```
@Query(value = QUERY)
void batchInsertOnDuplicateUpdate(Collection<DailyQuota> dailyQuotas);
```

Would you think that it is worth to add such a feature? I am considering to expande bean for the query and executing in a batch fashion.

**Comment by graemerocher** [comment]
Seems useful, but I think to make clear what is going on it probably needs to be `@Batch` annotation or something

**Comment by barddoo** [comment]
@graemerocher `@Batch` would work just for update and insert, and the query would be generated by the method, sure? Could you give more details on what you thought about this?

**Comment by graemerocher** [comment]
Probably update, insert and delete, and yeah

**Comment by Hc747** [comment]
Any updates on this @barddoo @graemerocher ?

**Comment by charlie-harvey** [comment]
I'd vote for this.

This is what I had to do:
```kotlin
@Repository(value = "account-service-datasource")
@JdbcRepository(dialect = Dialect.MYSQL)
abstract class UserMyRepository(
    @Named("account-service-datasource") private val jdbcOperations: JdbcOperations
) : CrudRepository {

  val stmt = """
    INSERT INTO mytable VALUES(id, name, color) (?, ?, ?)
    ON DUPLICATE KEY UPDATE name = VALUES(name), color = VALUES(color);
  """

  @Transactional
  @TransactionalAdvice("account-service-datasource")
  fun saveAll(things: List<Thing>) {
    return jdbcOperations.prepareStatement(sql) { statement ->
      things.forEach { thing ->
        statement.setInt(1, thing.id)
        statement.setString(2, thing.name)
        statement.setString(3, thing.color)
        statement.addBatch()
      }
      statement.execute()      
    }
  }
}
```

I would love to have something like `@Batch()` or `@Insert()` or even `@Modifying()/@Query` like in spring-data. Something to switch between `statement.executeQuery()` and `statement.addBatch()` and `statement.execute()`. There are times when I will want to just have strange insert statements.

**Comment by graemerocher** [comment]
This seems like a good idea @dstepanov ?

**Comment by dstepanov** [comment]
I think this can be added we already have some batches support
