### ISSUE TITLE
Adding new fields on DTO

### ISSUE THREAD

**Issue by cemo** [micronaut-projects/micronaut-data#701]
```
@Introspected
public class BookDTO {

    private String title;
    private int pages;

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public int getPages() {
        return pages;
    }

    public void setPages(int pages) {
        this.pages = pages;
    }
}
```

**The DTO should include properties that match the property names you wish to project on (in this case title and pages). If any properties do not match then a compilation error will occur.**

I would like to add a new computed column from database. When I check necessary implementation it checks necessary field on persistent entity. How this field is not available. What is the correct approach to solve this? 

```
    @Nullable
    @Override
    public Object read(@NonNull S object, @NonNull String name) throws ConversionErrorException {
        RuntimePersistentProperty<T> pp = persistentEntity.getPropertyByName(name);
        if (pp == null) {
            throw new DataAccessException("DTO projection defines a property [" + name + "] that doesn't exist on root entity: " + persistentEntity.getName());
        } else {
            return read(object, pp);
        }
    }
```

**Comment by graemerocher** [comment]
yeah I think we need to make this check more lenient and fallback to trying to read the column. Only issue is with that is the naming strategy to use to convert property names to column names

**Comment by cemo** [comment]
Would you please guide me? I may contribute this as well.

**Comment by cemo** [comment]
>  Only issue is with that is the naming strategy to use to convert property names to column names

Using persistentEntity's case maybe?

**Comment by graemerocher** [comment]
Already fixed by https://github.com/micronaut-projects/micronaut-data/commit/3d2377ce07847655acb8467974bf7dff4b248e20

**Comment by zepfred** [comment]
Hi @graemerocher, this new feature doesn't work for collections of elements. I could open an issue for this request if you think is viable.

**Comment by graemerocher** [comment]
@zepfred sure go ahead and open a new issue
