### ISSUE TITLE
Simple syntax for exists() in repositories

### ISSUE THREAD

**Issue by debuglevel** [micronaut-projects/micronaut-data#710]
* There is a simple syntax `Book find(String title);` in repositories which can be used instead of `Book findByTitle(String title);`
* There is *no* simple syntax `Boolean exists(String title);` in repositories. Only `Boolean existsByTitle(String title);` works.
* For greater consistency it would be nice if this would also work :-) (Perhaps also for other methods, if applicable).

### Environment Information

- **Micronaut Version:** 2.0.1

**Comment by rohitkg98** [comment]
I did some research on this, it seems we traverse on methods and then on the basis of finders, we build methodInfo and get the query from it. One thing I noticed is in `ExistsByFinder`, `buildInfo` is overridden and it seems like we will have to mimic some functionality for `exists` from the original `buildInfo` method from `AbstractPatternBasedMethod` class.

Please let me know  if this is correct

**Comment by graemerocher** [comment]
That is more or less correct

**Comment by Goldmensch** [comment]
@dstepanov this issue can also be closed
