### ISSUE TITLE
Micronaut - Embedded kafka - Consume from same topic

### ISSUE THREAD

**Issue by MicroHero-blip** [micronaut-projects/micronaut-data#75]
I've created a sample project to prove I can produce and consume the messages of the same topic with micronaut, you can find this in: https://github.com/MicroHero-blip/micronaut-ref-data
Everything is implemented in the tests but particularly if you run the test ReferenceDataKafkaClientSpec, in a mac it will pass immediately but if you run all tests it always fails.In linux it will always fail in my laptop but had a colleague that gets results all over the place. In Windows it always passes
The thing that makes the test fail is having a test that has @MicronautTest or embedded server before the ReferenceDataKafkaClientSpec test. For example if I rename my tests so ReferenceDataKafkaClientSpec is first everything will work.
If I replace the embedded kafka with a real one everything is fine in all 4 machines we used to test this.

**Comment by graemerocher** [comment]
The message is being sent occasionally before a Kafka rebalance has occurred and before offsets are assigned. Also even if offsets are assigned in time you would need to use an OffsetStrategy of EARLIEST

**Comment by MicroHero-blip** [comment]
I have set the time of the test to 10 minutes instead of 10 seconds, the message never gets received this is not a concurrency issue, and I cannot replicate this issue using spring.

**Comment by KrzysztofKowalczyk** [comment]
The problem is that for some reasons Sending of Message might happen before Listener attaches.
Because Listener is by default configured to listen from LATEST message in case of new consumer group it will skipp message sitting there.
If you set the offsetReset to EARLIEST then it will start from beginning and read the message.
In tests it will do that everytime, in prod it will do that only when given consumer group does not exist yet or have been removed.

**Comment by MicroHero-blip** [comment]
yep setting earliest does fix it weird that adding a test consistently makes it fail

**Comment by MicroHero-blip** [comment]
still think it's a bug, tests should not start until embedded kafka is ready

**Comment by graemerocher** [comment]
Embedded Kafka is in fact already ready when the test is started, however Kafka takes time to rebalance and assign partitions. This time that is taken to perform this task can mean the message is sent earlier than when the rebalance has occurred and the partition assigned to the listener. This is not a bug and is how Kafka behaves. The solution is to use the EARLIEST strategy as described.
