### ISSUE TITLE
Field not populated using MANY_TO_ONE

### ISSUE THREAD

**Issue by jeanbisutti** [micronaut-projects/micronaut-data#765]
### Task List

- [X] Steps to reproduce provided
- [X] Stacktrace (if present) provided
- [X] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce
Launch [this test method](https://github.com/jeanbisutti/micronaut-data-many-to-one/blob/main/src/main/java/org/quickperf/micronaut/micronauttest/service/PlayerService.java#L38).

```java
@JdbcRepository(dialect = Dialect.H2)
public interface PlayerRepository extends CrudRepository<Player, Long> {
}
```

```java
@MappedEntity
public class Player implements Serializable {

    @Id
    private Long id;

    private String firstName;

    private String lastName;

    @Relation(value = Relation.Kind.MANY_TO_ONE, mappedBy = "team_id")
    private Team team;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public Team getTeam() {
        return team;
    }

    public void setTeam(Team team) {
        this.team = team;
    }

}
```

```java

@MappedEntity
public class Team implements Serializable {

    @Id
    private Long id;

    private String name;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
```

### Expected Behaviour

On the console, the following lines should be displayed:
```
teamName =  Manchester United
```

```
teamName = Atlético de `Madrid`
```

If something is not correctly configured, Micronaut Data may raise an exception.

### Actual Behaviour

On the console:
```
teamName = null
```

```
teamName = null
```

### Environment Information

- **Operating System**: Windows 10
- **Micronaut Version:** 2.0.0.M3
- **JDK Version:** 15

### Example Application

[Here](https://github.com/jeanbisutti/micronaut-data-many-to-one)

**Comment by graemerocher** [comment]
This is not a bug. You need to specify what data you want to join. Altering `PlayerRepository` as follows resolves the "issue":

```
    @Override
    @Join("team")
    Iterable<Player> findAll();
```
