### ISSUE TITLE
DataType.JSON AbstractSqlRepositoryOperations different behaviour create vs update

### ISSUE THREAD

**Issue by berkum** [micronaut-projects/micronaut-data#766]
When saving JSON objects, the code is actually different whether we are in 'save' more or 'update' mode.

I have an attribute of type Set<String> to be persisted as json.
When the value is null, in 'save' mode (repository.save(entity)) the following code will apply (method persistOne) : 
Object value = beanProperty.get(entity);
...
 if (type == DataType.JSON && jsonCodec != null) {
      value = new String(jsonCodec.encode(value), StandardCharsets.UTF_8);
 }
preparedStatementWriter.setDynamic(
                                stmt,
                                index,
                                type,
                                value
                        );

So if value is null, the output produced will be "null" as jsonCodec.encode does not do any null check.

In update mode (method updateOne), no transformation : 
Object value = beanProperty.get(entity);
... // NO TRANSFORMATION, SO WE ARE GOOD
preparedStatementWriter.setDynamic(
                                            ps,
                                            i + 1,
                                            dataType,
                                            newValue
                                    );

### Expected Behaviour
The record should be persisted with a null value when it is null in 'save' mode.
### Actual Behaviour
The record is persisted with a 'null' string value when it is null in 'save' mode.

The fix is very simple, we need to do a add a null check in 'save' mode (method persistOne)
 if (type == DataType.JSON && jsonCodec != null **&& value != null**) {
        value = new String(jsonCodec.encode(value), StandardCharsets.UTF_8);
 }

### Environment Information

- **Operating System**: MacOS 10.15.7, Catalina
- **Micronaut Version:** micronaut-data-jdbc 1.0.2
-  **JDK Version:** 

### Example Application

- TODO: link to github repository with example that reproduces the issue

**Comment by graemerocher** [comment]
Seems like you have narrowed down the issue, would you like to send a PR?

**Comment by issmo** [comment]
> Seems like you have narrowed down the issue, would you like to send a PR?

This issue is similar to the one quoted in #762
The PR for #762 this issue

**Comment by berkum** [comment]
OK, will do.  Just reading your 'how to' for now.  Will try to do it today or tomorrow AM.

**Comment by berkum** [comment]
Found out that by removing some code related to jackson null management, I can have problem in both save and persist scenarios.  One in the superclass (AbstractSqlRepositoryOperations), the other in the subclass (DefaultJdbcRepositoryOperations).  It does make sense to have to have both fixed as it quite obviously has same unexpected result.
