### ISSUE TITLE
@EmbeddedId isn't considered during query building or schema generation

### ISSUE THREAD

**Issue by nhoughto** [micronaut-projects/micronaut-data#768]
Similar to https://github.com/micronaut-projects/micronaut-data/issues/716 and https://github.com/micronaut-projects/micronaut-data/issues/594

It appears @EmbeddedId has a few rough edges when used within relationships, schema generation doesn't understand that it represents potentially many fields and errors with

```
Bean definition [io.micronaut.data.jdbc.config.SchemaGenerator] could not be loaded: Error instantiating bean of type [io.micronaut.data.jdbc.config.SchemaGenerator]: Unable to create table column for property [id] of entity [example.domain.JoinOwner] with unknown data type: ENTITY
```

and query generation incorrectly adds the variable name / property name of the @EmbeddedId property into the query as if its a column, when it is potentially many columns:
```
Error executing SQL Query: ERROR: relation "join_join_owner_entity" does not exist
```

Reproducer test here:
https://github.com/nhoughto/micronaut-data-embeddedid in `JoinRepositoryTest`

**Comment by nhoughto** [comment]
I've tried working around this with `@IdClass` which isn't supported so can't help, seems like the only answer is to implement the queries yourself via JdbcOperations as described in https://github.com/micronaut-projects/micronaut-data/issues/594

**Comment by graemerocher** [comment]
Generally for these kinds of complex ORM mappings you are better off with JPA. 

The JDBC implementation is designed as a simple query result -> object mapper and the schema generation is only for quick tests and not a replacement for a schema migration tool like Flyway or Liquibase.

If you have the need to map a complex object layer onto relational databases stick with JPA if you simply need need to take a result set and bind it to a POJO and are happy to write your own SQL with some conveniences around automatically implementing queries then JDBC is for you.
