### ISSUE TITLE
NullPointerException thrown when native query returns 1 row, 1 column and the value is null

### ISSUE THREAD

**Issue by LucaFornelli** [micronaut-projects/micronaut-data#769]
### Description
In one of our repository classes, the query expects a `String` as result type, but it might occasionally return `null` value. 
When this happens a NullPointerException is thrown instead of the expected empty Optional.

### Steps to Reproduce
with this repository:

```
package default

import io.micronaut.data.annotation.Query
import io.micronaut.data.jdbc.annotation.JdbcRepository
import io.micronaut.data.model.query.builder.sql.Dialect
import io.micronaut.data.repository.GenericRepository

@JdbcRepository(dialect = Dialect.MYSQL)
abstract class NullTestRepository implements GenericRepository<String, Long> {

    @Query("select null")
    abstract Optional<String> somethingThatMightSometimesReturnNull()
}
```

When calling `somethingThatMightSometimesReturnNull()` a null pointer exception is thrown here:
https://github.com/micronaut-projects/micronaut-data/blob/master/data-runtime/src/main/java/io/micronaut/data/runtime/mapper/ResultReader.java#L50

Since the value is `null`, calling the `.getClass()` method will thrown a NullPointerException

### Expected Behaviour

When a null value is the result of a query, an empty Optional should be returned.

### Actual Behaviour

When a null value is the result of a query, a NullPointerException is thrown.

### Environment Information

- **Operating System**: MacOS 10.15.7
- **Micronaut Version:** 1.3.6
- **Micronaut Data Version:** 1.1.0 (also happening in version 1.1.3)
- **JDK Version:** 1.8

**Comment by graemerocher** [comment]
PR submitted for this https://github.com/micronaut-projects/micronaut-data/pull/767
