### ISSUE TITLE
Can't run examples in IDEA 2019.2

### ISSUE THREAD

**Issue by parkito** [micronaut-projects/micronaut-data#77]
I try to run kotlin-jdbc examples in IDEA (with enabled annotation processing). Unfourtanetely i can't use controllers after a such run. I should build jar and run it. Only after that i can use controllers.

Is it IDEA's issue or example's?

**Comment by parkito** [comment]
The main problem is if you change something in the code and try to run app form IDEA withoud gradle build - IDEA won't apply changes withoud building app before.

**Comment by graemerocher** [comment]
Currently Kotlin requires delegating to Gradle or Maven for building. I recommend you vote for this issue https://youtrack.jetbrains.com/issue/KT-15040 if you wish to see resolution
