### ISSUE TITLE
Column read/write SQL customization

### ISSUE THREAD

**Issue by tburch** [micronaut-projects/micronaut-data#78]
It'd be nice to have an annotation like Hibernate's [`ColumnTransformer`](https://docs.jboss.org/hibernate/orm/4.3/javadocs/org/hibernate/annotations/ColumnTransformer.html) annotation so that users can customize the read/write SQL for a given column (eg. call `pgp_sym_decrypt`/`pgp_sym_encrypt` on read/write).

**Comment by graemerocher** [comment]
Agreed, would be good to add this.
