### ISSUE TITLE
Placeholder in @Where annotation can not be resolved

### ISSUE THREAD

**Issue by lisa-tw** [micronaut-projects/micronaut-data#790]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create an entity and a repository
2. Add a method to find all entities and add a `@Where` annotation that uses a method parameter from the repository method signature
3. Call repository method

### Expected Behaviour

Placeholder should be resolved and used in `@Where` annotation value

### Actual Behaviour

Placeholder can not be resolved.

### Environment Information

- **Operating System**: Mac 10.15.6
- **Micronaut Version:** 2.0.0
- **JDK Version:** 11

### Example Application

https://github.com/lisa-tw/micronaut-data-where-annotation

**Comment by issmo** [comment]
The query generated by micronaut-data for the findAll(String description) automatically contains the where clause for the description column. There is no need to add a @Where annotation in this case.

I think the use of @Where annotation is to add additional static criteria such as for example @Where("status = 1") or similar.

I hope this helps.

**Comment by lisa-tw** [comment]
Thanks for your reply! In our app, I want to use the `@Where` annotation with a `findByDeletedFalseOrderByDateCreated` method, which is also annotated with multiple `@Join`. When I hardcode everything in the `@Where` annotation value, the correct SQL statement is created. However, using a parameter from the repository method is not possible. 

So my question is: Why can I use a dynamic parameter taken from a repository method with a `@Query` annotation, but not with `@Where`? Is this bug or am I doing something wrong?

----

This works: 
`@Where("LOWER(CONCAT_WS('', organization_.name, organization_.description)) LIKE CONCAT('%', LOWER('My org'}), '%')")
    fun findByDeletedFalse(filterTerm: String?, pageable: Pageable): Page<Organization>`

Placeholder can not be resolved:
`@Where("LOWER(CONCAT_WS('', organization_.name, organization_.description)) LIKE CONCAT('%', LOWER(\${filterTerm}), '%') OR \${filterTerm} is null")
    fun findByDeletedFalse(filterTerm: String?, pageable: Pageable): Page<Organization>`

**Comment by issmo** [comment]
In this case, try with the following pattern :filterTerm instead of ${filterTerm}
This is the pattern that micronaut-data looks for.

**Comment by lisa-tw** [comment]
Tried that already, but I get the following error message in our app:

`Unable to establish parameter value for parameter at position: 1`

**Comment by issmo** [comment]
The use of the ${filterTerm} will be resolved by configuration and not linked to the method parameter. looks like the @Where annotation doesn't supports this yet, it is almost there but not yet.
I'll try to have a look at it and possibly submit a PR.

**Comment by lisa-tw** [comment]
Sounds good! Would be great to be able to use method parameters with the annotation.

**Comment by issmo** [comment]
PR #800 submited for this issue.
This resolves the issue for both JDBC and Hibernate-JPA

**Comment by issmo** [comment]
I have just noticed that this does not pass the JDK8 test because of the use of StringBuilder. I am going to change it and post a new PR.
