### ISSUE TITLE
io.micronaut.data unresolved reference

### ISSUE THREAD

**Issue by jimisdrpc** [micronaut-projects/micronaut-data#808]
The error basically means io.microunat.data is missed but, as far as I can see, I followed carefully [https://micronaut-projects.github.io/micronaut-data/latest/guide/](url)

I added
```

    annotationProcessor("io.micronaut.data:micronaut-data-processor:2.1.1")
    implementation("io.micronaut.data:micronaut-data-hibernate-jpa:2.1.1")
```

In IntelliJ I see Unresolved reference: CrudRepository

Here is my repository:

```
import com.mybank.model.AccountHolder
import io.micronaut.data.repository.CrudRepository
import io.micronaut.context.annotation.Executable
import io.micronaut.data.annotation.*

@Repository
interface AccountHolderRepository: CrudRepository<AccountHolder, Long> {
    @Executable
    fun find(title: String): AccountHolder
}
```
Complete logs:

`gradle clean build --stacktrace

> Task :kaptKotlin FAILED
C:\_d\ZUP\WSs\demo\build\tmp\kapt3\stubs\main\com\mybank\repository\AccountHolderRepository.java:11: error: Unable to implement Repository method: AccountHolderRepository.find(String title). Cannot query entity [AccountHolder] on no
n-existent property: title
    public abstract com.mybank.model.AccountHolder find(@org.jetbrains.annotations.NotNull()
                                                   ^C:\_d\ZUP\WSs\demo\build\tmp\kapt3\stubs\main\com\mybank\repository\AccountHolderRepository.java:11: error: Unable to implement Repository method: AccountHolderRepository.find(Stri
ng title). No possible implementations found.
    public abstract com.mybank.model.AccountHolder find(@org.jetbrains.annotations.NotNull()
                                                   ^Note: Creating bean classes for 6 type elements
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':kaptKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptExecution
   > java.lang.reflect.InvocationTargetException (no error message)

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':kaptKotlin'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:200)
        ...
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: org.gradle.workers.internal.DefaultWorkerExecutor$WorkExecutionException: A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptExecution
        at org.gradle.workers.internal.DefaultWorkerExecutor$WorkItemExecution.waitForCompletion(DefaultWorkerExecutor.java:336)
        ...
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        ...
Caused by: org.jetbrains.kotlin.kapt3.base.util.KaptBaseError: Error while annotation processing
        at org.jetbrains.kotlin.kapt3.base.AnnotationProcessingKt.doAnnotationProcessing(annotationProcessing.kt:116)
        at org.jetbrains.kotlin.kapt3.base.AnnotationProcessingKt.doAnnotationProcessing$default(annotationProcessing.kt:34)
        at org.jetbrains.kotlin.kapt3.base.Kapt.kapt(Kapt.kt:45)
        ... 31 more

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
5 actionable tasks: 5 executed

`

build.gradle

```
`plugins {
    id "org.jetbrains.kotlin.jvm" version "1.4.10"
    id "org.jetbrains.kotlin.kapt" version "1.4.10"
    id "org.jetbrains.kotlin.plugin.allopen" version "1.4.10"
    id "com.github.johnrengelman.shadow" version "6.1.0"
    id "io.micronaut.application" version '1.0.5'
    id "com.gorylenko.gradle-git-properties" version "2.2.2"
}

version "0.1"
group "com.mybank"

repositories {
    mavenCentral()
    jcenter()
}

micronaut {
    runtime "netty"
    testRuntime "junit5"
    processing {
        incremental true
        annotations "com.mybank.*"
    }
}

dependencies {
    implementation("io.micronaut:micronaut-validation")
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8:${kotlinVersion}")
    implementation("org.jetbrains.kotlin:kotlin-reflect:${kotlinVersion}")
    implementation("io.micronaut.kotlin:micronaut-kotlin-runtime")
    implementation("io.micronaut:micronaut-runtime")
    implementation("javax.annotation:javax.annotation-api")
    implementation("io.micronaut:micronaut-http-client")
    implementation("io.micronaut:micronaut-management")

    //https://guides.micronaut.io/micronaut-data-access-jpa-hibernate/guide/index.html
//    implementation("io.micronaut.sql:micronaut-jdbc-hikari")
//    implementation("io.micronaut.sql:micronaut-hibernate-jpa")
    runtimeOnly("com.h2database:h2")

    //https://micronaut-projects.github.io/micronaut-data/latest/guide/
    annotationProcessor("io.micronaut.data:micronaut-data-processor:2.1.1")
    implementation("io.micronaut.data:micronaut-data-hibernate-jpa:2.1.1")

    runtimeOnly("ch.qos.logback:logback-classic")
    runtimeOnly("com.fasterxml.jackson.module:jackson-module-kotlin")



}

mainClassName = "com.mybank.ApplicationKt"
java {
    sourceCompatibility = JavaVersion.toVersion('11')
}

compileKotlin {
    kotlinOptions {
        jvmTarget = '11'
    }
}
compileTestKotlin {
    kotlinOptions {
        jvmTarget = '11'
    }
}
```

Whole project [https://github.com/jimisdrpc/micronaut-data-demo](url)

`

**Comment by issmo** [comment]
I am not able to reproduce this with the actual state of your repo. 
I see from the commits that you have corrected your code.

Micronaut Data annotation processor indicate that you are instructing it to implement a find method with a parameter **title** while this property does not exist in the *AccountHolder* entity. 
"Unable to implement Repository method: AccountHolderRepository.find(String title). Cannot query entity [AccountHolder] on non-existent property: title"

You should either have a property title in your entity or rename your parameter, otherwise, Micronaut Data would have no clue about your intent.

This is not a bug and the issue can be closed if this clarification is clear for you.

**Comment by graemerocher** [comment]
Please use

```
$ curl https://launch.micronaut.io/demo.zip?features=data-jpa -o demo.zip
$ unzip demo.zip -d demo
```

To create a working / correctly configured app.

Thanks
