### ISSUE TITLE
Data JDBC don't handle UUID stored as BINARY(16) in MySQL

### ISSUE THREAD

**Issue by rafaelrenanpacheco** [micronaut-projects/micronaut-data#832]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

Hello!

I'm trying to migrate my application from JPA to JDBC in order to have more control of the queries and avoid the 1+N from the beginning. I found a problem regarding UUID column (not as id, just a regular column) that micronaut is unable to query this column (UUID -> VARBINARY(16)) and to convert back the response from VARBINARY(16) to UUID. For Micronaut Data JPA this works just fine.

This is the table I'm using to store some rows with UUID and to query them on a MySQL 8 database:

```sql
CREATE TABLE establishment (
  id   INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  uuid BINARY(16) NOT NULL,
  name VARCHAR(50) NOT NULL
);
```

This is the entity:

```java
@Getter
@Setter
@MappedEntity
public class Establishment {

    @Id
    @GeneratedValue
    private Integer id;

    private UUID uuid;
    private String name;
}
```

The repository:

```java
@JdbcRepository(dialect = Dialect.MYSQL)
public interface EstablishmentRepository extends PageableRepository<Establishment, Integer> {

    Optional<Establishment> findByUuid(UUID uuid);
}
```

Ok, now the use cases:

1 - If I run `establishmentRepository.findByUuid(/*some valid uuid*/)`, nothing is found in the query, even tho the row exists in the database with that uuid. Micronaut Data on TRACE log even shows the UUID on the binding list, but the query returns nothing.

2 - If I run `establishmentRepository.findById(1)`, then the row is found but it throws an error when trying to convert from binary to uuid, something like this:

```
Cannot convert type [class java.lang.String] with value [�;$jNƑZ��] to target type: UUID uuid. Consider defining a TypeConverter bean to handle this case.
```

I took the suggestion and tried to create a few TypeConverters, but without success.

MySQL suggests the use of BINARY(16) to store UUIDs, and it works just fine in JPA. Is this feature missing in JDBC? I can help with some PR, just need some guidance on where to start looking to fix this UUID conversion.

### Environment Information

- **Operating System**: Linux
- **Micronaut Version:** 2.2.0
- **JDK Version:** 11

**Comment by graemerocher** [comment]
See https://github.com/micronaut-projects/micronaut-data/issues/821

**Comment by rafaelrenanpacheco** [comment]
Hello @graemerocher!

I've saw that issue before opening this one, but since that issue uses `varchar(36)` to store UUID it would not be related to this problem about `binary(16)`. Anyway, I tried the workaround suggest [here](https://github.com/micronaut-projects/micronaut-data/issues/821#issuecomment-734755210), that is, annotating the the field like this:

```java
    @TypeDef(type = DataType.STRING)
    private UUID uuid;
```

And got the exactly same issue as reported before when using `findById(1)`:

```
Cannot convert type [class java.lang.String] with value [�;$jNƑZ��] to target type: UUID uuid. Consider defining a TypeConverter bean to handle this case.
```

When using `findByUuid(/*some valid uuid*/)` the row was not found as well.

So, based on #821 it looks like storing uuid as varchar could work, but this is not storage and performance friendly. In 2015 the mysql team [posted this](https://mysqlserverteam.com/storing-uuid-values-in-mysql-tables/) explaining these two ways of storing uuid, and the advantages of using binary over varchar.

Since the column is binary, I tried this as well:

```java
    @TypeDef(type = DataType.BYTE_ARRAY)
    private UUID uuid;
```

This way `findById(1)` do encode the row to the target entity, but with a wrong UUID conversion. For example, the ID-1 in database have the UUID `EF033B246A084EC6915A88EF9082EC88`, but the entity got the UUID `e63879f5-9aef-318b-b845-d15591c6d7c2`. The `findByUuid(/*some valid uuid*/)` didn't find the row as well.

**Comment by graemerocher** [comment]
You may need to register a type converter for byte array to UUID and back

**Comment by rafaelrenanpacheco** [comment]
I'll try to make it work using the TypeConverter [explained here](https://micronaut-projects.github.io/micronaut-data/latest/guide/#jdbcDataTypes).

Thanks!

**Comment by rafaelrenanpacheco** [comment]
For some reason my `byte[]` to `UUID` is not being picked by the `DefaultConversionService`.

This is the converter:

```java
@Singleton
TypeConverter<byte[], UUID> byteToUuid() {
    return (object, targetType, context) -> {
        // this is not the right way to convert, it's just for debugging.
        return Optional.of(UUID.fromString(new String(object)));
    };
}
```

And deep down micronaut calls `return typeConverter.convert(object, targetType, context)`, but that `typeConverter` is not my converter. Looks like a default converter that calls `UUID.nameUUIDFromBytes` somewhere, I don't know where.

The good news is that the 16 bytes are there, I saw them. The bad news is this mysterious converter getting in front of my converter.

**Comment by charlie-harvey** [comment]
@rafaelrenanpacheco You closed this issue but I don't understand what you did to make it work. I am trying to do the same thing - store UUID as BINARY(16) in MySQL. Do you have the fix somewhere as an example? Thanks.

**Comment by rafaelrenanpacheco** [comment]
Hello @charlie-harvey!

I don't have a fix, I'm back to JPA and no longer using JDBC. If this bug is fixed I may get back to JDBC some day.

**Comment by charlie-harvey** [comment]
```java
@Factory
public class UUIDConverters {

    @Singleton
    public TypeConverter<UUID, byte[]> uuidByteArrayTypeConverter() {
        return (uuidId, targetType, context) -> Optional.of(ToBytesTransformer.transform(uuidId));
    }

    @Singleton
    public TypeConverter<byte[], UUID> byteArrayUuidTypeConverter() {
        return (byteArrayId, targetType, context) -> Optional.of(ToBytesTransformer.parse(byteArrayId));
    }
}

@MappedEntity
public class Establishment {
    @Id
    @MappedProperty(type = DataType.BYTE_ARRAY)
    @ColumnTransformer(read = "BIN_TO_UUID(establishment_.id)", write = "UUID_TO_BIN(?)")
    @TypeDef(type = DataType.STRING)
    var id: UUID;

    private String name;
}
```

This craziness works. Somehow the `TypeConverter` gets picked up ONLY on the way in. So the UUID gets turned into a byte[] with the correct ordering for the query. But when the data gets returned, the `TypeConverter` doesn't get picked up. I tried it over and over again with `@TypeDef(type = DataType.BINARY_ARRAY)` to no avail.
So, we have the `UUID_TO_BIN` and `BIN_TO_UUID` functions on the MySQL server. So the `@ColumnTransformer` will turn the return value into a String instead of a byte[], then the `@TypeDef` will turn the String into the UUID.

I don't like it but it is working.

**Comment by charlie-harvey** [comment]
This time for real. I found a way to beat the system. Create your own type, then the TypeConverter will "see" it and fire off.

```kotlin
@TypeDef(type = DataType.BYTE_ARRAY)
data class OptimizedUUID (val uuid: UUID)

@Repository
@JdbcRepository(dialect = Dialect.MYSQL)
interface UserAccountRepository : CrudRepository<UserAccount, OptimizedUUID> {
}

@Introspected
@MappedEntity
data class UserAccount (
    @field:Id
    var id: OptimizedUUID,
    var siteId: Int,
    var userId: OptimizedUUID,
    var username: String
)

@Factory
open class UUIDConverters {

    @Singleton
    open fun uuidByteArrayTypeConverter(): TypeConverter<OptimizedUUID, ByteArray> {
        return TypeConverter { uuidId, _, _ -> Optional.of(ToBytesTransformer.transform(uuidId.uuid)) }
    }

    @Singleton
    open fun byteArrayUuidTypeConverter(): TypeConverter<ByteArray, OptimizedUUID> {
        return TypeConverter { byteArrayId, _, _ -> Optional.of(OptimizedUUID(ToBytesTransformer.parse(byteArrayId))) }
    }
}
```
```
TRACE i.m.d.query - Binding parameter at position 1 to value OptimizedUUID(uuid=874b8832-1b8e-11ea-978f-2e728ce88125) with data type: BYTE_ARRAY
```
```
curl -X GET "http://localhost:8080/useraccount/874b8832-1b8e-11ea-978f-2e728ce88125"
{"id":"874b8832-1b8e-11ea-978f-2e728ce88125","siteId":10000,"userId":"7e76e3e9-a525-4225-9db1-c764cbd5e50f","username":"sara.smith"}
```
There you have it. Both of my UUIDs being converted. And the first one gets converted on the way in and the way out.

I wish the TypeConverter did not get overwritten so this would not be necessary. Maybe in a few weeks with the next release...

**Comment by athkalia** [comment]
@rafaelrenanpacheco it might be worth re-opening, this is still an issue. As @charlie-harvey mentioned, the converted gets used only on the way in, but not when reading the byte array and converting it to UUID. The solution that @charlie-harvey has above does work for me as well, (thanks!)
But it's not ideal because you need to:
- Maintain your own wrapper type
- You can't use the `@AutoPopulated` annotation any longer, so you need to create your own UUIDs in code

**Comment by rafaelrenanpacheco** [comment]
> Let's reopen this, if I understand it correctly you want to define `UUID` type as `BINARY`?

Hello!

The UUID in MySQL was stored as VARBINARY(16), but Micronaut JDBC were unable do convert the java type UUID when querying the data using UUID and also when converting back the value when a row had an UUID column. The solution seems to be to create a TypeConverter, but it didn't work for UUID. @charlie-harvey made it to work by creating a custom UUID type (OptimizedUUID), but has the downsides as said by @athkalia.

**Comment by athkalia** [comment]
@dstepanov can you please share an example of how that can be done, i.e. replacing the UUID converter by adding it after DataInitializer is invoked. ?

**Comment by dstepanov** [comment]
@athkalia Try something like this:
```
public class DataInitializer2 implements ApplicationEventListener<ApplicationStartupEvent> {
    @Override
    public void onApplicationEvent(ApplicationStartupEvent event) {
        ConversionService.SHARED.addConverter(...)
    }
}
```

**Comment by athkalia** [comment]
The above, worked thanks. I am having a related problem however:

When I try to call this function (the implementation of which is generated by Micronaut)
```
fun getByIdInList(uuids: List<UUID>): List<MyDbEntity>
```
I get an error:

```
Cannot convert type [class java.util.Arrays$ArrayList] to target type: class [B. Consider defining a TypeConverter bean to handle this case.
```
I tried to debug it and `[B` seems to be a `Byte[].class`

It seems like the `io.micronaut.data.runtime.operations.internal.AbstractSqlRepositoryOperations#expandMultipleValues` function is not expanding the list of UUIDs into multiple questionmarks in the sql query, because of this


```
       Iterator<Object> valuesIterator = new Iterator<Object>() {

            int i;

            @Override
            public boolean hasNext() {
                if (i >= parameterBinding.length) {
                    return false;
                }
                int parameterIndex = parameterBinding[i];
                DataType dataType = parameterTypes[i];
                if (parameterIndex == -1 || dataType.isArray()) {
                    i++;
                    return hasNext();
                }
                return true;
            }

            @Override
            public Object next() {
                Object queryParameter = queryParameters[parameterBinding[i]];
                i++;
                return queryParameter;
            }
        };
```

in the `io.micronaut.data.runtime.operations.internal.AbstractSqlRepositoryOperations#prepareStatement(io.micronaut.data.runtime.operations.internal.AbstractSqlRepositoryOperations.StatementSupplier<PS>, io.micronaut.data.model.runtime.PreparedQuery<T,R>, boolean, boolean)` method. Specifically the check

`    if (parameterIndex == -1 || dataType.isArray()) {`
returns true, which causes the iterator to suggest that there are no extra values.

Does this make sense?

**Comment by charlie-harvey** [comment]
@athkalia I was running into that same exact problem all day yesterday! I tried lists of other objects like String or Integer and they were fine. Byte[] or ByteArray is definitely broken. I swear this was working a few weeks ago. So glad someone else found the same problem and did all the hard work of tracking down the source.

**Comment by athkalia** [comment]
Yeah, other types like Strings definitely work. I guess a workaround would be to write custom SQL to perform this, rather than relying on Micronaut, but that is a bit of a hassle.

**Comment by dstepanov** [comment]
The check is supposed to skip expanding arrays but I guess it's invalid for a collection of something that is supposed to be converted to byte array

**Comment by athkalia** [comment]
thanks for confirming that @dstepanov . Is that something that can be resolved relatively easily?

**Comment by athkalia** [comment]
awesome!

**Comment by dstepanov** [comment]
In the next version, this can be implemented in a better way using `AttributeConverter` see https://github.com/micronaut-projects/micronaut-data/blob/ab9fe12c0206f35f2347f2f5cb674e59a8b934ee/data-jdbc/src/test/java/io/micronaut/data/jdbc/mysql/MySqlUuidEntity.java
