### ISSUE TITLE
JPA - Using @Join for multi parent level (single ended associations)

### ISSUE THREAD

**Issue by rafaelrenanpacheco** [micronaut-projects/micronaut-data#833]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

Hello!

I'm trying to join fetch 2 parents from a grandchildren entity, and based on #12 it should have work for single ended associations. But instead it is generating invalid SQL, and the alternative is to write my own query with those 2 fetches.

These are the entities:

```java
@Entity
public class State {

    @Id
    private Integer id;

    private String name;
}

@Entity
public class City {

    @Id
    private Integer id;

    @ManyToOne(fetch = FetchType.LAZY)
    private State state;

    private String name;
}

@Entity
public class Address {

    @Id
    private Integer id;

    @ManyToOne(fetch = FetchType.LAZY)
    private City city;

    private String cep;
}
```

And the repository:

```java
@Repository
public interface AddressRepository extends JpaRepository<Address, Integer> {

    @Join("city")
    @Join("city.state")
    Optional<Address> findByCep(String cep);
}
```

Running the `findByCep` throws the following exception:

```
org.hibernate.QueryException: could not resolve property: state of: com.micronaut.address.Address
```

With the following JPQL:

```sql
SELECT address_
FROM com.micronaut.address.Address AS address_
JOIN FETCH address_.city address_city_ -- this is ok
JOIN FETCH address_.state address_city_state_ -- this should have be address_city_.state
JOIN FETCH address_.state address_city_state_ -- this is duplicated?
WHERE (address_.cep = :p1)
```

When using only `@Join("city.state")` the following invalid JPQL is generated:

```sql
SELECT address_
FROM com.micronaut.address.Address AS address_
JOIN FETCH address_.state address_city_state_ -- this should have be address_.city
JOIN FETCH address_.state address_city_state_ -- this should have be address_city_.state
WHERE (address_.cep = :p1)
```

Am I using this `@Join` in the wrong way with JPA?

The workaround is to manually write the query, like this:

```java
@Repository
public interface AddressRepository extends JpaRepository<Address, Integer> {

    @Query("select a from Address a join fetch a.city c join fetch c.state where a.cep = :cep")
    Optional<Address> findByCep(String cep);
}
```

### Steps to Reproduce

1. Use `@join` to fetch parent and grandparent.

### Expected Behaviour

To parent and grandparent be fetched.

### Actual Behaviour

Invalid JPQL.

### Environment Information

- **Operating System**: Linux
- **Micronaut Version:** 2.2.0
- **JDK Version:** 11

**Comment by graemerocher** [comment]
Generally for complex JPA joints it is better to use `@EntityGraph`

**Comment by rafaelrenanpacheco** [comment]
You mean like this?

```java
@Repository
public interface AddressRepository extends JpaRepository<Address, Integer> {

    @EntityGraph(attributePaths = {"city", "city.state"})
    Optional<Address> findByCep(String cep);
}
```

It throws this:

```
Unexpected error occurred: Unable to locate Attribute  with the the given name [city.state] on this ManagedType [com.micronaut.address.Address]
```
