### ISSUE TITLE
Error when use DTO with @Query 

### ISSUE THREAD

**Issue by henriquelsmti** [micronaut-projects/micronaut-data#848]
Currently, the Micronaut cannot convert the query result to a DTO when the term type is a List, Flow, etc.

In this case work well:

    @Repository
    interface MyInterface extends GenericRepository<Person, Long> {

        @Query("select name as fullName from person where id = :id")
        FullNameDto getFullName(Long id);
    }

    @Introspected
    class FullNameDto {
        private String fullName;
    
       public String getFullName() {
            return fullName;
        }

        public void setFullName(String fullName) {
            this.fullName = fullName;
        }
    }

In this case I have an error

    @Repository
    interface MyInterface extends GenericRepository<Person, Long> {

        @Query("select name as fullName from person")
        List<FullNameDto> getFullName();
    }

    @Introspected
    class FullNameDto {
        private String fullName;
    
        public String getFullName() {
            return fullName;
        }

        public void setFullName(String fullName) {
            this.fullName = fullName;
        }   
    }

**Comment by henriquelsmti** [comment]
Hi, any news about this?

**Comment by graemerocher** [comment]
Will take a look soon, just wrapping up 2.3.. next week will have more time for Micronaut Data
