### ISSUE TITLE
Not possible to change transaction isolation level in Hibernate transactions

### ISSUE THREAD

**Issue by nleso** [micronaut-projects/micronaut-data#858]
- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

We had the need to change the transaction isolation level for an operation on a MariaDB. But when we tried to use the "official" functionality of `DefaultTransactionDefinition` an exception occurred with a long but rather obscure error message. The message hints at defaults that should be set but in our case these defaults haven't been overridden in the configuration. And I couldn't find any further information about this in the documentation. If this is really an intended behavior I think it should be at least documented.

As a workaround we now set (and restore) the isolation level directly on the JDBC connection inside the transactional code.

### Steps to Reproduce

1. Create new `DefaultTransactionDefinition`
2. Set custom transaction isolation level with `DefaultTransactionDefinition.setIsolationLevel()`
3. Execute Hibernate JPA transaction with the custom definition

### Expected Behaviour

Transaction should be performed with the given isolation level

### Actual Behaviour

`InvalidIsolationLevelException `from `HibernateTransactionManager:311` with error message
>HibernateTransactionManager is not allowed to support custom isolation levels: make sure that its 'prepareConnection' flag is on (the default) and that the Hibernate connection release mode is set to 'on_close' (the default for JDBC).

### Environment Information

- **Operating System**: Win10, Linux
- **Micronaut Version:** 2.2.0
- **JDK Version:** 8

**Comment by dstepanov** [comment]
Hibernate provides the default that is not compatible with changing isolation.
You can allow it by providing:
```
jpa.default.properties.hibernate.connection.handling_mode: DELAYED_ACQUISITION_AND_HOLD
```
