### ISSUE TITLE
 micronaut-data-bom:2.2.2 on maven central

### ISSUE THREAD

**Issue by natros** [micronaut-projects/micronaut-data#878]
Hi,

micronaut 2.2.3 depends on micronaut-data 2.2.2 but there is no micronaut-data-bom:2.2.2 on maven central

https://search.maven.org/artifact/io.micronaut/micronaut-bom/2.2.3/pom
https://search.maven.org/artifact/io.micronaut.data/micronaut-data-bom/2.2.2/pom

**Comment by graemerocher** [comment]
Thanks for the report. Running the sync https://github.com/micronaut-projects/micronaut-data/runs/1680590035?check_suite_focus=true

Should be available shortly

**Comment by natros** [comment]
micronaut-data-bom is already available.

https://search.maven.org/artifact/io.micronaut.data/micronaut-data-bom/2.2.2/pom

Thank you.
