### ISSUE TITLE
Add support for transaction by method + lambda

### ISSUE THREAD

**Issue by raderio** [micronaut-projects/micronaut-data#88]
Besides `@Transactional` annotation, add support for transaction by method + lambda. 
```
connection.transaction(lambda)
```
or in Kotlin
```
connection.transaction {
}
```
Examples
https://www.jooq.org/doc/3.11/manual/sql-execution/transaction-management/
https://www.playframework.com/documentation/2.5.x/JavaJPA#Running-transactions-decoupled-from-requests
https://github.com/JetBrains/Exposed/wiki/Transactions

In this case we can write 2 separate transaction in one method, and no need to make 2 separate methods just for adding `@Transactional`.
Also no need for annotation processing.

**Comment by raderio** [comment]
Another example is `use` extension method from Kotlin
https://github.com/Kotlin/kotlinx.support/blob/master/kotlinx-support-jdk7/src/main/kotlin/AutoCloseable.kt#L13

**Comment by graemerocher** [comment]
Implemented to with:

```java
@Inject SynchronousTransactionManager transactionManager

transactionManager.executeWrite {
     ...
}
```

**Comment by raderio** [comment]
Can we also specify isolation levels? 
like
```
transactionManager.executeWrite(isolation=TRANSACTIONAL) {
     ...
}
```

**Comment by graemerocher** [comment]
I added an `execute` variation that accepts a `TransactionDefinition` and added docs https://micronaut-projects.github.io/micronaut-data/snapshot/guide/#programmaticTransactions
