### ISSUE TITLE
Consider failing compilation when a private method is annotate  with @Transactional

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-data#882]
@sdelamo 

> With Micronaut Data JDBC annotating a Method as javax.transaction.Transactional rollbacks if the method is protected, package private or public but it does not rollback if private. That it is expected right?

@graemerocher 

> private method rollback would require reflection
> that should probably be a compilation error

**Comment by dstepanov** [comment]
Fixed in core by https://github.com/micronaut-projects/micronaut-core/pull/5569
