### ISSUE TITLE
Query generation not incorporating column transformations in where clause

### ISSUE THREAD

**Issue by mkimberlin** [micronaut-projects/micronaut-data#912]
### Steps to Reproduce

1. Annotate a field on an `@Entity` class with a `@ColumnTransformer` such as:
```
@ColumnTransformer(
          read =  "pgp_sym_decrypt(name::bytea,'${aes.key}')",
          write = "pgp_sym_encrypt(?,'${aes.key}') "
)
```
2. Create a `JdbcRepository` that has a method that yields a generated query on the annotated column (in this case name as above):
```
@JdbcRepository(dialect = Dialect.POSTGRES)
public interface SomeEntityRepository extends CrudRepository<SomeEntity, UUID> {

    Optional<SomeEntity> findByName(String name);

}
```
3. Utilize that repository method to query the database.

### Expected Behaviour

The resulting query applies the column transformer to the `select from ...` part of the query as well as the where clause. i.e:
```
SELECT
  team_."id",
  pgp_sym_decrypt(name::bytea,'BOGUS_TEST_KEY') AS name,
  pgp_sym_decrypt(description::bytea,'BOGUS_TEST_KEY') AS description
FROM "team" team_
WHERE (pgp_sym_decrypt(name::bytea,'BOGUS_TEST_KEY') = ?)
```

### Actual Behaviour

The resulting query applies the column transformer to the `select from ...` part of the query, but *NOT* to the where clause. i.e:
```
SELECT
  team_."id",
  pgp_sym_decrypt(name::bytea,'BOGUS_TEST_KEY') AS name,
  pgp_sym_decrypt(description::bytea,'BOGUS_TEST_KEY') AS description
FROM "team" team_
WHERE (team_."name" = ?)
```

### Environment Information

- **Operating System:** MacOS, Ubuntu, Windows
- **Micronaut Version:** 2.0.0
- **Micronaut Data Version:** 1.0.2
- **JDK Version:** Java 11 and 14

### Example Application

- This can be seen in the failing checks for [this PR](https://github.com/oci-labs/check-ins/pull/714)

**Comment by graemerocher** [comment]
Think this might duplicate #880

**Comment by mkimberlin** [comment]
@graemerocher I believe you are correct. I'm not sure how I missed that issue.
