### ISSUE TITLE
MND JDBC should generate indices from @Table annotation

### ISSUE THREAD

**Issue by musketyr** [micronaut-projects/micronaut-data#938]
### Steps to Reproduce

1. Create MND JDBC application with the following entity

```
@Entity
@Table(indexes = [
        @Index(name = 'ix_user_email', columnList = 'email', unique = true),
])
class User {

    @Id
    @GeneratedValue
    Long id
    String email = ''
}
```

2. Configure the data source with `schema-generate: CREATE`
3. Run the application

### Expected Behaviour

The table `user` is generated with the unique index `ix_user_email`.

### Actual Behaviour

The table `user` is generated without any indices.

### Environment Information

- **Operating System**: Mac OS X 10.15.7 x86_64
- **Micronaut Version:** 1.3.7
- **JDK Version:** 1.8.0_275 (Amazon.com Inc. 25.275-b01)

**Comment by Deviad** [comment]
Hello,
I have been looking into this. 
In order to solve this should I create an "indexes" property within MappedEntity and then in EntityAnnotationMapper do something like in ManyToManyMapper following what has been done for cascade with regard to indexes?
@graemerocher
