### ISSUE TITLE
Compilation error implementing repository interface with JPA and snapshot version

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-data#950]
The GraalVM CI has detected a compilation error with JPA applications when trying to implement the repository interface.

### Steps to Reproduce

- `git clone https://github.com/micronaut-graal-tests/micronaut-data-jpa-graal`
- `cd micronaut-data-jpa-graal`
- `git checkout 2.4.x_h2`
- `./gradlew run`

### Expected Behaviour

The appliction should compile and start properly.

### Actual Behaviour

The application fails during compilation.

```
> Task :compileJava FAILED
error: Unable to implement Repository method: PetRepository.findById(Object arg0). Parameter [arg0] of method [findById] is not compatible with property [id] of entity: example.domain.Pet
error: Unable to implement Repository method: PetRepository.existsById(Object arg0). Parameter [arg0] of method [existsById] is not compatible with property [id] of entity: example.domain.Pet
error: Unable to implement Repository method: PetRepository.deleteById(Object arg0). Parameter [arg0] of method [deleteById] is not compatible with property [id] of entity: example.domain.Pet
Note: Writing reflect-config.json file to destination: META-INF/native-image/example.jpa/micronaut-data-jpa-graal/reflect-config.json
Note: Writing resource-config.json file to destination: META-INF/native-image/example.jpa/micronaut-data-jpa-graal/resource-config.json
Note: Creating bean classes for 7 type elements
3 errors
```

### Environment Information

- **Operating System**: Linux Mint 20.1
- **Micronaut Version:** 2.4.1-SNAPSHOT and Micronaut Data 2.3.2-SNAPSHOT
- **JDK Version:** 8

**Comment by graemerocher** [comment]
Seems `-parameter` is not enabled or it isn't using the latest Gradle plugin which fixes missing `-parameters`

**Comment by graemerocher** [comment]
or maybe not, @dstepanov can you take a look?

**Comment by dstepanov** [comment]
`PetRepository` defines `UUID` identity which is not compatible with `Long` identity defined in `Pet`

**Comment by ilopmar** [comment]
As @dstepanov mentioned the type wasn't correct (it's been working until now). Fixed by https://github.com/micronaut-graal-tests/micronaut-data-jpa-graal/commit/24dfb5f50e26457a28287299aa5d655e38baee33
