### ISSUE TITLE
Sorting with a property below the first child throws an IllegalArgumentException: "Cannot sort on non-existent property path".

### ISSUE THREAD

**Issue by gasparetto** [micronaut-projects/micronaut-data#951]
Hi!
I am trying to sort a list of entities with some OneToOne relations. Sorting on a root property works, and sorting on a child property also works. Sorting with a property below the first child does not works and throws an IllegalArgumentException: "Cannot sort on non-existent property path". The same happens with mn-jdbc and mn-jpa. Is this not supported? Or can be a bug or enhancement?

With this sample repository:

    @Repository
    public interface Level1Repository extends JpaRepository<Level1, Long> {

        @Query("select distinct level1_ from Level1 level1_" +
                " left join fetch level1_.level2 level1_level2_" +
                " left join fetch level1_level2_.level3 level1_level2__level3_")
        @NonNull
        @Override
        List<Level1> findAll(@NonNull Sort sort);
    }

These works:

    List<Level1> items = repository.findAll(Sort.of(Sort.Order.asc("name1")));
    List<Level1> items = repository.findAll(Sort.of(Sort.Order.asc("level2.name2")));

This doesn't works:

    List<Level1> items = repository.findAll(Sort.of(Sort.Order.asc("level2.level3.name3")));

### Steps to Reproduce

1. Unzip the sample project "sortissue".
2. Run the test with Maven: `mvn clean compile test`

### Expected Behaviour

Sorting with a property below the first child should works.

### Actual Behaviour

Sorting with a property below the first child throws an IllegalArgumentException: "Cannot sort on non-existent property path".

### Environment Information

- **Operating System**: macOS 11.2.2
- **Micronaut Version:** 2.4.0
- **JDK Version:** 11.0.9

### Example Application

[sortissue.zip](https://github.com/micronaut-projects/micronaut-data/files/6148374/sortissue.zip)

**Comment by PiotrBaczkowski** [comment]
is there any workaround for this?

**Comment by dstepanov** [comment]
I have found a problem and fixed it. BTW you would need to use the default join alias `level1_level2_level3_` instead of `level1_level2__level3_`.
