### ISSUE TITLE
JPA: Update Entity leads to "detached entity passed to persist"

### ISSUE THREAD

**Issue by jworuna** [micronaut-projects/micronaut-data#96]
Hello,

if i use the Repository directly to update an Entity it's works. But if the Repository a Depency inside a Controller i always get the following Error:
`Unexpected error occurred: org.hibernate.PersistentObjectException: detached entity passed to persist: example.domain.Pet`

I extend the given Example (example-jpa) with the PetRepository. I create a update method inside the Controller:

```
@Put("/{petId}")`
    HttpStatus update(@QueryValue("petId") Long petId, Pet pet) {
        Optional<Pet> result = petRepository.findById(petId);
        if (result.isPresent()) {
            Pet current = result.get();
            current.setName(pet.getName());
            petRepository.persist(current);

            return HttpStatus.CREATED;
        }

        return HttpStatus.NOT_FOUND;
    }

```

I added the method as described in the documentation:
`Pet persist(Pet entity);`

And create a Test for the PUT endpoint:

```
@MicronautTest
public class PetUpdateControllerTest {

    @Inject
    @Client("/")
    RxHttpClient client;

    @Test
    void test() {
        Pet result = client.toBlocking().retrieve(HttpRequest.GET("/pets/Dino"), Pet.class);

        assertNotNull(result);
        assertEquals("Dino", result.getName());

        result.setName("Heino");
        String url = "/pets/" + result.getId();
        HttpStatus status = client.toBlocking().retrieve(HttpRequest.PUT(url, result), HttpStatus.class);
        assertEquals(204, status.getCode());
    }
}
```

Then i got this Error:
```
javax.persistence.PersistenceException: org.hibernate.PersistentObjectException: detached entity passed to persist: example.domain.Pet
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154)
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:181)
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:188)
	at org.hibernate.internal.SessionImpl.firePersist(SessionImpl.java:810)
	at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:788)
```

I discover the same error in my own project.
A direct Test with the Repository works.

Regards
Jan

**Comment by graemerocher** [comment]
The reason is because the transaction management applies at the method level for the repository. To resolve this you have 2 options:

1. Place `@Transactional` onto the controller method so both the `findById` and the `persist` methods participate in the same transaction

Or 

2. Use a batch update method to implement the same logic:

In repository:

```
void update(@Id Long id, String name)
```

In controller:

```java
@Put("/{petId}")`
    HttpStatus update(@QueryValue("petId") Long petId, Pet pet) {
        Optional<Pet> result = petRepository.findById(petId);
        if (result.isPresent()) {
            Pet current = result.get();
            petRepository.update(current.getId(), pet.getName());

            return HttpStatus.CREATED;
        }

        return HttpStatus.NOT_FOUND;
    }

```

**Comment by jworuna** [comment]
Thank you for your Help. I tested it and came to the following conclusion:

The first option leads to the same Error.
The second option works.

**Comment by jworuna** [comment]
Thank you for your Help. It works now.

**Comment by korri123** [comment]
Hey, I'm trying out your suggestion by placing `@Transactional` in the controller, but I keep getting this exception: 

`org.springframework.transaction.TransactionSystemException: No transaction manager configured`

My understanding was that by using Hibernate with Micronaut, a HibernateTransactionManager should already be used by default so I don't know where I am going wrong.

This is the method:

```java
    @Transactional
    @Put("/{userId}")
    @Secured("admin")
    public User updateUser(Long userId, @Body User user) {
        user.setId(userId);
        repository.save(user);
        return user;
    }
```

`repository` is an interface that extends `io.micronaut.data.repository.CrudRepository`.

[Full controller code](https://pastebin.com/NrASktdW)

[Repository code](https://pastebin.com/yRYDE3kG)

[Full exception stacktrace](https://pastebin.com/W5e35w2y)

**Comment by StephenOTT** [comment]
FYI for future ref of others who hit this issue: With the release of micronaut data M5, you can use using the `update` method for the Repositories such as:

```
interface UserTasksRepository: RxJavaCrudRepository<UserTaskEntity, UUID>{
    fun update(entity: UserTaskEntity): Single<UserTaskEntity>
}

...

return userTaskRepository.findById(taskId).flatMapSingle {
            it.assignee = assignee.assignee
            userTaskRepository.update(it)
        }.map {
            HttpResponse.ok(it)
        }
```

(Which seems to do a merge and thus allow the detached entity?)

compared to where the `save` method will cause a detached entity error.
