### ISSUE TITLE
AsyncCrudRepository.delete() can throw ClassCastException

### ISSUE THREAD

**Issue by rlubke** [micronaut-projects/micronaut-data#962]
When trying to invoke additional operations on the CompletableFuture<Void> returned from AsyncCrudRepository.delete() results in the following CCE:

> java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Void (java.lang.Integer and java.lang.Void are in module java.base of loader 'bootstrap')
> java.util.concurrent.CompletionException: java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Void (java.lang.Integer and java.lang.Void are in module java.base of loader 'bootstrap')
> 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
> 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
> 	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
> 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
> 	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
> 	at com.tangosol.util.AsynchronousAgent.complete(AsynchronousAgent.java:224)
> 	at com.tangosol.util.processor.SingleEntryAsynchronousProcessor.onComplete(SingleEntryAsynchronousProcessor.java:97)
> 	at com.tangosol.coherence.component.net.requestContext.asyncContext.AsyncProcessorContext.processCompletion(AsyncProcessorContext.java:123)
> 	at com.tangosol.coherence.component.net.requestContext.asyncContext.AsyncProcessorContext.processSingleResult(AsyncProcessorContext.java:178)
> 	at com.tangosol.coherence.component.util.daemon.queueProcessor.service.grid.partitionedService.PartitionedCache$InvokeRequest$Poll.onCompletion(PartitionedCache$InvokeRequest$Poll.java:149)
> 	at com.tangosol.coherence.component.net.Poll.close(Poll.java:328)
> 	at com.tangosol.coherence.component.net.Poll.onResponded(Poll.java:682)
> 	at com.tangosol.coherence.component.net.Poll.onResponse(Poll.java:693)
> 	at com.tangosol.coherence.component.net.message.requestMessage.DistributedCacheKeyRequest$Poll.onResponse(DistributedCacheKeyRequest$Poll.java:152)
> 	at com.tangosol.coherence.component.util.daemon.queueProcessor.service.Grid.onMessage(Grid.java:3031)
> 	at com.tangosol.coherence.component.util.daemon.queueProcessor.service.Grid.onNotify(Grid.java:3144)
> 	at com.tangosol.coherence.component.util.daemon.queueProcessor.service.grid.PartitionedService.onNotify(PartitionedService.java:5440)
> 	at com.tangosol.coherence.component.util.daemon.queueProcessor.service.grid.partitionedService.PartitionedCache.onNotify(PartitionedCache.java:5759)
> 	at com.tangosol.coherence.component.util.Daemon.run(Daemon.java:1247)
> 	at java.base/java.lang.Thread.run(Thread.java:834)
> Caused by: java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Void (java.lang.Integer and java.lang.Void are in module java.base of loader 'bootstrap')
> 	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
> 	... 17 more

In fact, if I change the code to do this:

`repository.delete(<some-object>).join()`

The result is indeed an Integer.

So either the `AsyncCrudRepository `signature is incorrect and should be `CompletableFuture<Integer>` or the interceptor implementation needs updated.

### Steps to Reproduce

Run something similar against an AsyncCrudRepository:

` repo.delete(DUNE).thenAccept(unused -> System.out.println("### DEBUG ###")).join();`

### Expected Behaviour

I expect the accept call to function without raising a CCE.

### Actual Behaviour

See above.

### Environment Information

- **Operating System**: MacOS 10.15.7
- **Micronaut Version:** 2.4.1; Data version -> 2.3.1
- **JDK Version:** JDK11

**Comment by graemerocher** [comment]
@dstepanov could you take a look, this is to support Coherence Data
