### ISSUE TITLE
[Enhancement] Add method updateAll to CrudRepository

### ISSUE THREAD

**Issue by altro3** [micronaut-projects/micronaut-data#971]
Hello! I saw an issue on adding batch update operation. And I saw that you have already complete it (https://github.com/micronaut-projects/micronaut-data/pull/961) and in the next release we will finally be able to use this feature :-). But I think that we should add the updateAll method to the standard CrudRepository, because now the full functionality in the repositories is not obtained: we have saveAll and deleteAll, but no updateAll.

Could you add this method to the standard CrudRepository with all the batch changes?

**Comment by dstepanov** [comment]
Yeah, it makes sense to add, do you want to create a PR?

**Comment by altro3** [comment]
@dstepanov Hi! Sorry, wanted to help you, but didn't have time on this week :-(. Will try in next time
