### ISSUE TITLE
DTO Projections do not work with @Query annotations

### ISSUE THREAD

**Issue by charlie-harvey** [micronaut-projects/micronaut-data#975]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [ ] Full description of the issue provided (see below)

### Steps to Reproduce

```kotlin
@Introspected
@MappedEntity
data class Thing(
    @field:GeneratedValue
    @field:Id
    var id: Int? = null,
    var name: String
    var score: Int,
    var site: String
)

@Introspected
data class ThingDTO(
    val thingId: Int,
    val thingName: String
)

@Repository
@JdbcRepository(dialect = Dialect.MYSQL)
interface CasbinRuleRepository : CrudRepository<Thing, Int> {

    fun findByName(name: String): List<Thing>  // works - of course

    @Query("""
      SELECT thing.id AS thingId, thing.name AS thingName
      FROM things thing
      WHERE thing.id = :id
    """)
    fun findThingDTOsByThingId(id: Int): List<ThingDTO>  // fails!
}
```

### Expected Behaviour
It should project the two fields onto the DTO

### Actual Behaviour
Compilation Error:
```
error: Unable to implement Repository method: ThingRepository.findThingDTOsByThingId(Integer id). Property thingId is not present in entity: com.example.entities.Thing
    public abstract java.lang.Object findThingDTOsByThingId(@org.jetbrains.annotations.NotNull()
```

### Environment Information

- **Operating System**: Mac/Linux
- **Micronaut Version:** 2.4.2
- **Micronaut Data Version:** 2.3.1
- **JDK Version:** 11

### Should this work?
I'm not actually sure if this is something that is supported. So this could be a bug or a feature!

**Comment by dstepanov** [comment]
This should be fixed in master. Can you please try a snapshot?

**Comment by charlie-harvey** [comment]
Outstanding! How did you do that so fast? ;) Compiles just fine now. Thanks a lot.

**Comment by dstepanov** [comment]
Superpowers...

**Comment by charlie-harvey** [comment]
Interesting thing happened. It turns everything into `underscore_columns` even though NOTHING is underscore anywhere. From the example above, it would turn `thingName` into `thing_name` and then tell me there is no column to match. Even though the query says `thingName` and (in my case), the column is actually `thingName`.

If I put `@field:MappedProperty("thingName")` onto the property it works. But I should not need that, it is a DTO.

Just a heads up while you work on the snapshot.

Thanks.

**Comment by dstepanov** [comment]
Can you provide a simple example?

**Comment by dstepanov** [comment]
@charlie-harvey Default naming strategy for an entity is `UnderScoreSeparatedLowerCase` so using `thing.name AS thingName` is not correct.

**Comment by charlie-harvey** [comment]
```
@MappedEntity(value = "things", namingStrategy = NamingStrategies.Raw::class)
```

That is the only place I can set the naming strategy. But I'm using a DTO, so that annotation can't go on my DTO. How do I change the naming strategy?

**Comment by dstepanov** [comment]
It should use the strategy defined on the repositorie's entity `Thing`
