### ISSUE TITLE
micronaut-data problem with JdbcRepository multiple data sources not accurate inject

### ISSUE THREAD

**Issue by hudiandian** [micronaut-projects/micronaut-data#980]
hi, I hava two data source in application.yml ,  I encountered injection problems during use
![image](https://user-images.githubusercontent.com/24569816/115173035-09ffec00-a0f9-11eb-8082-e8f17c72f736.png)

I want to use a read-only data source, and the default data source is injected as a result 
![image](https://user-images.githubusercontent.com/24569816/115174698-4e40bb80-a0fc-11eb-8098-5055489ca84d.png)

But using interface can normally inject read-only data sources
![image](https://user-images.githubusercontent.com/24569816/115190239-514aa480-a11a-11eb-8079-0ae33e274799.png)

I want to know that abstract class cannot use @Repository to specify the data source?  If I want to use abstract class to inject the specified data source, is there any way

Thank you for reading

### Environment Information
- **Operating System**: windows
- **Micronaut Version:** 2.3.1
- **JDK Version:** jdk11

**Comment by graemerocher** [comment]
Use `@Named('read-only')` on the `JdbcOperations` parameter

**Comment by hudiandian** [comment]
> Use `@Named('read-only')` on the `JdbcOperations` parameter

Thank you very much, the problem has been solved 
![image](https://user-images.githubusercontent.com/24569816/115218673-6256de00-a139-11eb-8742-ce9ec33d933d.png)
